### ISSUE TITLE
请问可以把任务清理功能做成小部件快捷方式吗？

### ISSUE THREAD

**Issue by zzzop** [Tornaco/Thanox#10]
您好，感觉这是一个小众的需求。手机只有2g内存，所以我希望可以用tasker之类的应用调用Thanox的“内存清理”功能，做到每次返回桌面都执行一次“内存清理”

**Comment by abcdol** [comment]
像应用管理那种把清理作为一个单独活动的方式也很好，可以直接用快速打开活动或者tasker或者edge调用，非常舒服。或者使用clipper这种广播调用的方式也很好～
![Screenshot_20191117-151815](https://user-images.githubusercontent.com/43516434/69004425-eb1e8880-094d-11ea-813e-d9be28f114bf.jpg)

**Comment by zzzop** [comment]
> 像应用管理那种把清理作为一个单独活动的方式也很好，可以直接用快速打开活动或者tasker或者edge调用，非常舒服。或者使用clipper这种广播调用的方式也很好～
> ![Screenshot_20191117-151815](https://user-images.githubusercontent.com/43516434/69004425-eb1e8880-094d-11ea-813e-d9be28f114bf.jpg)

用edge试过应用管理的清理活动屏幕会闪一下，是正常的吗

**Comment by abcdol** [comment]
是正常现象 会调用打开一个无界面的活动 目前在新版本找不到这个活动无法调用

**Comment by Tornaco** [comment]
adb shell am broadcast --user all -a thanox.a.running_process.clear

**Comment by Tornaco** [comment]
试试上面的广播。

**Comment by abcdol** [comment]
可以用 非常感谢～

**Comment by Tornaco** [comment]
暂时先关闭改ISSUE。
小部件暂时先不做了。
