### ISSUE TITLE
Thnaox下无法显示应用休眠的tag

### ISSUE THREAD

**Issue by HorrZzz** [Tornaco/Thanox#101]
**Describe the bug（现象描述）**
Thnaox下无法显示应用休眠的tag

。
例如这样：![image](https://user-images.githubusercontent.com/42233737/76143887-00aeee00-60b6-11ea-93bf-07a6c6415932.png)

**To Reproduce**（如何复现）
 目前已知这种情况，重装应用，调整字体，切换xposed框架，均无效。

**Expected behavior**（期望结果）
正常情况下：
![image](https://user-images.githubusercontent.com/42233737/76143900-1d4b2600-60b6-11ea-8b5a-6bc22494a23a.png)

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: OOS10.3.0 for oneplus 7 Pro[e.g. Android 10]
 - Version 1.1.7-1-bbdc866-dirty-prc

** Logs**（日志文件）
[thanox-core.log](https://github.com/Tornaco/Thanox/files/4301829/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/4301830/thanox-init.log)

**Comment by Tornaco** [comment]
@HorrZzz 你确定上述应用处于休眠状态吗？

**Comment by HorrZzz** [comment]
> @HorrZzz 你确定上述应用处于休眠状态吗？

@Tornaco 我确定，因为在thanox的应用管理列表里所有的APP全都没有了休眠的标签。并不是只有个别应用没有显示

**Comment by Tornaco** [comment]
@HorrZzz hao de  回头想办法加个调试功能。。目前没法确定是UI问题还是状态问题。

**Comment by HorrZzz** [comment]
@Tornaco 好的，辛苦！
