### ISSUE TITLE
活动管理、服务管理等一直处于刷新状态

### ISSUE THREAD

**Issue by guoyitian315** [Tornaco/Thanox#1029]
Describe the bug（现象描述）
各APP内容提供者管理可以打开，活动管理、服务管理一直处于刷新状态，广播接收器管理为空

To Reproduce（如何复现）
启动Thanox即可复现

Expected behavior（期望结果）
正常使用

Screenshots（截图）
![d93ab747675bf6f49e936b15c7840e0](https://github.com/user-attachments/assets/ae446f72-c5de-43c5-99f9-a3b6375e1839)
![b23a9f9582156c8bd439ad280577ecb](https://github.com/user-attachments/assets/f1102e09-2eef-4577-bd72-f028cb9d5c06)

**Version（发现问题的版本）:**
 - 系统版本，Android 11
 - 软件版本，5.1.5-row （google play付费版）

** Logs**（日志文件）
[Thanox-Log-2024-09-05-12_35_21.zip](https://github.com/user-attachments/files/16883983/Thanox-Log-2024-09-05-12_35_21.zip)

**Comment by Tornaco** [comment]
@guoyitian315  看下这个内部版本呢

加入：
 https://play.google.com/apps/internaltest/4699745136264046535

Latest release: 3080883 (5.1.6-row)

**Comment by guoyitian315** [comment]
> @guoyitian315 看下这个内部版本呢
> 
> 加入： https://play.google.com/apps/internaltest/4699745136264046535
> 
> Latest release: 3080883 (5.1.6-row)

解决。google play 也推送了。感谢！
