### ISSUE TITLE
thanox自己变成未激活状态

### ISSUE THREAD

**Issue by GreenDreenAct** [Tornaco/Thanox#1041]
**Describe the bug（现象描述）**
自己变成未激活状态，已经出现了很多次，偶尔打开软件的时候就会这样，需要自己重新激活。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 打开thanox

**Expected behavior**（期望结果）
显示激活状态

**Screenshots**（截图）
![Screenshot_20241005_143743_Thanox.png](https://github.com/user-attachments/assets/41959917-3189-417a-832d-ec5666779188)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 14]
 - Version [e.g. v5.1.6]

**Additional context**（其他信息）
补丁方式为xposed，手机是s23u，oneui 6.1

** Logs**（日志文件）
![Thanox-Log-2024-10-05-14_37_34.zip](https://github.com/user-attachments/files/17265369/Thanox-Log-2024-10-05-14_37_34.zip)

**Comment by Tornaco** [comment]
激活码问题请邮件联系 thanox@163.com
