### ISSUE TITLE
Feature request: 查看/复制 Intent 详情

### ISSUE THREAD

**Issue by MoeBakaW** [Tornaco/Thanox#1044]
可以在（如图）应用唤醒的对话框中提供一个 **查看/复制详细 Intent** 的功能吗？这样可以更便捷地获取应用 Intent 和唤醒时的 URL scheme；如果还能够支持 **编辑后再发送至目标应用** 就更好了。
![IMG_20241011_142556](https://github.com/user-attachments/assets/48a7e2ee-cbb7-47b2-a892-3928505882b1)

**Comment by Tornaco** [comment]
Added
