### ISSUE TITLE
请求增加新功能组件多选

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#1046]
一个应用好几百个服务光凭右上角的全部开启或全部关闭太不方便了，希望能增加像写轮眼一样的多选开启或者关闭，真的很需要这个功能，因为我现在测试当前这一页的服务的时候，只能一个个手动全开或者全关，就像图中这一页，我只能一个个手点全开或者全关![Screenshot_20241015-133159.png](https://github.com/user-attachments/assets/e8bbfb1b-04ae-41ee-a867-97ef9dda7aa9)

![Screenshot_20241015-133205_Thanox.png](https://github.com/user-attachments/assets/74e1125e-6aba-4967-9ffa-f98a6a387fce)

![Screenshot_20241015-133235_MyAndroidTools.png](https://github.com/user-attachments/assets/659e1252-0e0d-4653-b73a-284ca0e8f37c)

**Comment by Tornaco** [comment]
增加了当前页选择的功能。
