### ISSUE TITLE
谷歌pro版本在ksu的root中情景模式su失效

### ISSUE THREAD

**Issue by HanHanOuyeE** [Tornaco/Thanox#1049]
**Describe the bug（现象描述）**
谷歌pro版本在ksu的root中情景模式su失效
情景模式中我使用一个退后台就可以killQQ进程的一个但是不起作用，没法正常kill进程

**To Reproduce**（如何复现）
下载谷歌pro版本的灭霸，启用情景模式，使用
[

{

"name": "QQ进程优化",

"description": "优化保留双进程和通话",

"priority": -2,

"condition": "frontPkgChanged == true && from == \"com.tencent.mobileqq\"",

"actions": [

"Thread.sleep(3000);",

"su.exe(\"ps -ef|grep com.tencent.mobileqq:|grep -v :MSF|grep -v :video|grep -v grep|awk '{print $2}'|xargs kill -9\")"

]

}

]
su引擎失效没法正常工作

**Expected behavior**（期望结果）
能正常kill程序进程

一加ace3使用氧os14
ksu
使用xp模式

---------
![Screenshot_2024-10-25-14-25-50-87_9bd1be20abe2442bf84e81e62f440f7d.jpg](https://github.com/user-attachments/assets/70fa5108-4175-4660-b2e7-ae7c3ac598e3)
![Thanox-Log-2024-10-25-14_17_36.zip](https://github.com/user-attachments/files/17517079/Thanox-Log-2024-10-25-14_17_36.zip)

**Comment by Tornaco** [comment]
@HanHanOuyeE 你的shell命令执行结果：1729831784691|W|ThanoxApp|Shell res: out: [kill: missing argument (see "kill --help")] err: []

看起来是错误，缺少参数。

**Comment by HanHanOuyeE** [comment]
> @HanHanOuyeE 你的shell命令执行结果：1729831784691|W|ThanoxApp|Shell res: out: [kill: missing argument (see "kill --help")] err: []
> 
> 看起来是错误，缺少参数。

好的，更新到最新版本解决了，正常工作了
