### ISSUE TITLE
5.1.7 导致微信闪退

### ISSUE THREAD

**Issue by entr0pia** [Tornaco/Thanox#1050]
**Describe the bug（现象描述）**
微信闪退，回退到5.1.2正常

**Version（发现问题的版本）:**
 - OS: Android 13（索尼）
 - Version: 5.1.7，lsposed
 - 微信：Play版8.0.51

[Thanox-Log-2024-10-27-10_42_16.zip](https://github.com/user-attachments/files/17533098/Thanox-Log-2024-10-27-10_42_16.zip)

**Comment by Tornaco** [comment]
@entr0pia 有没有阻止微信的后台启动，如果阻止了，可以先放开试试。

**Comment by entr0pia** [comment]
> @entr0pia 有没有阻止微信的后台启动，如果阻止了，可以先放开试试。

没有阻止自启动


<details>
<summary>微信配置项</summary>

![Screenshot_20241027_163133](https://github.com/user-attachments/assets/024be159-b774-4c2e-af1b-7d5f6bd3b0e8)

</details>

**Comment by Tornaco** [comment]
@entr0pia 有没有用其他类似于ifw的模块，对微信进行设置。

**Comment by entr0pia** [comment]
> @entr0pia 有没有用其他类似于ifw的模块，对微信进行设置。

有安装blocker，但未对微信进行处理

**Comment by Tornaco** [comment]
@entr0pia 有没有禁用微信的某些服务组件。最新版本更改了一些被阻止、禁用的服务崩溃处理策略，本来是解决澎湃OS上微信莫名其妙的崩溃问题的。

**Comment by entr0pia** [comment]
> @entr0pia 有没有禁用微信的某些服务组件。最新版本更改了一些被阻止、禁用的服务崩溃处理策略，本来是解决澎湃OS上微信莫名其妙的崩溃问题的。

只有`com.tencent.matrix.lifecycle.supervisor.SupervisorService`服务是停用状态，但应该原本就是停用的，我没有动过

**Comment by Tornaco** [comment]
@entr0pia 就是这个服务导致的崩溃，这个服务我看了默认应该是启用的的。你可以开启试试。如果有其他人报告问题我看下怎么处理下。

**Comment by entr0pia** [comment]
> @entr0pia 就是这个服务导致的崩溃，这个服务我看了默认应该是启用的的。你可以开启试试。如果有其他人报告问题我看下怎么处理下。

OK了。谢谢
