### ISSUE TITLE
安卓14禁用获取应用列表功能失效

### ISSUE THREAD

**Issue by Jieoz** [Tornaco/Thanox#1064]
**Describe the bug（现象描述）**
安卓14禁用获取应用列表功能失效
**To Reproduce**（如何复现）
1.下载devcheck
2.打开应用程序标签
3.可以看到依旧可以获取到应用列表清单

**Expected behavior**（期望结果）
在安卓12系统上发现是可以禁止读取的

**Screenshots**（截图）
![](https://pnglog.com/XuTZVU.png)

**Version（发现问题的版本）:**
 - OS: Android 14
 - Version5.1.7-prcthanox@tornaco:a659618e-ad45-4b72-ad67-85bd3e3b4a26 lsposed

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
https://wwqq.lanzoub.com/iUgxa2e0pkyb

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？![Thanox-Log-2024-11-02-10_59_10.zip](https://github.com/user-attachments/files/17605373/Thanox-Log-2024-11-02-10_59_10.zip)

> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by StrollStars** [comment]
我也有这个感觉，但是未能证实。
@Jieoz 你用的是Xposed模式还是Magisk模式？

**Comment by Jieoz** [comment]
> 我也有这个感觉，但是未能证实。
> @Jieoz 你用的是Xposed模式还是Magisk模式？

lsposed模式运行的

**Comment by Tornaco** [comment]
@Jieoz 试试这个版本 https://app.circleci.com/pipelines/github/Tornaco/Thanox/1365/workflows/abf84ce8-d3af-4dbe-adc9-6b87db6e2d7f/jobs/1253/artifacts

**Comment by Jieoz** [comment]
> @Jieoz 试试这个版本 https://app.circleci.com/pipelines/github/Tornaco/Thanox/1365/workflows/abf84ce8-d3af-4dbe-adc9-6b87db6e2d7f/jobs/1253/artifacts

没问题了老大👌

**Comment by StrollStars** [comment]
> > 我也有这个感觉，但是未能证实。
> > @Jieoz 你用的是Xposed模式还是Magisk模式？
> 
> lsposed模式运行的

用的是[mywalkb的版本](https://github.com/mywalkb/LSPosed_mod)吧？原来的都存档了。
