### ISSUE TITLE
play最新版本ui问题

### ISSUE THREAD

**Issue by HanHanOuyeE** [Tornaco/Thanox#1066]
![IMG_20241104_212225.jpg](https://github.com/user-attachments/assets/501a23be-790b-4777-a6a2-639e3f95cf68)

ui靠上已经顶到了状态栏的位置
一加 ace3
安卓15 cos15系统

**Comment by Tornaco** [comment]
@HanHanOuyeE android15行为变更，我晚一些会适配。

**Comment by HanHanOuyeE** [comment]
> @HanHanOuyeE android15行为变更，我晚一些会适配。

好的，我看到其他界面貌似没什么问题，情景模式下的所有界面都是有这种问题

**Comment by Tornaco** [comment]
beta 频道已经推送修改版，如有问题请继续report
