### ISSUE TITLE
[bug] 后台疯狂报错

### ISSUE THREAD

**Issue by lamprose** [Tornaco/Thanox#1067]
**Describe the bug（现象描述）**
软件疯狂报错导致LSP日志全被thanox塞满
**To Reproduce**（如何复现）
打开LSP日志即可发现
**Expected behavior**（期望结果）
去除报错，至少报错一次后就好了 不要后台疯狂报错
**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [ColorOS15,Android 15]
 - Version [5.2.1]

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
[modules_2024-11-05T005240.991801.log](https://github.com/user-attachments/files/17625908/modules_2024-11-05T005240.991801.log)

**Comment by Tornaco** [comment]
@lamprose 发下system/framework/services.jar

**Comment by lamprose** [comment]
> @lamprose 发下system/framework/services.jar

[system/framework/services.jar](https://wwma.lanzoub.com/ixjsW2eblwde)   密码:6ejt

**Comment by Tornaco** [comment]
@lamprose 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/1345/workflows/0987a1fa-127f-4efe-8bcf-e99eb67bf7a4/jobs/1238/artifacts

如果你是Play版本，留下Google邮箱我可以推测试版给你。

**Comment by lamprose** [comment]
> @lamprose 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/1345/workflows/0987a1fa-127f-4efe-8bcf-e99eb67bf7a4/jobs/1238/artifacts
> 
> 如果你是Play版本，留下Google邮箱我可以推测试版给你。

测试已经不会疯狂报错了  现在就几行正常日志
[modules_2024-11-07T093900.384318.log](https://github.com/user-attachments/files/17654903/modules_2024-11-07T093900.384318.log)
