### ISSUE TITLE
情景模式设置屏幕方向无效ui.setRequestedOrientation(0)

### ISSUE THREAD

**Issue by Liberations** [Tornaco/Thanox#1069]
**Describe the bug（现象描述）**
情景模式设置屏幕方向无效
ui.setRequestedOrientation(0)
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
情景模式新增如下代码
`[
  {
    "name": "Current pkg",
    "description": "应用切换时，使用Toast显示当前应用的当前应用包名（仅做示例，请自行优化）",
    "priority": 2,
    "condition": "frontPkgChanged == true",
    "actions": ["ui.requestScreenOrientation(0);" ]
  }
]`

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[profile.log](https://github.com/user-attachments/files/17641291/profile.log)
[thanox-core.log](https://github.com/user-attachments/files/17641292/thanox-core.log)
[thanox-init.log](https://github.com/user-attachments/files/17641294/thanox-init.log)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
Xiaomi HyperOS android14
> 2. Thanox版本，补丁方式（xposed还是magisk？）
5.0.8-prc LSPosed
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Liberations** [comment]
#974

**Comment by Liberations** [comment]
哦哦 最新的正常 `[ { "name": "Current pkg", "description": "应用切换时，使用Toast显示当前应用的当前应用包名（仅做示例，请自行优化）", "priority": 2, "condition": "activityResumed", "actions": ["ui.requestScreenOrientation(0);" ] } ]`

**Comment by Tornaco** [comment]
OK 那就close
