### ISSUE TITLE
5.2.3阻止唤醒失败导致的手机触控短暂失效

### ISSUE THREAD

**Issue by Know233** [Tornaco/Thanox#1093]
系统：miui14.0.31.0，安卓13，激活方式xposed
现象：更新完thanox_5.2.3后使用com.hihonor.cloudmusic(网易音乐定制版)概率出现屏幕卡死无法触控但是显示正常的状态，此时手机没有软重启，输入法光标正常闪烁，后续疑似随着歌曲缓冲或缓冲完毕卡死恢复，卡死时长5秒至10秒不等。
bug复现过程：观察后台发现该定制版会不定期唤醒com.apkpure.aegon与com.xunmeng.pinduoduo与com.huawei.hwid与com.hihonor.id，如果把上述apkpure或pdd后台杀掉再看就比较像是在重新唤醒时会出现卡死。(com.apkpure.aegon与com.xunmeng.pinduoduo都已设置thanox冻结且都打开了活检解冻)，在thanox中关闭com.hihonor.cloudmusic的后台启动按钮且设置打开其他应用为询问上述唤醒看起来还是正常进行，后续卸载了apkpure，pdd设置唤醒锁禁止且关闭活检解冻，卡顿情况基本消失

**Comment by Know233** [comment]
[Uploading Thanox-Log-2024-11-28-11_19_33.zip…]()

**Comment by Know233** [comment]
[Thanox-Log-2024-11-28-11_19_33.zip](https://github.com/user-attachments/files/17953392/Thanox-Log-2024-11-28-11_19_33.zip)

**Comment by Tornaco** [comment]
@Know233 请测试下这个版本是否还有此类问题，如果还有问题，需要你在lspose中导出一份日志发给我，同时看下/data/anr中是否有日志文件，如果有，也要发给我。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/1404/workflows/6499a9ec-8f0f-46ed-a318-c89f47c4093c/jobs/1291/artifacts

**Comment by Know233** [comment]
由于系统应用bug遂升级系统至a14，hyperos1.0.13.0，使用了上述测试版一周，暂时没有碰到触控短暂失效的情况，关闭issue
