### ISSUE TITLE
Cant install thanox as magisk module

### ISSUE THREAD

**Issue by georgerabus** [Tornaco/Thanox#1098]
I installed the apk, then renamed the file from .apk to .zip, installed the module in magisk, it says done but I dont see the module in the list. Any help?

**Comment by Tornaco** [comment]
@georgerabus Pls provide the version info of the apk, and also the error log. and reopen this issue when you get things ready.

**Comment by georgerabus** [comment]
There is no error log
I purchased the Thanox Pro version from google play store 

![Screenshot_20241210_142402_Thanox Pro.jpg](https://github.com/user-attachments/assets/28564f86-633a-4531-a4ec-06bb0f27da39)

![Screenshot_20241210_142628.jpg](https://github.com/user-attachments/assets/63538ab1-03ad-4daa-a8c2-df7afa25ba31)

The module is missing from the module list.

Using magisk 28.1

**Comment by Tornaco** [comment]
@georgerabus You can join the Beta program on Play store Thanox app detail page. Latest version is 5.2.3, that issue has been fixed.

**Comment by georgerabus** [comment]
> @georgerabus You can join the Beta program on Play store Thanox app detail page. Latest version is 5.2.3, that issue has been fixed.

![Screenshot_20241211_142007_Thanox Pro.jpg](https://github.com/user-attachments/assets/f066382f-d683-40fa-b1a1-b599ef42b06c)

![Screenshot_20241211_142028.jpg](https://github.com/user-attachments/assets/5b96f5d3-9d3c-4f34-8982-cbf2a5acfc17)

Joined beta program, updates to 5.2.3 but still the module is missing and thanox pro is not active

Installation attempt on magisk 28.1

**Comment by Tornaco** [comment]
@georgerabus You can try active with Xposed(LSPosed), Magisk patch was not maintained since 2023.

**Comment by georgerabus** [comment]
> @georgerabus You can try active with Xposed(LSPosed), Magisk patch was not maintained since 2023.

when will it get more maintenance for magisk? I don't want to install xposed

**Comment by Tornaco** [comment]
@georgerabus I'm not sure. Patching with Magisk takes a lot of time, but I don't have that much

**Comment by GT13Lowe** [comment]
So as of now (May 2026) is it not possible to run Thanox in Magisk mode? If that's the case do you plan to update it so it's compatible with xposed api 101 like Vector?
