### ISSUE TITLE
冻结应用时，xposed框架有错误日志产生。

### ISSUE THREAD

**Issue by 4512369781** [Tornaco/Thanox#11]
**Describe the bug（现象描述）**
冻结应用时，或者说使用disable命令禁用应用组件，xposed日志里会有错误日志。

**Version（发现问题的版本）**
 - OS: Android 8.1.0
 - Version: v1.0.0-rc6

** Logs（日志文件）**
12-13 14:16:26.261 I/Xposed  (  691): -----------------
12-13 14:16:26.261 I/Xposed  (  691): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27
12-13 14:16:26.261 I/Xposed  (  691): Device: TA-1041 (HMD Global), Android version 8.1.0 (SDK 27)
12-13 14:16:26.261 I/Xposed  (  691): ROM: 00CN_2_24G
12-13 14:16:26.261 I/Xposed  (  691): Build fingerprint: Nokia/TA-1041_00CN/C1N:8.1.0/OPR1.170623.026/00CN_2_24G:user/release-keys
12-13 14:16:26.261 I/Xposed  (  691): Platform: arm64-v8a, 64-bit binary, system server: yes
12-13 14:16:26.261 I/Xposed  (  691): SELinux enabled: yes, enforcing: yes
12-13 14:16:26.288 I/Xposed  (  691): -----------------
12-13 14:16:26.288 I/Xposed  (  691): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-12 23:16:42.201 I/Xposed  (  691): Detected ART runtime
11-12 23:16:42.206 I/Xposed  (  691): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-12 23:16:43.726 I/Xposed  (  691): Loading modules from /data/app/bin.xposed.screenshotdelayremover.mod-Lv8fNz1RXjjX6hMSXv8hkg==/base.apk
11-12 23:16:43.747 I/Xposed  (  691):   Loading class bin.xposed.screenshotdelayremover.mod.XposedMod
11-12 23:16:43.748 I/Xposed  (  691): Loading modules from /data/app/com.jozein.xedgepro-ekjQCneot6vIxu2nYbeisA==/base.apk
11-12 23:16:43.814 I/Xposed  (  691):   Loading class com.jozein.xedgepro.xposed.HookMain
11-12 23:16:43.820 I/Xposed  (  691): [XEdgePro] android.system.ErrnoException: stat failed: EACCES (Permission denied)
11-12 23:16:43.878 I/Xposed  (  691): Loading modules from /data/app/ru.oEtSTDLk.PXFvMvjfF-rtY8jgOJCvV2MYnnXmoTpA==/base.apk
11-12 23:16:44.027 I/Xposed  (  691):   Loading class com.xposed.XSupport
11-12 23:16:44.051 I/Xposed  (  691): Loading modules from /data/app/li.lingfeng.ltweaks-_LDWWHixkrJz207LCJR1MQ==/base.apk
11-12 23:16:44.349 I/Xposed  (  691):   Loading class li.lingfeng.ltweaks.xposed.XposedLoader
11-12 23:16:44.425 I/Xposed  (  691): Loading modules from /data/app/com.flarejune.xposedblacklist-T6TcYVUPTdd_lGXtAt-cOQ==/base.apk
11-12 23:16:44.440 I/Xposed  (  691):   Loading class com.flarejune.xposedblacklist.XposedHook
11-12 23:16:44.444 I/Xposed  (  691): Loading modules from /data/app/com.darkeyes.tricks-KsQ-_esFthOxQOJTEvvk0w==/base.apk
11-12 23:16:44.465 I/Xposed  (  691):   Loading class com.darkeyes.tricks.Main
11-12 23:16:44.469 I/Xposed  (  691): Loading modules from /data/app/com.crossbowffs.nekosms-gc58NQmoQpfVMYfrU3PZEQ==/base.apk
11-12 23:16:44.567 I/Xposed  (  691):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
11-12 23:16:44.583 I/Xposed  (  691):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
11-12 23:16:44.584 I/Xposed  (  691): Loading modules from /data/app/xyz.paphonb.androidpify-IGggz-r9A9PIY2THLxjixA==/base.apk
11-12 23:16:44.786 I/Xposed  (  691):   Loading class xyz.paphonb.androidpify.XposedHook
11-12 23:16:44.827 I/Xposed  (  691): Loading modules from /data/app/dev.ukanth.ufirewall.donate-XrT00e9wIahmphFxed1aFg==/base.apk
11-12 23:16:45.215 I/Xposed  (  691):   Loading class dev.ukanth.ufirewall.xposed.XposedInit
11-12 23:16:45.239 I/Xposed  (  691): Loading modules from /data/app/com.sudocode.sudohide-pcH8S-qF849ba7epovf8kg==/base.apk
11-12 23:16:45.368 I/Xposed  (  691):   Loading class com.sudocode.sudoHideModule.XposedMain
11-12 23:16:45.384 I/Xposed  (  691): Loading modules from /data/app/ru.timjosten.disablepinripple-e34FkhWj_Ttl8jQapaNR-g==/base.apk
11-12 23:16:45.402 I/Xposed  (  691):   Loading class ru.timjosten.disablepinripple.DisablePINRipple
11-12 23:16:45.404 I/Xposed  (  691): Loading modules from /data/app/github.tornaco.android.thanos-eDD3kAG_DthjSkSCH_v5FQ==/base.apk
11-12 23:16:45.659 I/Xposed  (  691):   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
11-12 23:16:45.798 I/Xposed  (  691): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@32c798b]
11-12 23:16:45.800 I/Xposed  (  691): Loading modules from /data/app/fi.veetipaananen.android.disableflagsecure-eXjzB48Rymn457LCuwHtXQ==/base.apk
11-12 23:16:45.816 I/Xposed  (  691):   Loading class fi.veetipaananen.android.disableflagsecure.DisableFlagSecureModule
11-12 23:16:45.817 I/Xposed  (  691): Loading modules from /data/app/com.ceco.oreo.gravitybox-HjOxzUp93hYJycWe47bIlA==/base.apk
11-12 23:16:45.973 I/Xposed  (  691):   Loading class com.ceco.oreo.gravitybox.GravityBox
11-12 23:16:45.992 I/Xposed  (  691): GB:Hardware: qcom
11-12 23:16:45.992 I/Xposed  (  691): GB:Product: TA-1041_00CN
11-12 23:16:45.992 I/Xposed  (  691): GB:Device manufacturer: HMD Global
11-12 23:16:45.992 I/Xposed  (  691): GB:Device brand: Nokia
11-12 23:16:45.992 I/Xposed  (  691): GB:Device model: TA-1041
11-12 23:16:45.994 I/Xposed  (  691): GB:Device type: phone
11-12 23:16:45.996 I/Xposed  (  691): GB:Is MTK device: false
11-12 23:16:45.996 I/Xposed  (  691): GB:Is Xperia device: false
11-12 23:16:45.996 I/Xposed  (  691): GB:Is Moto XT device: false
11-12 23:16:45.997 I/Xposed  (  691): GB:Is OxygenOS ROM: false
11-12 23:16:45.997 I/Xposed  (  691): GB:Has telephony support: true
11-12 23:16:45.997 I/Xposed  (  691): GB:Has Gemini support: false
11-12 23:16:45.997 I/Xposed  (  691): GB:Android SDK: 27
11-12 23:16:45.997 I/Xposed  (  691): GB:Android Release: 8.1.0
11-12 23:16:45.997 I/Xposed  (  691): GB:ROM: 00CN_2_24G
11-12 23:16:45.997 I/Xposed  (  691): GB:Error logging: false
11-12 23:16:49.856 I/Xposed  (  692): -----------------
11-12 23:16:49.856 I/Xposed  (  692): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27
11-12 23:16:49.856 I/Xposed  (  692): Device: TA-1041 (HMD Global), Android version 8.1.0 (SDK 27)
11-12 23:16:49.856 I/Xposed  (  692): ROM: 00CN_2_24G
11-12 23:16:49.856 I/Xposed  (  692): Build fingerprint: Nokia/TA-1041_00CN/C1N:8.1.0/OPR1.170623.026/00CN_2_24G:user/release-keys
11-12 23:16:49.856 I/Xposed  (  692): Platform: arm64-v8a, 32-bit binary, system server: no
11-12 23:16:49.856 I/Xposed  (  692): SELinux enabled: yes, enforcing: yes
11-12 23:16:49.859 I/Xposed  (  692): -----------------
11-12 23:16:49.859 I/Xposed  (  692): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-12 23:16:51.066 I/Xposed  (  692): Detected ART runtime
11-12 23:16:51.069 I/Xposed  (  692): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-12 23:16:51.399 I/Xposed  (  692): Loading modules from /data/app/bin.xposed.screenshotdelayremover.mod-Lv8fNz1RXjjX6hMSXv8hkg==/base.apk
11-12 23:16:51.409 I/Xposed  (  692):   Loading class bin.xposed.screenshotdelayremover.mod.XposedMod
11-12 23:16:51.410 I/Xposed  (  692): Loading modules from /data/app/com.jozein.xedgepro-ekjQCneot6vIxu2nYbeisA==/base.apk
11-12 23:16:51.445 I/Xposed  (  692):   Loading class com.jozein.xedgepro.xposed.HookMain
11-12 23:16:51.451 I/Xposed  (  692): [XEdgePro] android.system.ErrnoException: stat failed: EACCES (Permission denied)
11-12 23:16:51.490 I/Xposed  (  692): Loading modules from /data/app/ru.oEtSTDLk.PXFvMvjfF-rtY8jgOJCvV2MYnnXmoTpA==/base.apk
11-12 23:16:51.610 I/Xposed  (  692):   Loading class com.xposed.XSupport
11-12 23:16:51.635 I/Xposed  (  692): Loading modules from /data/app/li.lingfeng.ltweaks-_LDWWHixkrJz207LCJR1MQ==/base.apk
11-12 23:16:51.932 I/Xposed  (  692):   Loading class li.lingfeng.ltweaks.xposed.XposedLoader
11-12 23:16:51.997 I/Xposed  (  692): Loading modules from /data/app/com.flarejune.xposedblacklist-T6TcYVUPTdd_lGXtAt-cOQ==/base.apk
11-12 23:16:52.008 I/Xposed  (  692):   Loading class com.flarejune.xposedblacklist.XposedHook
11-12 23:16:52.012 I/Xposed  (  692): Loading modules from /data/app/com.darkeyes.tricks-KsQ-_esFthOxQOJTEvvk0w==/base.apk
11-12 23:16:52.022 I/Xposed  (  692):   Loading class com.darkeyes.tricks.Main
11-12 23:16:52.025 I/Xposed  (  692): Loading modules from /data/app/com.crossbowffs.nekosms-gc58NQmoQpfVMYfrU3PZEQ==/base.apk
11-12 23:16:52.107 I/Xposed  (  692):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
11-12 23:16:52.116 I/Xposed  (  692):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
11-12 23:16:52.116 I/Xposed  (  692): Loading modules from /data/app/xyz.paphonb.androidpify-IGggz-r9A9PIY2THLxjixA==/base.apk
11-12 23:16:52.294 I/Xposed  (  692):   Loading class xyz.paphonb.androidpify.XposedHook
11-12 23:16:52.331 I/Xposed  (  692): Loading modules from /data/app/dev.ukanth.ufirewall.donate-XrT00e9wIahmphFxed1aFg==/base.apk
11-12 23:16:52.647 I/Xposed  (  692):   Loading class dev.ukanth.ufirewall.xposed.XposedInit
11-12 23:16:52.686 I/Xposed  (  692): Loading modules from /data/app/com.sudocode.sudohide-pcH8S-qF849ba7epovf8kg==/base.apk
11-12 23:16:52.793 I/Xposed  (  692):   Loading class com.sudocode.sudoHideModule.XposedMain
11-12 23:16:52.804 I/Xposed  (  692): Loading modules from /data/app/ru.timjosten.disablepinripple-e34FkhWj_Ttl8jQapaNR-g==/base.apk
11-12 23:16:52.817 I/Xposed  (  692):   Loading class ru.timjosten.disablepinripple.DisablePINRipple
11-12 23:16:52.818 I/Xposed  (  692): Loading modules from /data/app/github.tornaco.android.thanos-eDD3kAG_DthjSkSCH_v5FQ==/base.apk
11-12 23:16:53.052 I/Xposed  (  692):   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
11-12 23:16:53.162 I/Xposed  (  692): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@aa9d80b]
11-12 23:16:53.208 I/Xposed  (  692): Loading modules from /data/app/fi.veetipaananen.android.disableflagsecure-eXjzB48Rymn457LCuwHtXQ==/base.apk
11-12 23:16:53.218 I/Xposed  (  692):   Loading class fi.veetipaananen.android.disableflagsecure.DisableFlagSecureModule
11-12 23:16:53.219 I/Xposed  (  692): Loading modules from /data/app/com.ceco.oreo.gravitybox-HjOxzUp93hYJycWe47bIlA==/base.apk
11-12 23:16:53.355 I/Xposed  (  692):   Loading class com.ceco.oreo.gravitybox.GravityBox
11-12 23:16:54.292 E/Xposed  ( 2011): Zygote service is not accessible from PID 2011, UID 1000
11-12 23:16:54.311 I/Xposed  ( 2011): [XEdgePro] Xposed edge pro 5.5.1. HMD Global TA-1041, C1N, Android 8.1.0, SDK 27, ROM: 00CN_2_24G, SELinux enforced.
11-12 23:16:54.552 I/Xposed  ( 2011): [XEdgePro] System hooked
11-12 23:16:54.754 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedPreventReceiver for android, with prefs []
11-12 23:16:54.762 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedPreventExactAlarm for android, with prefs []
11-12 23:16:54.764 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedDarkWallpaperColor for android, with prefs [2131755132]
11-12 23:16:54.768 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedPreventForegroundService for android, with prefs []
11-12 23:16:54.769 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedPreventWakeLock for android, with prefs []
11-12 23:16:54.769 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedSetInactive for android, with prefs []
11-12 23:16:54.770 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedTrustAgentWifi for android, with prefs []
11-12 23:16:54.777 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedShareFilter for android, with prefs []
11-12 23:16:54.786 I/Xposed  ( 2011): Load li.lingfeng.ltweaks.xposed.system.XposedTextActions for all packages (exclude 1), with prefs []
11-12 23:16:54.787 I/Xposed  ( 2011): GB:Is AOSP forced: true
11-12 23:16:55.856 I/Xposed  ( 2011): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: clean_up_on_task_removed_pkgs
11-12 23:16:55.877 I/Xposed  ( 2011): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: app_lock_pkgs
11-12 23:16:55.885 I/Xposed  ( 2011): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: component_replacements
11-12 23:16:55.889 I/Xposed  ( 2011): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_device_id
11-12 23:16:55.891 I/Xposed  ( 2011): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_line1_num
11-12 23:16:55.893 I/Xposed  ( 2011): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: priv_sim_num
11-12 23:16:55.905 I/Xposed  ( 2011): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: reminding_ops
11-12 23:16:55.906 I/Xposed  ( 2011): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: op_reminding_pkgs
11-12 23:16:55.908 I/Xposed  ( 2011): [ThanosS][StringMapRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: op_template
11-12 23:16:55.928 I/Xposed  ( 2011): [ThanosS][StringSetRepo][u:0][t:ThanosSchedulers]	getBaseFile not exists, skip load: screen_on_notification_pkgs
11-12 23:17:00.426 I/Xposed  ( 2011): [XEdgePro] Screen size: 1080, 1920
11-12 23:17:01.797 I/Xposed  ( 2011): WallpaperColors is changed, but keep it black.
11-12 23:17:07.829 W/Xposed  ( 2575): useZygotePreferences, but instance exists.
11-12 23:17:07.829 I/Xposed  ( 2575): Load li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoMarket for com.android.settings, with prefs [2131755112]
11-12 23:17:07.838 I/Xposed  ( 2523): NekoSMS: NekoSMS initializing...
11-12 23:17:07.838 I/Xposed  ( 2523): NekoSMS: Phone manufacturer: HMD Global
11-12 23:17:07.838 I/Xposed  ( 2523): NekoSMS: Phone model: TA-1041
11-12 23:17:07.839 I/Xposed  ( 2523): NekoSMS: Android version: 8.1.0
11-12 23:17:07.839 I/Xposed  ( 2523): NekoSMS: Xposed bridge version: 90
11-12 23:17:07.839 I/Xposed  ( 2523): NekoSMS: NekoSMS version: 0.17.0 (34)
11-12 23:17:07.839 I/Xposed  ( 2523): NekoSMS: Hooking InboundSmsHandler constructor for Android v24+
11-12 23:17:07.843 I/Xposed  ( 2523): NekoSMS: Hooking dispatchIntent() for Android v23+
11-12 23:17:07.845 I/Xposed  ( 2523): NekoSMS: NekoSMS initialization complete!
11-12 23:17:07.880 W/Xposed  ( 2575): useZygotePreferences, but instance exists.
11-12 23:17:07.881 W/Xposed  ( 2575): useZygotePreferences, but instance exists.
11-12 23:17:07.881 I/Xposed  ( 2575): Load li.lingfeng.ltweaks.xposed.system.XposedAppInfoGoAppData for com.android.settings, with prefs [2131755113]
11-12 23:17:07.896 W/Xposed  ( 2575): useZygotePreferences, but instance exists.
11-12 23:17:08.325 I/Xposed  ( 2011): [XEdgePro] Display info{ initial size(1080, 1920), forced size(1080, 1920), initial density=420, scaled density=420 }
11-12 23:17:08.363 I/Xposed  ( 2011): [XEdgePro] Module initialed.
11-12 23:17:08.369 I/Xposed  ( 2523): NekoSMS: Registering SMS filter content observer
11-12 23:17:08.372 I/Xposed  ( 2523): NekoSMS: Registering app package state receiver
11-12 23:17:08.382 I/Xposed  ( 2523): NekoSMS: Checking if we have OP_WRITE_SMS permission
11-12 23:17:08.384 I/Xposed  ( 2523): NekoSMS: Already have OP_WRITE_SMS permission
**11-12 23:18:39.718 E/Xposed  ( 2011): d.c
11-12 23:18:39.718 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyService.isUidPrivacyDataCheat(Unknown Source:36)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyManagerStub.isUidPrivacyDataCheat(Unknown Source:2)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.xposed.hooks.privacy.PMSGetInstalledPackagesRegistry$1.beforeHookedMethod(Unknown Source:28)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.getInstalledPackages(<Xposed>)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:897)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
11-12 23:18:39.718 E/Xposed  ( 2011): 	at android.os.Binder.execTransact(Binder.java:697)
11-12 23:18:40.104 E/Xposed  ( 2011): d.c
11-12 23:18:40.104 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyService.isUidPrivacyDataCheat(Unknown Source:36)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyManagerStub.isUidPrivacyDataCheat(Unknown Source:2)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.xposed.hooks.privacy.PMSGetInstalledPackagesRegistry$1.beforeHookedMethod(Unknown Source:28)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.getInstalledPackages(<Xposed>)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:897)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
11-12 23:18:40.104 E/Xposed  ( 2011): 	at android.os.Binder.execTransact(Binder.java:697)
11-12 23:18:42.477 E/Xposed  ( 2011): d.c
11-12 23:18:42.477 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyService.isUidPrivacyDataCheat(Unknown Source:36)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyManagerStub.isUidPrivacyDataCheat(Unknown Source:2)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.xposed.hooks.privacy.PMSGetInstalledPackagesRegistry$1.beforeHookedMethod(Unknown Source:28)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.getInstalledPackages(<Xposed>)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:897)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
11-12 23:18:42.477 E/Xposed  ( 2011): 	at android.os.Binder.execTransact(Binder.java:697)
11-12 23:18:44.090 E/Xposed  ( 2011): d.c
11-12 23:18:44.090 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyService.isUidPrivacyDataCheat(Unknown Source:36)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.secure.PrivacyManagerStub.isUidPrivacyDataCheat(Unknown Source:2)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at github.tornaco.android.thanos.services.xposed.hooks.privacy.PMSGetInstalledPackagesRegistry$1.beforeHookedMethod(Unknown Source:28)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.getInstalledPackages(<Xposed>)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:897)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
11-12 23:18:44.090 E/Xposed  ( 2011): 	at android.os.Binder.execTransact(Binder.java:697)**
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Open App Data Folder
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Open App External Data Folder
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Open Device Encrypted Storage
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Open APK Folder
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Google Play
11-12 23:19:11.864 I/Xposed  ( 2575): New menu CoolApk
11-12 23:19:11.864 I/Xposed  ( 2575): New menu ApkPure
11-12 23:19:11.864 I/Xposed  ( 2575): New menu Mobilism
11-12 23:19:11.864 I/Xposed  ( 2575): New menu ApkMirror
11-12 23:21:32.776 I/XposedInstaller(13698): Downloaded https://dl.xposed.info/repo/partial/17944.xml.gz with status 0 (error: null), size 66 bytes
11-12 23:21:32.780 I/XposedInstaller(13698): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 17944 (0 new / 0 removed modules)

**Comment by Tornaco** [comment]
👍
