### ISSUE TITLE
Thanox导致Keep应用陷入账号异常loop

### ISSUE THREAD

**Issue by JunfXiao** [Tornaco/Thanox#116]
**Describe the bug（现象描述）**
启用Thanox且允许Keep所有权限时，打开Keep，则会无限弹出“用户token校验失败”及“账号异常”消息，导致无法正常使用应用。

**To Reproduce**（如何复现）
1. 在EdXposed中启用Thanox
2. 从酷安安装Keep（此时，处于**未登录**状态），不限制其任意权限。
3. 打开Keep并登录
4. 提示“用户token校验失败”，且无限弹出不可取消的Dialog。

**Expected behavior**（期望结果）
能够正常登录、使用Keep应用。

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![Screenshot_20200331-192029.jpg](https://i.loli.net/2020/04/01/X4fpYdrC1NvKSjs.jpg)![Screenshot_20200331-191450.jpg](https://i.loli.net/2020/04/01/VjXCEbvTu867Y93.jpg)

**Version（发现问题的版本）:**
 - OS: Oxygen OS Android 10

 - Version :Thenox 1.2.0-prc，Keep 6.38.0

**Additional context**（其他信息）
设备:一加7Pro

** Logs**（日志文件）
仅在*thanox-core*下日志中找到有用的相关信息：
1585741463311|W|ThanosS|PkgPool app: AppInfo(pkgName=com.gotokeep.keep, appLabel=Keep, versionCode=23896, versionName=6.38.0, flags=1, uid=10420, debuggable=false, minSdkVersion=21, targetSdkVersion=26, state=0, idle=false, isDummy=false, isSelected=false, payload=null)

**临时解决方案**
进入EdXposed关闭Thanox，重启后进入Keep登录账号，而后再次开启Thanox并重启，则Keep账号保持登录状态，不再陷入Loop。

**Comment by Tornaco** [comment]
@ForInfinity  移花接木有相关规则吗？

**Comment by JunfXiao** [comment]
> @ForInfinity 移花接木有相关规则吗？

解决了，是移花接木规则的问题。默认从splash activity跳转到main activity，导致了异常。
