### ISSUE TITLE
在关屏后能直接打开开启应用锁的软件

### ISSUE THREAD

**Issue by s235784** [Tornaco/Thanox#130]
现象描述:
开启应用锁的软件在手机关屏后按返回能直接打开该软件

如何复现:
1.开启任意软件的应用锁功能
2.打开该软件，并解锁应用
3.关屏
4.重新打开屏幕
5.在出现要求解锁的界面直接返回
6.有应用锁的软件未解锁就能打开

期望结果:
未解锁的软件应直接返回桌面而不是打开软件

发现问题的版本:
 - OS: Android10
 - Version: 1.2.0-prc

**Comment by Tornaco** [comment]
@s235784 正常情况下解锁系统锁屏后，Thanox验证界面点击返回后，Thanox是会强制返回桌面。

如果要定位你的问题，还需要发下日志。

**Comment by Tornaco** [comment]
```java
@ExecuteBySystemHandler
    private void onUserPresent() {
        String frontPkg = getCurrentFrontApp();
        if (isAppLockEnabled()
                && isVerifyOnScreenOffEnabled()
                && isPackageLocked(frontPkg)
                && shouldVerifyActivityStarting(getCurrentFrontComponentName(), frontPkg, "User present.")) {
            verifyActivityStarting(null, frontPkg, getCurrentFrontComponentName(), 0, 0, new IVerifyCallback.Stub() {
                @Override
                public void onVerifyResult(int verifyResult, int reason) {
                    if (verifyResult != VerifyResult.ALLOW) {
                        XLog.w("Inject home key, since verify failure.");
                        // Mock home button.
                        KeyEventSender.injectHomeKey();
                    }
                }
            });
        }
    }
```

**Comment by s235784** [comment]
[thanox-core.log](https://github.com/Tornaco/Thanox/files/4579358/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/4579359/thanox-init.log)

**Comment by s235784** [comment]
> ```java
> 
>                 && isVerifyOnScreenOffEnabled()
> ```

[thanox-core.log](https://github.com/Tornaco/Thanox/files/4579358/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/4579359/thanox-init.log)

**Comment by s235784** [comment]
> @s235784 正常情况下解锁系统锁屏后，Thanox验证界面点击返回后，Thanox是会强制返回桌面。
> 
> 如果要定位你的问题，还需要发下日志。

[thanox-core.log](https://github.com/Tornaco/Thanox/files/4579358/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/4579359/thanox-init.log)
