### ISSUE TITLE
乖巧模式中，开启“跳过有通知的应用”，在网易云听歌期间，状态栏有通知，但是无法点击网易云通知的所有按钮

### ISSUE THREAD

**Issue by sidesand** [Tornaco/Thanox#131]
**Describe the bug（现象描述）**
乖巧模式中，策略中开启了“跳过有通知的”、“休眠应用”、“阻止后台服务重启”三个选项，开启网易云音乐4.3.1版本(我记得新版网易云也是)的乖巧模式（没有使用任何乖巧规则），在播放音乐的时候，有音乐通知，正常播放，但是无法点击使用网易云通知中的所有按键（暂停、下一首等），我测试了一下，如果关闭策略中的“阻止后台服务重启”，则能正常使用通知中的按钮。

**Expected behavior**（期望结果）
我本理解的时，只要该应用有通知，则不执行乖巧的策略，所以按道理来说可以使用通知按钮。

**Version（发现问题的版本）:**
 - OS: [e.g. Android 10]
 - Version [e.g. v1.2.1]

还有另外一个事情，在不乖巧网易云的情况下，使用情景模式中的setInactive(pkgName)命令，比如设置任务网易云通知取消，休眠网易云。当通知取消后台休眠网易云后，长久使用不使用网易云（短期内没问题），再次打开，网易云无法播放音乐（所有界面能点击进去，如进入评论啊，歌单都可以），查看后台服务，有关播放的几个服务都在后台运行，但是就是无法播放、切歌，这个现象有点难复现，我猜测是不是休眠后（即使是使用setInactive而不是乖巧的休眠）就会阻止该服务唤醒？

**Comment by Tornaco** [comment]
@sidesand 拦截服务的时候，这块逻辑漏掉了，应该需要检查是不是有通知再确认拦截。

```java
if (!smartStandByBypassIfHasNotificationEnabled 
                    || !s.getNotificationManagerService().hasNotificationRecordsForPackage(servicePkg)) {
                return new StartResultExt(StartResult.BLOCKED_STANDBY, servicePkg);
            }
```

补上了这个判断，下个版本试试。
