### ISSUE TITLE
移动网络功能操作

### ISSUE THREAD

**Issue by zy10010** [Tornaco/Thanox#133]
1.情景模式现有数据功能只能凭借subid进行操作，但此项定义为插入一张新卡，数值递增，且不好查询，建议更换为slotid，即卡槽判别，操作更为简便，容易操作和理解
2.获取移动数据开启状态，现只能得到总体状态，希望能够细化到获取sim1和sim2，即当前是否sim1卡网络，便于切换操作

仅为个人使用过程中用到的因素提出意见，烦扰之处望理解

**Comment by Tornaco** [comment]
Added.
