### ISSUE TITLE
关于edxp通过safetynet

### ISSUE THREAD

**Issue by ghost** [Tornaco/Thanox#139]

**Comment by Tornaco** [comment]
F**k safetynet.

**Comment by fucksafetynet** [comment]
> F ** k安全网。

今天更新了20.5.19内测版，sn再次通过。这次没有丢失配置
![Screenshot_2020-05-19-21-40-47-547_github tornaco android thanos pro](https://user-images.githubusercontent.com/58792941/82333536-6e15be00-9a19-11ea-92d7-cc58933203c4.png)
![Screenshot_2020-05-19-21-20-44-668_com topjohnwu magisk](https://user-images.githubusercontent.com/58792941/82333543-71a94500-9a19-11ea-8fbb-8e38830baae1.png)
![Screenshot_2020-05-19-21-36-29-957_com android vending](https://user-images.githubusercontent.com/58792941/82333554-753ccc00-9a19-11ea-9a67-f27946c1af76.png)

**Comment by aruato** [comment]
情景模式  shell命令还是无法运行  
[{"name": "关闭屏幕，打开省电模式",
"description": "设置powersave模式",
"priority": 2,
"condition":
"screenOff == true",
"actions": [ " sh.exe(\"/data/powercfg.sh powersave\")"] }]   代码应该没问题吧  可是无法生效

**Comment by aruato** [comment]
1.2.7  QQ不进缓存了

**Comment by fucksafetynet** [comment]
![Screenshot_2020-05-22-14-58-06-902_com android vending](https://user-images.githubusercontent.com/58792941/82640194-be209a80-9c3c-11ea-996e-ff6f0666845a.png)
![Screenshot_2020-05-22-14-56-48-609_github tornaco android thanos pro](https://user-images.githubusercontent.com/58792941/82640199-bfea5e00-9c3c-11ea-9a5d-64a1736e9b73.png)
![Screenshot_2020-05-22-14-56-36-423_com topjohnwu magisk](https://user-images.githubusercontent.com/58792941/82640202-c11b8b00-9c3c-11ea-86bb-665dc23a588a.png)
![Screenshot_2020-05-22-14-59-05-536_org meowcat edxposed manager](https://user-images.githubusercontent.com/58792941/82640221-ca0c5c80-9c3c-11ea-907f-c32d6b9bb7de.png)

**Comment by fucksafetynet** [comment]
已确认是safetynet的问题，与thanox无关。
