### ISSUE TITLE
情景模式condition中的fcmPushMessageArrived不起作用

### ISSUE THREAD

**Issue by MadYGY** [Tornaco/Thanox#140]
**Describe the bug（现象描述）**
情景模式condition中的fcmPushMessageArrived不起作用，示例中的“感知GCM FCM推送”同样无法起作用

**To Reproduce**（如何复现）
[
  {
    "name": "Push message api",
    "description": "感知GCM FCM推送",
    "priority": 2,
    "condition": "fcmPushMessageArrived == true && pkgName == \"org.telegram.plus\"",
    "actions": [
      "ui.showShortToast(\"Plus messenger 收到了推送，该干啥干啥\"));"
    ]
  }
]
即使去掉pkgName == \"org.telegram.plus\"也触发不了action。

尝试使用APP"FCM通知转发"和skype，FCM Diagnostics里可以看到FCM的推送，但无法触发情景模式的action，即使FCM成功在通知栏显示通知也无法触发action

**Expected behavior**（期望结果）
感知到FCM推送后，执行设定的action

**Screenshots**（截图）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 10.0]
 - Version [e.g. v1.2.6]

**Additional context**（其他信息）
无

** Logs**（日志文件）
无

**Comment by Gladtbam** [comment]
你用的TG是官方的还是第三方的？

**Comment by MadYGY** [comment]
官方的TG

**Comment by MadYGY** [comment]
> 你用的TG是官方的还是第三方的？
官方的

**Comment by Gladtbam** [comment]
> > 你用的TG是官方的还是第三方的？
> 官方的
> 

那就对了，官方的包名不是org.telegram.plus，是org.telegram.messenger，改一下
