### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by JiZhi-Error** [Tornaco/Thanox#145]
使用太极，在从后台启动Thanox时，有一定几率会造成闪退
![image](https://user-images.githubusercontent.com/24365406/84965151-b28f9900-b140-11ea-9763-8e40add78f47.png)

**Comment by Tornaco** [comment]
@JiZhi-Error 是打开了Thanox插件回到后台吗？  能提供完整日志吗？

**Comment by JiZhi-Error** [comment]
好的，等我今天卡卡看，能不能复现出来

**Comment by Tornaco** [comment]
Reopen if re-prod.
