### ISSUE TITLE
老哥能提供一下开关自启动和锁屏运行的广播吗

### ISSUE THREAD

**Issue by abcdol** [Tornaco/Thanox#15]
因为一些原因需要在指定时间关闭自启动管理和锁屏清理开关，请问这个能shell快捷操作吗？如果不能的话就麻烦老哥把issue直接关闭吧，感谢老哥～

**Comment by abcdol** [comment]
就是后台启动的开关shell和后台运行的开关shell 刚才可能没表述清楚

**Comment by Tornaco** [comment]
@abcdol 可以。我加好了在恢复你。

**Comment by abcdol** [comment]
好的好的 感谢老哥～

**Comment by Tornaco** [comment]
1.0.6+版本支持：

查看帮助：
```bash
adb shell dumpsys tv_input
```

禁用后台启动：
```bash
adb shell dumpsys tv_input disable start-blocker
```

**Comment by abcdol** [comment]
😂打开帮助的shell不好使啊老哥 运行以后没有反应 能不能提供一下禁用【后台运行】的shell呢

**Comment by Tornaco** [comment]
@abcdol 写了。

**Comment by abcdol** [comment]
shell dumpsys tv_input disable start-blocker这个好像只能禁用【后台启动】啊老哥 禁用【后台运行】是哪一个呢？

**Comment by Tornaco** [comment]
@abcdol dumpsys tv_input help看看。记不住了

**Comment by abcdol** [comment]
帮助打不开啊老哥……我的两个手机都无效……edge和tasker执行shell都不行😥

**Comment by Tornaco** [comment]
@abcdol 后台的参数是background-manager好像

**Comment by abcdol** [comment]
好像不是……这个也无效……😂太麻烦你了老哥，就这样吧，我用模拟点击实现吧😂非常感谢👍👍👍

**Comment by Tornaco** [comment]
@abcdol 你装的那个版本?

**Comment by Tornaco** [comment]
@abcdol ➜  release git:(master) ✗ adb -s aefe7cf7 shell dumpsys tv_input
Thanox commands:
    help
        Print this help text.

    version
        Show thanox core version info.

    enable/disable [feature]
        Enable or disable thanox feature.
        Available features:
            start-blocker
            background-manager

➜  release git:(master) ✗

**Comment by abcdol** [comment]
重新下载最新版以后好了……可能是我记错了更新的手机……已经能用了，非常感谢～👍👍👍

**Comment by cmddot** [comment]
有没有 在shell 情景模式的开关? 看了help,还不支持?进入夜间模式时,这个关闭掉应该可以节省电量不
