### ISSUE TITLE
一加7pro 设置-蓝牙和设备连接 卡死黑屏

### ISSUE THREAD

**Issue by x-songmin** [Tornaco/Thanox#150]
**Describe the bug（现象描述）**
一加7pro 设置-蓝牙和设备连接 卡死黑屏

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）

后文的卡死黑屏均指 点击 设置--蓝牙和设备连接 后卡死黑屏

magisk模块全部取消只留taichi，太极模块只留thanox，确定是thanox引起卡死黑屏，取消thanox后就没问题了。

thanox清除数据后重启，卡死黑屏现象仍然存在。

补，thanox版本试了1.2.1 1.2.6 1.2.9  都一样  ，以前没问题，可能是系统更新的问题吧

**Screenshots**（截图）
![Screenshot_20200712-184643](https://user-images.githubusercontent.com/68186221/87244833-d8276e00-c472-11ea-98ff-ed5c29ee3c3a.jpg)

**Version（发现问题的版本）:**
 - OS: 安卓10 Hos b15   b13之后就有此情况了（系统版本，例如Android 6.0.1）
 - Version  1.2.9 （软件版本，例如v2.3.4

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

**Comment by Tornaco** [comment]
@xiasongmin1 麻烦提供下日志：
1. Thanox日志（App里有路径说明）
2. /data/anr下的无响应日志。

**Comment by x-songmin** [comment]
解决了。。禁用了打印服务。。
