### ISSUE TITLE
开发者设置里关闭"显示网络使用详情"后悬浮窗不消失

### ISSUE THREAD

**Issue by wanlyg** [Tornaco/Thanox#152]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）

开发者设置里关闭"显示网络使用详情"后悬浮窗不消失

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）

打开 设置-开发者-显示网络使用详情，有显示后关闭选项即可复现

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

修复bug

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

![Screenshot_20200716-221444_Thanox~2](https://user-images.githubusercontent.com/36926016/87683545-d269ab00-c746-11ea-9980-09d570085cba.png)

**Version（发现问题的版本）:**
 
安卓10 小米6 Evolution X
版本 1.2.9-prc

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

序号①是不消失的悬浮窗
在左下角的原因是手动拉过去但是因为全面屏手势拉不回来了，强行停止Thanox无效，只能重启手机

序号② 是另一个bug，两个插件都安装了，刚安装时好好的，过了一段时间就这样了，在其他类原生rom(安卓10)出现同样问题

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
无

**Comment by Tornaco** [comment]
Fixed.
