### ISSUE TITLE
建议更改定位权限为设置其中一个同时设置其它几个

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#155]
![Screenshot_2020-07-23-08-57-43-632_github tornaco android thanos pro](https://user-images.githubusercontent.com/49943258/88243503-29c9c700-ccc3-11ea-9c91-1230946893c3.jpg)
如图，类似于权限狗或者app ops，***将定位权限的设置改成设置粗略位置(打比方)为允许，同时其它位置权限也设置为允许***。每次部分应用偶尔需要位置(遇到特殊情况，其它时候完全不需要)时，都要一个个改，太麻烦了

**Comment by Tornaco** [comment]
@Gladtbam  Help test https://github.com/Tornaco/Thanox/releases/tag/v2.2

**Comment by Gladtbam** [comment]
> @Gladtbam Help test https://github.com/Tornaco/Thanox/releases/tag/v2.2

收到，等待Google play store更新中👍
