### ISSUE TITLE
[功能建议]情景模式弊端，排序问题

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#16]
1.希望能添加强制关闭情景模式功能，防止在测试新写的规则时，发现规则是死循环，导致系统卡死，现有版本只能通过重启手机或者在REC中解决。
2.希望增加情景模式排序功能。对于已开启的和未开启的情景模式分开，如：已开启的都排列在上部分，未开启的在下部分
并且对开启的和未开启的情景模式以首字母进行排序。
在调试新写的规则时，要不断的开启，如果不排序，每次开启找到新规则都特别浪费时间

**Comment by Tornaco** [comment]
@sakurabot  
1. 1.0.7增加了QS，可以尝试快速关闭。 
2. 1.0.7排序已经优化。
