### ISSUE TITLE
情境模式进度条bug

### ISSUE THREAD

**Issue by hldad** [Tornaco/Thanox#161]
**Describe the bug（现象描述）**

在情境模式中，点击右侧进度条程序退出重启。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入主程序
2. 进入情境模式
3. 增加情境模式到出现进度条，或导入默认
4. 点击进度条，出现错误。

**Expected behavior**（期望结果）
消除bug

**Screenshots**（截图）
![IMG_20200823_230320](https://cdn.hldad.cn/image/20200823-1598195033515.jpg)

**Version**（发现问题的版本）:
 - OS: Android 9
 - Version 
![xbtc2b2e155f50671c15a40c11b323123392](https://cdn.hldad.cn/image/20200823-1598195132740.jpg)

** Logs **（日志文件）

[data/system/thanox/logging](https://cdn.hldad.cn/image/logging.zip) 

[sdcard](https://cdn.hldad.cn/image/logs.zip)

**Comment by Tornaco** [comment]
Fixed,
