### ISSUE TITLE
功能請求跟發現小問題

### ISSUE THREAD

**Issue by noone315** [Tornaco/Thanox#18]
可以在權限管理中加上開機自啟動嗎？
還有最新版的應用模糊在已設定的應用中，會有螢幕重新打開時(非重開機，應用在前台)會在螢幕上看到短暫的模糊效果

**Comment by Tornaco** [comment]
开机自启动建议用启动管理来控制。
权限太多会很乱。

模糊在9和10上目前技术上之能做到这个地步了。也是目前设备兼容性最好的方案。
