### ISSUE TITLE
隐匿功能对TikTok无效，无法改区

### ISSUE THREAD

**Issue by SekiBetu** [Tornaco/Thanox#187]
我在使用应用变量的时候只修改SIM国际码为JP时，tiktok可以正常变为日区，
而Thanox只修改SIM国际码为JP时，仍旧为美区，对此甚是不解
应用变量不知道加了什么额外的东西可以成功让tiktok变成日区，还是说Thanox的sim国际码这一项隐匿失败了

**Comment by Tornaco** [comment]
@SekiBetu  我之前在android10 测试过，Tik Tok是可以变为jp区的。

**Comment by SekiBetu** [comment]
> @SekiBetu 我之前在android10 测试过，Tik Tok是可以变为jp区的。

MIUI12.5 21.1.26 Android 11
Magisk v21.4(21400)
Magisk Manger v8.0.7(4843)(15)
Riru - core v23.4
Riru - edxposed 93-v0.5.2.0_4672-master (SandHook)
EdXposed Manager v4.6.0-pre(45760)
TikTok 18.4.41

thanox_2.2-10-52e30aa-prc.apk
thanox_2.2-18-016b0b1-prc.apk
thanox_2.2-30-eb3f6da-prc.apk
thanox_2.2-39-1f22c22-prc.apk
thanox_2.2-42-c736d84-prc.apk
thanox_2.2-47-6611db9-prc.apk

实测不行，请问你的测试步骤是怎样的，我再按照你的严格步骤试试

**Comment by SekiBetu** [comment]
附图：
以下是Thanox步骤：
首先在edxp中激活模块重启手机
![image](https://user-images.githubusercontent.com/38283893/98937984-1f844080-24df-11eb-9eba-7842558ad35e.png)
进入模块的隐匿功能增加一个日本SIM国家码的模板，只修改SIM国家码为JP
![image](https://user-images.githubusercontent.com/38283893/98938022-2f9c2000-24df-11eb-9b45-5b997c0cb1a7.png)
为TikTok启用这个模板
![image](https://user-images.githubusercontent.com/38283893/98938039-362a9780-24df-11eb-85d0-9ce8602d8c54.png)
通知提示隐匿功能已经生效
![image](https://user-images.githubusercontent.com/38283893/98938061-3cb90f00-24df-11eb-965e-3ebcaa861cb4.png)
实际的搜索页面还是美区，推送的视频也无一例外全是英语标题的
![image](https://user-images.githubusercontent.com/38283893/98938094-46db0d80-24df-11eb-845c-f3e82a1ed3a8.png)


以下是应用变量步骤：
在edxp中激活模块重启手机，进入应用变量选择TikTok，只修改SIM国家码为JP
![image](https://user-images.githubusercontent.com/38283893/98938141-5bb7a100-24df-11eb-9167-26de0f0f9d2a.png)
保存配置后就生效了
![image](https://user-images.githubusercontent.com/38283893/98938156-61ad8200-24df-11eb-8cb3-cb56b79b8249.png)
打开TikTok的搜索页面，已经变为日区，推送的视频也很大一部分是日语标题的
![image](https://user-images.githubusercontent.com/38283893/98938173-683bf980-24df-11eb-839e-8cdfac418bfc.png)

**Comment by Tornaco** [comment]
@SekiBetu 周末我在找时间看下。。

**Comment by SekiBetu** [comment]
我的猜测是，应用变量没填的数据不会被TikTok读取，具体是不是我也不知道了，应用变量是开源的，可以参考 https://github.com/kingsollyu/AppEnv-Kotlin

上述过程我是修改了系统的时区到台湾的，不修改时区的话大陆时区tiktok也会检测，视频无法刷出来
如果想要评论和点赞等功能的话需要挂梯

上述过程我确定magisk hide没有添加tiktok和模块等APP，edxp关闭了黑/白名单模式，thanox作为全局模块使用

**Comment by Kylepoops** [comment]
@SekiBetu 你挂美区代理了吗

**Comment by SekiBetu** [comment]
> @SekiBetu 你挂美区代理了吗

如果你仔细看了我上述过程就能知道改区与网络环境无关，即使你不用梯子也能进日区正常观看视频

**Comment by SekiBetu** [comment]
更新：
测试了 thanox_2.2-10-52e30aa-prc.apk 仍旧无法改为日区
thanox_2.2-18-016b0b1-prc.apk则是开启隐匿功能就退回APP主界面
应用变量仍旧表现正常，可以改为日区
测试环境:https://github.com/Tornaco/Thanox/issues/187#issuecomment-726031965

**Comment by SekiBetu** [comment]
更新：
测试了最新的thanox_2.2-47-6611db9-prc.apk
一个一个试过去，发现修改了sim系列号为任意值和sim国家码后，可以正常使用tiktok，但不管怎么改sim国家码，都为美区，
于是我尝试修改APP的语言为日语，发现，只有在修改tiktok的APP语言为日语后，才会改为日区(改为日区的特征是评论区如果有日语评论，则会优先显示+搜索区为日区热点)
比如这个视频：https://www.tiktok.com/@deankoash/video/6913268138171829505
在APP不同语言下会有相应语言的优先显示，隐匿功能中的sim国家码很可能没有起效而只是作为了不让APP读取的功能生效了
应用变量模块中伪装为jp后则能在APP为中文繁体的情况下评论区也是日语评论优先显示+搜索区为日本热点

姑且认为隐匿功能正常了，先用家乡の语言用着了

**Comment by SekiBetu** [comment]
# 附图：
## Thanox模块隐匿下的APP只能通过切换APP语言换区：
### 中文繁体：
![image](https://user-images.githubusercontent.com/38283893/103488780-936c0680-4e07-11eb-821a-49e480381076.png)
### 英语：
![image](https://user-images.githubusercontent.com/38283893/103488787-9ff05f00-4e07-11eb-8636-5637036a8fe5.png)
### 日语：
![image](https://user-images.githubusercontent.com/38283893/103488792-a67ed680-4e07-11eb-9445-8f7587033480.png)
## 应用变量模块只修改sim国家码为JP情况下，APP语言任意的情况下的换区：
### 图为中文繁体，但是tiktok为日区，其余语言都测试过，APP的语言不会影响换区
![image](https://user-images.githubusercontent.com/38283893/103488812-c31b0e80-4e07-11eb-81cf-b561e3df843b.png)

**Comment by SekiBetu** [comment]
更新：
Thanox隐匿后，tiktok的点赞功能失效，无法保存点赞，认为是隐匿不完全导致的

**Comment by SekiBetu** [comment]
时隔一年多，再回来试了下，最新版4.0.4已经可以上tiktok了，tiktok所有功能正常
