### ISSUE TITLE
反复提示请重新启设备且重启后设置恢复默认

### ISSUE THREAD

**Issue by schalkiii** [Tornaco/Thanox#189]
**Describe the bug（现象描述）**
反复提示请重新启设备， 重启设备之后提示已成功激活，但是仍让会反复提示请重新启设备。 且设置没办法持续的生效， 一旦重启过后所有设置恢复默认需要重新导入。

**To Reproduce**（如何复现）
三星one UI2.5 Android 10
Edxposed YAHFA 0.4.6.4 (4563) 

**Expected behavior**（期望结果）
不再提示重启设备。设置能够持续地生效

**Screenshots**（截图）
![微信图片_20201122204449](https://user-images.githubusercontent.com/30932387/99904063-98677180-2d03-11eb-957a-739e44c653f8.jpg)

**Version（发现问题的版本）:**
Thanox 2.0-4-0e2a340-prc

**Additional context**（其他信息）
尝试重新安装expose， 取消勾选thanox 重新勾选thanox， 问题依旧

** Logs**（日志文件）
[logging.zip](https://github.com/Tornaco/Thanox/files/5579486/logging.zip)
[2020-11-22.zip](https://github.com/Tornaco/Thanox/files/5579489/2020-11-22.zip)

**Comment by Tornaco** [comment]
@schalkiii Please contact thanox@163.com, You will get help.
