### ISSUE TITLE
2.1-4最新版本无限重启

### ISSUE THREAD

**Issue by hanxin1997** [Tornaco/Thanox#192]
**Describe the bug（现象描述）
安装完新版，重新打开后，无限重启，只要打开任意软件后一会就重启。

**To Reproduce**（如何复现）
安装完新版，重新重启后，无限重启，只要打开任意软件后几秒就重启，在edxp关闭灭霸后就正常了。

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: miui12 20.11.19 安卓10
 - Version 2.1-4-f795802-pro

**Additional context**（其他信息）
edxp：riru：v22版本 riru-edxposed：v0.5.0.6—4573 YAHFA版本
edxp已开启白名单，白名单有android系统

** Logs**（日志文件）
/data/system/thanos路径下的logging压缩上传上来了
[logging.zip](https://github.com/Tornaco/Thanox/files/5597064/logging.zip)

**Comment by hanxin1997** [comment]
在酷安和群都发现有翻车的 好像都是安卓10的

**Comment by wanlyg** [comment]
有没有控制变量，只更新了thanox吗？同版本的edxp模块用上个版本会boom吗？新版edxp模块关闭了对/data/system/的权限，会导致thanos读不到配置文件boom，请检查一下 @hanxin1997

**Comment by Tornaco** [comment]
@hanxin1997 日志中未见系统异常，等下我试试小米手机。。我的AOSP测试Android10没发现问题。

**Comment by hanxin1997** [comment]
> 有没有控制变量，只更新了thanox吗？同版本的edxp模块用上个版本会boom吗？新版edxp模块关闭了对/ data / system /的权限，会导致thanos读不到配置文件boom，请检查一下@ hanxin1997

有使用情景模式不知道算不算使用了变量 上版本不会，同样的新版edxp

**Comment by Tornaco** [comment]
@hanxin1997 如果有条件的话帮忙抓个开机到异常重启的adb log。不行的话只能等我这边测试一台小米，不确定能否复现。

**Comment by lonelydogin** [comment]
> 有没有控制变量，只更新了thanox吗？同版本的edxp模块用上个版本会boom吗？新版edxp模块关闭了对/data/system/的权限，会导致thanos读不到配置文件boom，请检查一下 @hanxin1997

我这边控制变量了，新版edxp使用上个版本正常。更新后就boom了。

**Comment by lonelydogin** [comment]
> @hanxin1997 如果有条件的话帮忙抓个开机到异常重启的adb log。不行的话只能等我这边测试一台小米，不确定能否复现。

。怎么抓adb log

**Comment by Tornaco** [comment]
1. 设备全程链接电脑。
2. 电脑端执行命令adb logcat > logs.txt
3. 操作复现直到异常重启。
4. log.txt就是日志了。

@lonelydogin

**Comment by wanlyg** [comment]
我说的是控制变量法。不过好像只动了Android10的。@hanxin1997 

刚才发送的一瞬间我Android11软重启了，我去提一个新issus @Tornaco

**Comment by Tornaco** [comment]
@wanlyg :(

**Comment by Tornaco** [comment]
[thanox_2.1-6-078c351-dirty-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597233/thanox_2.1-6-078c351-dirty-prc.apk.zip)
@hanxin1997 @lonelydogin  试试这个版本

**Comment by lonelydogin** [comment]
> 2\. adb logcat > logs.txt

[adb_log.zip](https://github.com/Tornaco/Thanox/files/5597251/adb_log.zip)

**Comment by lonelydogin** [comment]
> [thanox_2.1-6-078c351-dirty-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597233/thanox_2.1-6-078c351-dirty-prc.apk.zip)
> @hanxin1997 @lonelydogin 试试这个版本

依然重启。

**Comment by hanxin1997** [comment]
> [thanox_2.1-6-078c351-dirty-prc.apk.zip ](https://github.com/Tornaco/Thanox/files/5597233/thanox_2.1-6-078c351-dirty-prc.apk.zip)
> @ hanxin1997 @lonelydogin 试试这个版本

试过了  还是一样.. 没安装上adb 无法抓取异常日志

**Comment by Tornaco** [comment]
[thanox_2.1-7-2d389c5-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597322/thanox_2.1-7-2d389c5-prc.apk.zip)

@hanxin1997  @lonelydogin 这个呢。。

**Comment by Y161537** [comment]
@Tornaco 一加七pro未发生重启

**Comment by hanxin1997** [comment]
> [thanox_2.1-7-2d389c5-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597322/thanox_2.1-7-2d389c5-prc.apk.zip)
> 
> @ hanxin1997 @lonelydogin这个呢。。。

未发生重启 使用正常 刚想用adb抓日志，不过没发生重启。

**Comment by Y161537** [comment]
@Tornaco

**Comment by Tornaco** [comment]
@Y161537   @hanxin1997 感谢，找到错误位置了。。

**Comment by lonelydogin** [comment]
> [thanox_2.1-7-2d389c5-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597322/thanox_2.1-7-2d389c5-prc.apk.zip)
> 
> @hanxin1997 @lonelydogin 这个呢。。

到目前为止 工作正常

**Comment by Y161537** [comment]
@Tornaco 一切正常

**Comment by Q761109021** [comment]
> [thanox_2.1-7-2d389c5-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597322/thanox_2.1-7-2d389c5-prc.apk.zip)
> 
> @hanxin1997 @lonelydogin 这个呢。。

这个没重启，但是进入软件后会崩溃重载，一加安卓11

**Comment by hanxin1997** [comment]
我的问题解决了，作者可以关评论了。有其他问题的安卓11的朋友。可以另开问题。

**Comment by Tornaco** [comment]
[thanox_2.1-5-f38c7d7-prc.apk.zip](https://github.com/Tornaco/Thanox/files/5597794/thanox_2.1-5-f38c7d7-prc.apk.zip)


@ hanxin1997 再帮忙测试下这个。thanks
