### ISSUE TITLE
LG，21-6，软重启

### ISSUE THREAD

**Issue by qiuyouxin** [Tornaco/Thanox#194]
**Describe the bug（现象描述）**
2.1-6，出现软重启，我这里表现有时装完app后出现软重启，不是每次。

GitHub2.0b2后酷安发布的2.0-4也有软重启现象，当时回退2.0b2用了很长时间无软重启。

不知道哪些log有用，按要求目录下都搬来了。

**Version（发现问题的版本）:**
 - OS: LG，官方，android8.0.0 
 - thanox 2.1-6

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[Android-date-thanoscache.zip](https://github.com/Tornaco/Thanox/files/5606440/Android-date-thanoscache.zip)
[data-system-thanos-logging.zip](https://github.com/Tornaco/Thanox/files/5606441/data-system-thanos-logging.zip)

**Comment by Tornaco** [comment]
@qiuyouxin Got

**Comment by Tornaco** [comment]
@qiuyouxin Pls help test: https://github.com/Tornaco/Thanox/releases/tag/v2.2

**Comment by qiuyouxin** [comment]
@Tornaco thanox2.2，经过差不多一天使用，没有相关软启现象发生，应该是解决了。
另外2个建议
1.权限控制增加shell的使用，对隐藏root有一定帮助。
2.最近任务模糊功能，增加模糊程度控制或者使用自选图片覆盖，现在程度的不够。
