### ISSUE TITLE
一加6t 不能进入桌面

### ISSUE THREAD

**Issue by paolo0** [Tornaco/Thanox#197]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
下载了酷安的  2.1-6-76ee4ff-prc 版本能正常重启，但是重启完一解锁不到一秒就立刻重启。

**Version（发现问题的版本）:**
 - OS:  OxygenOS 10.3.6
 - Version: Thanox 2.1-6-76ee4ff-prc

**Additional context**（其他信息）
手机里面有太极， 手机一整年没备份的照片幸好能通过 fastboot adb 进入临时twrp进行备份， 试着在Twrp 的文件管理删除了taichi , magisk，thanox 的文件夹还是是一样的问题。 现在备份完只能重置系统从0开始。。。。

** Logs**（日志文件）
把文件夹都删了，无。

**Comment by Tornaco** [comment]
@paolo0  

做过什么配置吗？例如系统核心应用的某些组件配置

没有日志无法分析呢。

**Comment by paolo0** [comment]
> @paolo0
> 
> 做过什么配置吗？例如系统核心应用的某些组件配置
> 
> 没有日志无法分析呢。

hmm，忘了，但是应该是只弄了和微信相关单位，其他设置应该没什么要弄的，昨天一心想着数据就把文件夹删了... 现在我重装了2.0 beta2 ( 出事前我用的版本） 以及最新的那个2.1.6？ 已经在太极阳里面激活，重启过几次，但是thanox 一直显示未激活，请在Xposed 里面激活。然后在软件里面 什么设置，软件列表都是空的。

**Comment by Tornaco** [comment]
No resp
