### ISSUE TITLE
可以屏蔽应用的PackageManager.queryIntentActivities吗？

### ISSUE THREAD

**Issue by 4512369781** [Tornaco/Thanox#20]
新的权限管理里增加了新的功能：Query intent activities，可以禁止应用读取其他应用的意图，想问下是否可以禁止应用广播意图，比如屏蔽淘宝，这样它就不会出现在打开方式以及分享里。

**Comment by Tornaco** [comment]
目前暂时不支持~

**Comment by 4512369781** [comment]
> 目前暂时不支持~

了解。
