### ISSUE TITLE
使用最新版edxposed4646Y会有偶发性软重启

### ISSUE THREAD

**Issue by skyline-89** [Tornaco/Thanox#208]
bug描述
多出现在使用返回桌面手势和冷启动微信，qq，哔哩哔哩时
会跳到开机第二屏

版本
手机：小米8UD  Android 10
Thanox版本：2.1-6-76ee4ff-prc

** Logs**
[2020-12-24.txt](https://github.com/Tornaco/Thanox/files/5739586/2020-12-24.txt)

[native_crash_com.tencent.mm_2020-12-24-20_34_59.log](https://github.com/Tornaco/Thanox/files/5739588/native_crash_com.tencent.mm_2020-12-24-20_34_59.log)
[thanox-core.log](https://github.com/Tornaco/Thanox/files/5739616/thanox-core.log)

**Comment by Lucifersian** [comment]
我也是 你看看是不是只要触发了返回键就会软重启
