### ISSUE TITLE
2.0开始打开代收插件闪退

### ISSUE THREAD

**Issue by Cucko01** [Tornaco/Thanox#209]
**Describe the bug（现象描述）**
   2.0版本开始打开代收插件闪退
*
MIUI11 Android 9
 `-软件版本：2.2-10-52e30aa-prc

@Tornaco 

1608821352845|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821352848|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821352851|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821352854|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821352856|D|ThanoxApp|onAttach
1608821352857|D|ThanoxApp|onCreate
1608821352868|D|ThanoxApp|onActivityCreated
1608821352890|V|ThanoxApp|isPaid? true
1608821352942|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821354160|D|ThanoxApp|onAttach
1608821354161|D|ThanoxApp|onCreate
1608821354205|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1608821354205|D|ThanoxApp|onActivityCreated
1608821354226|V|ThanoxApp|loadedPlugin: LoadedPlugin(pluginClassLoader=github.tornaco.android.nitro.framework.plugin.PluginClassLoader[DexPathList[[zip file "/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]], pluginRes=android.content.res.MiuiResources@af84a7e, packageName=github.tornaco.android.plugin.push.message.delegate)
1608821354232|V|ThanoxApp|callerClazz: class github.tornaco.android.plugin.push.message.delegate.StatusCallable
1608821355285|V|ThanoxApp|parseLaunchIntent, installedPlugin: InstalledPlugin(name=github.tornaco.android.plugin.push.message.delegate, packageName=github.tornaco.android.plugin.push.message.delegate, versionCode=2031524, versionName=1.2.6-dirty, label=消息代收, description=Push message proxy plugin, minRequiredVersion=1, stable=false, withHooks=true, mainActivityName=github.tornaco.android.plugin.push.message.delegate.MainActivity, originFile=/storage/emulated/0/Android/data/github.tornaco.android.thanos/cache/temp_1608747845203.tp, apkFile=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.apk, dexFile=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.dex, libFile=null, sourceDir=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source, statusCallableClass=github.tornaco.android.plugin.push.message.delegate.StatusCallable, pluginActivityInfoList=[PluginActivityInfo(id=8, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, name=github.tornaco.android.plugin.push.message.delegate.MainActivity, activityInfo=ActivityInfo{e666c84 github.tornaco.android.plugin.push.message.delegate.MainActivity}), PluginActivityInfo(id=9, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, name=github.tornaco.android.thanos.picker.AppPickerActivity, activityInfo=ActivityInfo{8c49c6d github.tornaco.android.thanos.picker.AppPickerActivity})], pluginApplicationInfo=PluginApplicationInfo(pluginPackageName=github.tornaco.android.plugin.push.message.delegate, applicationInfo=ApplicationInfo{cae00a2 github.tornaco.android.plugin.push.message.delegate}), activityIntentFilterList=[ActivityIntentFilter(id=5, name=github.tornaco.android.plugin.push.message.delegate.MainActivity, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, intentFilter=android.content.IntentFilter@993d133)])
1608821355286|D|ThanoxApp|loadPluginActivityInstance, request: Launcher.Request(componentName=ComponentInfo{github.tornaco.android.plugin.push.message.delegate/github.tornaco.android.plugin.push.message.delegate.MainActivity}, plugin=InstalledPlugin(name=github.tornaco.android.plugin.push.message.delegate, packageName=github.tornaco.android.plugin.push.message.delegate, versionCode=2031524, versionName=1.2.6-dirty, label=消息代收, description=Push message proxy plugin, minRequiredVersion=1, stable=false, withHooks=true, mainActivityName=github.tornaco.android.plugin.push.message.delegate.MainActivity, originFile=/storage/emulated/0/Android/data/github.tornaco.android.thanos/cache/temp_1608747845203.tp, apkFile=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.apk, dexFile=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.dex, libFile=null, sourceDir=/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source, statusCallableClass=github.tornaco.android.plugin.push.message.delegate.StatusCallable, pluginActivityInfoList=[PluginActivityInfo(id=8, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, name=github.tornaco.android.plugin.push.message.delegate.MainActivity, activityInfo=ActivityInfo{e666c84 github.tornaco.android.plugin.push.message.delegate.MainActivity}), PluginActivityInfo(id=9, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, name=github.tornaco.android.thanos.picker.AppPickerActivity, activityInfo=ActivityInfo{8c49c6d github.tornaco.android.thanos.picker.AppPickerActivity})], pluginApplicationInfo=PluginApplicationInfo(pluginPackageName=github.tornaco.android.plugin.push.message.delegate, applicationInfo=ApplicationInfo{cae00a2 github.tornaco.android.plugin.push.message.delegate}), activityIntentFilterList=[ActivityIntentFilter(id=5, name=github.tornaco.android.plugin.push.message.delegate.MainActivity, pluginPackageName=github.tornaco.android.plugin.push.message.delegate, intentFilter=android.content.IntentFilter@993d133)]))
1608821355287|D|ThanoxApp|loadPluginActivityInstance, activityInfo: ActivityInfo{e666c84 github.tornaco.android.plugin.push.message.delegate.MainActivity}
1608821355294|V|ThanoxApp|loadedPlugin: LoadedPlugin(pluginClassLoader=github.tornaco.android.nitro.framework.plugin.PluginClassLoader[DexPathList[[zip file "/data/user/0/github.tornaco.android.thanos/files/plugins/github.tornaco.android.plugin.push.message.delegate/source/github.tornaco.android.plugin.push.message.delegate_2031524.apk"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64]]], pluginRes=android.content.res.MiuiResources@af84a7e, packageName=github.tornaco.android.plugin.push.message.delegate)
1608821355295|V|ThanoxApp|factoryClazz: class github.tornaco.android.nitro.framework.plugin.ComponentFactory
1608821355327|V|ThanoxApp|pluginActivity: PluginActivity(pluginContext=github.tornaco.android.nitro.framework.plugin.PluginContext@bf301fa, themeResource=0, hostActivityInvoker=null)
1608821355342|W|ThanoxApp|pluginActivity=github.tornaco.android.nitro.framework.plugin.wrapper.PluginActivityWrapper@80e7d9
1608821355354|V|ThanoxApp|pluginThemeRes: 2131820863

**Comment by anysoft** [comment]
mark一下，我的也点代收插件闪退，不过错误不一样，
`2020-12-29 00:16:19.561 E/Thanox-Core: onApplicationCrashing: native_crash github.tornaco.android.thanos ProcessRecord(packageName=github.tornaco.android.thanos, processName=github.tornaco.android.thanos, pid=6634, uid=10455, notResponding=false, crashing=false) *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/natrium/natrium:8.0.0/OPR1.170623.032/V11.0.2.0.OBGCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 6634, tid: 6634, name: .android.thanos  >>> github.tornaco.android.thanos <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
Cause: null pointer dereference
    x0   0000000000000ac4  x1   0000000000000004  x2   0000000000001f0f  x3   0000000000000008
    x4   0000007ff0a37d88  x5   00000071e75c5100  x6   0000000000000004  x7   000000000002e01c
    x8   00000000142c9b11  x9   0000000000000000  x10  0000000000000000  x11  00000071e75c55e8
    x12  0000000000000008  x13  0000000000000024  x14  000000000000000d  x15  0000000000000000
    x16  00000071efca9f80  x17  00000071efca6600  x18  0000000013042d80  x19  0000000000000008
    x20  0000000000000a6a  x21  00000000a0bab21e  x22  00000071d224bcb0  x23  0000007ff0a38000
    x24  0000000000000001  x25  00000071e75c5558  x26  00000071e75c5100  x27  00000071f00aa1c0
    x28  00000000266ad233  x29  0000007ff0a37ea0  x30  00000071efca08a0
    sp   0000007ff0a37df0  pc   00000071efca08c4  pstate 0000000060000000

backtrace:
    #00 pc 00000000001788c4  /system/lib64/libart.so (offset 0x359000)
    #01 pc 000000000017889c  /system/lib64/libart.so (offset 0x359000)

2020-12-29 00:16:19.562 W/Thanox-Core: Writing to log file: /data/system/thanos/logging/application_logging/log/crash/native_crash_github.tornaco.android.thanos_2020-12-29-00:16:19.log
2020-12-29 00:16:19.563 W/Thanox-Core: Write complete to log file: /data/system/thanos/logging/application_logging/log/crash/native_crash_github.tornaco.android.thanos_2020-12-29-00:16:19.log
`

1.3.2没问题,2.0开始闪退。
@Tornaco 
[logging.zip](https://github.com/Tornaco/Thanox/files/5748026/logging.zip)

**Comment by anysoft** [comment]
> mark一下，我的也点代收插件闪退，不过错误不一样，
> `2020-12-29 00:16:19.561 E/Thanox-Core: onApplicationCrashing: native_crash github.tornaco.android.thanos ProcessRecord(packageName=github.tornaco.android.thanos, processName=github.tornaco.android.thanos, pid=6634, uid=10455, notResponding=false, crashing=false) *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'Xiaomi/natrium/natrium:8.0.0/OPR1.170623.032/V11.0.2.0.OBGCNXM:user/release-keys'
> Revision: '0'
> ABI: 'arm64'
> pid: 6634, tid: 6634, name: .android.thanos >>> github.tornaco.android.thanos <<<
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
> Cause: null pointer dereference
> x0 0000000000000ac4 x1 0000000000000004 x2 0000000000001f0f x3 0000000000000008
> x4 0000007ff0a37d88 x5 00000071e75c5100 x6 0000000000000004 x7 000000000002e01c
> x8 00000000142c9b11 x9 0000000000000000 x10 0000000000000000 x11 00000071e75c55e8
> x12 0000000000000008 x13 0000000000000024 x14 000000000000000d x15 0000000000000000
> x16 00000071efca9f80 x17 00000071efca6600 x18 0000000013042d80 x19 0000000000000008
> x20 0000000000000a6a x21 00000000a0bab21e x22 00000071d224bcb0 x23 0000007ff0a38000
> x24 0000000000000001 x25 00000071e75c5558 x26 00000071e75c5100 x27 00000071f00aa1c0
> x28 00000000266ad233 x29 0000007ff0a37ea0 x30 00000071efca08a0
> sp 0000007ff0a37df0 pc 00000071efca08c4 pstate 0000000060000000
> 
> backtrace:
> #00 pc 00000000001788c4 /system/lib64/libart.so (offset 0x359000)
> #1 pc 000000000017889c /system/lib64/libart.so (offset 0x359000)
> 
> 2020-12-29 00:16:19.562 W/Thanox-Core: Writing to log file: /data/system/thanos/logging/application_logging/log/crash/native_crash_github.tornaco.android.thanos_2020-12-29-00:16:19.log
> 2020-12-29 00:16:19.563 W/Thanox-Core: Write complete to log file: /data/system/thanos/logging/application_logging/log/crash/native_crash_github.tornaco.android.thanos_2020-12-29-00:16:19.log
> `
> 
> 1.3.2没问题,2.0开始闪退。
> @Tornaco
> [logging.zip](https://github.com/Tornaco/Thanox/files/5748026/logging.zip)

另外这份日志还有几个sockettimeout异常，thanox.emui.tech这个域名是什么作用？我是MIUI的系统，emui不是华为么。

**Comment by Tornaco** [comment]
@anysoft 域名不重要，所有设备都是这个，这是thx激活服务器。

**Comment by Tornaco** [comment]
@anysoft 插件重新安装也崩溃吗

**Comment by anysoft** [comment]
@Tornaco  重装，清空应用数据，删除/data/system/thanox目录还是闪退。我看日志是因为libart.so报错，空指针引用。
你先分析下原因，我过几天备份系统数据后格式化data分区再试试

**Comment by anysoft** [comment]
> @anysoft 域名不重要，所有设备都是这个，这是thx激活服务器。

解析的ip我在深圳长城和深圳电信经常连接超时，我看应该是不是网络不通，可能服务器压力过大？

**Comment by Cucko01** [comment]
更新1月3号的版本恢复正常了

**Comment by anysoft** [comment]
> 更新1月3号的版本恢复正常了
1月三号版本在哪下载？

**Comment by JiZhi-Error** [comment]
@anysoft 昨天的啊

**Comment by JiZhi-Error** [comment]
@anysoft https://github.com/Tornaco/Thanox/releases/tag/v2.2

**Comment by anysoft** [comment]
> @anysoft https://github.com/Tornaco/Thanox/releases/tag/v2.2

3q我以为发新版本了，原来只是更新release。我下载试试看
