### ISSUE TITLE
[功能建议]情景模式的代码编辑功能增强

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#21]
希望情景模式代码编辑时能提供额外的键盘输入选项，将[ ] \ " : ; ! 等常用符号列出来，避免代码编辑时频繁的切换中英文键盘以及符号键盘的切换，提高效率

**Comment by Tornaco** [comment]
@sakurabot 👌🏻

**Comment by Gladtbam** [comment]
还没添加这个功能吗？😭

**Comment by Tornaco** [comment]
@sakurabot 等等。。

**Comment by Tornaco** [comment]
1.1.0 rc 已经支持

**Comment by Gladtbam** [comment]
![photo_2020-01-16_20-30-28](https://user-images.githubusercontent.com/49943258/72525526-524db000-389f-11ea-9550-887225179483.jpg)
希望添加的符号能放在图示这里，现有这样对提高效率帮助不大

**Comment by dxl1236** [comment]
> ![photo_2020-01-16_20-30-28](https://user-images.githubusercontent.com/49943258/72525526-524db000-389f-11ea-9550-887225179483.jpg)
> 希望添加的符号能放在图示这里，现有这样对提高效率帮助不大

如果大家对这功能用得多，我觉得作者可以考虑把语法规则关键词也做进去，有点类似于autojs，直接点击选取关键词
