### ISSUE TITLE
一加7pro pe10 使用thanox pro侧边返回手势触发重启

### ISSUE THREAD

**Issue by Lucifersian** [Tornaco/Thanox#214]
安装thanox pro，在edxposed中激活并重启后，任意界面侧边返回手势触发导致软重启

**激活thanoxpro后任意界面侧边返回即软重启
edxposed版本为EdXposed-YAHFA-v0.5.1.4_4655-master-debug.zip
magisk版本为20.4
riru core版本为23.1
thanox pro版本为版本 2.1-6-76ee4ff-row

**Comment by cheng2004237** [comment]
一加8pro,安卓11，也经常性软重启

**Comment by Lucifersian** [comment]
已解决 原因未知 突然可以了

**Comment by Deleted-Account** [comment]
我的 一加7pro 安卓10 也是触发返回软重启。
用的 thanox_2.2-47-6611db9-prc
手机环境为 Riru 23.3，EdXposed 0.5.2（4672）
Magisk 21.4 Manager 8.0.7
EdXposed Manager 4.6.0


卸载Thanox，重新安装 v1.3.2-beta3 软重启依旧

是不是需要设置黑白名单？如果需要的话如何设置
