### ISSUE TITLE
[功能建议]权限管理中点击APP图标可以启动APP

### ISSUE THREAD

**Issue by 2220209876** [Tornaco/Thanox#22]
![YuanEn_2019-12-25_21-44-09](https://user-images.githubusercontent.com/7346652/71446608-2471c180-2760-11ea-9e58-caf67dc80779.png)

**Comment by Gladtbam** [comment]
在这里点击应用图标可以复制包名，方便写情景模式规则，换成启动app反而有点不方便的吧🤔

**Comment by 2220209876** [comment]
> 在这里点击应用图标可以复制包名，方便写情景模式规则，换成启动app反而有点不方便的吧🤔

在这里你不点击应用图标也能复制包名

**Comment by Tornaco** [comment]
1.1.3 支持。暂时关闭。
