### ISSUE TITLE
bug 隐藏已安装应用对部分软件不生效，权限管理和隐匿都试过。

### ISSUE THREAD

**Issue by 2220209876** [Tornaco/Thanox#22]
好像对双开类软件无法生效，其它软件暂未发现，酷安可以隐藏已安装应用

下面这两个不行
https://play.google.com/store/apps/details?id=do.multiple.cloner

https://play.google.com/store/apps/details?id=com.excelliance.multiaccounts

**Comment by Tornaco** [comment]
试试Query intent activities权限。

**Comment by 2220209876** [comment]
> 试试Query intent activities权限。

开启Query intent activities后可以隐藏已安装应用

**Comment by Tornaco** [comment]
请根据需求使用Query intent activities进行严格限制
