### ISSUE TITLE
应用随机消失

### ISSUE THREAD

**Issue by Sentsuki** [Tornaco/Thanox#23]
更新Thanox1.09后问题再次出现，1.08未发生，这次一个系统应用消失了

Xiaomi 6 Lineageos 16 (android 9)
 - thanox 1.0.9 magisk 20.1 exposed 0.4.5.1 (sandhook)
附日志如下
[log.zip](https://github.com/Tornaco/Thanox/files/4002439/log.zip)

**Comment by Sentsuki** [comment]
1.10问题还在发生。。。

**Comment by Tornaco** [comment]
@Yabalina 。。。

**Comment by Sentsuki** [comment]
我先关了吧，这个问题好奇怪

**Comment by Tornaco** [comment]
@Yabalina 暂时没有遇到

**Comment by Sentsuki** [comment]
改用太极几天好像没问题了，可能是edxp的问题吧
