### ISSUE TITLE
网易云音乐设置任务清理后，划卡并未被清理

### ISSUE THREAD

**Issue by dxl1236** [Tornaco/Thanox#24]
![Screenshot_20191210-091207](https://user-images.githubusercontent.com/31926240/70486599-6af2d980-1b2d-11ea-90bd-ae3a29d317f7.jpg)
对于网易云音乐
1.锁屏清理后台有效
2.划卡后任务清理无效，无论是否有通知栏都不清理
测试了其他软件，即使有通知栏也会正常清理掉
手机：红米note 7 pro 
系统：PixelExperience_Plus_violet-9.0-20190906-1615-OFFICIAL
edxp4463
thanox 1.03

**Comment by Tornaco** [comment]
@dxl1236 我也发现这个问题了，应该是之前为了不杀死微信的小程序做了些处理，伦理出问题了。有空修一下

**Comment by dxl1236** [comment]
1.04版已经修复了

**Comment by Tornaco** [comment]
@dxl1236 好的
