### ISSUE TITLE
华为荣耀V10  安卓8.0.0，Edxposed和Lspxposed均无法激活Thanox

### ISSUE THREAD

**Issue by ghost** [Tornaco/Thanox#241]
**问题描述：**
华为荣耀V10安卓8.0.0，Edxposed和Lspxposed均无法激活Thanox

**To Reproduce**（如何复现）
（1）将riru模块从v21.3升级到v23.5，edxposed模块从v0.4.6.1（4510）升级到v0.5.2.2_4683-master后，thanox无法激活
（2）我升级各模块后，也曾尝试用lspxposed（v0.5.4.1），也发现无法激活
之所以不同步升级magisk，是因为magisk从20.4升级到21.4后会丢失root。

**Version（发现问题的版本）:**
手机型号：华为荣耀V10  安卓8.0.0  EMUI8.0.0.204(C00GT)
Thanox版本：v2.3-prc，降级到老版本也无法激活
magisk版本：v20.4（20400）
riru模块版本：v23.5
edxposed版本：管理器版本v4.6.2（46200）、模块版本v0.5.2.2_4683-master

** Logs**（日志文件）
本次提供的是使用edxposed激活产生的日志，只找到一个日志，还有一个地方我删除原日志后，就不产生了。
[2021-02-19.zip](https://github.com/Tornaco/Thanox/files/6010626/2021-02-19.zip)

**Comment by Tornaco** [comment]
@achooyu  EdXposed或者LSP日志有吗？

**Comment by Tornaco** [comment]
@achooyu  如果还有问题请补充日志。暂时CLOSE

**Comment by ghost** [comment]
> @achooyu埃德克斯波德 · 斯莱普 · 斯普 · 斯库斯 ？
不好意思，太久没上github了。
[EdXposed_Verbose_20210608_143518.txt](https://github.com/Tornaco/Thanox/files/6614035/EdXposed_Verbose_20210608_143518.txt)

**Comment by ghost** [comment]
> > @achooyu埃德克斯波德 · 斯莱普 · 斯普 · 斯库斯 ？
> > 不好意思，太久没上github了。
> > [EdXposed_Verbose_20210608_143518.txt](https://github.com/Tornaco/Thanox/files/6614035/EdXposed_Verbose_20210608_143518.txt)

lsp不是最新版，因为安卓8.0装不了。
[LSPosed_Verbose_20210608_145833.log.txt](https://github.com/Tornaco/Thanox/files/6614171/LSPosed_Verbose_20210608_145833.log.txt)
