### ISSUE TITLE
最新版灭霸会让miui系统的备份挂掉

### ISSUE THREAD

**Issue by hanxin1997** [Tornaco/Thanox#242]
**Describe the bug（现象描述）
最新版灭霸会让miui系统的备份挂掉，

**To Reproduce**（如何复现）
安装就这样了，哪怕什么功能都没开也会。一直卡在0 ，卸载灭霸就好了

**Expected behavior**（期望结果）
修复

**Screenshots**（截图）
![QQ图片20210220161413](https://user-images.githubusercontent.com/58620096/108588933-b3935d00-7396-11eb-8a90-06fe96a70a9f.jpg)

**Version（发现问题的版本）:**
 - OS:安卓11 miui12.5 21.2.3 
 - 框架：lsposed v0.5.4.1{5178} 作用域设置系统框架
 - Version thanox_2.3-19-67bbf53-prc.apk 谷歌最新版2.3也是

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
获取不到 就一直在那

**Comment by Tornaco** [comment]
@hanxin1997  试试 https://github.com/Tornaco/Thanox/releases/tag/v2.3 thanox_2.3-20-8ff78c8-prc.apk

**Comment by hanxin1997** [comment]
> @ hanxin1997 试试https://github.com/Tornaco/Thanox/releases/tag/v2.3 thanox_2.3-20-8ff78c8-prc.apk

我装了，发现可以正常恢复备份了。
