### ISSUE TITLE
[问题反馈]Thanox2.3版本导致PE系统备份被停用/无法启用

### ISSUE THREAD

**Issue by suzakuo** [Tornaco/Thanox#245]
具体为备份界面显示:被管理员停用
云端硬盘备份开关打开后自动关闭,相关进程如下
com.google.android.gms/com.google.android.gms.backup.component.BackupSettingsActivity
这个进程无法打开开关
关闭Thanox模块,问题可以解决

这几天试了一下 2.3版本会出现这个问题
退回2.2就不会出现这个问题

Android 10  
应用版本: 2.3-3版本

**Comment by Tornaco** [comment]
@hhaii 试试 

https://github.com/Tornaco/Thanox/releases/tag/v2.3
thanox_2.3-20-8ff78c8-prc.apk

**Comment by zkwcw** [comment]
在最新的play版thanox pro中也有这个问题，关闭模块后可以正常工作。Android11，应用版本23-3-abd3490-row

**Comment by suzakuo** [comment]
> @hhaii 试试
> 
> https://github.com/Tornaco/Thanox/releases/tag/v2.3
> thanox_2.3-20-8ff78c8-prc.apk

问题解决，谢谢。
另外看到上面有个朋友也遇到了相同的问题，希望能尽快上架play。
