### ISSUE TITLE
情景模式蓝牙相关参数无法获取，返回为null

### ISSUE THREAD

**Issue by Ctrl-Ling** [Tornaco/Thanox#249]
**现象描述**

情景模式-蓝牙事件
btBoundedDeviceAliasNames参数无法获取绑定的蓝牙设备Alias列表，返回为null
蓝牙能力相关的参数如btBoundedDevices.get(0).getAddress()，蓝牙已成功链接的情况下返回也是null

**Screenshots**（截图）
![image](https://user-images.githubusercontent.com/36662875/109772025-78b3e380-7c38-11eb-8cee-d29fbaa962de.png)

**Version（发现问题的版本）:**
系统版本 安卓11 miui 12.5 红米K30U
软件版本 v2.4

**Comment by Tornaco** [comment]
@Ctrl-Ling  给个日志。

**Comment by Ctrl-Ling** [comment]
> 日志： 
[Thanox-log.zip](https://github.com/Tornaco/Thanox/files/6084128/Thanox-log.zip)

**Comment by Tornaco** [comment]
@Ctrl-Ling 试试 https://github.com/Tornaco/Thanox/releases/tag/v2.4

修复了蓝牙设备信息获取失败问题。

**Comment by Ctrl-Ling** [comment]
> @Ctrl-Ling 试试 https://github.com/Tornaco/Thanox/releases/tag/v2.4
> 
> 修复了蓝牙设备信息获取失败问题。

测试已解决！感谢
