### ISSUE TITLE
情景模式-shell命令方法sh.exe()的返回类型CommandResult接口文档？

### ISSUE THREAD

**Issue by Ctrl-Ling** [Tornaco/Thanox#250]
情景模式-shell命令方法sh.exe()的返回类型CommandResult如何对其返回结果进行解析、处理，有没有CommandResult类的接口文档之类的，想获取shell命令的输出结果（out）
![image](https://user-images.githubusercontent.com/36662875/109772639-317a2280-7c39-11eb-9c7f-4b0fccc57169.png)

具体遇到的问题是这样的：
![image](https://user-images.githubusercontent.com/36662875/109772769-5ec6d080-7c39-11eb-8e27-ca29f801349b.png)

**Comment by Tornaco** [comment]
参数如下：
后续会更新到文档里。

你的Shell命令返回的是`true`

```java
public final class SuRes implements Parcelable {
    /**
     * Shell result output.
     */
    private List<String> out;
    /**
     * Shell error output.
     */
    private List<String> err;
    /**
     * Return code of the cmd.
     */
    private int code;
}
```

**Comment by Ctrl-Ling** [comment]
> 参数如下：
> 后续会更新到文档里。
> 
> 你的Shell命令返回的是`true`
> 
> ```java
> public final class SuRes implements Parcelable {
>     /**
>      * Shell result output.
>      */
>     private List<String> out;
>     /**
>      * Shell error output.
>      */
>     private List<String> err;
>     /**
>      * Return code of the cmd.
>      */
>     private int code;
> }
> ```

请问这个SuRes类是否有获取Out参数的方法 比如SuRes.getOut()

**Comment by Tornaco** [comment]
@Ctrl-Ling  试试 https://github.com/Tornaco/Thanox/releases/tag/v2.4 

修复了蓝牙设备信息获取失败问题。

**Comment by Tornaco** [comment]
> 参数如下：
> 后续会更新到文档里。
> 
> 你的Shell命令返回的是`true`
> 
> ```java
> public final class SuRes implements Parcelable {
>     /**
>      * Shell result output.
>      */
>     private List<String> out;
>     /**
>      * Shell error output.
>      */
>     private List<String> err;
>     /**
>      * Return code of the cmd.
>      */
>     private int code;
> }
> ```

目前没有这个API。需要的话可以加上。

**Comment by Ctrl-Ling** [comment]
> > 参数如下：
> > 后续会更新到文档里。
> > 你的Shell命令返回的是`true`
> > ```java
> > public final class SuRes implements Parcelable {
> >     /**
> >      * Shell result output.
> >      */
> >     private List<String> out;
> >     /**
> >      * Shell error output.
> >      */
> >     private List<String> err;
> >     /**
> >      * Return code of the cmd.
> >      */
> >     private int code;
> > }
> > ```
> 
> 目前没有这个API。需要的话可以加上。

目前暂时使用了SuRes.toString().matches(正则)的形式获取out参数，比较麻烦，希望可以加一下相关api，毕竟shell能获取到的系统变量很多，辛苦了

**Comment by countrysideboy** [comment]
也需要类似的功能，要是能加个api就好了
