### ISSUE TITLE
升级新版本后卡开机第二屏，无法进入系统

### ISSUE THREAD

**Issue by flower-elf** [Tornaco/Thanox#253]
**Describe the bug（现象描述）**
升级thanox到2.4-11-24a90c5以后，在任何的框架管理器中激活模块，皆会导致无法启动（卡开机第二屏），停用模块后恢复正常

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1.安装edxp或者lsp（基于riru版本23.9）
2.在任何一个框架管理器内启用thanox
3.卡开机界面第二屏

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

启用模块，并且重启以后模块能正常工作。

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

由于在出现问题后无法进入系统，所以无法截取日志
如有截取方法请告知

**Version（发现问题的版本）:**
 - OS: QQ3A.200805.001
PixelExperience_Plus_lithium-10.0-20201223-0235-OFFICIAL
 - Version 2.4-11-24a90c5 （Google play）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

riru版本：23.9
lsp版本：1.2.2
edxposed版本：0.5.2.2_4683-master
thanox为Google play版本
手机型号：小米mix（lithium）
** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

由于在模块启用后会无法进入系统，故无法截取log

**Comment by Tornaco** [comment]
@raindrops2005  模块禁用之后，可以进系统查看日志。/data/system/thanos/xxx

或者最好能adb截取一份完整日志。

**Comment by flower-elf** [comment]
@Tornaco 好的

**Comment by flower-elf** [comment]
[thanox-core.log](https://github.com/Tornaco/Thanox/files/6102011/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/6102013/thanox-init.log)

@Tornaco 日志如上。希望能有所帮助

**Comment by flower-elf** [comment]
> @



> @raindrops2005 模块禁用之后，可以进系统查看日志。/data/system/thanos/xxx
> 
> 或者最好能adb截取一份完整日志。

如果需要Adb日志的话，可能需要明天晚上才可以，在data下的日志已经上传

**Comment by Tornaco** [comment]
@raindrops2005  最好有adb日志。

刚看了你给的日志，17:03:58.左右有一次launcher CRASH，再没有别的有用的信息了。

**Comment by flower-elf** [comment]
@Tornaco 如果这样的话。。。我试试adb能不能出来一些有用的东西

**Comment by flower-elf** [comment]
@Tornaco 如果还是没有的话那就可能会很麻烦了

**Comment by flower-elf** [comment]
@Tornaco [all.log](https://github.com/Tornaco/Thanox/files/6104309/all.log)
[modules.log](https://github.com/Tornaco/Thanox/files/6104312/modules.log)
补充：这是lsp框架日志
今晚会发adb日志的

**Comment by Tornaco** [comment]
@raindrops2005 OK 等你抓了日志看下。

**Comment by flower-elf** [comment]
问题已解决，此issue关闭
（PS：我手机在卡开机的时候是没法adb的，只能进rec进行恢复，所以也就很难抓日志）

**Comment by liqideqq** [comment]
@raindrops2005 哪个解决？

**Comment by flower-elf** [comment]
> @raindrops2005 哪个解决？

卡开机的问题已经解决
