### ISSUE TITLE
升级新版本后卡开机第二屏，无法进入arrow系统

### ISSUE THREAD

**Issue by liqideqq** [Tornaco/Thanox#254]
**Describe the bug（现象描述）
升级thanox到2.4-14-29874c6以后，在任何的框架管理器中激活模块，皆会导致无法启动（卡开机第二屏），停用模块后恢复正常，用的小米8se arrow安卓10.
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1.安装lsp（基于riru版本23.9）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
启用模块，并且重启以后模块能正常工作。

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
禁用模块后，进了arrow，进入了目录/data/system/thanos/xxx里没有日志，无法查看日志。
**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
riru版本：23.9
lsp版本：1.2.2
thanox为Thanox_2.4-14-29874c6-prc_2143064.apk

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
不能查看日志

**Comment by Tornaco** [comment]
@liqideqq 有日志没 /data/system/thanos/logging

或者能adb抓个日志更好。

**Comment by liqideqq** [comment]
[thanox-init.log](https://github.com/Tornaco/Thanox/files/6109514/thanox-init.log)
[thanox-core.log](https://github.com/Tornaco/Thanox/files/6109515/thanox-core.log)
server_logging的日志，application_logging的文件夹里没有日志

**Comment by liqideqq** [comment]
2.4-19正常开机，已解决
