### ISSUE TITLE
thanox最新版会导致大圣净化部分闪退。

### ISSUE THREAD

**Issue by hanxin1997** [Tornaco/Thanox#255]
**Describe the bug（现象描述）
只要安装上thanox就会让大圣净化闪退，排除后发现thanox安装后会导致大圣净化两个组件未开启（如图显示，而且开启也会自动关闭，在lsp框架关闭thanox恢复正常）。

**To Reproduce**（如何复现）
只要开启灭霸就会这样，在框架不激活thanox就不会闪退了。

**Expected behavior**（期望结果）
希望修复。问过大圣净化的作者也不知原因

**Screenshots**（截图）
![Screenshot_2021-03-11-15-47-55-169_github tornaco](https://user-images.githubusercontent.com/58620096/110754774-218ac000-8283-11eb-9320-cdd4611d9433.jpg)

**Version（发现问题的版本）:**
 - OS: miui12.5 官方开发版21.2.24 安卓11
 - Version：thanox pro2.4-20-9244957-row 大圣净化v3.8.80

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

**Comment by hanxin1997** [comment]
刚发现  关闭灭霸的任务清理，就不闪退了，不过组件没有恢复。

**Comment by Tornaco** [comment]
@hanxin1997 又没有设置什么情景模式之类的把这些组件关闭了呢。。这些组件thanox不会主动关闭。
