### ISSUE TITLE
[问题反馈] thanox

### ISSUE THREAD

**Issue by suzakuo** [Tornaco/Thanox#257]

**Comment by Tornaco** [comment]
@hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。

试试最新版本呢。

**Comment by hhaii** [comment]
> @hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。
> 
> 试试最新版本呢。

多谢回复
问题大概出现在 3-15 18:50左右
我把问题反馈里包含的日志目录下的文件都打包了
结果只有core日志管用
目前就是thanox pro最新版
因为问题偶现，所以很难复现
平时日用是没问题的，在2.2版本几乎没有出现
2.3也是稳定使用，更新2.4后似乎频繁了起来。
怀疑跟乖巧模式或者情景模式有关。
但是我打开关闭也都有软重启出现过
问题出现的极为偶然，所以并不知道具体的原因

**Comment by hhaii** [comment]
> @hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。
> 
> 试试最新版本呢。

另外，我尽量在下一次出现问题的时候尽快发送日志。
因为问题出现的很偶然，所以我也感到迷惑

**Comment by hhaii** [comment]
> @hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。
> 
> 试试最新版本呢。


在3-17 06:30左右出现问题了
这是日志
[thanox-core.log](https://github.com/Tornaco/Thanox/files/6152598/thanox-core.log)

**Comment by hhaii** [comment]
> > @hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。
> > 试试最新版本呢。
> 
谢谢回复
问题大概出现在 3-15 18:50左右

> 在3-17 06:30左右出现问题了
> 这是日志
> [thanox-core.log](https://github.com/Tornaco/Thanox/files/6152598/thanox-core.log)

**Comment by hhaii** [comment]
> @hhaii 日志最早的时间到2021-03-15 22:34:06.576 ，没发现有系统出错的日志。
> 
> 试试最新版本呢。

3-20 11:37 又出现相同的问题
这是日志 麻烦看一下
[logs.zip](https://github.com/Tornaco/Thanox/files/6174829/logs.zip)

**Comment by liu-cool-cmd** [comment]
@hhaii 我开启应用锁就会不定期软重启
