### ISSUE TITLE
重启后配置丢失

### ISSUE THREAD

**Issue by Wittoy** [Tornaco/Thanox#26]
**重启后配置丢失，且开机后第一屏自动打开Magisk**

 - OS: Android 10
 - Version 1.0.9
 - EDXposed Version 90.0-v0.4.6.0(4471)YAHFA
  
 **Log**
`1577430974921|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430974929|W|ThanoxApp|Platform app idle enabled: 1
1577430975060|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975392|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975430|V|ThanoxApp|isPaid? false
1577430975441|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975446|E|ThanoxApp|android.content.pm.PackageManager$NameNotFoundException: github.tornaco.practice.honeycomb.locker
1577430975447|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975449|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975452|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975454|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975455|V|ThanoxApp|java.lang.Throwable: onResume
1577430975456|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975456|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975458|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577430975728|D|ThanoxApp|onAttach
1577430975728|D|ThanoxApp|onCreate
1577430975728|D|ThanoxApp|onAttach
1577430975728|D|ThanoxApp|onCreate
1577430975728|D|ThanoxApp|onAttach
1577430975729|D|ThanoxApp|onCreate
1577430975729|D|ThanoxApp|onAttach
1577430975729|D|ThanoxApp|onCreate
1577430975815|D|ThanoxApp|onActivityCreated
1577430975827|D|ThanoxApp|onActivityCreated
1577430975831|D|ThanoxApp|onActivityCreated
1577430975846|D|ThanoxApp|onActivityCreated
1577431052483|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052490|W|ThanoxApp|Platform app idle enabled: 1
1577431052583|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052758|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052784|V|ThanoxApp|isPaid? false
1577431052793|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052798|E|ThanoxApp|android.content.pm.PackageManager$NameNotFoundException: github.tornaco.practice.honeycomb.locker
1577431052798|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052808|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052814|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052817|V|ThanoxApp|java.lang.Throwable: onResume
1577431052819|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052822|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052822|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052822|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431052869|D|ThanoxApp|onAttach
1577431052870|D|ThanoxApp|onCreate
1577431052870|D|ThanoxApp|onAttach
1577431052870|D|ThanoxApp|onCreate
1577431052870|D|ThanoxApp|onAttach
1577431052870|D|ThanoxApp|onCreate
1577431052871|D|ThanoxApp|onAttach
1577431052871|D|ThanoxApp|onCreate
1577431052936|D|ThanoxApp|onActivityCreated
1577431052946|D|ThanoxApp|onActivityCreated
1577431052950|D|ThanoxApp|onActivityCreated
1577431052961|D|ThanoxApp|onActivityCreated
1577431054359|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431054402|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431054407|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054467|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054469|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054521|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054523|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054589|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054591|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054649|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054687|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054690|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054692|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054774|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054818|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054911|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054913|D|ThanoxApp|loadProcess, filter index: _3rd
1577431054948|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055006|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055039|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055040|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055041|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055042|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055044|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055045|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055046|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055047|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055049|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055085|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055086|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055088|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055089|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055090|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055092|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055093|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055094|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055095|D|ThanoxApp|loadProcess, filter index: _3rd
1577431055191|D|ThanoxApp|loadData: github.tornaco.android.thanos
1577431055192|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055200|D|ThanoxApp|loadData: com.PmTqbZJ.kMH.KWnh
1577431055201|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055228|D|ThanoxApp|loadData: com.iflytek.inputmethod.google
1577431055229|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055243|D|ThanoxApp|loadData: co.tgbot.peekfun
1577431055243|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055263|D|ThanoxApp|loadData: com.github.kr328.clash
1577431055264|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055277|D|ThanoxApp|loadData: com.xiaomi.xmsf
1577431055278|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055289|D|ThanoxApp|loadData: com.tencent.mm
1577431055290|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055316|D|ThanoxApp|loadData: com.tencent.androidqqmail
1577431055317|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055343|D|ThanoxApp|loadData: com.maxmpz.audioplayer
1577431055343|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055369|D|ThanoxApp|loadData: com.fenbi.android.solar
1577431055375|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055378|D|ThanoxApp|loadData: com.google.android.webview
1577431055378|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431055387|D|ThanoxApp|loadData: com.omarea.vtools
1577431055388|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056126|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056130|V|ThanoxApp|isPaid? false
1577431056131|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056134|E|ThanoxApp|android.content.pm.PackageManager$NameNotFoundException: github.tornaco.practice.honeycomb.locker
1577431056135|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056138|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056139|V|ThanoxApp|java.lang.Throwable: onResume
1577431056139|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056140|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056140|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056141|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056144|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056844|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056949|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056950|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431056954|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057238|D|ThanoxApp|loadData: com.agilebits.onepassword
1577431057239|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057258|D|ThanoxApp|loadData: tv.danmaku.bili
1577431057258|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057280|D|ThanoxApp|loadData: com.coderstory.toolkit
1577431057281|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057297|D|ThanoxApp|loadData: wangdaye.com.geometricweather
1577431057297|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057314|D|ThanoxApp|loadData: com.google.android.calculator
1577431057314|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057332|D|ThanoxApp|loadData: com.scliang.bqcalendar
1577431057333|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057350|D|ThanoxApp|loadData: com.coolapk.market
1577431057351|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057375|D|ThanoxApp|loadData: com.quark.browser
1577431057375|W|ThanoxApp|Init thanos manager for package: github.tornaco.android.thanos
1577431057385|D|ThanoxApp|loadData: com`

**Comment by Tornaco** [comment]
手动设置data/system/thanos的owner为1000

不要用钛备份等root备份app备份系统配置。

**Comment by sandianyue** [comment]
大佬我修改了thanos文件夹拥有者 只是解决了备份权限被拒的问题 可以正常备份了 但是重启还是会丢失配置

**Comment by Tornaco** [comment]
@sandianyue 截图看下文件夹权限。 另外下面有日志吗？

**Comment by sandianyue** [comment]
> @sandianyue 截图看下文件夹权限。 另外下面有日志吗？

老大 不好意思  回复完之后 莫名又好了 之前每次重启确实都会 权限也给到了 暂时无法帮助复现了
