### ISSUE TITLE
能不能增加关联唤醒发起者的名单呢老哥

### ISSUE THREAD

**Issue by abcdol** [Tornaco/Thanox#26]
看抖音都是几百次唤醒，想知道能不能看看是谁把它唤醒的，最好有个统计，看哪个软件唤醒其他软件的次数最多。
还有就是想问一下切断关联启动就不会耗电了吗？一天几万次唤醒实在是吓人，发起唤醒请求不会很耗电吗？

**Comment by Tornaco** [comment]
@abcdol 1. 阻止采用拦截方式，额外耗电可能在于读取内存里的设定值所消耗的cpu时间所用电量。可以忽略不计。
2. 启动是正常现象，无非是某些应用设定的启动触发多一些。建议不要慌张。可以不看。

**Comment by abcdol** [comment]
好滴 感谢～
