### ISSUE TITLE
[严重]操作系统经常随机重启

### ISSUE THREAD

**Issue by Gokou-Ruri** [Tornaco/Thanox#262]
**Describe the bug（现象描述）**
手机突然重启（快速重启，非完整重启），此问题随机复现，可能是聊天打字时，也可能是浏览网页时，也可能是看视频时，<b>甚至连手机待机时也会突然重启，完全随机没有规律。</b>自从2.4升到2.5以后就经常出现，平均一天或两天一次，已经出现很多次了。
昨天我把Thanox日志全部清空，并手动重启了手机，直到刚才又出现了一次，现在我把日志打包上传了。

**To Reproduce**（如何复现）
无法稳定复现，完全随机出现。

**Version（发现问题的版本）:**
 - OS: Android 11
 - Version 2.5-4-3d60991-row

** Logs**（日志文件）
<b>/data/media/0/Android/data/github.tornaco.android.thanos.pro/cache/logs</b>
 [logs.tar.gz](https://github.com/Tornaco/Thanox/files/6215766/logs.tar.gz) 

<b>/data/system/thanos/logging</b>
 [logging.tar.gz](https://github.com/Tornaco/Thanox/files/6215767/logging.tar.gz) 

3.28续：刚才又出现这个情况了，是在玩游戏的时候。日志在下面：
 [logs.tar.gz](https://github.com/Tornaco/Thanox/files/6217158/logs.tar.gz) 
 [logging.tar.gz](https://github.com/Tornaco/Thanox/files/6217161/logging.tar.gz) 

3.29续：新的随机重启日志：
 [logs.tar.gz](https://github.com/Tornaco/Thanox/files/6218248/logs.tar.gz)
[logging.tar.gz](https://github.com/Tornaco/Thanox/files/6218249/logging.tar.gz) 

3.29续2：当天第二次随机重启日志：
[logs.tar.gz](https://github.com/Tornaco/Thanox/files/6218952/logs.tar.gz)
[logging.tar.gz](https://github.com/Tornaco/Thanox/files/6218953/logging.tar.gz)

3.30续：在LSPosed中禁用Thanox超过24小时未出现随机重启现象，在此之前随机重启现象已经出现了约20次左右。

**Comment by Gokou-Ruri** [comment]
4.2续：安装了logcat模块，然后把Thanox启用，重启，然后持续把logcat打印为文件，碰到随机重启现象后，手机开机，从输出的log文件中提取了末尾1000行。
以下是两次随机重启前logcat输出的内容：
[1000-1.log.tar.gz](https://github.com/Tornaco/Thanox/files/6247804/1000-1.log.tar.gz)

[1000-2.log.tar.gz](https://github.com/Tornaco/Thanox/files/6247796/1000-2.log.tar.gz)

**Comment by Tornaco** [comment]
@Gokou-Ruri  能抓logcat的话，1000行太少了。。完整日志发下吧。

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 能抓logcat的话，1000行太少了。。完整日志发下吧。

完整的有1G、6G多的，<s>不知道github能不能上传这么大的文件。
我压缩了试试。</s>好像最大只允许10M的文件……
我传到Telegram上吧。
https://t.me/shirochan_share/4?single
文件名是日期

补充：我发现只要是随机重启的日志文件基本上都很大，哪怕只有数小时的logcat都有好几个G。而稳定运行不重启的情况下，logcat哪怕持续记录好几天也只有1、2G。

**Comment by ghost** [comment]
手机信息：
Manufacturer: LeEco
Brand: LeEco
Device: le_zl1
Product: le_zl1
Model: LEX720
Fingerprint: LeEco/ZL1_NA/le_zl1:6.0.1/WEXNAOP5802101261S/letv01261206:user/release-keys
ROM description: le_zl1-user 6.0.1 WEXNAOP5802101261S eng.letv.20170126.120318 release-keys
Architecture: arm64-v8a
Android build: RQ2A.210305.006
Android version: 11
Android sdk: 30
LSPosed version: v1.3.4 (5534)
Riru version: v25.3.4.r399.84f7084 (399)
Riru api: 25
Magisk: 66e30a77 (22006
Thanox Pro：版本 2.5-4-3d60991-row
描述错误（现象描述）
手机出现异常卡机后直接关机，此问题随机复现，第一次出现版本未知，刚刷了机，自刷机到现在出现过三次，未成功捕捉日志
复制（如何复现）
无法稳定复现，完全随机出现。多（95%以上几率）出现在正在刷抖音（我只玩抖音其他未知）直接卡，然后重启,

版本（发现问题的版本）：

操作系统：Android 11
版本 2.5-4-3d60991-row
