### ISSUE TITLE
【功能请求】希望在组件管理中加入提供器（manage Providers）

### ISSUE THREAD

**Issue by ashurajo** [Tornaco/Thanox#263]
现在已经可以禁用Activities、Receivers、Services，但是Providers还要用其他的工具来修改。。。有点麻烦，希望作者能增加下这个功能。

**Comment by ashurajo** [comment]
@Tornaco 大佬有空看看喵？

**Comment by Tornaco** [comment]
@ashurajo 3.1.1已支持。
