### ISSUE TITLE
我激活不了Thanox，我用edxp激活其他基于xp的软件可以激活，但是重启了好多次，thanox还是激活不了，于是我换了lsp，更新到最新的lsp5563版本，还是激活不了。我试了更新面具，还是激活不了。

### ISSUE THREAD

**Issue by ilikekissing** [Tornaco/Thanox#271]
lsp日志log:LSPosed Log
--------- beginning of information
Manufacturer: HUAWEI
Brand: HUAWEI
Device: HWSCM
Product: SCM
Model: SCM-AL09
Fingerprint: HUAWEI/SCM-AL09/HWSCM:9/HUAWEISCM-AL09/108C00:user/release-keys
ROM description: SCM-AL09-user 9.1.1 HUAWEISCM-AL09 108-CHN-LGRP1 release-keys
Architecture: arm64-v8a
Android build: HUAWEISCM-AL09
Android version: 9
Android sdk: 28
LSPosed version: v1.3.5 (5563)
Riru version: v25.4.2.r415.f42e9c3 (415)
Riru api: 25
Magisk: 22.1 (22100)
2021-04-25 16:46:02.002 I/?(5389-5389): hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@4e90a61]
//****Thanox log
********log1
1619367044903|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619367044903|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619367044904|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619367044904|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619367044905|D|ThanoxApp|onAttach
1619367044905|D|ThanoxApp|onCreate
1619367044912|D|ThanoxApp|onActivityCreated
1619367044915|V|ThanoxApp|isPaid? false
1619367044916|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368248965|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368248965|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368248966|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368248966|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368248967|D|ThanoxApp|onAttach
1619368248967|D|ThanoxApp|onCreate
1619368248974|D|ThanoxApp|onActivityCreated
1619368248979|V|ThanoxApp|isPaid? false
1619368248980|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368352335|V|ThanoxApp|isPaid? false
1619368352338|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368611314|V|ThanoxApp|isPaid? false
1619368611316|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619368830861|V|ThanoxApp|isPaid? false
1619368830863|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369162205|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369162205|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369162206|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369162206|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369162207|D|ThanoxApp|onAttach
1619369162207|D|ThanoxApp|onCreate
1619369162214|D|ThanoxApp|onActivityCreated
1619369162218|V|ThanoxApp|isPaid? false
1619369162220|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369517450|V|ThanoxApp|isPaid? false
1619369517453|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
1619369520132|V|ThanoxApp|isPaid? false
1619369520134|V|ThanoxApp|A92E8A9A743FE6648E2E4743FDAC89E9EB4A568F
**

**Comment by amazing3k** [comment]
一样，付费后作者都不管了

**Comment by Tornaco** [comment]
请提供完整lsposed日志或者尝试最新thanox版本。

**Comment by sangerge** [comment]
这玩意儿根本激活不了，面具也试了，xposed也试了，没用
