### ISSUE TITLE
Thanox Pro 乖巧模式与系统双击唤醒冲突

### ISSUE THREAD

**Issue by humbleoxygen12** [Tornaco/Thanox#275]
当Thanox开启乖巧模式，每次重启系统不操作息屏后，双击将无法亮屏，关闭乖巧模式后正常。

 - OS: Android 11 Pixel Experiences
 - Version 2.4-20 Google Play

**Comment by aboutZZ** [comment]
+1
每次都要强制关机

**Comment by Tornaco** [comment]
乖巧模式里加了哪些app呢。。
