### ISSUE TITLE
应用被「任务清理」后无法被 FCM 及时唤醒，即便借助「情景模式」

### ISSUE THREAD

**Issue by ChrAlpha** [Tornaco/Thanox#285]
应用被「任务清理」后**无法被 FCM 及时唤醒**，即便借助「情景模式」依旧**无法唤醒推送通知**。

我发送测试信息后，FCM 在 `18:04:58.426` 第一次收到（Recived），但是**没有推送任何通知**，而是在 FCM log 中返回 `Failed to broadcast to stopped app`；直至 `18:34` 左右（通知栏显示时间）延迟 30 分钟才收到通知，此时再打开 FCM log **没有任何相关时间点的记录**。

> 补充：
> 
> 再次测试发现被「任务清理」后超过半小时亦无法收到通知推送，上述延迟 30 分钟收到通知的现象可能是偶然情况，一直未能复现。
> 
> 使用「乖巧模式」限制是能被「情景模式」及时唤醒推送的，故又有疑问 3。

此时打开 Thanox 后台运行列表，发现应用已经在「运行中」列表内；而当应用被从最近任务中划掉时，确认过是不在「运行中」列表内的。这岂不是又启动在后台了，「任务清理」效果被覆盖。

- 疑问 1：「任务清理」效果是否类似于 Android 系统的 "Force Stop"，据我所知这个状态**无法被 FCM 唤醒推送**
- 疑问 2：「后台运行」超时后清理的效果是否类似于 Android 系统的 "Force Stop"，同上
- 疑问 3：「乖巧模式」中的「停止所有服务」、「处于待机状态」与「任务清理」中的「清理应用后台」实现上有何异同？

如果确实是这样，那是否可以得到「想要保留应用的通知能力，就不能对应用进行『任务清理』且要给予『后台运行』权限」的结论？又或者是否可以借助「情景模式」先**及时地**唤醒应用进行通知推送（30 分钟显然说不上及时地）、然后在通知推送完成后再让应用进入**被清理的状态**？

情景模式配置（默认的 GCM Push 配置）：

```json
[
  {
    "name": "GCM Push",
    "description": "感知GCM FCM推送",
    "priority": 2,
    "condition": "fcmPushMessageArrived == true",
    "actions": [
      "activity.launchProcessForPackage(pkgName);"
    ]
  }
]
```

确认设备能正常使用 FCM 服务，确认已经开启「情景模式 - 引擎 - 推送消息」，确认 Thanox 在系统优化白名单可以保持后台常驻，确认在 Thanox 电池配置中未开启任何省电策略。

**Comment by ChrAlpha** [comment]
破案了，没有给予应用「自启动」权限，给予后便能正常唤醒通知，且在息屏数分钟后又被后台运行限制而释放内存。

**Comment by csy19960309** [comment]
> 破案了，没有给予应用「自启动」权限，给予后便能正常唤醒通知，且在息屏数分钟后又被后台运行限制而释放内存。

「自启动」是指后台启动的设置中允许微信后台启动么？我勾上了微信，但是仍然因Failed to broadcast to stopped app而无法拉起应用。

**Comment by PoseidonWake** [comment]
请问自启动权限是在打开后台启动吗？我开了后台启动，fcm日志里显示successful broadcast，应用也在出现在缓存里了，但是通知栏没消息
