### ISSUE TITLE
未激活

### ISSUE THREAD

**Issue by fjfh158** [Tornaco/Thanox#286]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

>EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Google
Brand: google
Device: crosshatch
Product: crosshatch
Model: Pixel 3 XL
Fingerprint: google/crosshatch/crosshatch:9/PQ2A.190405.003/5310204:user/release-keys
ROM description: crosshatch-user 9 PQ2A.190405.003 5310204 release-keys
Architecture: arm64-v8a
Android build: PQ2A.190405.003
Android version: 9
Android sdk: 28
EdXposed version: v0.5.2.2_4683-master
EdXposed api: 93
Riru version:  ()
Riru api: 25
Magisk: 20.0 (20000)
--------- beginning of main
--------- beginning of system
07-16 20:10:41.912  1691  1691 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:41.939  1691  1691 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.019  1711  1711 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.022  1711  1711 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.027  1728  1728 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.031  1728  1728 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.343  1820  1820 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.349  1820  1820 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.467  1844  1844 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.472  1844  1844 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.540  1815  1815 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.550  1815  1815 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.745  1861  1861 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.750  1835  1835 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.758  1861  1861 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.759  1835  1835 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.780  1691  1691 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:42.784  1828  1828 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:42.791  1728  1728 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:42.796  1828  1828 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:42.796  1691  1691 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:42.830  1728  1728 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:42.920  1711  1711 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:42.980  1711  1711 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:43.018  1900  1900 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:43.024  1900  1900 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:43.102  1691  1691 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.187  1728  1728 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.296  1711  1711 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.393  1820  1820 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:43.416  1820  1820 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:43.611  1820  1820 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.646  1815  1815 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:43.675  1815  1815 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:43.723  1844  1844 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:43.772  1844  1844 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:43.928  1828  1828 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:43.929  1861  1861 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:43.938  1815  1815 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.974  1861  1861 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:43.997  1835  1835 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:44.019  1835  1835 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:44.143  1844  1844 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:44.153  1900  1900 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:44.166  1900  1900 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:44.208  1828  1828 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:44.253  1835  1835 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:44.346  1900  1900 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:33.507  2162  2162 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:33.512  2162  2162 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:34.043  2162  2162 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:34.055  2162  2162 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:34.181  2253  2253 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:34.185  2253  2253 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:34.205  2162  2162 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:34.711  2253  2253 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:34.722  2253  2253 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:34.891  2253  2253 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:35.055  2280  2280 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:35.060  2280  2280 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:35.671  2334  2334 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:35.680  2334  2334 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:35.703  2352  2352 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:35.711  2352  2352 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:35.887  2367  2367 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:35.895  2280  2280 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:35.896  2367  2367 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:35.907  2280  2280 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:36.227  2280  2280 I EdXposed-Bridge:   Loading class com.xposed.XSupport
07-16 20:10:36.619  2426  2426 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.629  2426  2426 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:36.719  2387  2387 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.727  2387  2387 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:36.734  2405  2405 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.756  2405  2405 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:36.780  2396  2396 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.785  2396  2396 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:36.878  2434  2434 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.889  2434  2434 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:36.960  2352  2352 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:36.989  2441  2441 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:36.997  2441  2441 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:37.016  2367  2367 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:37.024  2352  2352 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:37.041  2367  2367 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:37.049  2413  2413 I EdXposed-Bridge: Loading modules from /data/app/github.tornaco.android.thanos-ePkKaBt5FccarQF_Kdiong==/base.apk
07-16 20:10:37.096  2413  2413 I EdXposed-Bridge:   Loading class github.tornaco.android.thanos.services.xposed.XposedHookEntry
07-16 20:10:37.156  2334  2334 I EdXposed-Bridge: hookSystemServiceRegistry, unhooks=[de.robv.android.xposed.XC_MethodHook$Unhook@f15f06e]
07-16 20:10:37.178  2334  2334 I EdXposed-Bridge: Loading modules from /data/app/ru.SELjkbil.KZCYXOodo-l_FtPp2LIXjF431sclxkkg==/base.apk
07-16 20:10:37.243  2420  2420 I EdXposed-Bridge: Loading modules from /dat

**Comment by Tornaco** [comment]
请按照Thanox-设置-反馈 中指定的反馈流程补充thanox相关日志。暂时close.
