### ISSUE TITLE
功能正常 日志一直打印 Report nativeInjectInputEvent 

### ISSUE THREAD

**Issue by puzzle9** [Tornaco/Thanox#29]
![Screenshot_2019-12-30-11-43-25-117_github tornaco android thanos](https://user-images.githubusercontent.com/13518196/71567477-6f8e2a80-2afa-11ea-919e-374ea8cff9c3.jpg)
![Screenshot_2019-12-30-11-43-08-282_org meowcat edxposed manager](https://user-images.githubusercontent.com/13518196/71567478-70bf5780-2afa-11ea-9d9e-2161511706e1.jpg)

**Comment by Tornaco** [comment]
@puzzle9 观察细致

**Comment by Tornaco** [comment]
@puzzle9 回头去掉

**Comment by Tornaco** [comment]
新版本1.1.2-x已经去除。如还有问题再讨论。
