### ISSUE TITLE
riru-thanox-3.0导致的 大部分软件打不开

### ISSUE THREAD

**Issue by j0912H97** [Tornaco/Thanox#290]
S20 ULTRA
SM-G988N
ONEUI 3.1
Android 11
MAGISK alpha 1eb83ad8-alpha-26
RIRU 26.0.1
riru-thanox-3.0-alpha-3-25b0faf-release.zip
THANOX PRO 3.0 alpha-6
刷入面具模块之后 手机卡顿 大部分软件打不开
日志较大 你忍一下

[bootlog.zip](https://github.com/Tornaco/Thanox/files/6876786/bootlog.zip)

**Comment by Tornaco** [comment]
[riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip](https://github.com/Tornaco/Thanox/files/6877798/riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip)

@j0912H97 试试这个版本？

**Comment by j0912H97** [comment]
> [riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip](https://github.com/Tornaco/Thanox/files/6877798/riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip)
> 
> @j0912H97 试试这个版本？



> [riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip](https://github.com/Tornaco/Thanox/files/6877798/riru-thanox-3.0-alpha-3-25b0faf-dirty-release.zip)
> 
> @j0912H97 试试这个版本？

大部分软件都能打开了（不确定）
但是我的kiwi浏览器虽然能打开 但一直是假期状态
然后用 aurora store不能更新软件
还有一个很久之前就有的问题 就是插件无法使用 一直显示重启后激活的状态
我在给你一份日志。
[bootlog.ZIP](https://github.com/Tornaco/Thanox/files/6881856/bootlog.ZIP)
谢谢你@tornaco

**Comment by Tornaco** [comment]
@j0912H97  Magisk补丁和xposed补丁不能同时使用。你确定你使用magisk补丁激活后thanox app里有插件这个功能？

**Comment by j0912H97** [comment]
> @j0912H97 Magisk补丁和xposed补丁不能同时使用。你确定你使用magisk补丁激活后thanox app里有插件这个功能？

我一直是 再装了lsp框架的情况下提供的日志
在以前我记得框架和面具的thanox是可以共存的
然后thanox插件这个问题是无论装不装magisk thanox都会出的问题
下面这个日志你再看一下 看看插件的问题

你的意思是如果我在lsp框架下激活了thanox就不能用magisk版本的thanox？
 
[bootlog.zip](https://github.com/Tornaco/Thanox/files/6886110/bootlog.zip)

**Comment by Tornaco** [comment]
@j0912H97 两者取其一。Xposed和Magisk补丁都是给系统打补丁，哪个兼容自己的设备用哪个就OK了。

**Comment by j0912H97** [comment]
> @j0912H97 两者取其一。Xposed和Magisk补丁都是给系统打补丁，哪个兼容自己的设备用哪个就OK了。

好的 明白了 谢谢你的耐心解答
我刚才在lsp框架下禁用了thanox pro
只启用了magisk thanox的状态下发现 手机会无限重启
你要不再看看？（其实不看也行，因为lsp启用thanox pro的状
[bootlog.zip](https://github.com/Tornaco/Thanox/files/6886275/bootlog.zip)
态下并没有什么问题 除了插件一直显示重启状态）

**Comment by h0cheung** [comment]
> @j0912H97 两者取其一。Xposed和Magisk补丁都是给系统打补丁，哪个兼容自己的设备用哪个就OK了。

Android 11 都可以使用时更推荐哪一个

**Comment by PuerNya** [comment]
> > @j0912H97 两者取其一。Xposed和Magisk补丁都是给系统打补丁，哪个兼容自己的设备用哪个就OK了。
> 
> Android 11 都可以使用时更推荐哪一个

现在是抓小白鼠阶段如果你想用稳一点就 xposed 模式激活

**Comment by Tornaco** [comment]
@j0912H97  最新版有改进了吗？

**Comment by Tornaco** [comment]
Fixed & Close
