### ISSUE TITLE
关于 riru 模组炸 appops 这件事

### ISSUE THREAD

**Issue by PuerNya** [Tornaco/Thanox#291]
**Describe the bug（现象描述）**
riru 模组会炸掉 appops 组件

**To Reproduce**（如何复现）
刷写 riru-thanox_core

**Expected behavior**（期望结果）
appops 组件爆炸，无法被相关软体（AppOps，权限狗等）进行管理，也无法通过 adb 命令进行管理

**Screenshots**（截图）
![Screenshot_20210727-093945628](https://user-images.githubusercontent.com/16221246/127253249-ae5539eb-8869-4cf4-bdbe-0477dedd0ddf.jpg)

**Version（发现问题的版本）:**
 - OS: 11
 - Version: 25b0faf

**Additional context**（其他信息）
🈚️

** Logs**（日志文件）
暂时没有落鸽，等我有空复现一下烤了发上来

**Comment by Tornaco** [comment]
@kaniwow OK 应该是hook冲突了，后续会关注。

**Comment by Tornaco** [comment]
@kaniwow Is it fix on latest release?

**Comment by Tornaco** [comment]
Close then.
