### ISSUE TITLE
更新thanox po 卡 检查页面

### ISSUE THREAD

**Issue by Cokeblue** [Tornaco/Thanox#292]
之前是4.99刀入的pro 
版本号是2.4.20.9244957
一切都挺正常
用就挺长时间，今天突然出现点开闪退
我就
去google play 升级成了最新版2.5 的
于是就一直卡正在检查网络 能否正常访问google play 

我挂着工具 手机浏览器的google play stroe 和手机的google play store都是一切正常的 
手机是 oppo reno ace  color os 7.1 基于安卓10 无系统级<面具>的Gapp 
特此来求助

去tg咨询了下群友，我的想法是想下回原来那版本的apk，我备份了原来那版本的数据，忘记备份apk了。 。群友推荐了Aurora.store
然而我又不知道如何获取
2.4.20.9244957的version code

**Comment by Tornaco** [comment]
@Cokeblue 通常都是GMS框架问题。

为了维护已购买用户的利益，2.5-4版本添加了Play购买资质验证；
目前看来还是可能会误伤，稍后会更新一个去除验证的版本，后续可能就不再进行验证了~:(

**Comment by Tornaco** [comment]
Fixed.
