### ISSUE TITLE
运行管理显示bug

### ISSUE THREAD

**Issue by KanoCifer** [Tornaco/Thanox#299]
运行管理内，休眠显示灰框

![Screenshot_20210815-142854.png](https://user-images.githubusercontent.com/57797351/129469408-0fa7c57d-486f-449c-82b4-4b95bd196bde.png)

）Android 11
）3.0-Alpha2

**Comment by Tornaco** [comment]
@KanoCifer Please try latest release alpha apk [thanox_3.0-alpha02-3-12b9d59-prc.apk](https://github.com/Tornaco/Thanox/releases/tag/v3.0-alpha02)

Close for now.

**Comment by KanoCifer** [comment]
> @KanoCifer Please try latest release alpha apk [thanox_3.0-alpha02-3-12b9d59-prc.apk](https://github.com/Tornaco/Thanox/releases/tag/v3.0-alpha02)
> 
> Close for now.

ok，解决了
