### ISSUE TITLE
1.0.4版本直装1.0.6升级后 无法激活

### ISSUE THREAD

**Issue by dreamermt** [Tornaco/Thanox#3]
该问题已经自行解决 希望后续版本不再出现

解决步骤：
1、进入edxposed installer取消模块勾选，重启。
2、进入edxposed installer勾选模块，重启。

不确定edxposed manger是否会出现该现象，日志忘了保存，看了下edxposed installer模块日志，显示某文件（路径也记不清了）don't exit，因此想到取消勾选尝试解决。

**Comment by Tornaco** [comment]
@dreamermt 请不要把xpodedinstaller组织启动。应用更新后apk路径会发生变化，如果xposedinstaller感知不到这个变化，就无法找到对应的apk位置。，导致无法加载apk。无法激活。

**Comment by dreamermt** [comment]
> @dreamermt 请不要把xpodedinstaller组织启动。应用更新后apk路径会发生变化，如果xposedinstaller感知不到这个变化，就无法找到对应的apk位置。，导致无法加载apk。无法激活。

能不能加上（关联启动规则）？ （应用管理）中的ALLOW和DENY指令很好用，google play 服务太容易自启动了，在（任务清理）添加上也没用，直接在（后台启动）里取消勾选不允许自启动和关联启动太强硬了，导致谷歌商店、谷歌游戏等必须依赖google play 服务的软件无法正常运行。
    如果能设置成不允许自启动、不允许关联启动（这两个功能最好能分开设置），只允许被某几个APP关联启动就完美了。

**Comment by Tornaco** [comment]
@dreamermt 规则还是会考虑下有没有必要的使用场景。目前是希望尽可能设置简单些，太复杂容易出问题且不好排查。具体还是要看使用场景。

**Comment by Tornaco** [comment]
该问题关闭，不在插件处理范围。
