### ISSUE TITLE
Edxposed勾选激活重启后依然显示未激活

### ISSUE THREAD

**Issue by Coconutat** [Tornaco/Thanox#301]
这里是EdXposed的log文件。
[EdXposed_log.zip](https://github.com/Tornaco/Thanox/files/7005903/EdXposed_log.zip)
机型是华为p10

**Comment by Tornaco** [comment]
@Coconutat 请提供data/system/thanos/logging下的日志

**Comment by Coconutat** [comment]
> @Coconutat 请提供data/system/thanos/logging下的日志

目录下没有thanos这个文件夹。

**Comment by Coconutat** [comment]
> @Coconutat 请提供data/system/thanos/logging下的日志

大佬，有没有支持安卓8.0的Thanos v2.5.4的Magisk模块？我这个手机Magsik v20以上都无法支持，Xposed也只能刷EdXposed。

**Comment by Tornaco** [comment]
@Coconutat Magisk模块适配成本较高，暂不考虑低版本了~

**Comment by Tornaco** [comment]
Close since no log provided.
