### ISSUE TITLE
app ops功能部分失效

### ISSUE THREAD

**Issue by Hidarihitomi** [Tornaco/Thanox#304]
xposed模式激活情况下，app ops功能部分失效，关闭了应用的toast通知还是会跳通知。关掉亮度权限的应用又正常，不会被app强制高亮，其他的没有发现。

**Comment by Tornaco** [comment]
@Hidarihitomi Android版本？

**Comment by Hidarihitomi** [comment]
> @Hidarihitomi Android版本？

11，氧os。3.0之前的版本tosat也都正常可以修改，3.0之后才不行

**Comment by Tornaco** [comment]
@Hidarihitomi  Toast 图标的问题可以试试把目标app的lsp作用域也勾选上。
