### ISSUE TITLE
激活不了

### ISSUE THREAD

**Issue by Sfssup** [Tornaco/Thanox#306]
Android9；MIUI11 从3.0的第二个版本开始就激活不了

**Comment by Tornaco** [comment]
@EatmeIon 请补充详细信息：xposed还是magisk？ 日志？

**Comment by Sfssup** [comment]
> @EatmeIon 请补充详细信息：xposed还是magisk？ 日志？

LSPosed1.5.1
Magisk23

日志的话不会弄..

**Comment by Tornaco** [comment]
Close since no log provided.
