### ISSUE TITLE
关于桌面启动器后台的钩子坏了

### ISSUE THREAD

**Issue by PuerNya** [Tornaco/Thanox#307]
**Describe the bug（现象描述）**
riru 模式下开启后台模糊无效果

**To Reproduce**（如何复现）
不需要多余操作

**Expected behavior**（期望结果）
如题

**Screenshots**（截图）
null

**Version（发现问题的版本）:**
 - OS: Android 11 PEP
 - Version: alpha03

**Additional context**（其他信息）
null

** Logs**（日志文件）
null

**Comment by LiAlH4qwq** [comment]
@kaniwow 你确定riru版本有这个功能？

**Comment by PuerNya** [comment]
> @kaniwow 你确定riru版本有这个功能？

ui 没删除

**Comment by LiAlH4qwq** [comment]
@kaniwow 我这边可以自动删除，你是不是同时激活了riru版和xposed版

**Comment by Tornaco** [comment]
Magisk补丁暂不支持任务模糊，App配置页面后续会隐藏该配置项，Close.
