### ISSUE TITLE
riru module cause random soft reboot

### ISSUE THREAD

**Issue by LiAlH4qwq** [Tornaco/Thanox#308]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
riru module cause random soft reboot. it seems that zygote crashes.
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）
install riru module and wait for reproducing.
**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
reduce the frequency of soft reboot
**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
can't give a screenshot
**Version（发现问题的版本）:**
 - OS: [e.g. Android 

> 6.0.1]（系统版本，例如Android 6.0.1）

 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）
Android 11, v3.0-alpha03
**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
riru is latest version
** Logs**（日志文件）
[务必将截取到的日志文件发到该issue里。](url)
[log.tar.xz.zip](https://github.com/Tornaco/Thanox/files/7043061/log.tar.xz.zip)

**Comment by Tornaco** [comment]
@Fe3O4-Git 你是在xposed和magisk里同时勾选了thanox相关模块？

**Comment by LiAlH4qwq** [comment]
> @Fe3O4-Git 你是在xposed和magisk里同时勾选了thanox相关模块？

可能当时我没取消掉edxposed中的hook，我现在取消xp uook后再使用一段时间，如果没有问题就close issue
