### ISSUE TITLE
Magisk模块卡开机

### ISSUE THREAD

**Issue by SukiEva** [Tornaco/Thanox#309]
**Describe the bug（现象描述）**
最新Pre-Release刷入magisk后（未用xposed）卡开机动画

**To Reproduce**（如何复现）
刷入magisk zip

**Version（发现问题的版本）:**
 - OS: 安卓11 OxygenOS Oneplus 8T

** Logs**（日志文件）
我的log也很大，你忍一下
[all_2021-08-29_13-52-54.zip](https://github.com/Tornaco/Thanox/files/7072015/all_2021-08-29_13-52-54.zip)

**Comment by StephenSSR** [comment]
氢os安卓11也卡开机了，一加7

**Comment by hanxin1997** [comment]
miui开发版安卓11也卡开机 k20pro

**Comment by Tornaco** [comment]
Mark OOS Android11
```
java.lang.ClassCastException: $Proxy2 cannot be cast to com.android.server.am.ActivityManagerService
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.SocketTransition.<init>(Unknown Source:33)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.SocketTransition.getInstance(Unknown Source:6)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.bio.t(Unknown Source:85)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.AppRecordManagerService.processStart(Unknown Source:177)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.OpAppRecordInjector.processStart(OpAppRecordInjector.java:267)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.ProcessList.handleProcessStartedLocked(ProcessList.java:2748)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.ProcessList.handleProcessStartedLocked(ProcessList.java:2718)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.ProcessList.handleProcessStart(ProcessList.java:2259)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.ProcessList.lambda$startProcessLocked$0$ProcessList(ProcessList.java:2189)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.am.-$$Lambda$ProcessList$jjoaAPSQT_weAnGqu0R0SCcvKqw.run(Unknown Source:22)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at android.os.Looper.loop(Looper.java:233)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-29 13:53:05.475  2269  2774 E ActivityManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-29 13:53:05.475  2269  2774 I ActivityManager: Force stopping com.google.android.networkstack appid=1073 user=0: start failure
08-29 13:53:05.475  2269  2774 W ActivityManager: Slow operation: 94ms so far, now at startProcess: asking zygote to start proc
```

**Comment by Tornaco** [comment]
[thanox_3.0-alpha05-1-e189cc7-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7111725/thanox_3.0-alpha05-1-e189cc7-prc.3060128.apk.zip)

@SukiEva @StephenSSR @hanxin1997 试试这个呢？

**Comment by hanxin1997** [comment]
> [thanox_3.0-alpha05-1-e189cc7-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7111725/thanox_3.0-alpha05-1-e189cc7-prc.3060128.apk.zip)
> 
> @SukiEva @StephenSSR @hanxin1997 试试这个呢？

我这里显示Copying zip to temp directory Unzip error，用的alpha面具。。

**Comment by SukiEva** [comment]
> [thanox_3.0-alpha05-1-e189cc7-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7111725/thanox_3.0-alpha05-1-e189cc7-prc.3060128.apk.zip)
> 
> @SukiEva @StephenSSR @hanxin1997 试试这个呢？

刷入后正常开机，试了一下通知、情景、乖巧都正常运行❤️

**Comment by hanxin1997** [comment]
> [thanox_3.0-alpha05-1-e189cc7-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7111725/thanox_3.0-alpha05-1-e189cc7-prc.3060128.apk.zip)
> 
> @SukiEva @StephenSSR @hanxin1997 试试这个呢？

我也正常开机和激活了。

**Comment by Tornaco** [comment]
1. 先解压，解压后是个apk
2. apk安装
3. apk改名为zip后masigk刷入

**Comment by Tornaco** [comment]
> > [thanox_3.0-alpha05-1-e189cc7-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7111725/thanox_3.0-alpha05-1-e189cc7-prc.3060128.apk.zip)
> > @SukiEva @StephenSSR @hanxin1997 试试这个呢？
> 
> 我也正常开机和激活了。

OK，建议再等等下个版本，当前版本可能会有其他问题。

**Comment by Tornaco** [comment]
@SukiEva @StephenSSR @hanxin1997 

Test apk arrive:

1. 先解压，解压后是个apk
2. apk安装
3. apk改名为zip后masigk刷入

[thanox_3.0-alpha05-14-1734c40-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148025/thanox_3.0-alpha05-14-1734c40-prc.3060128.apk.zip)

**Comment by hanxin1997** [comment]
> @SukiEva @StephenSSR @hanxin1997
> 
> Test apk arrive:
> 
> 1. 先解压，解压后是个apk
> 2. apk安装
> 3. apk改名为zip后masigk刷入
> 
> [thanox_3.0-alpha05-14-1734c40-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148025/thanox_3.0-alpha05-14-1734c40-prc.3060128.apk.zip)

刷成功了，也开机了，但是显示没有激活，面具里有模块

**Comment by SukiEva** [comment]
> @SukiEva @StephenSSR @hanxin1997
> 
> Test apk arrive:
> 
> 1. 先解压，解压后是个apk
> 2. apk安装
> 3. apk改名为zip后masigk刷入
> 
> [thanox_3.0-alpha05-14-1734c40-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148025/thanox_3.0-alpha05-14-1734c40-prc.3060128.apk.zip)

同样正常开机显示未激活
开机日志如下：
[boot.zip](https://github.com/Tornaco/Thanox/files/7148634/boot.zip)

**Comment by Tornaco** [comment]
[thanox_3.0-alpha05-17-9f69ad5-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148806/thanox_3.0-alpha05-17-9f69ad5-prc.3060128.apk.zip)

@SukiEva @hanxin1997 Thanks，日志很有帮助。

又更新了一个版本，有时间可以再试试，操作步骤不变。

**Comment by SukiEva** [comment]
> [thanox_3.0-alpha05-17-9f69ad5-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148806/thanox_3.0-alpha05-17-9f69ad5-prc.3060128.apk.zip)
> 
> @SukiEva @hanxin1997 Thanks，日志很有帮助。
> 
> 又更新了一个版本，有时间可以再试试，操作步骤不变。

可正常开机并激活

**Comment by hanxin1997** [comment]
> [thanox_3.0-alpha05-17-9f69ad5-prc(3060128).apk.zip](https://github.com/Tornaco/Thanox/files/7148806/thanox_3.0-alpha05-17-9f69ad5-prc.3060128.apk.zip)
> 
> @SukiEva @hanxin1997 Thanks，日志很有帮助。
> 
> 又更新了一个版本，有时间可以再试试，操作步骤不变。

正常开机并激活，暂时没发现没什么问题

**Comment by Tornaco** [comment]
@SukiEva @hanxin1997 Nice~
