### ISSUE TITLE
插件+号点击闪退

### ISSUE THREAD

**Issue by yuehun** [Tornaco/Thanox#31]
清除了软件数据，恢复默认了配置，重启了手机还是闪退
Thanox 1.1.0，Android版本9.0
[2020-01-04.zip](https://github.com/Tornaco/Thanox/files/4021600/2020-01-04.zip)

**Comment by Tornaco** [comment]
@yuehun data/system/thanos下的日志发一下

**Comment by yuehun** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/4021604/logging.zip)

**Comment by yuehun** [comment]
@Tornaco 不是这里的问题，是所有的导入都不能用，我导入软件配置也闪退

**Comment by yuehun** [comment]
![Screenshot_2020-01-04-20-56-26-453_github tornaco android thanos](https://user-images.githubusercontent.com/24507941/71765879-b635b780-2f34-11ea-97ae-9326f2bc01b7.jpg)
酷安最新版这样

**Comment by Tornaco** [comment]
@yuehun 最新版呢

**Comment by Tornaco** [comment]
暂时关闭。如果有问题再打开。
