### ISSUE TITLE
play商店付费版thanox pro 3.0alpha4无法在lsposed管理器中激活

### ISSUE THREAD

**Issue by 7starsseeker** [Tornaco/Thanox#313]
作者您好，我是购买的play商店付费版thanox pro，刚更新到3.0alpha4。手机为一加9p+氧os（11.2.8.8.LE15BA），xp框架用的lsposed（1.5.3（5984））。上个3.0alpha3版可以正常使用，但是更新alpha4版之后无论如何都无法激活，换用magisk方式后会直接卡开机。想回退版本却在play商店找不到该功能，而github和酷安上都是Thanox而不是Thanox pro，应用包名都不一样，装上之后还提示未激活……
lsposed日志导出后为一个zip压缩包，当中的内容我不确定哪个是有用的，所以把整个压缩包全部上传到网盘了，链接如下：
https://dr7s.cowtransfer.com/s/483f2b59d04341
取件码853558

**Comment by StephenSSR** [comment]
同3.0alpha4无法在lsposed管理器中激活，另在氢os11上Magisk激活仍卡开机

**Comment by SmartDevil-02** [comment]
同3.0alpha4不能用lsposed激活，但是03可以激活，没有试magisk

**Comment by Tornaco** [comment]
How about 3.0-alpha05-row? Released a moment ago.

**Comment by SmartDevil-02** [comment]
> How about 3.0-alpha05-row? Released a moment ago.

我去试试

**Comment by SmartDevil-02** [comment]
> ‎3.0-阿尔法05行怎么样？发布前一刻。‎

没找到3.0alpha05，最新只看见04

**Comment by 7starsseeker** [comment]
> How about 3.0-alpha05-row? Released a moment ago.

It works via lsposed manager. Thanks.
在lsp里面能用了，谢谢！
magisk method is not tested.
magisk那边没有试。

**Comment by SmartDevil-02** [comment]
> How about 3.0-alpha05-row? Released a moment ago.

可以激活了

**Comment by Tornaco** [comment]
Nice
