### ISSUE TITLE
昨天发的仍然激活不了

### ISSUE THREAD

**Issue by Sfssup** [Tornaco/Thanox#314]
Android9；MIUI11；Magisk23；Riru2612；LSPosed153...

**Comment by Tornaco** [comment]
@EatmeIon 麻烦发下log

**Comment by Sfssup** [comment]
> @EatmeIon 麻烦发下log

日志文件咋上传

**Comment by EatmeIon** [comment]
> @EatmeIon 麻烦发下log

[]()https://ws28.cn/f/6bj7wgq9cit

**Comment by Tornaco** [comment]
@EatmeIon 收到，已经定位到问题，正在测试。

**Comment by Sfssup** [comment]
> @EatmeIon 收到，已经定位到问题，正在测试。

新的已激活

**Comment by Tornaco** [comment]
Nice
