### ISSUE TITLE
移花接木，自启动规则，乖巧规则导入导出功能无效

### ISSUE THREAD

**Issue by jinbolin227** [Tornaco/Thanox#324]
**Describe the bug（现象描述）**
移花接木，自启动规则，乖巧规则导入导出不可用

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进移花接木，自启动，乖巧规则导出的文件是空白
2. 移花接木，自启动，乖巧规则导入也没有任何反应
3.THANOX备份恢复或权限管理，移花接木，情景模式也会每次开机关闭，情景模式读取不到规则
**Expected behavior**（期望结果）
希望可以修复，不然软件太多，认为刷机后不可用备份的话手动操作起来太耗时间
A clear and concise description of what you expected to happen.（描述一下期望的结果）
2.5.9版本权限管理没问题，3.0开始权限管理的摄像头不起作用

**Screenshots**（截图）
![QQ图片20210923105643](https://user-images.githubusercontent.com/56496767/134449079-67b89c8f-7ed6-4b58-976c-b756f722b703.jpg)

If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: Android 11.0
 - Version [e.g. v2.5.9/v3.0-alpha05

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[thanox-init.log](https://github.com/Tornaco/Thanox/files/7214822/thanox-init.log)
[thanox-core.log](https://github.com/Tornaco/Thanox/files/7214823/thanox-core.log)

**Comment by jinbolin227** [comment]
修改data/system/thanoxs权限也没有效果

**Comment by Tornaco** [comment]
@jinbolin227 2.5版本也有问题吗？

手动删除data/system/thanos重启试过么？

**Comment by jinbolin227** [comment]
> @jinbolin227 2.5版本也有问题吗？
> 
> 手动删除data/system/thanos重启试过么？

是的，删除重试还是老样子，我现在都搞崩溃了，不知道哪里问题，几天9008刷了10多次才确定

**Comment by Tornaco** [comment]
我也有点懵。

**Comment by Tornaco** [comment]
我也有点懵。

**Comment by jinbolin227** [comment]
> 我也有点离。

我现在只有自己一点一点手动添加和设置才会生效（包括重启）备份可以用，但恢复不行（一加氢可以恢复），移花接木，乖巧规则的导入导出用不了，就是导出了也是空文件，自启规则干脆导入导出都没作用，2.5版本权限管理摄像头可以拦截，3.0以后就拦截不住了
