### ISSUE TITLE
任务清理导致浏览器打开失败

### ISSUE THREAD

**Issue by SukiEva** [Tornaco/Thanox#327]
**Describe the bug（现象描述）**
任务清理加入浏览器后，如果有其他应用使用应用内打开将会导致浏览器闪退。推测是chrome tab之类调用后不会出现在最近任务里导致触发任务清理，从任务清理中移除可避免该问题

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 任务清理加入浏览器
2. 在其他应用中打开链接调起浏览器
3. 闪退

**Expected behavior**（期望结果）
浏览器既能调出，又能划卡即停

**Version（发现问题的版本）:**
 - OS:  Android 11 OxygenOS

**Additional context**（其他信息）
这该不会是Feature吧🤡

**Comment by Tornaco** [comment]
```
Thanox-Core: onTaskRemovingInternal: task pkg is: com.android.chrome, multipleTaskKeep? false
```

@SukiEva Chome存在多个任务，remove一个之后，触发了`任务清理`被杀死了。

计划折中处理一下：`任务清理`杀死app之前检测其是否有其他任务存在。

**Comment by Tornaco** [comment]
Fixed & Close
