### ISSUE TITLE
插件无法激活

### ISSUE THREAD

**Issue by dqwfgzs** [Tornaco/Thanox#328]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
安装好微信代收插件、勾选启用并重启后仍然提示需要重启，无法激活
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![Screenshot_20210927-081316](https://user-images.githubusercontent.com/34101212/134829180-adb3dae8-2bbd-46a6-8907-092dd438efbb.png)
![Screenshot_20210927-081312](https://user-images.githubusercontent.com/34101212/134829189-404ab55a-1575-45d7-9747-672a0fac0b45.png)

**Version（发现问题的版本）:**
系统版本：Android 9 47.2.A.11.228 Sony Xperia XZ1
软件版本：Thanox Pro 3.0-alpha06-row

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[logging.zip](https://github.com/Tornaco/Thanox/files/7232513/logging.zip)

**Comment by Tornaco** [comment]
@dqwfgzs 你是magisk還是xposed模式？

**Comment by Tornaco** [comment]
@dqwfgzs 能用日誌工具抓個重新開機過程中的完整adb日誌嗎？thanox日誌記錄器沒記錄到加載的錯誤信息。

**Comment by dqwfgzs** [comment]
> @dqwfgzs 能用日誌工具抓個重新開機過程中的完整adb日誌嗎？thanox日誌記錄器沒記錄到加載的錯誤信息。

我尝试一下，稍后给你详细的日志。这个插件安装之后直接勾选启用病重新启动了设备，但是重启后仍然处于不可用的状态

**Comment by dqwfgzs** [comment]
> @dqwfgzs 能用日誌工具抓個重新開機過程中的完整adb日誌嗎？thanox日誌記錄器沒記錄到加載的錯誤信息。

试着抓了一下开机过程中的日志，您可以看一
[20210930161143log.txt](https://github.com/Tornaco/Thanox/files/7257864/20210930161143log.txt)
下

**Comment by Tornaco** [comment]
[thanox_3.0-alpha06-3-ed99968-dirty-prc(3060130).apk.zip](https://github.com/Tornaco/Thanox/files/7264078/thanox_3.0-alpha06-3-ed99968-dirty-prc.3060130.apk.zip)

@dqwfgzs 上面的日志很有帮助。试试这个版本呢？我加了更多日志，还是需要完整adb日志。

**Comment by dqwfgzs** [comment]
> [thanox_3.0-alpha06-3-ed99968-dirty-prc(3060130).apk.zip](https://github.com/Tornaco/Thanox/files/7264078/thanox_3.0-alpha06-3-ed99968-dirty-prc.3060130.apk.zip)
> 
> @dqwfgzs 上面的日志很有帮助。试试这个版本呢？我加了更多日志，还是需要完整adb日志。
好的，我试一下。play版在其他版本的固件（xda上第三方开发的android 10/11）是可以正常使用该插件的，但在索尼官方的固件上并不是所有的时候都能使用

**Comment by dqwfgzs** [comment]
> [thanox_3.0-alpha06-3-ed99968-dirty-prc(3060130).apk.zip](https://github.com/Tornaco/Thanox/files/7264078/thanox_3.0-alpha06-3-ed99968-dirty-prc.3060130.apk.zip)
> 
> @dqwfgzs 上面的日志很有帮助。试试这个版本呢？我加了更多日志，还是需要完整adb日志。

刚才通过Play商店更新了最新的alpha7版本，可以正常激活该插件，可用性目前仍在观察

**Comment by dqwfgzs** [comment]
暂时关闭该issue，如有问题将以新的issue代之

**Comment by Tornaco** [comment]
@dqwfgzs 能再抓下日志吗？上次看你的日志有些错误。

**Comment by dqwfgzs** [comment]
> @dqwfgzs 能再抓下日志吗？上次看你的日志有些错误。


[20211002 75903log.txt](https://github.com/Tornaco/Thanox/files/7270602/20211002.75903log.txt)
这次使用的版本是新的play商店版本：3.0-alpha07-row

**Comment by dqwfgzs** [comment]
> > [thanox_3.0-alpha06-3-ed99968-dirty-prc(3060130).apk.zip](https://github.com/Tornaco/Thanox/files/7264078/thanox_3.0-alpha06-3-ed99968-dirty-prc.3060130.apk.zip)
> > @dqwfgzs 上面的日志很有帮助。试试这个版本呢？我加了更多日志，还是需要完整adb日志。
> 
> 刚才通过Play商店更新了最新的alpha7版本，可以正常激活该插件，可用性目前仍在观察

现在有个新的问题，重置了app以后又无法激活该插件了，以下是adb l
[20211002 94805log.txt](https://github.com/Tornaco/Thanox/files/7270736/20211002.94805log.txt)
og

**Comment by dqwfgzs** [comment]
目前最新版本可以正常使用，暂时关闭该Issue

**Comment by LiangPro** [comment]
![image](https://user-images.githubusercontent.com/55148219/147870238-1e42d59c-9076-40e1-927b-fafbd08132c9.png)
软件版本：thanox_3.2-prc.3060350.apk
安卓9，三方miui12同样遇到问题
微信代收开关无效

**Comment by Tornaco** [comment]
Fixed，代收已经不再是插件了~
