### ISSUE TITLE
安卓12

### ISSUE THREAD

**Issue by linmumudesti** [Tornaco/Thanox#329]
安卓12什么时候可以用lsp激活啊，面具激活的少了好多功能，不能装插件

**Comment by Tornaco** [comment]
@linmumudesti 试试新版本 alpja06

**Comment by Tornaco** [comment]
https://github.com/Tornaco/Thanox/releases/tag/v3.0-alpha06 @linmumudesti

**Comment by Tornaco** [comment]
暂时关闭，如果测试有问题请重新open该issue。
