### ISSUE TITLE
3.0b1错误显示测试版图标

### ISSUE THREAD

**Issue by marklezhao** [Tornaco/Thanox#341]
**Describe the bug（现象描述）**
A clear and concise description of what the 主界面中测试版图标还在，功能是完整版的功能

**To Reproduce**（如何复现）
点进去就能看到

**Screenshots**（截图）
![98E52024-DA8E-4EC7-B506-E15A89AF4245](https://user-images.githubusercontent.com/60564677/138557335-212134ba-cc05-4c13-8973-8604360d104a.jpeg)

**Version（发现问题的版本）:**
 - OS: Android 11
 - Version: 3.0beta1 (GitHub下载)
 - LSPosed: 1.6.2 ，没用(过)magisk模块

**Additional context**（其他信息）
从2.5覆盖升级过来的，看起来功能没什么问题。

**Comment by Tornaco** [comment]
@marklezhao Beta 版本都会显示这个图标（alpha应该也显示，可能是bug了之前的alpha版本都没显示）。
