### ISSUE TITLE
开启 后台运行-显示通知，设备软重启

### ISSUE THREAD

**Issue by GSWXXN** [Tornaco/Thanox#345]
复现步骤
1. 清理某应用后台
2. 对该应用取消勾选后台运行，开启显示通知
3. 桌面点击应用图标启动
4. 系统界面短暂卡死后软重启

关闭显示通知后，应用运行正常

Thanox版本: 3.0 beta2

系统版本
小米11 Ultra 开发版 21.10.25
MIUI 12.5
Android 12

**Comment by GSWXXN** [comment]
日志文件对 115(com.ylmf.androidclient) 执行上述步骤
[log.zip](https://github.com/Tornaco/Thanox/files/7425437/log.zip)

**Comment by Tornaco** [comment]
@GSWXXN  Will fix it.

**Comment by Tornaco** [comment]
https://github.com/Tornaco/Thanox/releases/tag/v3.0-beta3 @GSWXXN

**Comment by GSWXXN** [comment]
> https://github.com/Tornaco/Thanox/releases/tag/v3.0-beta3 @GSWXXN 

新版本不会再软重启，但是点击通知详情没有反应![IMG_20211029_233324.jpg](https://user-images.githubusercontent.com/34705923/139462601-042df00d-df6f-4a08-bad6-6cc42017d29f.jpg)

**Comment by Tornaco** [comment]
[thanox_3.0-beta3-22-2d26360-prc(3060137).apk.zip](https://github.com/Tornaco/Thanox/files/7467554/thanox_3.0-beta3-22-2d26360-prc.3060137.apk.zip)

@GSWXXN  再试试这个，修了一下点击跳转。

**Comment by GSWXXN** [comment]
> [thanox_3.0-beta3-22-2d26360-prc(3060137).apk.zip](https://github.com/Tornaco/Thanox/files/7467554/thanox_3.0-beta3-22-2d26360-prc.3060137.apk.zip)
> 
> @GSWXXN  再试试这个，修了一下点击跳转。

没有问题啦，可以正常跳转
