### ISSUE TITLE
希望程序列表可以在APP名称后面标上APP包名。

### ISSUE THREAD

**Issue by Gokou-Ruri** [Tornaco/Thanox#348]
例如女娲石的微信增强包名称也是“微信”，图标也一样，经常会把这俩选错。
或者有些APP的“共存版”名称也和原版相同。
希望可以同时显示包名来精确定位APP。

**Comment by Tornaco** [comment]
@Gokou-Ruri 3.0-rc2已经支持，如有问题再讨论。
