### ISSUE TITLE
像綠色守護的GCM推送喚醒

### ISSUE THREAD

**Issue by noone315** [Tornaco/Thanox#35]
1.希望可以增加像綠色守護(xposed模式)的收到GCM推送就喚醒相關應用，應用場景如line或tg有人電話過來，如果用GCM代收無法在螢幕上跳出接聽電話的介面
2.希望可以增加像應用管理一樣的三指下滑截圖
希望這些功能可以做成插件

**Comment by Tornaco** [comment]
@noone315 1. 情景模式后面会有PUSH API 可以支持。 2. 这些功能会做到插件里。

**Comment by noone315** [comment]
> 
> 
> @noone315 1. 情景模式后面会有PUSH API 可以支持。 2. 这些功能会做到插件里。

情境模式的push api與變量一起使用時無效...

**Comment by Tornaco** [comment]
> > @noone315 1. 情景模式后面会有PUSH API 可以支持。 2. 这些功能会做到插件里。
> 
> 情境模式的push api與變量一起使用時無效...

什么变量？

**Comment by noone315** [comment]
> > > @noone315 1. 情景模式后面会有PUSH API 可以支持。 2. 这些功能会做到插件里。
> > 
> > 
> > 情境模式的push api與變量一起使用時無效...
> 
> 什么变量？

全局變量

**Comment by Tornaco** [comment]
@noone315 具体什么情况？详细些？

**Comment by noone315** [comment]
> @noone315 具体什么情况？详细些？

像下面的代碼完全沒效果
[
  {
    "name": "GCM Push",
    "description": "感知GCM FCM推送",
    "priority": 2,
    "condition": "fcmPushMessageArrived == true && globalVarOf$GCMapps.contains(to)",
    "actions": [
      "activity.launchProcessForPackage(to);"
    ]
  }
]

**Comment by Tornaco** [comment]
@noone315 [ 
  { 
    "name": "GCM Push", 
    "description": "感知GCM FCM推送", 
    "priority": 2, 
    "condition": "fcmPushMessageArrived == true && globalVarOf$GCMapps.contains(pkgName)", 
    "actions": [ 
      "activity.launchProcessForPackage(pkgName);" 
    ] 
  } 
]

**Comment by Tornaco** [comment]
@noone315 写错了肯定没效果。注意包名参数在文档里写的是pkgName
