### ISSUE TITLE
刷机再恢复数据后，thanox的功能少了很多

### ISSUE THREAD

**Issue by nonlog** [Tornaco/Thanox#350]
**Describe the bug（现象描述）**
    使用的是最新测试版thanox，刷机再恢复数据功能少了几个，已激活lsposed和magisk模块
**To Reproduce**（如何复现）
    如上
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
    恢复所有功能

**Screenshots**（截图）
    
![Screenshot_20211031-081620979](https://user-images.githubusercontent.com/61723005/139562042-23e0a8d4-08e7-4144-81a4-8aa46c7536b2.jpg)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）crdroid，Android11
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）v3.00-beta3

**Additional context**（其他信息）
    卸载再下载2.5.4有同样的问题

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

**Comment by Tornaco** [comment]
1. Magisk方式激活的本来就这些功能。
2. Xposed和Magisk模块两种激活方式二选一，不要同时。

建议看下wiki：https://tornaco.github.io/Thanox/2-Install-Activate/

如果还有问题在open这个问题吧
