### ISSUE TITLE
点击最近任务，再点返回键，弹出重选桌面

### ISSUE THREAD

**Issue by littlepony0** [Tornaco/Thanox#353]
复现步骤

nova设为默认桌面，系统自带桌面shady launcher(launcher3)为最近任务提供器。
1.点击最近任务键
2.点击返回键或者全部清除最近任务卡片
3.弹出“将nova设为主屏幕应用

Thanox版本: 3.0+(Thanox 2 无此问题)
系统版本
havoc 3.12
Android 10
包名
com.teslacoilsw.launcher
com.android.launcher3

**Comment by Tornaco** [comment]
@littlepony0 提供下日志吧，另外把你的配置导出个备份发出来看下。

**Comment by littlepony0** [comment]
@Tornaco 没有日志，logging文件夹是空的，另把所有功能都关闭依旧有此问题。
[Thanox-Backup-2021-11-03-19_59_46.zip](https://github.com/Tornaco/Thanox/files/7467434/Thanox-Backup-2021-11-03-19_59_46.zip)

**Comment by Tornaco** [comment]
```
 1 [
   2   {
   3     "name": "Kill app on background",
   4     "description": "应用回到后台杀死他（仅做示例，请自行优化）",
   5     "priority": 1,
   6     "condition": "frontPkgChanged == true && !from.contains(\"launcher\") && (from != \"com.tencent.mm\")",
   7     "actions": [
   8       "ui.showShortToast(\"杀死他...\");",
   9       "killer.killPackage(from);"
  10     ]
  11   }
  12 ]
```

把这个情景模式关掉试试呢？

**Comment by Tornaco** [comment]
@littlepony0

**Comment by littlepony0** [comment]
@Tornaco 我把这个情景模式删了还是这样，而且我也没启用情景模式。

**Comment by littlepony0** [comment]
@Tornaco 刚才弄错了，重启后thanox未激活(我忘记在lsp重新启用thanox了)。再次重启后还是要重选桌面。

**Comment by Tornaco** [comment]
@littlepony0 现在有日志了吗？

**Comment by Tornaco** [comment]
@littlepony0 已经定位到原因，稍后会发布测试版本。

**Comment by Tornaco** [comment]
@littlepony0  帮忙验证下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/123/workflows/4e413ad6-a694-434b-8a2c-8eeb5b1aa1cb/jobs/119/artifacts

**Comment by Tornaco** [comment]
Fixed since v3.2 https://github.com/Tornaco/Thanox/releases/tag/v3.2
