### ISSUE TITLE
最新 v3.0 rc1-4 play版 magisk方式无法激活,

### ISSUE THREAD

**Issue by kiddin9** [Tornaco/Thanox#355]
magisk中已安装Thanox-Core, Riru显示有成功载入thanox模块, 但是重启多次Thanox中依然显示未激活.

系统版本
OneUI 3.1
Android 11

**Comment by PuerNya** [comment]
@kiddin9 请提供 log

**Comment by andystarmk** [comment]
s10也是这个现象。
![68f8e118a65bb117d0542ee9114047c](https://user-images.githubusercontent.com/94593605/142361541-ef1eef71-775f-452f-bac2-398a12fb6591.jpg)
![f4fd3d0d4e458d81e9170b538de6228](https://user-images.githubusercontent.com/94593605/142361546-28b498ba-85e1-46bc-ade4-a86835f5400f.jpg)
![6b6efa3ba502b1881e256f1d4faf7b4](https://user-images.githubusercontent.com/94593605/142361551-80a090ab-f6d4-49f6-a29c-040df3f1d6b2.jpg)

**Comment by Tornaco** [comment]
请各位大哥提供日志后在开启本issue。
