### ISSUE TITLE
乖巧模式打开后，辅助功能全部失效

### ISSUE THREAD

**Issue by suroot66** [Tornaco/Thanox#357]
1. 问题描述：
    在打开乖巧模式后，像fv悬浮球、全局复制等需要辅助功能的app，就获取不到辅助功能权限了。我在无障碍设置中打开了对应辅助功能开关，但是app却依然判定我没有开启辅助功能。而一旦关闭乖巧模式，这些app立刻就恢复正常了。
2. 初步发现
    1. 是由于“阻止后台服务重启”开关造成的问题，关闭这个开关后，再使用“休眠应用”的乖巧模式就不会造成辅助功能失灵了
    2. 问题发生时，并不是100%的所有辅助功能都失灵了，所有手动在设置中开启的辅助功能都没有效果，但那些通过root获取辅助功能权限的app却能够成功获取。例如auto.js、femind等app支持通过root权限一键开启辅助功能，这个方式是成功的。
 3. 版本
     - 安卓10
     - thanox 3.0-alpha-6-db4e3f1-prc
     - Lsposed 1.6.3, Riru 25.4.4
     - Mokee系统

**Comment by Tornaco** [comment]
不要对辅助功能app开启乖巧模式呢? app提供的辅助功能是会启用一个专用服务的。

**Comment by suroot66** [comment]
嗯嗯，确实，单独关闭对fv悬浮球的乖巧模式就正常了
那就没问题了
