### ISSUE TITLE
手动更换应用配置模板ui无变化

### ISSUE THREAD

**Issue by HHH3366** [Tornaco/Thanox#359]
exThmUI 安卓11 版本3.0 alpha3，后来直升rc1。都有这个问题（已恢复过默认配置）

**Comment by HHH3366** [comment]
刚发现，应用模板菜单的已选项ui是跟着自动配置模板的首选走的，不过选其他模板还是不会变

**Comment by Tornaco** [comment]
@HHH3366 能截图描述一下吗？没理解到你的意思。

**Comment by HHH3366** [comment]
![GIF-211118_193803](https://user-images.githubusercontent.com/51955828/142409796-69a13078-a9d5-4716-9cbe-1416f6bbdb98.gif)

**Comment by Tornaco** [comment]
@HHH3366 你是说右上角弹出来的选择模块的对话框UI，没有选中当前模板吗？

**Comment by HHH3366** [comment]
大概是这个意思

**Comment by Tornaco** [comment]
@HHH3366 哦 这个Dialog本意是就是不会做模板匹配的，后面会调整Dialog样式。

**Comment by Tornaco** [comment]
@HHH3366 rc2 UI 已经调整。暂时关闭。
