### ISSUE TITLE
[功能建议]情景模式"findAndClickViewByText"功能增加根据ViewID点击

### ISSUE THREAD

**Issue by GitHubd3b7c** [Tornaco/Thanox#36]
根据文字自己使用有时并不准确,且一些需要点击的地方并不包含文字,不知道作者对于这个功能有没有开发计划,还是说有这个功能但是我看文档的时候忽略了

**Comment by Tornaco** [comment]
@shawnleetttt 之前确实没有。需要的话就加上。一直没人提哈哈

**Comment by Tornaco** [comment]
请测试最新1.1.1版本，https://tornaco.github.io/Thanox/2019-12-02-Profile/#055-ui

**Comment by Tornaco** [comment]
暂时关闭，有问题再讨论。
