### ISSUE TITLE
安卓12thanox微信代收插件不能正常使用

### ISSUE THREAD

**Issue by LQOS8720** [Tornaco/Thanox#360]
设备信息： 红米K40 MIUI12.5 21.11.17 安卓版本12
thanox pro信息：3.0-rc1-4-60c4d86-row  谷歌商店下载安装
具体表现：消息代收插件已安装并重启 点击模拟消息无反应，实际测试微信无后台也不推送消息。

**Comment by Tornaco** [comment]
@LQOS8720 日志发下

**Comment by LQOS8720** [comment]
lsp框架日志我放到蓝奏云网盘了
下面是日志的下载链接。
https://krypt.lanzoui.com/i7pFPwoxwvc

**Comment by LQOS8720** [comment]
[LSPosed_2021-11-24T15_46_58.139.zip](https://github.com/Tornaco/Thanox/files/7593665/LSPosed_2021-11-24T15_46_58.139.zip)

**Comment by LQOS8720** [comment]
> @LQOS8720 日志发下
[LSPosed_2021-11-24T15_46_58.139.zip](https://github.com/Tornaco/Thanox/files/7593685/LSPosed_2021-11-24T15_46_58.139.zip)

**Comment by LQOS8720** [comment]
手机恢复出厂设置后，消息代收插件正常使用。
