### ISSUE TITLE
搜索应用速度很慢，搜索完也会卡在加载

### ISSUE THREAD

**Issue by hanxin1997** [Tornaco/Thanox#363]
搜索应用速度很慢，搜索完也会卡在加载

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入任何需要搜索应用的功能项）
2. 搜索任意应用
3. 就会发现搜索很慢有时候搜索不出来一直转圈圈，搜索完也会一直转圈圈，好像一些字母不会比如j，而且转圈圈只能返回。

**Expected behavior**（期望结果）
解决
**Screenshots**（截图）
![QQ图片20211126185401](https://user-images.githubusercontent.com/58620096/143570241-6b15105f-61c0-4035-b48e-90023d77df67.jpg)

**Version（发现问题的版本）:**
 - OS: 安卓11  miui 12.5.6 
 - Version 3.0-rc2-prc

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

**Comment by Tornaco** [comment]
@hanxin1997 试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/82/workflows/3783da52-7361-44c7-ac36-f2d810c229fa/jobs/78/artifacts

**Comment by hanxin1997** [comment]
> @hanxin1997 试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/82/workflows/3783da52-7361-44c7-ac36-f2d810c229fa/jobs/78/artifacts

这个没问题了

**Comment by Tornaco** [comment]
Close since it has been fixed.
