### ISSUE TITLE
情景模式导入示例以后，就算删掉了，重启后又出现。

### ISSUE THREAD

**Issue by MMCYY** [Tornaco/Thanox#370]
我用的最新版，xp方式激活，系统是
miui12.5.20，安卓11。
情景模式里，刚开始没有选择导入示例，一切正常。有一次点了一下导入示例以后，用完把所有导入的事例都删了，重启手机又有了，再删掉，重启手机又有了。这应该是Bug吧。

**Comment by Tornaco** [comment]
@MMCYY 日志发一下。暂时关闭这个issue，等你补充了日志再打开~
