### ISSUE TITLE
情景模式 wifiState.ssid 做为条件不生效

### ISSUE THREAD

**Issue by xiaostrong** [Tornaco/Thanox#372]
**Describe the bug（现象描述）**

配置文件示例

```
[
  {
    "name": "Wifi state",
    "description": "Wifi State Example",
    "priority": 1,
    "condition": "wifiStateChanged == true && wifiState.ssid == \"CERNET\"",
    "actions": [
      "ui.showLongToast(\"WIFI CHANGED...\" + wifiState.ssid);"
    ]
  }
]
```

**To Reproduce**（如何复现）
将上述配置导入情景模式，并开启。
开关WIFI，连接上名为CERNET的WIFI。

**Expected behavior**（期望结果）
执行动作，toast 显示当前WIFI状态与SSID

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: [e.g. Android 11]
 - Version [e.g. v2.5-2]
 - Version [e.g. v3.0-release-rpc]

**Additional context**（其他信息）
LSPosed

** Logs**（日志文件）
[logcat.log](https://github.com/Tornaco/Thanox/files/7783854/logcat.log)

**Comment by Tornaco** [comment]
[thanox_3.2-28-a2db6b0-dirty-prc(3060350).apk.zip](https://github.com/Tornaco/Thanox/files/7876277/thanox_3.2-28-a2db6b0-dirty-prc.3060350.apk.zip)

@xiaostrong 麻烦测试下这个开发版本，并抓取/data/system/thanos_xxx下的日志打包发出来。

**Comment by xiaostrong** [comment]
测试 WIFI SSID 为 CU_dds4， 对应配置文件也已修改。
[logging.zip](https://github.com/Tornaco/Thanox/files/7879164/logging.zip)

**Comment by Tornaco** [comment]
@xiaostrong 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/149/workflows/bb75216f-e756-4f69-b1a3-48157b57f855/jobs/145/artifacts

如果还不行就继续发下日志。

**Comment by xiaostrong** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/7888593/logging.zip)

**Comment by Tornaco** [comment]
> [logging.zip](https://github.com/Tornaco/Thanox/files/7888593/logging.zip)

你确定这个日志是装了 https://app.circleci.com/pipelines/github/Tornaco/Thanox/149/workflows/bb75216f-e756-4f69-b1a3-48157b57f855/jobs/145/artifacts 这个版本了？麻烦确认下。

**Comment by xiaostrong** [comment]
应该就是这个版本的，我是直接覆盖安装的，会有影响么。

我又打包了一份日志，你看下这个正确不。


[logging2022-01-19.zip](https://github.com/Tornaco/Thanox/files/7890590/logging2022-01-19.zip)

![Screenshot_20220119-001014569](https://user-images.githubusercontent.com/12859414/149975069-072851d2-356e-410f-86c9-af94768e145d.jpg)

**Comment by Tornaco** [comment]
[thanox_3.2-39-e93fc5a-prc(3060350).apk.zip](https://github.com/Tornaco/Thanox/files/7901858/thanox_3.2-39-e93fc5a-prc.3060350.apk.zip)

那个日志我也不理解。我手动打了包，用这个再试试，试玩日志发我下。**这次我们手动清空一下日志文件：装完重启手机之前手动把data/system/thanos_xxx/logging这个文件夹删除。**

@xiaostrong

**Comment by xiaostrong** [comment]
adb 安装。然后重启。开关情景模式，模板启动thanox情景模式有效。

开关WiFi，测试配置不生效。

[logging2022-01-20.zip](https://github.com/Tornaco/Thanox/files/7901982/logging2022-01-20.zip)

![892725ee4095f66ec7a918b6ab30a98](https://user-images.githubusercontent.com/12859414/150265547-bc61c054-92f3-457f-bd32-fa5315310e6e.jpg)

**Comment by Tornaco** [comment]
> 开关情景模式，模板启动thanox情景模式有效。
这句话是啥意思。。

@xiaostrong 看日志，wifi变化的事件已经发出：
```
 WifiStatusTracker, callback.run, ws: WifiState(enabled=true, statusLabel=No network, ssid="CU_dds4")
2022-01-20 11:07:46.698 V/Thanox-Core: WifiStatusTracker Wifi update: WifiState(enabled=true, statusLabel=No network, ssid="CU_dds4")
```

现在的问题是啥来着？你的情景模式脚本匹配的是CU_dds4这个ssid吗？

**Comment by xiaostrong** [comment]
意思是导入的默认情景模式有效，例如杀死thanox后重新启动。这个导入的示例配置生效。

需求是匹配到指定 ssid，执行指定动作。

启用配置文件，匹配到 CU_dds4，没有执行 Toast 。

```
[
  {
    "name": "Wifi state",
    "description": "Wifi State Example",
    "priority": 1,
    "condition": "wifiStateChanged == true && wifiState.ssid == \"CU_dds4\"",
    "actions": [
      "ui.showLongToast(\"WIFI CHANGED...\" + wifiState.ssid);"
    ]
  }
]
```

**Comment by Tornaco** [comment]
@xiaostrong https://app.circleci.com/pipelines/github/Tornaco/Thanox/154/workflows/75e90777-80e1-458a-89a0-e89129aacd2b/jobs/150/artifacts

测试下这个，应该好了。

**Comment by xiaostrong** [comment]
@Tornaco 现在正常了
