### ISSUE TITLE
自动重置默认桌面

### ISSUE THREAD

**Issue by 006hjy** [Tornaco/Thanox#373]
版本 3.1.1-row
谷歌商店购买，已激活。
lsposed框架激活thanox，仅勾选系统框架
红米k20p尊享版
系统版本号：QQ3A.200805.001
PixelExperience_Plus_raphael-10.0-20201226-0051-OFFICIAL

一个问题：
我是PixelExperience安卓10

安卓10不能用magisk激活，我用xposed激活以后，未做任何设置。

我是底部三键导航栏，点击多任务键进入多任务界面后，想要返回桌面，默认桌面被重置，弹出选择默认桌面的提示。

每次进入多任务界面都会重置默认桌面。而直接点home键返回桌面就不会。
bug复现视频：
https://wwe.lanzoup.com/iB34Wy5pnna

**Comment by 006hjy** [comment]
不仅仅会重置默认桌面，还会重置默认安装器

**Comment by YouandYu** [comment]
总要选择安装器，我还以为手机系统的问题。现在知道是灭霸的问题了！

**Comment by Tornaco** [comment]
@YouandYu 已经定位到原因，稍后会发布测试版本。

**Comment by Tornaco** [comment]
@006hjy  @YouandYu  帮忙验证下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/123/workflows/4e413ad6-a694-434b-8a2c-8eeb5b1aa1cb/jobs/119/artifacts

**Comment by 006hjy** [comment]
> @YouandYu 已经定位到原因，稍后会发布测试版本。

刚刚的测试版中这个问题被解决了。请尽快更新到谷歌商店。

**Comment by Tornaco** [comment]
Fixed since v3.2 https://github.com/Tornaco/Thanox/releases/tag/v3.2
