### ISSUE TITLE
返回主桌面一直重复提示把xxx设为主屏幕应用

### ISSUE THREAD

**Issue by yusichun** [Tornaco/Thanox#375]
**Describe the bug（现象描述）**
任意界面返回主桌面，一直重复提示把xxx设为主屏幕应用，老版本没有这个问题，选择始终设置还是会弹出

**To Reproduce**（如何复现）
以上
Steps to reproduce the behavior:（复现步骤）
以上

**Expected behavior**（期望结果）
立即修复
 expected to happen.（描述一下期望的结果）
不提示

**Screenshots**（截图）
![Screenshot_20220103-224925](https://user-images.githubusercontent.com/79388494/147944527-fb395957-94d7-4fce-b28d-95c0631c412c.jpg)

**Version（发现问题的版本）:**
 - OS: 系统版本安卓10 Hydrogen OS 10.5.13.IN11
 - Version [e.g. 3060246]（软件版本，3.1-prc，3060246

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）

**Comment by yusichun** [comment]
![Screenshot_20220103-224931](https://user-images.githubusercontent.com/79388494/147945024-e3e57cfe-7e77-480f-bd45-90f7fc64f025.jpg)

**Comment by yusichun** [comment]
日志
[thanox-core.log](https://github.com/Tornaco/Thanox/files/7802542/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/7802543/thanox-init.log)

**Comment by YouandYu** [comment]
3.2不是修复了吗？怎么还发这问题。

**Comment by Tornaco** [comment]
@yusichun 请在3.2版本上测试。如果还是有问题在打开该issue。

**Comment by yusichun** [comment]
因为你酷安没更新，所以我安装了以后还有问题才发的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月04日 02:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Tornaco/Thanox] 返回主桌面一直重复提示把xxx设为主屏幕应用 (Issue #375) |

3.2不是修复了吗？怎么还发这问题。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HeiZiSama** [comment]
@yusichun 酷安不更新的
