### ISSUE TITLE
【问题反馈】只要激活了Thanox，不做其他任何的配置和设置，从相机的左下角预览框打开照片进入相册会卡住

### ISSUE THREAD

**Issue by Cuddly-Red-Fox** [Tornaco/Thanox#378]
问题描述

只要激活了Thanox，不做其他任何的配置和设置，从相机的左下角预览框打开照片进入相册会卡住，约卡住15-30秒才进入相册打开照片，（如不激活Thanox则不存在该问题，预览框打开相册可以秒开）

问题复现步骤
1，通过LSP勾选系统框架，激活Thanox，然后重启，使软件激活（软件未进行任何设置，均为默认初始化状态）。
2，随后打开相机，通过相机页面左下角预览框点击，进入相册查看已经拍摄的照片（或刚刚拍摄的照片）。
整个相机会卡住，画面和整个系统停顿一动不动约15秒到30秒才会打开相册进入对应照片。
（如果在相机中拍完照片，然后回到桌面单独打开相册APP则不受影响，仅通过相机的预览框进入相册照片时存在该问题。）

期望结果
希望修复此问题或错误。

以下是截图与录屏存档（该问题截图无法体现，录屏及截图文件见附件或注明链接）

系统版本Android11（Evolution X）（设备代号davinci）
发现问题的软件版本（Thanox 3.2-prc）(github.tornaco.android.thanos)
截图👇
![QQ图片20220111122454](https://user-images.githubusercontent.com/42781095/148880935-c4112ec7-9c8b-42ed-ab8c-98982fe6de88.jpg)

![QQ图片20220111122401](https://user-images.githubusercontent.com/42781095/148880970-e7d0fe15-edc2-4879-9c65-2228d7c11eab.jpg)

（阿里云盘截图与录屏文件存档链接）👇
https://www.aliyundrive.com/s/bvLmgu3F6cs

👇包含在LSP中在仅激活Thanox，其余LSP模块全部不激活，的情况下LSP记录的模块日志与详细日志文件。

[LSPosed_2022-01-11T13_20_10.191.zip](https://github.com/Tornaco/Thanox/files/7843930/LSPosed_2022-01-11T13_20_10.191.zip)

[LSPosed_2022-01-11T13_20_38.022.zip](https://github.com/Tornaco/Thanox/files/7843931/LSPosed_2022-01-11T13_20_38.022.zip)

**Comment by Cuddly-Red-Fox** [comment]
经过测试，最高版本3.0-beta1-prc 版本不存在该问题，该版本以及之前的版本，不存在该问题，高于该版本以上的全部版本均存在该问题。

**Comment by Tornaco** [comment]
@asuszwbUbuntu OK 我看下

**Comment by Tornaco** [comment]
@asuszwbUbuntu 我在evo android11上测试未复现该问题。 麻烦再提供下/data/system/thanos_xxx下的日志。
同时最好做如下测试：
1. 卡住的同时，不停地点击屏幕
2. 10秒左右，系统可能会提示程序无响应
3. 把/data/anr下的日志也发出来

----------------

**Comment by Gokou-Ruri** [comment]
有同样的问题，但奇怪的是只有MIUI相机才会这样，其它第三方相机（包括谷歌相机）不会出现这个情况。

**Comment by Tornaco** [comment]
@Gokou-Ruri  https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157 这个呢，这个是最新的，可能对你的问题有修复。

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157 这个呢，这个是最新的，可能对你的问题有修复。

刚才我把Play版冻结并在LSP里禁用了Play版，安装了这个CI版并在LSP中启用，重启系统后MIUI相机能正常迅速调用图库预览照片了。
卸载CI版本，解冻Play版并在LSP中启用，重启系统后相机问题复现。
感谢开发者！希望此版本能尽快发布到Google Play。🙏

**Comment by Cuddly-Red-Fox** [comment]
在Thanox APP更新至最新的3.7.1-prc，之后，该问题已不存在，似乎是已经修复了，非常感谢







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tornaco/Thanox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 上午8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tornaco/Thanox] 【问题反馈】只要激活了Thanox，不做其他任何的配置和设置，从相机的左下角预览框打开照片进入相册会卡住 (Issue #378)





 
@asuszwbUbuntu 我在evo android11上测试未复现该问题。 麻烦再提供下/data/system/thanos_xxx下的日志。
 同时最好做如下测试：
  
卡住的同时，不停地点击屏幕
 
10秒左右，系统可能会提示程序无响应
 
把/data/anr下的日志也发出来
  
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
