### ISSUE TITLE
任务清理/划卡 XP模式下”失效“

### ISSUE THREAD

**Issue by Oosl** [Tornaco/Thanox#382]
**Describe the bug（现象描述）**
工作模式为Xposed激活，打开任务清理后，划后台卡片无法清理部分应用。比较直观的现象为有通知的应用（如支付宝）划卡后，通知仍在，而用xposed egde杀死当前应用的方式，通知也会被一起杀掉。

**To Reproduce**（如何复现）
1、打开支付宝任务清理
2、让支付宝在后台，让联系人发一个消息，通知栏弹出通知。
3、多任务划卡关掉支付宝，通知栏仍有支付宝的通知。

**Expected behavior**（期望结果）
第3步划掉支付宝时，支付宝的通知也会清除。

**Screenshots**（截图）
![enable_kill](https://user-images.githubusercontent.com/27420243/149607771-c6ef29bd-42ec-4e0f-ab33-570433a3e3ca.jpg)
打开支付宝任务清理，并已划掉支付宝后台
![alipay_alive](https://user-images.githubusercontent.com/27420243/149607868-8964dd75-7fde-4ceb-b53b-731fa5a07b8f.jpg)
支付宝通知仍在

**Version（发现问题的版本）:**
 - OS:  Android 12（ColorOS 12，已冻结Athena）
 - Version: v3.2

**Additional context**（其他信息）
1、标题中的“失效”之所以加上引号的原因在于，我不确定这是否是预期行为。因为我用Scene查看后台进程，在划掉卡片的时候，对应的后台进程确实是被杀掉了没错。
2、对于1中所说的后台进程被杀掉，我也同样不确定这是安卓自身的行为还是Thanox的行为。（即是Thanox未生效还是Thanox生效了，只是行为就是如此）

** Logs**（日志文件）
[logging.zip](https://github.com/Tornaco/Thanox/files/7874194/logging.zip)

**Comment by Tornaco** [comment]
@Oosl  从你的日志看，是thanox兼容问题，导致thanox未检测到任务被移除的事件，因此支付宝并未被清理。

麻烦上传下你的rom里的一个文件：/system/framework/services.jar 我看下能否修复。

**Comment by Oosl** [comment]
[services.zip](https://github.com/Tornaco/Thanox/files/7874233/services.zip)

ok，还有一个开机初始化的时候有一个Adding TV input services的错误，需要再开一个issue么

**Comment by Tornaco** [comment]
@Oosl 那个不是错误，正常开发打印的trace日志。

**Comment by Oosl** [comment]
好吧，我看是抛出异常打印，以为是异常行为。（略微强迫症😂正常启动日志里有个“异常”打印

**Comment by Tornaco** [comment]
@Oosl https://app.circleci.com/pipelines/github/Tornaco/Thanox/145/workflows/ba0b26ac-93ff-4548-ba7e-5f3957d364ca/jobs/141/artifacts

试试这个版本，我加了日志，试完了日志再发下。

**Comment by Oosl** [comment]
测试了，还是没生效，这是日志
[logging.zip](https://github.com/Tornaco/Thanox/files/7874330/logging.zip)

**Comment by Tornaco** [comment]
@Oosl 要不手动吧日志删了，xposed里重新勾选一下重启，再试试，并抓日志。

你发的日志看起来不是最新测试版thanox。确保安装上面链接中的版本。

**Comment by Oosl** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/7874480/logging.zip)
删除日志重新勾选重启后的日志，不过上面最新的安装后我play买的无法激活专业版，是试用版，不知是否会有影响

**Comment by Oosl** [comment]
> @Oosl 从你的日志看，是thanox兼容问题，导致thanox未检测到任务被移除的事件，因此支付宝并未被清理。
> 
> 麻烦上传下你的rom里的一个文件：/system/framework/services.jar 我看下能否修复。

再反馈一个情况，当使用 Xposed edge pro 的“结束前台”快捷方式（ 不会移除多任务） + Thanox 情景模式中的 Task removal时，Thanox是能够正确感知到应用被杀死，然后移除多任务的。说明Thanox其实是能收到应用被杀死的事件？

**Comment by Tornaco** [comment]
> [logging.zip](https://github.com/Tornaco/Thanox/files/7874480/logging.zip) 删除日志重新勾选重启后的日志，不过上面最新的安装后我play买的无法激活专业版，是试用版，不知是否会有影响

日志还是不对啊。。你同时还装了play版本？

**Comment by Oosl** [comment]
完整是这样的。
1. 之前一直安装使用的play版本，并用此版本给你反馈了最初的日志。
2. 你发了刚编译的新版后，我下载安装，包名不同所以我发现手机上有两个Thanox。
3. 于是我到Lsposed里取消了play的thanox（但是没有卸载play版本）并勾选启用了你发的测试版本。
4. 重启后给你反馈了第二份日志。
5. 你说日志不对，我删除日志，重新勾选测试版，重启后给你反馈了第三份日志。

**Comment by Tornaco** [comment]
[thanox_3.2-26-f9af629-prc(3060350).apk.zip](https://github.com/Tornaco/Thanox/files/7875002/thanox_3.2-26-f9af629-prc.3060350.apk.zip)

@Oosl 

好吧，情况有点复杂，你就用我给你发的这个吧，pro版本一定要取消激活。

**Comment by Oosl** [comment]
ok，是取消激活的没错，只是没卸载。我再测测这个

**Comment by Oosl** [comment]
> [thanox_3.2-26-f9af629-prc(3060350).apk.zip](https://github.com/Tornaco/Thanox/files/7875002/thanox_3.2-26-f9af629-prc.3060350.apk.zip)
> 
> @Oosl
> 
> 好吧，情况有点复杂，你就用我给你发的这个吧，pro版本一定要取消激活。  

[logging.zip](https://github.com/Tornaco/Thanox/files/7875054/logging.zip)

**Comment by Tornaco** [comment]
@Oosl 已定位到原因，测试下：https://app.circleci.com/pipelines/github/Tornaco/Thanox/146/workflows/428c6691-64e3-435a-879e-0d42829df8f6/jobs/142/artifacts

**Comment by Oosl** [comment]
@Tornaco 最新版测试Ok了，划卡工作正常了。划掉应用对应的通知也没了

**Comment by Tornaco** [comment]
OK, Thanks

**Comment by Oosl** [comment]
好像现在划卡清理又有异常，偶尔能正常工作，偶尔又不行。
我测试发现好像是手动从桌面打开app，就能划卡清理。但是好像用xposed edge那些启动app的划卡就无法清理。（只是根据情况猜测
这是[logging打包](https://wwe.lanzouo.com/ibrcXzc3cwj)。
（抱歉，手机无法上传附件
