### ISSUE TITLE
[建议]在解冻App时同时解冻指定的App

### ISSUE THREAD

**Issue by Star-ZER0** [Tornaco/Thanox#385]
例：解冻Muse Dash时同时解冻Taptap（为了正版验证）
解冻Arcaea时同时解冻Google Play 游戏（游戏进度同步）
解冻Google Camera时解冻Google 框架和Google Play 服务（支持库）
万分感谢！已入正支持！
愿项目越来越好

**Comment by Gokou-Ruri** [comment]
建议学习情景模式用法，你可以自由发挥。
提供思路：例如你可以让Thanox检测到A程序处于前台时，解冻B程序。
还有Tasker、XposedEdgePro等软件也能做到类似效果，思路都差不多，如果不想编写情景模式的话也可以尝试这些软件的图形化操作方案。

**Comment by Tornaco** [comment]
确实可以考虑基于情景模式拓展，可以参考情景的 `pkg`包管理相关 API：https://tornaco.github.io/Thanox/6-Profile/#0512-pkg
