### ISSUE TITLE
智能冻结后，启动App闪退、无反应

### ISSUE THREAD

**Issue by i-CraftY** [Tornaco/Thanox#386]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
冻结后，创建快捷方式后，点击桌面图标，打不开app只会一闪而过或者没反应，多次点击后可能仍无效，甚至直接进入Thanox
以挂起方式冻结，需要点击两次，第一次点击会弹框

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 冻结应用，创建快捷方式
2. 点击快捷方式图标
**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
点击快捷方式，打不开
挂起，出现弹框
**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![1643022804426](https://user-images.githubusercontent.com/42453713/150774189-3ff1607c-2e56-4d75-b25a-a08fa6b46e2e.jpg)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Android 12
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）
 - v3.2,3.3均出现

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[logging.zip](https://github.com/Tornaco/Thanox/files/7925121/logging.zip)
此次测试的app为支付宝（应用包名：com.eg.android.AlipayGphone)

以下为adb抓取的日志，测试的app为百度贴吧(com.baidu.tieba)
[adb_log.zip](https://github.com/Tornaco/Thanox/files/7925130/adb_log.zip)

**Comment by Tornaco** [comment]
@OopsSnap 3.2之前的版本点击快捷方式可以启动吗？ 创建的代理app能启动冻结的app吗？

**Comment by Gokou-Ruri** [comment]
> @OopsSnap 3.2之前的版本点击快捷方式可以启动吗？ 创建的代理app能启动冻结的app吗？

这个bug其实是Thanox存在了很久的问题了……2020年底我刚开始用Thanox就存在这个问题，智能冻结以后的APP偶尔需要点击多次才能启动（和上面那位用户一样是一闪而过，点击5-10次以上才可以启动）。
另外还有这个问题：https://github.com/Tornaco/Thanox/issues/265#issuecomment-814773681
APP自己结束某个Activity或Activity出现异常崩溃时，APP会被Thanox冻结。
我认为第二个问题和第一个问题有可能是同一个问题。

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157/artifacts

试试这个能启动了吗？

**Comment by i-CraftY** [comment]
> @OopsSnap 3.2之前的版本点击快捷方式可以启动吗？ 创建的代理app能启动冻结的app吗？

3.2入的坑，启动是没问题的，只是快捷方式有几率打不开app出现一闪而过的问题。
关于挂起的问题酷安上有讨论
![Screenshot_2022-01-26-19-54-04-349_com miui gallery](https://user-images.githubusercontent.com/42453713/151158754-111e8f66-f83f-4395-af59-19305a92fcc2.jpg)



创建代理app没有这些问题

**Comment by i-CraftY** [comment]
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157/artifacts
> 
> 试试这个能启动了吗？

依旧存在需要点击多次才能启动的问题，唯一不同是没有遇到一闪而过的情况而是直接没反应
1.26 ，20点以后做的测试，测试app仍为支付宝（com.eg.android.AlipayGphone）
[logging.zip](https://github.com/Tornaco/Thanox/files/7941633/logging.zip)

**Comment by Gokou-Ruri** [comment]
> > @OopsSnap 3.2之前的版本点击快捷方式可以启动吗？ 创建的代理app能启动冻结的app吗？
> 
> 3.2入的坑，启动是没问题的，只是快捷方式有几率打不开app出现一闪而过的问题。 关于挂起的问题酷安上有讨论 ![Screenshot_2022-01-26-19-54-04-349_com miui gallery](https://user-images.githubusercontent.com/42453713/151158754-111e8f66-f83f-4395-af59-19305a92fcc2.jpg)
> 
> 创建代理app没有这些问题

“挂起”功能开发者说过以后会优化这个功能的： https://github.com/Tornaco/Thanox/issues/349#issuecomment-974824850

**Comment by Tornaco** [comment]
> > https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157/artifacts
> > 试试这个能启动了吗？
> 
> 依旧存在需要点击多次才能启动的问题，唯一不同是没有遇到一闪而过的情况而是直接没反应 1.26 ，20点以后做的测试，测试app仍为支付宝（com.eg.android.AlipayGphone） [logging.zip](https://github.com/Tornaco/Thanox/files/7941633/logging.zip)

```
reportOnActivityResumed: Intent { cmp=github.tornaco.android.thanos/.power.ShortcutStubActivity }
2022-01-26 20:03:18.199 W/Thanox-Core: PmSetAppEnabledApplicationPackageEnabler setApplicationEnabledSetting, setup hide state to false
2022-01-26 20:03:18.206 W/Thanox-Core: launchSmartFreezePkgInternal, com.eg.android.AlipayGphone waitRes: true
2022-01-26 20:03:18.322 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkgName: [com.eg.android.AlipayGphone]
2022-01-26 20:03:18.387 W/Thanox-Core: taskIdCompMap has no task for package: github.tornaco.android.thanos, pull from legacy.
2022-01-26 20:03:18.391 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
2022-01-26 20:03:18.695 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2022-01-26 20:03:18.732 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
2022-01-26 20:03:18.758 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2022-01-26 20:03:18.785 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2022-01-26 20:03:18.871 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
2022-01-26 20:03:19.116 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.eg.android.AlipayGphone/.AlipayLogin }
2022-01-26 20:03:19.710 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
2022-01-26 20:03:19.712 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
2022-01-26 20:03:21.734 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
2022-01-26 20:03:21.841 W/Thanox-Core: taskIdCompMap has no task for package: com.eg.android.AlipayGphone, pull from legacy.
2022-01-26 20:03:21.849 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.eg.android.AlipayGphone, multipleTaskKeep? false
2022-01-26 20:03:21.856 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.eg.android.AlipayGphone
```

上面是截取的一段日志，看起来确实是支付宝被启动了，2s左右之后又回到了桌面；日志中并未出现异常错误，不知道为啥会遮掩，很奇怪。你要不再截取一段启动快捷方式过程中的完整adb log；我尽量看下吧。

**Comment by Tornaco** [comment]
挂起启动会弹出对话框这个问题后面我会想办法优化，现在这个对话框是系统的活动拦截器弹出的，暂时没法屏蔽。

**Comment by i-CraftY** [comment]
> > > https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157/artifacts
> > > 试试这个能启动了吗？
> > 
> > 
> > 依旧存在需要点击多次才能启动的问题，唯一不同是没有遇到一闪而过的情况而是直接没反应 1.26 ，20点以后做的测试，测试app仍为支付宝（com.eg.android.AlipayGphone） [logging.zip](https://github.com/Tornaco/Thanox/files/7941633/logging.zip)
> 
> ```
> reportOnActivityResumed: Intent { cmp=github.tornaco.android.thanos/.power.ShortcutStubActivity }
> 2022-01-26 20:03:18.199 W/Thanox-Core: PmSetAppEnabledApplicationPackageEnabler setApplicationEnabledSetting, setup hide state to false
> 2022-01-26 20:03:18.206 W/Thanox-Core: launchSmartFreezePkgInternal, com.eg.android.AlipayGphone waitRes: true
> 2022-01-26 20:03:18.322 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkgName: [com.eg.android.AlipayGphone]
> 2022-01-26 20:03:18.387 W/Thanox-Core: taskIdCompMap has no task for package: github.tornaco.android.thanos, pull from legacy.
> 2022-01-26 20:03:18.391 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
> 2022-01-26 20:03:18.695 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.732 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
> 2022-01-26 20:03:18.758 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.785 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.871 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:19.116 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.eg.android.AlipayGphone/.AlipayLogin }
> 2022-01-26 20:03:19.710 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
> 2022-01-26 20:03:19.712 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
> 2022-01-26 20:03:21.734 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
> 2022-01-26 20:03:21.841 W/Thanox-Core: taskIdCompMap has no task for package: com.eg.android.AlipayGphone, pull from legacy.
> 2022-01-26 20:03:21.849 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.eg.android.AlipayGphone, multipleTaskKeep? false
> 2022-01-26 20:03:21.856 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.eg.android.AlipayGphone
[log.zip](https://github.com/Tornaco/Thanox/files/7942217/log.zip)

> ```
> 
> 上面是截取的一段日志，看起来确实是支付宝被启动了，2s左右之后又回到了桌面；日志中并未出现异常错误，不知道为啥会遮掩，很奇怪。你要不再截取一段启动快捷方式过程中的完整adb log；我尽量看下吧。



> > > https://app.circleci.com/pipelines/github/Tornaco/Thanox/161/workflows/238c555b-c215-465b-8628-8a0cff680f69/jobs/157/artifacts
> > > 试试这个能启动了吗？
> > 
> > 
> > 依旧存在需要点击多次才能启动的问题，唯一不同是没有遇到一闪而过的情况而是直接没反应 1.26 ，20点以后做的测试，测试app仍为支付宝（com.eg.android.AlipayGphone） [logging.zip](https://github.com/Tornaco/Thanox/files/7941633/logging.zip)
> 
> ```
> reportOnActivityResumed: Intent { cmp=github.tornaco.android.thanos/.power.ShortcutStubActivity }
> 2022-01-26 20:03:18.199 W/Thanox-Core: PmSetAppEnabledApplicationPackageEnabler setApplicationEnabledSetting, setup hide state to false
> 2022-01-26 20:03:18.206 W/Thanox-Core: launchSmartFreezePkgInternal, com.eg.android.AlipayGphone waitRes: true
> 2022-01-26 20:03:18.322 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkgName: [com.eg.android.AlipayGphone]
> 2022-01-26 20:03:18.387 W/Thanox-Core: taskIdCompMap has no task for package: github.tornaco.android.thanos, pull from legacy.
> 2022-01-26 20:03:18.391 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
> 2022-01-26 20:03:18.695 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.732 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
> 2022-01-26 20:03:18.758 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.785 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:18.871 W/Thanox-Core: bindServiceLocked result < 0, we will fix it to 0.
> 2022-01-26 20:03:19.116 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.eg.android.AlipayGphone/.AlipayLogin }
> 2022-01-26 20:03:19.710 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
> 2022-01-26 20:03:19.712 W/Thanox-Core: Blocked ComponentSetting for pkg: [com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone, com.eg.android.AlipayGphone]
> 2022-01-26 20:03:21.734 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.miui.home/.launcher.Launcher }
> 2022-01-26 20:03:21.841 W/Thanox-Core: taskIdCompMap has no task for package: com.eg.android.AlipayGphone, pull from legacy.
> 2022-01-26 20:03:21.849 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.eg.android.AlipayGphone, multipleTaskKeep? false
> 2022-01-26 20:03:21.856 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.eg.android.AlipayGphone
> ```
> 
> 上面是截取的一段日志，看起来确实是支付宝被启动了，2s左右之后又回到了桌面；日志中并未出现异常错误，不知道为啥会遮掩，很奇怪。你要不再截取一段启动快捷方式过程中的完整adb log；我尽量看下吧。
[log.zip](https://github.com/Tornaco/Thanox/files/7942223/log.zip)
只复现了一次

**Comment by Tornaco** [comment]
@OopsSnap 再试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/166/workflows/ea81e991-307b-4999-9d71-1937cdec9720/jobs/160/artifacts

**Comment by i-CraftY** [comment]
> @OopsSnap 再试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/166/workflows/ea81e991-307b-4999-9d71-1937cdec9720/jobs/160/artifacts

抱歉现在才看到，还是复现了，好像比提issue的时候出现几率小了（不知道是不是错觉
[logging.zip](https://github.com/Tornaco/Thanox/files/8030786/logging.zip)
到

**Comment by Tornaco** [comment]
@OopsSnap 能录个屏看下效果吗

**Comment by i-CraftY** [comment]
> @OopsSnap 能录个屏看下效果吗

[logging.zip](https://github.com/Tornaco/Thanox/files/8040689/logging.zip)
**录屏：https://www.bilibili.com/video/BV1p34y117W4/**


包名：tw.nekomimi.nekogram
出现的几率是小了些

**Comment by Tornaco** [comment]
![Screen Shot 2022-02-10 at 8 30 47 PM](https://user-images.githubusercontent.com/23255526/153409909-c1d1afe8-dd97-41b6-97de-f4a871f97272.png)


这个应用开启图中这个开关了吗？看日志好像没开？

**Comment by Tornaco** [comment]
另外你刷的是哪个ROM，我看下我又没有资源复现一下试试

@OopsSnap

**Comment by Gokou-Ruri** [comment]
> 
> 这个应用开启图中这个开关了吗？看日志好像没开？

我这边自从更新了这个功能开始，闪退现象就很少见了。
现在闪退虽然还是有，但好几天才能碰上一次，很难复现。

**Comment by i-CraftY** [comment]
> ![Screen Shot 2022-02-10 at 8 30 47 PM](https://user-images.githubusercontent.com/23255526/153409909-c1d1afe8-dd97-41b6-97de-f4a871f97272.png)
> 
> 这个应用开启图中这个开关了吗？看日志好像没开？

是打开的
![Screenshot_2022-02-10-22-17-22-053_github tornaco](https://user-images.githubusercontent.com/42453713/153426056-b076b897-6e06-41b1-90b2-b01730b9ef0e.jpg)

Android12 MIUI13开发版1.24
现在极少出现这种情况，复现有点难度

**Comment by Tornaco** [comment]
OK 暂时关闭该issue。建议使用时打开检测活动请求后解冻的开关。

**Comment by i-CraftY** [comment]
> OK 暂时关闭该issue。建议使用时打开检测活动请求后解冻的开关。


[logging.zip](https://github.com/Tornaco/Thanox/files/8048472/logging.zip)
今晚出现的：com.xiaomi.router
以上的问题全都是在开启检测活动请求后解冻的情况下发生的
如果thanox在后台则闪退后会拉起thanox

https://user-images.githubusercontent.com/42453713/153589877-3f521507-d69c-4b32-bc09-8b58a22191fb.mp4
