### ISSUE TITLE
对于分身无法进行冻结

### ISSUE THREAD

**Issue by black11191** [Tornaco/Thanox#387]
在智能冻结中 无法冻结炼妖壶中的应用
 它在冻结时即使显示冻结也是假冻结
而冰箱可以做到完美冻结
机型 小米10s   版本:12.5

**Comment by Tornaco** [comment]
@black11191 多用户支持已经开始开发了，请测试下：https://app.circleci.com/pipelines/github/Tornaco/Thanox/208/workflows/e05d9ec6-5075-48d1-b541-ff6f7bb19dc9/jobs/195/artifacts
