### ISSUE TITLE
乖巧模式在免费版的UI下依旧能被勾选

### ISSUE THREAD

**Issue by recreationx** [Tornaco/Thanox#390]
**Describe the bug（现象描述）**
乖巧模式的按钮在免费版 App Manager -> 选择App并查看其选项下可以被勾选

**To Reproduce**（如何复现）
综上所述

**Expected behavior**（期望结果）
UI应该对该页面中未解锁的模式进行一个提醒或者隐藏。

**Version（发现问题的版本）:**
 - OS: Android 12
 - Version: 3.3.1

**Additional context**（其他信息）
NIL.

** Logs**（日志文件）
Unrelated.

**Comment by Tornaco** [comment]
Fixed since v3.5
