### ISSUE TITLE
在3.3.1版本智能冻结不能在添加应用之后自动打开“检测活动启用app”

### ISSUE THREAD

**Issue by yizhidiandian** [Tornaco/Thanox#391]
在上个版本是可以自己打开这个开关的

**Comment by Gokou-Ruri** [comment]
不要光更新却不看更新日志，这个更改根本就不是从3.3.1才开始的。
https://github.com/Tornaco/Thanox/releases/tag/v3.3
另外：
https://github.com/Tornaco/Thanox/releases/tag/v3.4

**Comment by Tornaco** [comment]
v3.5 已经加入多种开关，可按需调整。
