### ISSUE TITLE
希望取消对Thanox安装来源的识别判定

### ISSUE THREAD

**Issue by Gokou-Ruri** [Tornaco/Thanox#393]
目前Thanox Play版会识别安装来源，只有从Play安装才能通过正版检查，但是新版本出现了严重问题时（例如#392 ），无法从Play回退到旧版本，如果开发者无法快速修复问题，用户就只能持续使用这个存在问题的最新版本了。

**Comment by fucksafetynet** [comment]
pm install -i "com.android.vending" thanox.apk

**Comment by Gokou-Ruri** [comment]
> pm install -i "com.android.vending" thanox.apk

没有Thanox Pro 3.3.0安装包。

**Comment by fucksafetynet** [comment]
> > pm install -i "com.android.vending" thanox.apk
> 
> 没有Thanox Pro 3.3.0安装包。

Aurora Store 登自己账号手动下载，versioncode 通常与 GitHub Release 版本一致

**Comment by Gokou-Ruri** [comment]
> > > pm install -i "com.android.vending" thanox.apk
> > 
> > 
> > 没有Thanox Pro 3.3.0安装包。
> 
> Aurora Store 登自己账号手动下载，versioncode 通常与 GitHub Release 版本一致

谢谢提供的下载方法，成功了。
