### ISSUE TITLE
模块是否考虑增加zygisk版本

### ISSUE THREAD

**Issue by hanxin1997** [Tornaco/Thanox#394]
随着日卡卡的存储重定向出zygisk，后面的主流应该是zygisk，而且zygisk有更成熟的隐藏方案，是否考虑将依赖riru模块的thanox模块转换为zygisk版，或者两个版本同时存在？

**Comment by Tornaco** [comment]
@hanxin1997 zygisk版本，请测试下是否工作： https://app.circleci.com/pipelines/github/Tornaco/Thanox/175/workflows/186ed892-0e6e-4994-84c7-5c4875aa92b9/jobs/169/artifacts
