### ISSUE TITLE
magisk激活导致偶发性异常重启

### ISSUE THREAD

**Issue by STTecCEO** [Tornaco/Thanox#396]
现象描述
magisk激活后不定时黑屏重启，频率一天一到两次

发现问题的版本
 - OS: [Android 11]
 - Version [v3.3.1-prc]

其他信息
偶发性异常重启后开机无限软重启，强制关机重启后正常

** Logs**

[anr_2022-01-30-15-54-21-337.zip](https://github.com/Tornaco/Thanox/files/7965549/anr_2022-01-30-15-54-21-337.zip)

**Comment by Tornaco** [comment]
@STTecCEO 可以试试支持zygisk的版本 https://app.circleci.com/pipelines/github/Tornaco/Thanox/175/workflows/186ed892-0e6e-4994-84c7-5c4875aa92b9/jobs/169/artifacts 

如果还是有问题，请同时抓一下data/system/thanos/logging以及data/tombstones

**Comment by STTecCEO** [comment]
[异常重启.zip](https://github.com/Tornaco/Thanox/files/8053388/default.zip) 使用中卡死重启,时间2.12 20:24
[loop.zip](https://github.com/Tornaco/Thanox/files/8053389/loop.zip) magisk仍然无法单独生效，会导致开机一解锁就卡死重启（设定 已停止运行），不解锁则无事发生。xp与magisk同时激活则能正常开机，同时在单独启用xp激活下失效的划卡清理也恢复正常，但Thanox里显示的补丁状态是 Xposed 。

**Comment by Tornaco** [comment]
@STTecCEO 

最新版本测试了吗？

xp和magisk不能同时激活哦。
