### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [Tornaco/Thanox#400]
**Is your feature request related to a problem? Please describe.**
Could this app be published on F-Droid? It seems it's not fully open-sourced.

**Describe the solution you'd like**
If this app can be built from source I can help package it for F-Droid.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tornaco** [comment]
@linsui I'm afraid not, Thanox is not 100% open-sourced for now. Thanks~

**Comment by linsui** [comment]
Will it be fully open source in the future? I thought I can just wait?

**Comment by Tornaco** [comment]
Yes, but I can't guarantee when

**Comment by linsui** [comment]
Thanks!

**Comment by IzzySoft** [comment]
@Tornaco could you please let us know when you reach the "fully FOSS" state? Your app is currently [in my repo](https://apt.izzysoft.de/fdroid/index/apk/github.tornaco.android.thanos). @linsui pointed me to this issue and I agree this raises some difficulties. Criteria for my repo are slightly more relax than on F-Droid, so I just added the `NonFreeDep` anti-feature now (stating the app depends on non-free parts). Once that limitation is lifted, I gladly remove the anti-feature again.

No pressure – but even if you can trim down the non-free parts that would be welcome already. Transparency is valued high when it comes to privacy – and open code is part of that :wink: Thanks in advance!

**Comment by Tornaco** [comment]
@IzzySoft Thank you for your work, I personally am very willing to open source, but due to COV-2019, I need some of this app's revenue to live. I often work 12 hours a day and also take time out to maintain the app, if 100% open source, I am worried that I will lose some of the revenue, which will make my life stress bigger. In the future, when economic pressures are lessened, I will fully open it up. In addition, I am also a person who loves programming :)

**Comment by IzzySoft** [comment]
Fully understood. Wish you best progress– and please let me know when the situation changed and I can lift the "mark".

**Comment by IzzySoft** [comment]
Just checking back in to look if chances have been improved? Maybe until you could open-source those parts, could you confirm some library paths from below list to be from those "personal parts" so I mark them in my scanner library (to get pinged by my scanner when they disappear)?

- [ ] <s>/github/tornaco/android/nitro</s> (part of this repo: `android/nitro`)
- [ ] <s>/github/tornaco/android/plugin</s> (part of this repo: `android/plugins/*`)
- [ ] <s>/github/tornaco/android/thanox</s> (seems to be part here as well, e.g. magisk_bridge)
- [ ] <s>/github/tornaco/practice</s> (part of this repo: `android/modules/module_locker/src/main/java/github/tornaco/practice`)
- [ ] <s>/github/tornaco/thanos/android</s> (also found here)
- [ ] <s>/github/tornaco/thanos/module</s> => (also found here (module component manager))
- [ ] <s>/github/tornaco/thanox/android</s> (also found here)
- [ ] <s>/github/tornaco/xposed</s> (also found here)
- [ ] /tornaco/android/sec => this I cannot find here
- [ ] <s>/util/os</s> (found here: android_framework)
- [ ] <s>/util/q</s> (found here: android_framework)

Thanks in advance! If you have a name for them (I could group all relevant as one library, or group them in multiple libraries, just as you wish) that would be great, too :smiley:

**Comment by IzzySoft** [comment]
OK, so I've just walked the list myself – seems to be only 1 entry left which I could not find defined in this repo here: `/tornaco/android/sec`. So I'd use that to set my trigger. As for this it needs to be part of my library definitions (which are public), I'd need to set up a full entry. I'll use that as the ID, will give it the name "Thanox Sec Module" and put it into the category "Utility". As I cannot tell what it is, the description will just be "proprietary part of the Thanox app" (I can easily update that if you give me an alternative string).

Done that now, so my framework will notify me once that is gone – or you will notify me once it's available as FOSS :wink: Looking forward to that :smiley:

**Comment by Turhvjbufv** [comment]
@Tornaco any update on the /tornaco/Android/sec?

**Comment by Tornaco** [comment]
@Turhvjbufv Buddy, Sec is a android library module, responsibility is to verify the Pro version activation network response😅
