### ISSUE TITLE
冻结应用功能异常

### ISSUE THREAD

**Issue by PianCat** [Tornaco/Thanox#402]
**Describe the bug（现象描述）**
在Android 12上启用冻结应用功能中的挂起功能后，无法正常从桌面启动应用

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1.随意冻结一个应用，且启用挂起功能
2.从桌面点击该应用图标
3.无法打开应用，且弹出设置已停止运行

**Expected behavior**（期望结果）
无报错，且该应用从挂起状态中恢复并打开

**Screenshots**（截图）
![Screenshot_20220205-135635_Lawnchair](https://user-images.githubusercontent.com/50688679/152630586-7428694a-3f84-4232-b129-88142488edd6.png)

**Version（发现问题的版本）:**
 - OS: Android 12 (Arrow OS 12)
 - Version V3.3.1 Play Beta
**Additional context**（其他信息

** Logs**（日志文件）
[logcat.log](https://github.com/Tornaco/Thanox/files/8007475/logcat.log)
[logging.zip](https://github.com/Tornaco/Thanox/files/8007476/logging.zip)

**Comment by Tornaco** [comment]
试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/166/workflows/ea81e991-307b-4999-9d71-1937cdec9720/jobs/160/artifacts

**Comment by Tornaco** [comment]
Fix v3.5
