### ISSUE TITLE
zygisk版在coloros开机解锁后软重启

### ISSUE THREAD

**Issue by DBinkCunese** [Tornaco/Thanox#406]
zygisk版在coloros11.2和coloros12都会开机解锁后软重启
[boot-2022-02-10-23-20-57_112439.zip](https://github.com/Tornaco/Thanox/files/8042429/boot-2022-02-10-23-20-57_112439.zip)
[bootlog-2022-02-10-23-52-18.zip](https://github.com/Tornaco/Thanox/files/8042428/bootlog-2022-02-10-23-52-18.zip)

**Comment by Tornaco** [comment]
@DBinkCunese  把你的thanox配置备份发我一下。我在coloros11.2测试，目前没发现重启问题。我用你的备份试试 。

**Comment by DBinkCunese** [comment]
@Tornaco 
你试试[Thanox-Backup-2022-02-12-01_51_14.zip](https://github.com/Tornaco/Thanox/files/8050713/Thanox-Backup-2022-02-12-01_51_14.zip)

**Comment by Tornaco** [comment]
coloros12 我也升上去了，测试没复现问题。

@DBinkCunese 如果你有电脑的话可以扣扣（1300332322）远程，我来抓个日志看下。

**Comment by Tornaco** [comment]
请测试 https://github.com/Tornaco/Thanox/releases/tag/v3.6

**Comment by Tornaco** [comment]
试试这个。。https://app.circleci.com/pipelines/github/Tornaco/Thanox/183/workflows/db310b56-5926-4bcb-880c-2cdeadbf93bf/jobs/174/artifacts
