### ISSUE TITLE
刷入3.5prc导出的magisk模块后开机循环软重启

### ISSUE THREAD

**Issue by luckyzyx** [Tornaco/Thanox#407]
**Describe the bug（现象描述）**
刷入模块后，开机到锁屏页面，3-5秒左右软重启，循环，禁用模块后正常启动

**To Reproduce**（如何复现）
1. 刷入模块
2. 重启
3. 开机到锁屏页面等待几秒
4. 软重启

**Expected behavior**（期望结果）
修bug

**Screenshots**（截图）
暂无

**Version（发现问题的版本）:**
 - OS: ColorOS12  Android11  一加9RT
 - Version 3.5 prc

**Additional context**（其他信息）
暂无

** Logs**（日志文件）
利用magisk模块 LogCatcher模块抓取的log
[蓝奏云log](https://luckyzyx.lanzouy.com/iIU1Dzvph7a)

**Comment by xushet** [comment]
我也遇到了这种情况，但不确定是这个模块版的原因，试过用mm管理器一键禁用全部模块，开机还是出现了软重启现象，但是在twrp重新刷一遍rom后再开机就不会了

**Comment by Tornaco** [comment]
如果你有电脑的话可以扣扣（1300332322）远程，我来抓个日志看下。   @luckyzyx

**Comment by Tornaco** [comment]
请测试 https://github.com/Tornaco/Thanox/releases/tag/v3.6

**Comment by luckyzyx** [comment]
> 请测试 https://github.com/Tornaco/Thanox/releases/tag/v3.6

非常遗憾，他还是循环重启，不过有丝毫好转，首次解锁后才循环重启，不解锁就一直那个解锁页面
[蓝奏logcatcher](https://luckyzyx.lanzouy.com/ikYAv001lpqj)

**Comment by Tornaco** [comment]
试试这个。。https://app.circleci.com/pipelines/github/Tornaco/Thanox/183/workflows/db310b56-5926-4bcb-880c-2cdeadbf93bf/jobs/174/artifacts

**Comment by luckyzyx** [comment]
> 试试这个。。https://app.circleci.com/pipelines/github/Tornaco/Thanox/183/workflows/db310b56-5926-4bcb-880c-2cdeadbf93bf/jobs/174/artifacts

这个不重启了，修好了，好耶
