### ISSUE TITLE
刷入3.5prc_zygisk_magisk模块后开机软重启 

### ISSUE THREAD

**Issue by qingcheng6** [Tornaco/Thanox#408]
**Describe the bug（现象描述）**
刷入模块后，开机到锁屏页面，3-5秒左右软重启，循环，禁用模块后正常启动

**To Reproduce**（如何复现）
刷入zygisk_thanox

**Expected behavior**（期望结果）
修复

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: [e.g. PixelExperience Android 12]
 - Version [e.g. v3.5]

**Comment by Tornaco** [comment]
请测试 https://github.com/Tornaco/Thanox/releases/tag/v3.6

**Comment by qingcheng6** [comment]
不行，问题依旧

**Comment by Tornaco** [comment]
试试这个。。https://app.circleci.com/pipelines/github/Tornaco/Thanox/183/workflows/db310b56-5926-4bcb-880c-2cdeadbf93bf/jobs/174/artifacts
