### ISSUE TITLE
刷入zygisk_thanox-3.6.zip软重启

### ISSUE THREAD

**Issue by qingcheng6** [Tornaco/Thanox#409]
**Describe the bug（现象描述）**
同之前软重启情况相同，但这次刷入会禁用zygisk，强制开启zygisk后软重启

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 刷入zygisk_thanox-3.6.zip

**Expected behavior**（期望结果）
修复

**Screenshots**（截图）
![Screenshot_20220213-230459_Settings](https://user-images.githubusercontent.com/83507302/153759435-2ef98b1e-66fd-482e-bf46-fa0f49d4a151.png)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 12]（系统版本，例如Android 12）
 - Version [e.g. v3.6（软件版本，例如v3.6）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
我在14日下午或许可以协助你抓取log，如果你有时间的话

**Comment by Tornaco** [comment]
试试这个。。https://app.circleci.com/pipelines/github/Tornaco/Thanox/183/workflows/db310b56-5926-4bcb-880c-2cdeadbf93bf/jobs/174/artifacts
