### ISSUE TITLE
隐匿功能不起作用

### ISSUE THREAD

**Issue by Sentsuki** [Tornaco/Thanox#41]
Thanox正常激活，其他功能正常。开启隐匿模式之后拦截次数始终为0 ，打开APP时通知栏有隐匿模式的通知，但使用Devcheck等应用测试后发现读取到的是真实数据。 重启、清除数据重试均不生效。

（截图）
![photo_2020-01-13_14-36-11](https://user-images.githubusercontent.com/52487960/72496896-f31f7980-3865-11ea-9e0c-220e7b27453a.jpg)

**Version（发现问题的版本）:**
 - OS: LineageOS 16  Android 9 小米6
 - Magisk 20.3   太极magisk 6.1.6  Thanox Pro 保持最新

** Logs**（日志文件）
[2020-01-15.txt](https://github.com/Tornaco/Thanox/files/4069563/2020-01-15.txt)
[2020-01-16.txt](https://github.com/Tornaco/Thanox/files/4069564/2020-01-16.txt)

**Comment by Tornaco** [comment]
@Yabalina Hello 需要提供data/system/thanos下的日志。这输入核心层问题。

**Comment by Sentsuki** [comment]
[thanox-core.txt](https://github.com/Tornaco/Thanox/files/4075257/thanox-core.txt)
已上传，顺便再反映一个小bug，当开启代收插件时，core的日志不会生成。。。

**Comment by Tornaco** [comment]
@Yabalina Thanox备份导出来，分享一下。看下是不是没配置需要隐藏的Field.

**Comment by Sentsuki** [comment]
[Thanox-Backup-2020-01-25-00:10:02.zip](https://github.com/Tornaco/Thanox/files/4109419/Thanox-Backup-2020-01-25-00.10.02.zip)
[thanox-core.txt](https://github.com/Tornaco/Thanox/files/4109436/thanox-core.txt)
顺便上传这几天的日志

**Comment by Tornaco** [comment]
@Yabalina DevCheck 关于设备ID的值目前有三个，具体是哪个不生效？还是都不生效？

**Comment by Sentsuki** [comment]
IMEI和IMEI2是真实的，Device ID既不是真实的也不是我设定的（均以thanox显示为准）
附上最新版本日志
[thanox-core.txt](https://github.com/Tornaco/Thanox/files/4113213/thanox-core.txt)
