### ISSUE TITLE
添加"主题随系统变换"(请求)

### ISSUE THREAD

**Issue by qingcheng6** [Tornaco/Thanox#410]
![Screenshot_20220213-232002_Edge](https://user-images.githubusercontent.com/83507302/153760028-200212cf-231e-4cb9-89d9-d27bf39f13fe.png)
类似这样
而且3.6版本貌似主题切换失败

**Comment by Oosl** [comment]
主题列表的最下面有一个auto，就是随系统主题自动变

**Comment by Tornaco** [comment]
请选择auto
