### ISSUE TITLE
“通知记录”里面重现消息后，该app消息无法清除。

### ISSUE THREAD

**Issue by xiuhu318** [Tornaco/Thanox#413]
我在thanox的消息记录功能里面选择重现滴答清单的消息，然后发现滴答清单的消息都无法清空了。

**To Reproduce**（如何复现）
1. 打开thanos，点击通知记录。
2. 选择该记录，点击重现。

**Expected behavior**（期望结果）
就像正常软件弹出消息那样，可以点击通知跳转滴答清单

**Version（发现问题的版本）:**
 - 安卓版本11，miui版本12.5 21.12.8（开发版）（系统版本，例如Android 6.0.1）
 - thanox版本3.6prc，滴答清单版本6.1.9.6

![image](https://user-images.githubusercontent.com/80893803/154202848-2c204de6-e7a0-4eb0-a42c-cf22c4516fc0.png)

** Logs**（日志文件）
日志不知道怎么抓取。

**Comment by xiuhu318** [comment]
重装滴答清单已经恢复

**Comment by xiuhu318** [comment]
。。好像并没有解决。还是无法清理

**Comment by Tornaco** [comment]
@xiuhu318 请先确认是否是thanox导致的，理论上通知能否清理不受thanox影响。你把thanox取消激活会有这个问题吗？
