### ISSUE TITLE
[Feature request] 易用性改进

### ISSUE THREAD

**Issue by entr0pia** [Tornaco/Thanox#417]
1. magisk (zygisk) 模块随apk自动更新
2. 应用休眠和运行的状态标识以不同颜色显示

![Screenshot_20220220-132339](https://user-images.githubusercontent.com/30486766/154829706-0e6dabeb-0ee0-4518-be54-687ea1bbad9d.png)

**Comment by Tornaco** [comment]
1. 当前暂不支持。
2. 3.7.3已经区分开了
@entr0pia
