### ISSUE TITLE
miui13在3.6.1、3.7、3.7.1上都有问题

### ISSUE THREAD

**Issue by Taylor13Swift** [Tornaco/Thanox#418]
是bug吗还是我的设置问题。。3.6.1、3.7的微信代收一点开就闪退，情景模式保存不了。3.7.1的根本激活不了，只用面具或者lsp还是两者都开启都是未激活。所有的情景模式写进去不能保存，点了没反应，只能退出放弃保存

**Comment by Taylor13Swift** [comment]
还有就是显示当前活动也不会显示，没有反应，权限什么的都已经开了

**Comment by Tornaco** [comment]
日志发一下吧。

**Comment by Tornaco** [comment]
情景模式也发一下

**Comment by Taylor13Swift** [comment]
@Tornaco 打包过去了，劳烦作者大大尽快修复
https://xinpingtai.lanzouj.com/iblIx00g3wfc
Miui13 小米11 安卓12 版本3.7 lsp激活的

**Comment by Taylor13Swift** [comment]
[
{
"name": "微信保活",
"description": "微信睡死时启动",
"priority": 1,
"condition": "pkgKilled == true && (pkgName == \"com.tencent.mm\")",
"actions": [
"ui.showShortToast(\"启动微信\");",
"activity.launchProcessForPackage(\"com.tencent.mm\")"
]
}
]

**Comment by Tornaco** [comment]
@Taylor13Swift 

暂时先手动删除这个文件，重启试试。

/data/system/thanos_xxxx/sec-data/u/0..../start.db

这是后台启动记录的数据库，不知道日志中显示为什么你这个文件损坏了导致一些异常。

**Comment by Tornaco** [comment]
[thanox_3.7.2-prc(3060852).zip](https://github.com/Tornaco/Thanox/files/8114313/thanox_3.7.2-prc.3060852.zip)

激活问题可以更新到这个版本试试。

**Comment by Taylor13Swift** [comment]
Perfect! 完美修复，谢谢啦

**Comment by aoxuexiaoyao** [comment]
> [thanox_3.7.2-prc(3060852).zip](https://github.com/Tornaco/Thanox/files/8114313/thanox_3.7.2-prc.3060852.zip)
> 
> 激活可以更新到这个版本尝试问题。

[
  {
    "name": "Task removal",
    "description": "应用被杀死时，移除任务（仅做示例，请自行优化）",
    "priority": 1,
    "condition": "pkgKilled == true",
    "actions": [
      "task.removeTasksForPackage(pkgName);"
    ]
  }
] 
这模式3.71 3.72都不能用了 3.6可以

**Comment by Tornaco** [comment]
> > [thanox_3.7.2-prc(3060852).zip](https://github.com/Tornaco/Thanox/files/8114313/thanox_3.7.2-prc.3060852.zip)
> > 
> > 激活可以更新到这个版本尝试问题。
> 
> [
>   {
>     "name": "Task removal",
>     "description": "应用被杀死时，移除任务（仅做示例，请自行优化）",
>     "priority": 1,
>     "condition": "pkgKilled == true",
>     "actions": [
>       "task.removeTasksForPackage(pkgName);"
>     ]
>   }
> ] 
> 这模式3.71 3.72都不能用了 3.6可以 

不能用只指什么意思？

**Comment by Taylor13Swift** [comment]
![Screenshot_2022-02-22-17-20-20-038_github tornaco android thanos](https://user-images.githubusercontent.com/62124320/155101521-a313dcb9-6f67-44ce-85df-9c9a59a2322c.jpg)
我不会写这个代码，我复制粘贴别人的，这个样子不是已经启用了嘛

**Comment by aoxuexiaoyao** [comment]
> 

就是应用被杀后 多任务不自动移除了 
3.6的时候一直用着没问题 3.7没试 3.71 3.72就不管用了

**Comment by aoxuexiaoyao** [comment]
> > > [thanox_3.7.2-prc(3060852).zip](https://github.com/Tornaco/Thanox/files/8114313/thanox_3.7.2-prc.3060852.zip)
> > > 激活可以更新到这个版本的试用问题。
> > 
> > 
> > [ 
> > { 
> > "name": "任务移除", 
> > "description": "应用被杀时，移除任务（仅做示例，请自行优化）", 
> > "priority": 1, 
> > "condition": "pkgKilled = = true", 
> > "actions": [ 
> > "task.removeTasksForPackage(pkgName);" 
> > ] 
> > } 
> > ]
> > 这种模式 3.71 3.72 都不能用了 3.6可以
> 
> 不能只用指的英文吗？

就是应用被杀后 多任务不自动移除了
3.6 的时候一直用着没问题 3.7 没试 3.71 3.72 就不管用了

**Comment by Tornaco** [comment]
> 

应该是最近几个版本重构的时候这部分逻辑被破坏了，我修改了一下，你再测试下这个版本呢：

https://app.circleci.com/pipelines/github/Tornaco/Thanox/194/workflows/988b0147-7bcd-4251-b508-17ad5510f26c/jobs/183/artifacts

@[aoxuexiaoyao](https://github.com/aoxuexiaoyao)

**Comment by aoxuexiaoyao** [comment]
> > 
> 
> 应该是最近几个版本重构的这部分逻辑被修改了，我注意到，你再测试下这个版本呢：
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/194/workflows/988b0147-7bcd-4251-b508-17ad5510f26c/jobs/183/artifacts

这个可以了

> > 
> 
> 应该是最近几个版本重构的这部分逻辑被修改了，我注意到，你再测试下这个版本呢：
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/194/workflows/988b0147-7bcd-4251-b508-17ad5510f26c/jobs/183/artifacts
> 
> @[傲雪小瑶](https://github.com/aoxuexiaoyao)

这个可以了 能用了

**Comment by aoxuexiaoyao** [comment]
> > 
> 
> 应该是最近几个版本重构的时候这部分逻辑被破坏了，我修改了一下，你再测试下这个版本呢：
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/194/workflows/988b0147-7bcd-4251-b508-17ad5510f26c/jobs/183/artifacts
> 
> @[aoxuexiaoyao](https://github.com/aoxuexiaoyao)

这个可以用了 能自动移除了

**Comment by Tornaco** [comment]
先关闭这个问题，请关注接下来的正式版。
