### ISSUE TITLE
后台启动的启动记录，点击统计环状图有怪触发

### ISSUE THREAD

**Issue by halloth** [Tornaco/Thanox#419]
**Describe the bug（现象描述）**
后台启动的启动记录页面，点击统计环状图有怪触发。顺时针点击最大的环块的区域，会按照下方次数列表顺序进入相应的app应用管理页面，点击其他环块则无反应

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入后台启动管理的启动记录页面
2. 顺时针点击统计图最大环块的不同区域
3. 会按照下方次数列表顺序进入相应的app应用管理页面
4. 点击其他环块则无反应

**Expected behavior**（期望结果）
点击环状统计图代表不同app的色块，进入到对应app的应用管理页面
**Screenshots**（截图）
![Screenshot_20220222-154318~2](https://user-images.githubusercontent.com/80349988/155335715-e78e5ce3-909a-45c3-aeb7-bc9296e5e594.jpg)

**Version（发现问题的版本）:**
 - OS: 氢OS，Android 11
 - Version: 3.7-row 

**Additional context**（其他信息）

** Logs**（日志文件）

**Comment by halloth** [comment]
更新版本到3.9-row，激活方式lsposed，打开关闭电池选项里的尽力省电，依然会触发同样的怪现象。依照之前图示，具体现象就是点击环状图代表Google play服务的区域，会任意进入下方应用列表中某个app的详细管理页面。而点击环状图中除此之外的任何区域，都不会产生反应

**Comment by Tornaco** [comment]
请测试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/288/workflows/3e8fcebc-5041-44ef-b097-0b174f76d6fa/jobs/269/artifacts

**Comment by halloth** [comment]
测试结果总体良好，统计图触发可以相互对应了。另外触发范围稍微有点小问题

https://user-images.githubusercontent.com/80349988/167229708-754c243e-bddd-43f9-aa84-53c291c9b0c1.mp4

点击环带外正常无反应，点击环带内测一定范围仍会触发统计图内容
