### ISSUE TITLE
[功能建议]硬件操作能力情景模式功能增强

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#42]
1.请问能否增加**连接指定WIFI或者蓝牙**时执行指定操作的功能

2.坐标点击能否增加设定**延时功能**，因为可能因为各种原因，APP无法在执行点击操作时及时进入需要执行点击操作的界面，加入延时可以在一定程度上缓解这种情况

3.请问能否更新一下情景模式手册

**Comment by Tornaco** [comment]
@sakurabot 请先测试下蓝牙功能。

**Comment by Gladtbam** [comment]
> @sakurabot请先测试下蓝牙功能。

已经在写规则测试了,很好用，就是略显复杂，部分参数类型不知道该填什么，比如，蓝牙电量剩余20%，我应该用20表示，还是20%，或者其它方法表示？

**Comment by Gladtbam** [comment]
WiFi能否增加判断WiFi是否连接的接口
