### ISSUE TITLE
查看通知记录，部分通知点击重现thanox会停止运行

### ISSUE THREAD

**Issue by eryldgd** [Tornaco/Thanox#420]
问题描述：查看通知记录点击重现thanox会停止运行

不是所有通知重现都会崩溃，目前已知就是Google Play、小爱同学、米窗的消息重现会崩溃

其它我什么也没做，因为其它功能没有问题。
这个通知记录也不常用！
还有就是我不知道问题出在哪为了避免乱搞出问题最好就哪里也不动了。
后来我把消息清空了还是一样出问题，也没法测试了
![Video_20220223_072059_33](https://user-images.githubusercontent.com/98635421/155542411-6e3e102f-fded-4bd0-ac34-b07498e799ea.gif)

thanox版本：3.7.1-prc
系统版本：Android 12 MIUI 13  22.2.21

日志：
[crash_github.tornaco.android.thanos_2022-02-23-18:48:48.log](https://github.com/Tornaco/Thanox/files/8133248/crash_github.tornaco.android.thanos_2022-02-23-18.48.48.log)
[crash_github.tornaco.android.thanos_2022-02-23-18:48:59.log](https://github.com/Tornaco/Thanox/files/8133249/crash_github.tornaco.android.thanos_2022-02-23-18.48.59.log)
[crash_github.tornaco.android.thanos_2022-02-23-18:50:11.log](https://github.com/Tornaco/Thanox/files/8133250/crash_github.tornaco.android.thanos_2022-02-23-18.50.11.log)
[crash_github.tornaco.android.thanos_2022-02-23-19:16:57.log](https://github.com/Tornaco/Thanox/files/8133251/crash_github.tornaco.android.thanos_2022-02-23-19.16.57.log)
[crash_github.tornaco.android.thanos_2022-02-23-19:17:07.log](https://github.com/Tornaco/Thanox/files/8133252/crash_github.tornaco.android.thanos_2022-02-23-19.17.07.log)
[crash_github.tornaco.android.thanos_2022-02-23-21:21:24.log](https://github.com/Tornaco/Thanox/files/8133253/crash_github.tornaco.android.thanos_2022-02-23-21.21.24.log)
[crash_github.tornaco.android.thanos_2022-02-23-21:22:06.log](https://github.com/Tornaco/Thanox/files/8133254/crash_github.tornaco.android.thanos_2022-02-23-21.22.06.log)

**Comment by Tornaco** [comment]
@eryldgd 3.7.3 OK吗？

**Comment by eryldgd** [comment]
> @eryldgd 3.7.3 OK吗？

试了试，没发现问题了！Good job.
