### ISSUE TITLE
一加桌面卡死

### ISSUE THREAD

**Issue by zzzzs3** [Tornaco/Thanox#421]
1.系统版本：安卓10
2.Thanox版本：3.7.2-row    xpsed方式
3.问题描述：锁定屏幕后，解锁打开桌面，桌面有几率卡死
4.不激活无此问题
5.Thanox不配置问题依旧存在
6.日志文
[log.zip](https://github.com/Tornaco/Thanox/files/8138630/log.zip)
件

**Comment by Tornaco** [comment]
有几个问题确认下：
1. 之前的版本有这个问题吗？
2. 解锁后出现问题，是指第一次开机后第一次解锁，还是每次解锁都可能出现问题？
3. 桌面卡死后，桌面重启了对吧？系统有重启吗？

@zzzzs3

**Comment by zzzzs3** [comment]
找到原因了，是因为我的动态刷新率模块问题。
