### ISSUE TITLE
可自主选择关闭提示语

### ISSUE THREAD

**Issue by finale-site** [Tornaco/Thanox#424]
希望增加一个小功能，可以自主选择关闭情景或者冻结的提示语
![Screenshot_2022-02-28-23-11-37-816_com baidu tieba](https://user-images.githubusercontent.com/56009574/156008076-5625a3d5-0d48-4fc4-b404-2e44d648ed98.jpg)
如把上述的文字可以取消，感谢开发者！！！

**Comment by Gokou-Ruri** [comment]
+1，现在Toast太多了，有时候操作比较快，都已经执行完了，后面几条Toast要等好几秒才会显示出来。

**Comment by Tornaco** [comment]
Please test this build when it's done: https://app.circleci.com/pipelines/github/Tornaco/Thanox/234/workflows/cd8f8357-95b5-438d-9275-4a075257aea8/jobs/219/artifacts
