### ISSUE TITLE
通过suspend模式冻结某个程序后其依旧在后台运行是正常情况吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [Tornaco/Thanox#429]
现在对suspend的可靠性存疑了，刚才玩游戏的时候发现间歇性卡顿，打开3c toolbox一看谷歌相册在后台把小核心占满了，然后在Thanox里查看相册确实是被冻结的状态。
![Screenshot_20220305-130111_Nova_Launcher](https://user-images.githubusercontent.com/26711804/156872974-a93ac931-42a3-4ef7-905a-c99e0eba87c9.png)
![Screenshot_20220305-130125_3C_一体工具箱](https://user-images.githubusercontent.com/26711804/156872987-d85a5955-0714-465b-9565-50889004a786.png)

**Comment by liu-cool-cmd** [comment]
@Gokou-Ruri 同问，我现在都用正常的disable了

**Comment by Tornaco** [comment]
suspend 通常用来做DPC管理；目前看系统的代码是系统会限制这些app的Activity启动。至于是否能从后台启动一些服务之类的就没仔细研究了。

**Comment by Gokou-Ruri** [comment]
> suspend 通常用来做DPC管理；目前看系统的代码是系统会限制这些app的Activity启动。至于是否能从后台启动一些服务之类的就没仔细研究了。

那我再观察一阵看看。
