### ISSUE TITLE
无法感知FCM推送

### ISSUE THREAD

**Issue by Adlyq** [Tornaco/Thanox#430]
**Describe the bug（现象描述）**
如题

**To Reproduce**（如何复现）
开启微信代收，FCM显示广播成功，等几分钟才有微信的通知（微信在乖巧模式）
情景模式的例子（收到推送时显示Toast，删了包名匹配）也没有提示
可以确定nekogram收到了FCM通知被唤醒

**Version（发现问题的版本）:**
 - OS: 安卓12，小米11，最新开发板内测
 - Version 3.8.1-row

** Logs**（日志文件）
暂不清楚日志存放位置

**Comment by Adlyq** [comment]
你好，请问有解决办法吗

**Comment by Tornaco** [comment]
@Adlyq  你的问题是啥？thanox没有检测到微信的GCM消息事件吗？
如果是这个问题请先抓一下日志。

**Comment by Adlyq** [comment]
[log.zip](https://github.com/Tornaco/Thanox/files/8236919/log.zip)
日志（截取之前，FCM有收到通知）

**Comment by Tornaco** [comment]
@Adlyq 你的问题是啥？thanox没有检测到微信的GCM消息事件吗？

**Comment by Tornaco** [comment]
@Adlyq  Magisk版本暂时不支持微信代收哦。 代收入口后续会隐藏调。

**Comment by Adlyq** [comment]
@Tornaco 能magiak xp一起开吗

**Comment by Tornaco** [comment]
这个问题没意义。

**Comment by Clorasun** [comment]
@Tornaco 微信无法显示消息详情，是失效了吗？

**Comment by MRDQ123** [comment]
@Tornaco 新版本谷歌版有导致系统界面无响应的bug

**Comment by Tornaco** [comment]
@MRDQ123 有问题请具体描述，就这么一句话说了等于没说

**Comment by Clorasun** [comment]
> @MRDQ123 有问题请具体描述，就这么一句话说了等于没说

就是微信推送能收到但是推送只显示推送了几条消息，开了显示消息内容，但开不开一个样
