### ISSUE TITLE
冻结微信分身，但是后台显示主程序冻结

### ISSUE THREAD

**Issue by eryldgd** [Tornaco/Thanox#431]
冻结微信分身，但是后台显示主程序冻结

**Screenshots**（截图）

![IMG_20220305_170828](https://user-images.githubusercontent.com/98635421/156877248-4b68e095-665e-463f-9739-c76697f2a5f6.jpg)
![IMG_20220305_170941](https://user-images.githubusercontent.com/98635421/156877258-61fb4185-2e9c-4ac3-a223-065a4a3d5e5f.jpg)
![IMG_20220305_171013](https://user-images.githubusercontent.com/98635421/156877260-c15f161e-933c-4415-a105-aeb62d3ef4d5.jpg)

**Version（发现问题的版本）:**
 如图
![Screenshot_2022-03-05-17-27-19-646_github tornaco android thanos](https://user-images.githubusercontent.com/98635421/156877362-371fe250-0a95-460a-bce6-29aa15803d07.png)
![Screenshot_2022-03-05-17-28-40-582_com android settings](https://user-images.githubusercontent.com/98635421/156877368-866a3a78-b9f6-4bfb-96ab-fd1d0eca355f.png)

**Additional context**（其他信息）
没有其他问题，不妨碍正常使用

** Logs**（日志文件）
这个就不需要日志了吧

**Comment by Tornaco** [comment]
@eryldgd  这种问题修不了，就怪MIUI吧。
