### ISSUE TITLE
Translate donation page  to English

### ISSUE THREAD

**Issue by xxxxme** [Tornaco/Thanox#433]
**Is your feature request related to a problem? Please describe.**
I'm interested in donation information. The donation page appears to be in Chinese, but I can only read English, and to a lesser extent Spanish and German.

**Describe the solution you'd like**
Please translate the donation page into English.

**Describe alternatives you've considered**
Alternately, if the text on the page would be selectable, it could easily be machime translated by the user to understand the gist.

**Comment by Tornaco** [comment]
Donate page currently is designed only for PRC users, we should keep this issue until we have another general donate method rather than Wechat/Ali pay

**Comment by imol-ai** [comment]
So there is no way to get pro features for non-chinese users currently?

**Comment by Tornaco** [comment]
@FadeDave77 From Google play store

**Comment by Tornaco** [comment]
> @FadeDave77 From Google play store

https://www.google.com/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dgithub.tornaco.android.thanos.pro%26hl%3Dzh%26gl%3DUS%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Dthanox%2Bpro%26pcampaignid%3DAPPU_1_Dic5YvSVGIaB0wSO24aoCQ&ved=2ahUKEwj01M2hydj2AhWGwJQKHY6tAZUQ5YQBegQIAxAC&usg=AOvVaw3uDGyJKltFLArbM60tYQFU

**Comment by imol-ai** [comment]
Oh. Well, I don't use google so i guess that's sad for me then. I love it when apps include other ways to purchase premium features than google, but I do understand why using google's LVL api is convenient.
Thanks for you help though.

**Comment by Tornaco** [comment]
Good luck.
