### ISSUE TITLE
想要杀后台但是能收到通知，应该用哪个功能？

### ISSUE THREAD

**Issue by lazureice** [Tornaco/Thanox#434]
我想要的功能类似多任务界面上滑杀后台，但是不需要手动清理，而是可以锁屏后自动清理。

我本来以为是“后台运行”。但是发现锁屏后应用被 force stop，无法再收到通知。
如果不 force stop，应该用哪个功能呢？

**Comment by Tornaco** [comment]
如果什么功能都不用呢？

**Comment by lazureice** [comment]
呃，什么功能都不开启，app会一直占用内存，锁屏也不会清理

**Comment by Gokou-Ruri** [comment]
要有通知就必须有后台，要想有后台的话就不能清理，需求互相矛盾无法实现。
这是又想马儿跑又不想马儿吃草？想收通知又不想程序耗电？那只能用iOS了。

**Comment by lazureice** [comment]
@Gokou-Ruri 
请问在多任务界面上滑关闭APP，这个叫什么？似乎既不是force stop，也不是常驻后台。

**Comment by Gokou-Ruri** [comment]
> @Gokou-Ruri 请问在多任务界面上滑关闭APP，这个叫什么？似乎既不是force stop，也不是常驻后台。

Android默认操作逻辑就是多任务划掉只杀Activity，不force-stop。所以你这个需求没必要用Thanox。
