### ISSUE TITLE
情景模式无法启动app进程。

### ISSUE THREAD

**Issue by xiuhu318** [Tornaco/Thanox#435]
**Describe the bug（现象描述）**
情景模式无法启动被停止的app进程。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 启动qq。
2. 打开thanox进程管理，选择qq，停止qq。

**Expected behavior**（期望结果）
qq进程被停止，然后情景模式进行恢复qq进程。

**实际结果
qq进程被停止，屏幕下方显示情景模式设置的提示语：启动QQ…，重复出现大约3次，然后结束，并没有重新启动qq进程。

**Screenshots**（截图）
![image](https://user-images.githubusercontent.com/80893803/157163302-7860314b-348f-48b6-b4e1-b21b1047e4c3.png)

**Version（发现问题的版本）:**
 - OS: miui12.5.18，安卓11，红米note11pro（系统版本，例如Android 6.0.1）
 - Version [3.8.1]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
手机设置qq微信电池不优化，关闭自启动，后台智能限制，打开乖巧模式。（尝试过打开自启动，关闭乖巧模式也都无法使用上述情景模式启动qq）。
thanox里面启动记录，并没有阻止记录。
使用magisk23版本，riru lsp模块激活。

使用另一个情景模式内容可以在停止后启动qq，但是会直接打开qq界面，并不方便使用。
![image](https://user-images.githubusercontent.com/80893803/157163786-2914cf71-1dab-4216-91d7-04a6e20b891a.png)

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
没有发现日志，日志文件夹日期是前些天的。

**Comment by xiuhu318** [comment]
新增发现。thanox进程管理里面停止qq和微信会导致这两个软件开机自启动失效。多次重启均无法回复。最终我关机，然后开机恢复。该问题可以稳定复现，恢复方法有点玄学，不是很摸得清。

**Comment by Gokou-Ruri** [comment]
同样发现`activity.launchProcessForPackage`无法拉起程序的问题，版本3.9，但这个问题应该大约是3.5版前后就出现了。

**Comment by Tornaco** [comment]
我试了这个API在Android R S上确实会有兼容问题问题
```java
W Thanox-Core: java.lang.NoSuchMethodError: com.android.server.am.ActivityManagerService#addAppLocked(android.content.pm.ApplicationInfo,null,java.lang.Boolean,null)#bestmatch
```

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/239/workflows/eb85eac5-3000-406c-a010-9b453261ca99/jobs/223/artifacts

@xiuhu318 @Gokou-Ruri  等CI这个包出了可以试试。

**Comment by xiuhu318** [comment]
android/out/app/outputs/apk/prc/debug/thanox_3.9-1-d3ec24c-prc(3061051).apk。
是使用点进链接最底下这个安装包吗？

**Comment by xiuhu318** [comment]
我手机系统更新到了13.0.0.1.13。安卓12。还没有适配的root包。过段时间测试

**Comment by Tornaco** [comment]
> 我手机系统更新到了13.0.0.1.13。安卓12。还没有适配的root包。过段时间测试

OK

**Comment by Gokou-Ruri** [comment]
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/239/workflows/eb85eac5-3000-406c-a010-9b453261ca99/jobs/223/artifacts
> 
> @xiuhu318 @Gokou-Ruri 等CI这个包出了可以试试。

测试有效！坐等Play版！
