### ISSUE TITLE
建议给乖巧模式添加仅锁屏时触发功能

### ISSUE THREAD

**Issue by nakixii** [Tornaco/Thanox#436]
因为我不需要收到QQ消息通知，而且QQ经常在锁屏时唤醒，所以把QQ加入了乖巧模式，且没有设置规则。但是这样会导致QQ进去之后需要加载一会儿才能收到消息，在持续使用的时候这样有点烦人，所以希望添加仅锁屏时触发功能。

**Comment by zhuzebi** [comment]
> 因为我不需要收到QQ消息通知，而且QQ经常在锁屏时唤醒，所以把QQ加入了乖巧模式，且没有设置规则。但是这样会导致QQ进去之后需要加载一会儿才能收到消息，在持续使用的时候这样有点烦人，所以希望添加仅锁屏时触发功能。

这个可以用情景模式解决，解锁移出乖巧模式
