### ISSUE TITLE
thanox无法打开未加载图标的应用

### ISSUE THREAD

**Issue by ajdgsu** [Tornaco/Thanox#437]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
thanox无法打开未加载出缩略图的应用，打开就直接崩溃，重置软件也无效(在v3.9之前都没有这个问题)
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
如图
![GIF-220313_110658](https://user-images.githubusercontent.com/45306865/158043289-ceeb74ce-fa51-455c-aa9a-391a4bfb6356.gif)

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
正常运行

**Version（发现问题的版本）:**
 - OS: [Android 11]
 - Version [v3.9.2]

**Additional context**（其他信息）
自从我使用这个软件以来就是这样大多数图标加载不了，不过只有在v3.9之后才打不开这些加载不出来图标的应用

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[LSPosed_2022-03-13T11_24_06.740.zip](https://github.com/Tornaco/Thanox/files/8238923/LSPosed_2022-03-13T11_24_06.740.zip)

**Comment by Tornaco** [comment]
@ajdgsu  麻煩把/system/framework/framework.jar抓一下，發出來~

**Comment by Tornaco** [comment]
@ajdgsu 順便測試一下這個版本 圖標是否可以正常加載。https://app.circleci.com/pipelines/github/Tornaco/Thanox/249/workflows/394411af-9b5b-4d55-af8e-682a2ef1e313/jobs/232/artifacts

**Comment by ajdgsu** [comment]
没有问题，完全正常。不过每次进应用管理都需要超长时间加载(将近10秒)；以及这是这次的日志(如果需要的话)
[LSPosed_2022-03-13T15_14_06.967.zip](https://github.com/Tornaco/Thanox/files/8239111/LSPosed_2022-03-13T15_14_06.967.zip)

**Comment by ajdgsu** [comment]
还有顺便问下在thanox里应用创建的后台终端进程也会被杀死是特性还是bug？(比如说用mt管理器里的终端模拟器使用nohup后台运行脚本，哪怕把oom_adj和oom_score_adj全改最小，划卡强退mt管理器也会导致脚本停止运行。只有正常退出mt管理器后再划卡脚本才不会被强退)

**Comment by ajdgsu** [comment]
这是framework.jar
[framework.jar.7z.zip](https://github.com/Tornaco/Thanox/files/8239133/framework.jar.7z.zip)
其次我认为和它关系可能不是很大，三星有个奇怪的地方就是selinux怎么样都关不掉，永远都是enforcing，只有把selinux直接禁用掉才能关闭，而且目前android11、12也没法禁用selinux(好像一禁用就会瞬间被启用)

**Comment by Tornaco** [comment]
@ajdgsu 杀死应用的工作方式是force-stop，mt管理器启动的任何进程都会被干掉。

**Comment by Tornaco** [comment]
若图标可以正常加载，可关闭该issue
