### ISSUE TITLE
MIUI点击下拉框磁铁后下拉框不消失

### ISSUE THREAD

**Issue by MartinVon1021** [Tornaco/Thanox#439]
**Describe the bug（现象描述）**
如标题

**To Reproduce**（如何复现）
如标题，点击“应用管理”磁铁。应用管理本身成功弹出，但是MIUI下拉框未消失。

**Expected behavior**（期望结果）
点击磁铁后，应用管理页面弹出，下拉框自动消失。

**Screenshots**（截图）

**Version（发现问题的版本）:**
 - MIUI 13，Thanox 3.9.2。每一个版本都这样。

**Additional context**（其他信息）
MIUI自带的大部分磁铁由于是开关功能，没有弹窗，所以不消失是正确的。以“滴答清单”为例的第三方APP，点击“添加任务“磁铁后，有弹窗显示，同时下拉框自动消失。

** Logs**（日志文件）

**Comment by MartinVon1021** [comment]
xposed版本

**Comment by Tornaco** [comment]
请测试：https://app.circleci.com/pipelines/github/Tornaco/Thanox/256/workflows/93d64e1d-15b1-499f-accc-259b33eac02a/jobs/239/artifacts

@MartinVon1021

**Comment by MartinVon1021** [comment]
OK it works
