### ISSUE TITLE
移花接木-特定情况下可引发手机黑屏卡死

### ISSUE THREAD

**Issue by hui-shao** [Tornaco/Thanox#440]
**Describe the bug**
对某些 APP 启用移花接木规则去除开屏广告时，会导致手机黑屏卡死，无法响应，只能通过强制重启恢复。

**To Reproduce**
这里以“百词斩”为例。

1. 在 Thanox 配置移花接木规则（`com.jiongji.andriod.card/com.baicizhan.main.activity.LoadingPageActivity` -> `com.jiongji.andriod.card/com.baicizhan.main.activity.MainTabActivity`）
2. 在桌面打开“百词斩”APP
3. 手机卡死无响应，伴有发热现象。

**Screenshots**
无。（手机卡死无法截图）

**Version**
 - OS: Android 11.0  MIUI12.5
 - App Version: v3.9.0
 - Mode: Lsposed

**Additional context**
个人看法：

高度怀疑是 Thanox 不断尝试启动第二个 activity 造成。

理由有以下几个：
- 手机并非立马卡死，而是先运行极度缓慢，之后才完全卡死，有一定时间过程。
- 手机在黑屏之后，按下指纹解锁按钮，可见一闪而过的百词斩界面。（会连续闪几次）
- 为了验证猜想，我做了一个测试。首先通过 MyAndroidTools 禁用 `com.jiongji.andriod.card/com.baicizhan.main.activity.LoadingPageActivity`，再用“创建快捷方式” APP 以 root 权限打开`com.jiongji.andriod.card/com.baicizhan.main.activity.MainTabActivity`
。结果是，百词斩界面一闪而过（FC）。

由此看来，应该是百词斩进行了某种检测，导致从其他入口无法打开相应 activity。然后 Thanox 检测到 activity 启动失败，不断重试，陷入死循环。

**Expected behavior**
应避免此类卡死问题出现。

_如果确实是重复启动 activity 造成，可以加一个计数检测，比如启动三次失败了就不再启动，并弹出 Toast 提示用户。_

当然，上述内容有很多我自己的猜测，具体的还请作者尽快分析修复吧。

**Logs**
注：将下列图片的png后缀去除即为压缩包。（手机端 Github 似乎不好传文件？）

另：问题出现时间大致为 2022-03-18 21时

![server_logging.zip.png](https://user-images.githubusercontent.com/31568606/159041560-243ee690-34f2-4434-9a2f-f156331790d8.png)

**Comment by Tornaco** [comment]
@hui-shao  稍后测试下这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/255/workflows/9abb7163-e9a2-4939-a684-69a07b5f5b0f/jobs/238/artifacts

百词斩自己检测到LoadingPageActivity没完成后自己又启动了LoadingPageActivity，导致无限loop了。
```java
 if (!d.a().b()) {
            finish();
            overridePendingTransition(R.anim.ae, R.anim.ae);
            startActivity(new Intent(this, LoadingPageActivity.class));
            overridePendingTransition(R.anim.ae, R.anim.ae);
            return;
        }
```

**Comment by hui-shao** [comment]
> @hui-shao 稍后测试下这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/255/workflows/9abb7163-e9a2-4939-a684-69a07b5f5b0f/jobs/238/artifacts
> 
> 百词斩自己检测到LoadingPageActivity没完成后自己又启动了LoadingPageActivity，导致无限loop了。
> 
> ```java
>  if (!d.a().b()) {
>             finish();
>             overridePendingTransition(R.anim.ae, R.anim.ae);
>             startActivity(new Intent(this, LoadingPageActivity.class));
>             overridePendingTransition(R.anim.ae, R.anim.ae);
>             return;
>         }
> ```

我的是 Google Play 版本，没有权限测试普通版。
可以等其它小伙伴帮忙测试下。
或者给个临时的激活码也可以 hui-shao@outlook.com

**Comment by Tornaco** [comment]
@hui-shao 可以在xp里只激活国内版，重启后用pro版本进行设置。

**Comment by hui-shao** [comment]
@Tornaco 
测试成功。百词斩fc后不再出现卡死问题。
nice！
