### ISSUE TITLE
情景模式，电量变化isCharging(是否在充电)，始终为false

### ISSUE THREAD

**Issue by MajoSissi** [Tornaco/Thanox#443]
应用版本：3.8.1 ~ 3.9.3
系统UI版本：MIUI 12.5

最新稳定版到预览版，不管是否在充电isCharging测试始终为false

**Comment by Tornaco** [comment]
请提供对应测试用的情景模式，以及日志。

**Comment by MajoSissi** [comment]
> 请提供对应测试用的情景模式，以及日志。

补充系统为 Android 11

测试的情景模式：
============================
```
[
    {
        "name": "test",
        "description": "测试",
        "priority": 1,
        "condition": "frontPkgChanged && !isCharging",
        "actions":
        [
            "ui.showNotification(\"test\",\"充电状态\",isCharging,true);"
        ]
    }
]
```
============================

日志：
[logging.zip](https://github.com/Tornaco/Thanox/files/8354835/logging.zip)

测试视频：
https://user-images.githubusercontent.com/45786458/160222847-e83d22bd-f9ce-48f6-b7ef-236bef58cbbe.mp4

**Comment by Tornaco** [comment]
@RoyalSissi  试试 [这个版本](https://app.circleci.com/pipelines/github/Tornaco/Thanox/263/workflows/8da63673-1a4e-41c2-a4b3-16d8ddbb37fd/jobs/245)，新增了Battery API可以获取最新[电池状态](https://github.com/Tornaco/Thanox/blob/master/android/android_framework/base/src/main/java/github/tornaco/android/thanos/core/profile/state/BatteryState.kt)。注意，你的情景模式需要修改为：


```json
[
    {
        "name": "test",
        "description": "测试",
        "priority": 1,
        "condition": "frontPkgChanged",
        "actions":
        [
            "ui.showNotification(\"test\", \"充电状态\", battery.getBatteryState().isCharging, true);"
        ]
    }
]
```

**Comment by MajoSissi** [comment]
ok了
