### ISSUE TITLE
Thanox导致1password填充功能失效

### ISSUE THREAD

**Issue by Matthew-Harris-36** [Tornaco/Thanox#445]
一加7T，安卓10，LSP模块加载，之前发过issues。https://github.com/Tornaco/Thanox/issues/441#issue-1174882630
故障描述和判断是thanox的bug过程都已经描述过了，说下后续吧。更新到3.9.1后，只是暂时恢复了正常，重启手机之后再次出现故障，而且此后也一直存在。
希望开发者能尽快修复这个bug，没有了1password的自动填充，少了很多便利。
日志文件：[logging.zip](https://github.com/Tornaco/Thanox/files/8354751/logging.zip)

**Comment by Tornaco** [comment]
@BlueDolphin9527 关闭-情景模式--设置---UIAuto引擎 试试。

**Comment by Matthew-Harris-36** [comment]
我试了两次，关闭和开启这项设置，没有变化，问题还是存在。

**Comment by Tornaco** [comment]
@BlueDolphin9527 建议关闭这个引擎后，重新开关1passwoprd的辅助功能后试试。

**Comment by Tornaco** [comment]
看日志1password是有一个辅助功能的。试过重置thanox的配置吗？没有试过的话可以试试，先排除是配置的问题还是兼容问题。
可以先备份一下thanox数据，再恢复为默认试试。
