### ISSUE TITLE
微信代收无法拉起微信；情景模式启动app进程无法启动微信

### ISSUE THREAD

**Issue by simplerick-simplefun** [Tornaco/Thanox#451]
**Describe the bug（现象描述）**
微信代收功能：无法拉起微信；
情景模式启动app进程：无法启动微信

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 打开微信
2. 进入设置-应用信息（微信）-强行停止
3. 情景模式设置："condition": "fcmPushMessageArrived == true && pkgName == \"com.tencent.mm\"", "actions": ["activity.launchProcessForPackage(\"com.tencent.mm\")",]
4. 微信代收设置：拉起应用+显示消息内容
5. 通过其他微信账号发送给本机微信账号消息。此时能够接收fcm广播。此时thanox可以发出微信新消息通知。
6. 但是通过“开发者模式-正在运行的服务”查看，微信没有被拉起。通过adb查看，也没有拉起。微信也不能弹出接收到新消息的通知。也无法看到消息内容。

**Expected behavior**（期望结果）
微信被拉起；微信收到新消息并发出通知；看到消息内容

**Version（发现问题的版本）:**
**手机：**
一加7pro。GM1910。
安卓11，Hydrogen OS 11.0.5.1 GM21
**环境：**
Magisk 24.3
Zygisk - LSPosed 1.8.0
**应用：**
Thanox pro(Google Play) 3.9-row
通过LSPosed运行

**Comment by simplerick-simplefun** [comment]
尝试了：https://github.com/Tornaco/Thanox/issues/435
里面的测试包，解决了launchProcessForPackage的问题。微信拉起功能在这个测试包里面不能使用，无法测试。
希望能尽快修复好并更新到playstore。
另：未更新修复前，有没有/能否提供一个shell command来临时代替拉起微信这个功能？

**Comment by Tornaco** [comment]
Play商店早就更新到3.9.3了，加入beta计划。
