### ISSUE TITLE
通知记录无记录

### ISSUE THREAD

**Issue by topxuemu** [Tornaco/Thanox#452]
**Describe the bug（现象描述）**
开启通知记录后无记录（之前有过一次正常记录），

**To Reproduce**（如何复现）
之前清除了两次记录，省点模式也关了

**Expected behavior**（期望结果）
可以看到通知记录

**Screenshots**（截图）
![Screenshot_2022-04-03-13-53-42-86_f2caa21d3de1d45abee5464dd1c275bf.jpg](https://user-images.githubusercontent.com/98678767/161414091-e59378c1-4a71-4e2c-b6eb-28653fb72177.jpg)

**Version（发现问题的版本）:**
 - OS: 安卓11
 - Version ：3.9.1
**Additional context**（其他信息）
_magisk 24.3

**Comment by topxuemu** [comment]
@topxuemu

**Comment by Tornaco** [comment]
@topxuemu 补丁下激活方式与日志。

**Comment by snowzlm** [comment]
![Uploading Screenshot_2022-04-05-18-56-23-44_f2caa21d3de1d45abee5464dd1c275bf.jpg…]()

**Comment by topxuemu** [comment]
@fenghuangmu

**Comment by snowzlm** [comment]
> @topxuemu 补丁下激活方式与日志。

![Screenshot_2022-04-05-18-56-23-44_f2caa21d3de1d45abee5464dd1c275bf](https://user-images.githubusercontent.com/102895281/161740471-68304bd6-9f51-4223-a9cc-7b50142a99e7.jpg)

[日志](https://muxiansheng.lanzouw.com/ifc2J02nwlpe)

**Comment by snowzlm** [comment]
@Tornaco 已发截图与日志

**Comment by Tornaco** [comment]
目前看日志没找到原因，等下3.9.5版本，在里面加了日志，复现之后在发下日志。

**Comment by snowzlm** [comment]
@Tornaco 好的
