### ISSUE TITLE
在控制面板中不显示代理应用（开关）

### ISSUE THREAD

**Issue by isnthzy** [Tornaco/Thanox#46]
![Screenshot_2020-01-21-23-28-23-273_github tornaco android thanos](https://user-images.githubusercontent.com/56492968/72818068-cde79c80-3ca5-11ea-8b17-ca596b3ba0cb.png)
如图，会夹杂在各类应用中间，让人感觉不舒服

**Comment by Tornaco** [comment]
1.1.3 支持筛选。暂时关闭。
