### ISSUE TITLE
后台启动统计图问题

### ISSUE THREAD

**Issue by Vstory** [Tornaco/Thanox#460]
**Describe the bug（现象描述）**
应用名称与启动拦截数据间距问题

**To Reproduce**
1. 点击『后台启动』选项，再点击右上角三点菜单；
2. 选择『启动记录』；
3. 可以看到，应用『AdGuard』的应用名称和拦截数据之间没有间隔。

**Expected behavior**
应用名称与拦截数据之间保持间距。

**Screenshots**
[![LZvO5n.jpg](https://s1.ax1x.com/2022/04/12/LZvO5n.jpg)](https://imgtu.com/i/LZvO5n)

**Version（发现问题的版本）:**
 - OS: Android 12
 - Version: 3.9.4-row

** Logs**
No.

**Comment by Tornaco** [comment]
请测试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/288/workflows/3e8fcebc-5041-44ef-b097-0b174f76d6fa/jobs/269/artifacts
