### ISSUE TITLE
无法终止部分app进程

### ISSUE THREAD

**Issue by suroot66** [Tornaco/Thanox#464]
【问题】
Thanox无法终止应用Apkpure的进程
打开apkpure后，无论通过“一键加速”还是“任务清理”功能，都不能杀死其进程，尝试手动在thanox进程列表里长按apkpure终止进程，下拉刷新后该进程依然存在
（thanox功能对于其他app来说是正常生效的）
【环境】
Thanox 3.9.4-prc
激活方式: zygisk-lsposed 1.8.1
ROM: Flyme 9  设备: 魅族16s
安卓版本: 10
涉及app版本: apkpure 3.17.45
【复现】
100%复现
【其他现象】
在apkpure未从系统后台卡片划掉时，thanox中看到其有0个运行中的进程，有3个缓存中的进程：
![S20417-13591319(1)](https://user-images.githubusercontent.com/84700088/163703302-a47dccec-f780-4a79-be4c-21eb53642370.png)
在划掉其后台卡片后，thanox中看到apkpure有1个运行中的进程，0个缓存中的进程：
![S20417-14034234(1)](https://user-images.githubusercontent.com/84700088/163703337-69c44eaf-2312-4f7b-bc68-45d17e40c0c1.png)
在另一款名为3C all-in-one toolbox的工具中，可以看到apkpure始终有两个进程：
![S20417-13594654(1)](https://user-images.githubusercontent.com/84700088/163703361-0187c268-b2dd-4988-a154-4f5115848094.png)
此外，在系统设置界面，停止apkpure应用也是无效的，目前只能在3C中终止掉其进程
【猜测】
可能由于thanox未正确识别其后台进程，或者调用了系统设置停止进程的接口（？）所以导致终止失败

**Comment by suroot66** [comment]
如果需要thanox日志，我可以提供哈😹

**Comment by suroot66** [comment]
目前暂时通过黑阈app缓解了，我为apkpure单独设置了不活跃5min自动强行停止，于是划掉后台后5min那个进程就被杀掉了😋

**Comment by Tornaco** [comment]
日志。

**Comment by suroot66** [comment]
https://wwt.lanzout.com/iRO8503dfl7a
早先的日志

**Comment by suroot66** [comment]
问题原因似乎找到了，就是apkpure不知通过何种手段在我系统上启动了类似保活的进程。这有可能是flyme9独有的bug，也有可能是apkpure最近几个版本在很多系统上都出现了问题
当我执行命令`ps | grep com.apkpure.aegon`时，只能看到两个进程，是开发者选项里可以看到的进程：
![S20419-17031494(1)](https://user-images.githubusercontent.com/84700088/164005602-62b8a4c3-9bfc-4dd8-adaf-47c9507a243c.png)
但当我显示线程和完整信息时，`ps -ATf | grep com.apkpure.aegon`可以看到4个进程（划线处为pid）：
![图叨叨_20220419_171018(1)](https://user-images.githubusercontent.com/84700088/164005933-f7384ab7-2abe-4efd-baee-b07c0b9ecf51.jpg)
其中，后两个进程隐藏得较深，无论是我在设置中强行停止，在thanox中强行停止，还是用`am force-stop com.apkpure.aegon`命令，均无法杀死后两个进程，而这两个进程的作用就是当我杀死前两个进程时重新启动两者（这时可以看到前两个进程的pid变化）
所以只要将4个进程一起杀死，就不会出现apkpure死者苏生的现象了

**Comment by Tornaco** [comment]
![Screen Shot 2022-04-22 at 9 26 03 AM](https://user-images.githubusercontent.com/23255526/164578518-c6e6f815-8c70-4968-8942-2f6530b82c74.png)


@suroot66 apkpure发一下，我只能下载到APKPure_v3.17.50_apkpure.com.apk 版本，另外在MIUI上，测试发现没有那2个奇怪的进程。

另外你可以CI上安装最新Thanox，进程管理UI有调整。 
https://app.circleci.com/pipelines/github/Tornaco/Thanox/280/workflows/1cf65fa8-ea09-40fa-89a1-139c34cf620e/jobs/261/artifacts

**Comment by suroot66** [comment]
@Tornaco 
不用发了，我刚刚也去试那个3.17.50了，还是不行，看来这里面一定有系统因素的，miui上没事😢
另外最新版的Thanox我试了，进程界面更详细了，不过好像没有“缓存中的进程了”？是去掉了，还是合并到“运行中”的里面去了🤔

**Comment by Tornaco** [comment]
> @Tornaco 不用发了，我刚刚也去试那个3.17.50了，还是不行，看来这里面一定有系统因素的，miui上没事😢 另外最新版的Thanox我试了，进程界面更详细了，不过好像没有“缓存中的进程了”？是去掉了，还是合并到“运行中”的里面去了🤔

截个图如何？我发的截图不是缓存的吗？

**Comment by Bigbox02** [comment]
之前也发现了，pure强行常驻后台，你可以试试老版本比如3.17.35

**Comment by suroot66** [comment]
哦，真的耶，那可能是我看错了    不想折腾了😂刚回来旧版  还因为lsp变砖了，又救回来了   等到时候正式版发布了再折腾新的吧😂

**Comment by suroot66** [comment]
@Bigbox02 我直接用情景模式帮我杀了apkpure😏

**Comment by Tornaco** [comment]
那就关闭这个问题了。
