### ISSUE TITLE
打开后台运行勾选部分软件锁屏立即失效

### ISSUE THREAD

**Issue by Mc-user1688** [Tornaco/Thanox#467]
【问题】
后台运行打开勾选部分软件，一锁屏勾选的后台软件立即失效
![Screenshot_2022-04-22-00-34-01-840_github tornaco android thanos](https://user-images.githubusercontent.com/73388367/164508383-0aa10fc9-990f-4bef-907d-b2656ca84861.png)
【版本】
机型：Redmi K40 Pro
ROM：MIUI13
安卓版本：12
Thanox版本：3.9.4-prc
[logging.zip](https://github.com/Tornaco/Thanox/files/8532820/logging.zip)

**Comment by Tornaco** [comment]
没理解什么意思，请补充描述后再open。
