### ISSUE TITLE
执行actor情景模式的时候出现不兼容

### ISSUE THREAD

**Issue by Paranoid999** [Tornaco/Thanox#468]
**Describe the bug（现象描述）**
执行actor情景模式的时候出现不兼容

**To Reproduce**（如何复现）
创建FACT VALUE为“ceshi”的快捷方式到桌面，点击快捷方式图标，即可复现。（注：请用自己手机中已有的情景模式名字“name”替换掉举例中的“请替换”）

举例：
[
  {
    "name": "Profile shortcut '测试'",
    "description": "监听快捷方式'测试'启动事件",
    "priority": 2,
    "condition": "shortcutLaunched == true && shortcutValue == \"ceshi\"",
    "actions": [
      "thanos.getProfileManager().disableRuleByName(\"请替换\");",
      "actor.delayed(10000, \"thanos.getProfileManager().enbleRuleByName(\\\"请替换\\\")\")",
      "ui.showShortToast(\"已停用10秒！\");"
    ]
  }
]

**Expected behavior**（期望结果）
修复不兼容

**Screenshots**（截图）
![正在上传 w{5e06e64} (a8b06806-4897-42ff-a3e3-d4d120ca1ee9 id=0x7f0a0194 tag=CreateIssueFragment)…]()

**Version（发现问题的版本）:**
 - OS: [e.g. Android 10][MIUI12]
 - Version [3.9-prc]，未更新新版是因为之前更新到3.9.1导致我多用户（user10，user11）里原本的机型信息被重置，不得已回退到3.9。最新版Thanox不兼容问题应该也没修。

** Logs**（日志文件）
此不兼容问题未生成log。但很容易复现（可用最新版Thanox进行测试复现）

**Comment by Tornaco** [comment]
请在最新版本上测试，这个问题之前修过。如果新版还有问题再open。

**Comment by Paranoid999** [comment]
你好，又用最新版本3.9.4测试了，依然不兼容。

**Comment by Paranoid999** [comment]
我反馈不兼容问题反馈过4次，这4次都石沉大海，唉

**Comment by Tornaco** [comment]
@Paranoid999 发下日志。你没必要抱怨，我也很忙，问题也要一个个处理，但凡issue描述清晰，且有日志的，我看到了能改的都会改。

**Comment by Tornaco** [comment]
另外如果这个action要延迟的话，不建议用actor，可以直接用delay属性，例子：

```json
[
  {
    "name": "Delayed action example",
    "description": "Execute the action delay 2000 ms: show a short toast 2s after app switched.",
    "priority": 1,
    "delay": 2000,
    "condition": "frontPkgChanged == true",
    "actions": [
      "xxxx"
    ]
  }
]
```

**Comment by Paranoid999** [comment]
1、我也想发日志，但这个不兼容未生成日志。

2、我举例那个情景模式改成delay应该怎么改呢？因为actions部分，有两条需要立即执行，一条延迟执行。请问这种用delay应该怎么写？或者其他有效的写法都行，现在Thanox对延时执行的情景模式太不友好了，希望可以考虑出个解决方案。另外定时任务也没有，比如9点10分执行某某任务，但很无奈，Thanox目前不支持

**Comment by Tornaco** [comment]
@Paranoid999 日志一定有，/data/system/thanos_xx/logging/xxx。  定时任务可以提需求啊，没见几个人提这个需求。

**Comment by Tornaco** [comment]
另外你有什么好的解决方案也可以提出来，技术上我看能实现不。

**Comment by suroot66** [comment]
@Paranoid999 delayed不生效那个问题我也遇到过，你可以改用终端命令sleep，但是会导致sleep前的toast无法显示   或者你把脚本拆成两个，具体案例可以见我写的教程https://zhuanlan.zhihu.com/p/501431479

**Comment by suroot66** [comment]
定时任务装busybox，然后用crontab可以实现，thanox作为开机启动crond服务的工具人
不过比较折腾就是了，可能的话我也希望thanox能出一个定时的condition

**Comment by Paranoid999** [comment]
@suroot66 
感谢，以前就是用sleep延时，但sleep延时执行这段过程中，Thanox其他情景模式会失效，所以作者才推荐的用actor，然后actor各种不兼容。现在作者说用delay，但delay只能让actions部分整体延时，不能某个action单独延时。总之，Thanox处理延时还是不太友好，希望能慢慢改进。再次感谢你写的教程，辛苦了👍

**Comment by Paranoid999** [comment]
@suroot66 
好的，我试试crontab

**Comment by Paranoid999** [comment]
@Tornaco 
为了提供有用的log，我之前把log删除了之后开始测试的，测试完成未发现生成新的log（但以前版本会新生成）。然后我只能重启手机，再次测试，测试时间为6点12分0秒，请看这之后的log。

抱歉，实在是没找到上传附件的选项，刚开始用GitHub Issue，见谅

**Comment by Tornaco** [comment]
@Paranoid999 日志传哪里去了，你不需要手动清理日志，全都发给我我来筛选就可以。

**Comment by Paranoid999** [comment]
上传到蓝奏了，https://wwc.lanzouj.com/b0dxxbdsh 密码:dada
麻烦再看一下吧

**Comment by Tornaco** [comment]
@Paranoid999 https://app.circleci.com/pipelines/github/Tornaco/Thanox/284/workflows/e4d3ca0b-c086-4f94-b17a-0c13ac9f2205/jobs/265/artifacts

试试这个。注意：你上面贴的情景模式有单次拼错了应该是`enable`

另外这个版本加了一个后门：如果priority < 0，那么这条情景模式会在新thread执行，意味着你可以随意使用sleep，而不影响其他情景模式。

**Comment by Paranoid999** [comment]
1、不兼容的问题测试了已解决，非常感谢！！👍👍👍👍👍👍

2、sleep延时还是有点小问题，比如同一个App设置了两个情景模式（一个是sleep延时，一个不是），等到开始执行的时候，两个情景模式都会延时。（非sleep那个情景模式也会被延时）

举例：
（注：请把两个情景模式的“全局变量”都添加同一个App，然后用这个App进行测试。关闭此App，测试gps关闭期间，蓝牙是否也被延时关闭）

情景模式一（sleep延时）：
[
{
"name": "自动开关GPS",
"description": "打开应用开启定位，应用回到后台20秒(1000毫秒＝1秒)后关闭定位。应用名单来自全局变量gps",
"priority": 2,
"condition": "if( hw.isLocationEnabled() == false && frontPkgChanged == true && globalVarOf$gps.contains(to)) { (hw.enableLocation() ) } else if ( hw.isLocationEnabled() == true && frontPkgChanged == true && !from.contains(\"launcher\") && globalVarOf$gps.contains(from)) { ( Thread.sleep(20000) + hw.disableLocation() )}",
"actions": [
""
]
}
]



情景模式二（无延时）：
[
{
"name": "自动开关蓝牙",
"description": "自动开关蓝牙，应用名单来自全局变量bt",
"priority": 2,
"condition": "if(frontPkgChanged == true && globalVarOf$bt.contains(to)) { (hw.enableBT() ?) } else if ( pkgKilled == true && globalVarOf$bt.contains(pkgName)) { (hw.disableBT() ?) }",
"actions": [
""
]
}
]



只设置了gps延时20秒关闭，实测发现，蓝牙也被延时了同样时间才关闭。


又测试了不同App应用不同情景模式的场景，实测发现，sleep延时开始执行的时候，其他情景模式是无效的，和之前sleep bug一样。

举例：
还是上面两个情景模式，只不过将“全局变量”分别添加两个不同App进行测试，测试gps延时20秒这期间，另一个情景模式是否会失效。



所以，sleep要是不好改不改也行，恢复到之前没修改的状态。（虽然会有延时执行期间，其他情景模式无效的bug）

**Comment by Tornaco** [comment]
```
如果priority < 0，那么这条情景模式会在新thread执行，意味着你可以随意使用sleep，而不影响其他情景模式。
```

你仔细看一下这句话，你的第一条"priority"改了吗？

**Comment by Paranoid999** [comment]
明白了，原来是改这里。我再测试下

再请教下具体怎么改，
"priority": -1,这样吗？
还是"priority": priority < 0,
或者"priority":  < 0,

这几种只有"priority": -1,不提示语法错误。实测和之前一样。


不会是直接写到condition里边吧？

**Comment by Paranoid999** [comment]
priority < 0具体应该怎么改呢，能举个例子吗？

**Comment by Tornaco** [comment]
priority = -1
