### ISSUE TITLE
手机无限重启

### ISSUE THREAD

**Issue by nansi00** [Tornaco/Thanox#469]
**Describe the bug（现象描述）**
在lsp中激活后手机会无限重启

**To Reproduce**（如何复现）
激活后会在随机时间内重启，之后进入桌面会进入循环重启

**Expected behavior**（期望结果）
希望解决问题，

**Version（发现问题的版本）:**
Flyme9  安卓11
软件版本3.9.4  3.9.3都试过

** Logs**（日志)
http://124.223.95.159:9002/s/MXTw

**Comment by Tornaco** [comment]
@nansi00  https://app.circleci.com/pipelines/github/Tornaco/Thanox/283/workflows/dbeda6e9-c70b-4adb-9ae1-16c0b83bf2fd/jobs/264/artifacts
请测试这个版本。
