### ISSUE TITLE
[功能建议]更新后如果不重启增加确定按钮可以操作软件

### ISSUE THREAD

**Issue by 2220209876** [Tornaco/Thanox#47]
![Screenshot_20200125-220347_Thanox_pro](https://user-images.githubusercontent.com/7346652/73122359-e4039e80-3fbe-11ea-86fa-da6edfed79ac.png)

这个提示要不要加个确定按钮，确定完还可以操作软件，要是更新软件、更新插件，这样要重启两次

**Comment by Tornaco** [comment]
1.1.3 支持。暂时关闭。
