### ISSUE TITLE
Thanox可信初始化时遇到兼容性错误

### ISSUE THREAD

**Issue by brownfo** [Tornaco/Thanox#470]
**Describe the bug（现象描述）**
重启偶现"核心初始化错误": Thanox可信初始化时遇到兼容性错误，可能会影响某些功能，请把/data/system/thanos/log下面的日志反馈给开发者

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
尚不清楚，有时连续重启都显示不兼容，有时一直正常

**Expected behavior**（期望结果）
希望开发者能够根据日志修复这个问题，或者能帮忙找出是否我配置有问题

**Screenshots**（截图）
![Screenshot_2022-04-23-18-48-47-2026590606](https://user-images.githubusercontent.com/76164253/164891872-bead74d8-53e0-435e-811b-7af60f51ef0e.png)

**Version（发现问题的版本）:**
 - OS: 联想小新pad pro 2021 13.1.549 稳定版 安卓11
 - Version thanox 3.9.4
thanox@tornaco:307d16e5-b6e3-44f7-bfd2-83ca2ccc7555
3.9.4-prc
thanox@tornaco:307d16e5-b6e3-44f7-bfd2-83ca2ccc7555
Sat Apr 09 11:12:43 CST 2022
Mac OS X

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
[thanox-core.log](https://github.com/Tornaco/Thanox/files/8546785/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/8546786/thanox-init.log)

**Comment by Tornaco** [comment]
@brownfo 请测试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/287/workflows/bb857093-02b9-4176-822d-f90327f12edd/jobs/268/artifacts

**Comment by brownfo** [comment]
> @brownfo 请测试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/287/workflows/bb857093-02b9-4176-822d-f90327f12edd/jobs/268/artifacts

开发者你好，经过四次不规律的间断重启测试和使用后，问题未再复现，若有复现，我会及时反馈
