### ISSUE TITLE
12 L锁屏无法杀后台

### ISSUE THREAD

**Issue by gwc12412** [Tornaco/Thanox#471]
**Describe the bug（现象描述）**
锁屏无法杀后台

**Expected behavior**（期望结果）
锁屏可以杀后台

**Version（发现问题的版本）:**
 - OS: [e.g. Android 12 L]
 - Version [e.g. v3.9.4-prc ]

**Additional context**（其他信息）
一键加速可以杀后台，后台运行无法杀后台，已取消勾选应用

**Comment by Tornaco** [comment]
请提供日志和配置截图。
