### ISSUE TITLE
12L锁屏无法杀后台

### ISSUE THREAD

**Issue by gwc12412** [Tornaco/Thanox#473]
**Describe the bug（现象描述）**
锁屏无法杀后台，一键加速可以杀后台。

**To Reproduce**（如何复现）
以酷安为例：
1. 打开酷安
2. 上滑回到主界面
3. 锁屏
4. 解锁屏幕打开酷安发现酷安依然是回到主界面之前的样子，没有启动过程
5. 尝试一键加速功能可以杀死酷安

**Expected behavior**（期望结果）
可以锁屏杀后台

**Screenshots**（截图）
![Screenshot_20220425-134403_Thanox](https://user-images.githubusercontent.com/18442546/165030057-ace6198b-e6ce-4d23-9f4f-e7fe3e5050fc.png)
 
**Version（发现问题的版本）:**
 - OS: [e.g. Android 12, API: 32, 版本号: SP2A.220405.004]
 - Version [e.g. v3.9.4-prc]

**Additional context**（其他信息）
一键加速和乖巧模式正常

** Logs**（日志文件）
不知道怎么上传Log，已打包上传蓝奏云：
https://gwc12412.lanzouf.com/b00pmtzwj
密码:90rr

**Comment by Tornaco** [comment]
@gwc12412 
https://app.circleci.com/pipelines/github/Tornaco/Thanox/289/workflows/6597fe81-4225-49d4-af89-839f1638edc5/jobs/270/artifacts

**Comment by gwc12412** [comment]
> @gwc12412 https://app.circleci.com/pipelines/github/Tornaco/Thanox/289/workflows/6597fe81-4225-49d4-af89-839f1638edc5/jobs/270/artifacts

我不懂程序和代码，点开链接我有看到“[services] remove keyguard check”这句话，是让我删除锁屏密码重新测试吗？

**Comment by gwc12412** [comment]
> @gwc12412 https://app.circleci.com/pipelines/github/Tornaco/Thanox/289/workflows/6597fe81-4225-49d4-af89-839f1638edc5/jobs/270/artifacts

已经解决，作者大大效率很高，点赞🥰😋
