### ISSUE TITLE
情景模式就可以加个省电模式的设置吗

### ISSUE THREAD

**Issue by hw1020** [Tornaco/Thanox#474]
比如开启屏幕，就关闭省电模式，关闭屏幕就开起省电模式

**Comment by Tornaco** [comment]
是需要省点模式开关的API吗？还是要一条情景模式？没理解你想要什么？

**Comment by Gokou-Ruri** [comment]
情景模式让开发者来写，那开发者做这个情景模式是为了什么？衣来伸手饭来张口可不是个好习惯。
而且和#482 重复了。

**Comment by hw1020** [comment]
开关的api，如果能有监听省电模式开关状态当然更好啦

wangchuanhong
________________________________
发件人: Tornaco ***@***.***>
发送时间: 2022年4月28日 13:00
收件人: Tornaco/Thanox ***@***.***>
抄送: hw1020 ***@***.***>; Author ***@***.***>
主题: Re: [Tornaco/Thanox] 情景模式就可以加个省电模式的设置吗 (Issue #474)


是需要省点模式开关的API吗？还是要一条情景模式？没理解你想要什么？

―
