### ISSUE TITLE
增加危险警告标识

### ISSUE THREAD

**Issue by Guhe-o** [Tornaco/Thanox#476]
**Is your feature request related to a problem? 
冻结软件界面能否新增一个类似appops那样的危险警告？不知道哪些禁了会无法开机

**Describe the solution you'd like**
冻结界面提示“该应用冻结可能导致无法开机”这样的警告语，对那些冻结百分百无法开机的将冻结按钮变成灰色

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2022-04-26-14-04-46-406_moe shizuku redirectstorage](https://user-images.githubusercontent.com/67861307/165232708-efd3b4d6-31f1-4263-a7ae-e6818711fad9.png)
就像这样的

**Comment by liu-cool-cmd** [comment]
@Termux000001 这。。。有点多余吧（

**Comment by Termux000001** [comment]
😂😂想省电又不敢下手

**Comment by Guhe-o** [comment]
> @Termux000001 这。。。有点多余吧（

想省电又不敢下手😂

**Comment by suroot66** [comment]
刷个自救模块，无法开机自动解冻所有app😏

**Comment by Guhe-o** [comment]
> 

😃😃😃懂了，谢谢
