### ISSUE TITLE
Google服务异常

### ISSUE THREAD

**Issue by Guhe-o** [Tornaco/Thanox#477]
问题描述：不知道是冻结了什么东西还是MIUI的问题，突然Google服务就没了，点击重试无反应，打开谷歌邮箱会提示英文

我尝试在lsp里把thanox关闭并重启手机，重启手机后恢复正常；但当我把thanox再次在lsp里打开并重启手机，这个问题再次出现

系统版本：
红米k40  MIUI 13 开发版 22.4.8 安卓13
thanox版本：
Pro版  3.9.4-row

![Screenshot_2022-04-26-23-56-42-239_github tornaco android thanos pro](https://user-images.githubusercontent.com/67861307/165348976-9a6bc6b2-07f9-485f-a1fe-c12dad144cbf.png)
![Screenshot_2022-04-26-23-54-43-936_com google android gm](https://user-images.githubusercontent.com/67861307/165348999-ef10b344-936e-4b66-ac64-00bfd2252d80.png)
![Screenshot_2022-04-26-23-26-48-957_com android vending](https://user-images.githubusercontent.com/67861307/165349033-ae5e7e4d-1367-472b-99ce-b51203ba020b.png)
![Screenshot_2022-04-26-23-30-02-817_rikka safetynetchecker](https://user-images.githubusercontent.com/67861307/165349098-21a50687-9b2b-4e84-805a-9776699b0446.png)
#

>

**Comment by Guhe-o** [comment]
最后一张图传错了
![Uploading Screenshot_2022-04-27-00-00-28-486_com.android.settings.png…]()

**Comment by Guhe-o** [comment]
不知道怎么上传log，只好发到tg群里了

**Comment by Bigbox02** [comment]
清除play数据缓存后试试，我的可以，不过我用基本功能一般不在lsp勾选模块也能正常使用，问下哪些功能是要勾选模块的，

**Comment by Guhe-o** [comment]
@Bigbox02 尝试卸载更新，然而并没有意料之外的喜事🤣🤣

**Comment by KanoCifer** [comment]
我跟你一样的问题，不要对谷歌服务做任何操作，比如乖巧。我就是这样，搞了好久。。还以为版本问题
