### ISSUE TITLE
使用一段时间后输入法振动失效

### ISSUE THREAD

**Issue by recycle007** [Tornaco/Thanox#479]
**Describe the bug（现象描述）**
使用几天后输入法振动就失效，一直以为是一加的原因，看酷安好多人说是thanox的缘故，而且我手机用一段时间在打开全屏应用或视频时会非常卡，也不知道这个是不是thanox的原因

**To Reproduce**（如何复现）
不知如何复现。。有时候几天一次，有时候用很久才出现，但基本都会发生，重启解决

**Expected behavior**（期望结果）
解决bug

**Screenshots**（截图）
截图无法体现

**Version（发现问题的版本）:**
 - OS: Android 10
 - Version v3.9.4
 - 老版本到现在一直都会发生

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

**Comment by Tornaco** [comment]
Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。

所以问题反馈请务必提供更详细的信息。

1. 系统版本

2. Thanox版本，补丁方式（xposed还是magisk？）

3. 问题现象的详细描述，有图或者视频更好

4. 不激活thanox有问题吗？

5. Thanox激活后不做任何配置有问题吗？

6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by recycle007** [comment]
> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 
> 所以问题反馈请务必提供更详细的信息。
> 
> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

关键是这个问题随机出现，可能一个月出现一次。。中间要是重启过时间还得延长。。已经严重依赖thanox，还要不激活用几个月测试不激活有没有问题实在忍不了，相比之下半个月重启一次也可以忍受了。。主要我看酷安很多人提这个问题，以为是常见问题想问问有没有解决办法，麻烦开发者了😂

**Comment by Tornaco** [comment]
建议不要对这个输入法最一些奇怪的设置再观察一下。最好能排查下是不是哪个配置导致的。暂时关闭issue。

**Comment by liu-cool-cmd** [comment]
@Tornaco 是不是对输入法乖巧了

**Comment by PoseidonWake** [comment]
请问你最终找到问题源头了吗？我这也出现了这个现象，像是随机出现，但确实是在装了thanox后才发生的，而我并未对Gboard做任何配置。
刚发现输入法振动失效后微信发语音消息也录不进去
