### ISSUE TITLE
[功能建议]情景模式增加额外的对 手电筒的硬件操作

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#48]
希望能增加对手电筒的开关的控制操作（这是我个人的请求）

附上酷友 @翔呜呜的请求：实现滑盖或者AI键触发手电筒开关的action,现在主要需要硬件控制api里增加对手电筒开关的控制。😋😋（最好是前后手电筒单独可控）

**Comment by Tornaco** [comment]
@sakurabot 请测试1.1.4-beta1 https://github.com/Tornaco/Thanox/releases/tag/v1.1.4-beta1

**Comment by Tornaco** [comment]
已实现，若无问题暂时关闭。
