### ISSUE TITLE
12L权限管理屏幕亮度失效

### ISSUE THREAD

**Issue by pgigli** [Tornaco/Thanox#480]
1. 系统版本 
Android 12
2. Thanox版本，补丁方式（xposed还是magisk？）
Lsposed
3. 问题现象的详细描述，有图或者视频更好
权限管理屏幕亮度管理失效，打开付款码亮度拉满
4. 不激活thanox有问题吗？

5. Thanox激活后不做任何配置有问题吗？

6.  按照app首頁最下面「反饋」的提示抓取日志并上传到issue里
[log.txt](https://github.com/Tornaco/Thanox/files/8589513/log.txt)

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/400/workflows/aa49323e-8b8c-4eb9-999d-a632cfd6e14b/jobs/367/artifacts


@pgigli 测试下这个版本呢

**Comment by Tornaco** [comment]
dup with #388 请关注这个issue即可
