### ISSUE TITLE
你好 能不能添加一个情景模式 超过十分钟未打开屏幕自动进入省电模式 打开屏幕自动退出

### ISSUE THREAD

**Issue by yyz0313** [Tornaco/Thanox#482]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Gokou-Ruri** [comment]
情景模式让开发者来写，那开发者做这个情景模式是为了什么？衣来伸手饭来张口可不是个好习惯。
