### ISSUE TITLE
Play版无法安装及谷歌验证错误

### ISSUE THREAD

**Issue by claydeck** [Tornaco/Thanox#485]
**Describe the bug（现象描述）**
Play版Thanox显示无法安装，包括测试版和普通版
此时会发现已经安装成功，但无法通过验证
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 在Play中安装Thanox，显示无法安装，但事实是成功安装了，Play这边依然是未安装状态，见截图1
2. 打开刚刚安装的Thanox Pro，验证错误，见截图2
3. 跳过验证可正常激活（已测试lsposed）
4. Play的其他应用均无此安装问题，且手机ROM为国际版ROM，自带谷歌服务，且通过shamiko对谷歌框架和Play商店隐藏了root以此通过saftynet检测（不知何这个有无关系）
5. Magisk、lsposed以zygisk运行

**Expected behavior**（期望结果）
正常安装使用Thanox Pro

**Screenshots**（截图）
![Screenshot_20220503-230554](https://user-images.githubusercontent.com/10060276/166480837-09f75d94-fd25-4d13-9a5c-a5b0700e9e9e.jpg)
![Screenshot_20220503-230644](https://user-images.githubusercontent.com/10060276/166480928-132549a9-0368-44e9-b1a0-10e05d324a63.jpg)

**Version（发现问题的版本）:**
 - OS: [Android 11]
 - Version [Play上的测试版和普通版]

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@im20A0 如果连安装都失败的话，我也解决不了~

**Comment by AnnualfireCHW** [comment]
> @im20A0 如果连安装都失败的话，我也解决不了~

我也无法安装，跟他一模一样的提示

**Comment by AnnualfireCHW** [comment]
> @im20A0 如果连安装都失败的话，我也解决不了~

除了你们的软件之外都可以正常安装
