### ISSUE TITLE
多用户里的机型信息被重置

### ISSUE THREAD

**Issue by Paranoid999** [Tornaco/Thanox#489]
**Describe the [bug（现象描述）**]
多用户里的机型信息被重置，像在新手机登录新App那样。具体表现：①、user 10、user 11里的微信登录提示新机型（和从新手机登录时的情形一模一样）；②、user 11 QQ无法打开；③、多用户里的MIUI权限被重置；④、多用户里的手机管家设置也被重置。

**To Reproduce**（如何复现）
偶发复现（版本3.9.6，3.9.5的log都抓到了，麻烦看一下）

**Version（发现问题的版本）:**
 - OS: [ Android 10 (MIUI 12)]
 - Version [3.9.6，3.9.5，3.9.1，以及更早的某些版本也出现过这种问题]，

 - 

** Logs**（日志文件）
@Tornaco 麻烦看一下

最新版本3.9.6提取的log：https://wwc.lanzouj.com/b0dxzt0xe
密码:1dwq

3.9.5版本提取的log：https://wwc.lanzouj.com/b0dxzc5aj
密码:8de1

---------

> 1. 系统版本：安卓10（MIUI 12）
> 2. 补丁方式：xposed

**Comment by Paranoid999** [comment]
@Tornaco 麻烦看一下哈，真的太影响使用了，感谢，辛苦了

**Comment by Tornaco** [comment]
@Paranoid999 激活什么都不做就这样？

**Comment by Paranoid999** [comment]
> @Paranoid999 激活什么都不做就这样？

Thanox的某些版本没有这个问题（测试过很长时间），某些版本会有（更新了thanox很短时间就复现bug了），基本能确定就是Thanox的问题。

**Comment by Tornaco** [comment]
@Paranoid999 建议你恢复thanox为默认数据试试，排除是你自己做的一些配置导致的还是thanox的bug（这个是bug的可能性较小）。这个问题暂时没有收到其他人反馈，我会回去复现，如果无法复现，那么这个问题我也无法解决。

**Comment by Paranoid999** [comment]
在我更新到Thanox 3.9.9.2-prc(3061063)版本之后，此问题又复现了，附上刚抓到的log。因为多用户里机型信息被重置，导致user10 QQ打不开了，我用Logcat Reader也抓了log，麻烦看下能否找到有用信息。

提取的log：
https://wwc.lanzouj.com/ikjyM066jgdg

（根据抓的log，麻烦看看QQ在不清空数据的前提下有办法打开吗？因为清空数据之后QQ聊天记录就没了）

我之前用的版本3.9.6-prc(3061057)，也是刚更新之后出现了重置多用户机型信息的bug，但只是刚更新后出现过那一次，之后一直很稳定(用了很长时间)，未出现此bug。所以我猜想，貌似和更新Thanox版本有关系(更新一次新thanox版本就会重置一次多用户机型信息？)。此猜想我后续会持续进行验证。
