### ISSUE TITLE
一键加速存在bug

### ISSUE THREAD

**Issue by Clorasun** [Tornaco/Thanox#491]
一键加速存在bug（这种bug是去掉了后台运行，勾选了任务清理仍然生效的）
对该bug进行了测试确实存在这种情况!
test相关图片:https://www.helloimg.com/images/2022/05/09/RNsTQg.jpg
版本:3.9.6-row thanox May0713:24:46
相关log文件:链接：https://www.123pan.com/s/CDzA-1TsOA

_使用 [FastHub-RE](https://github.com/LightDestory/FastHub-RE/) 从我的 meizu 18 Pro 发送_

**Comment by Tornaco** [comment]
@MRDQ123 一键清理时跳过了有通知的应用，你可以关闭这个开关试试。

```
2022-05-09 12:15:31.235 W/Thanox-Core: Package com.chinamobile.mcloud has notification, ignore.

```

**Comment by csy19960309** [comment]
> @MRDQ123 一键清理时跳过了有通知的应用，你可以关闭这个开关试试。
> 
> ```
> 2022-05-09 12:15:31.235 W/Thanox-Core: Package com.chinamobile.mcloud has notification, ignore.
> ```

请问“有通知的应用”是如何定义的？实测把通知栏里的通知划掉后，一键加速还是不能把相对应的App杀死。

**Comment by Clorasun** [comment]
通知栏有消息通知，通知没划掉。或是通知栏常驻有禁止滑动删除机制的

**Comment by csy19960309** [comment]
> 通知栏有消息通知，通知没划掉。或是通知栏常驻有禁止滑动删除机制的

都没有，确定划掉了，但是一键清理没有杀掉。微信和QQ有这个问题，微信用FCM唤醒，QQ用 HMS Core唤醒

**Comment by Clorasun** [comment]
是有bug，这个我提过了，我也检查过了，之后又发过一次issue，我删掉了。情景模式也有些问题懒得反馈了。
