### ISSUE TITLE
su enabler失效

### ISSUE THREAD

**Issue by UISSD** [Tornaco/Thanox#492]
机型K50 miui13 13.0.10.0 稳定版, thanox版本为3.9.6-prc, 插件su enabler启用无效,情景模式的sh命令执行失败, 无论是以magisk还是lsposed方式激活都存在同样的问题

**Comment by UISSD** [comment]
系统为安卓12
log文件:https://wwz.lanzouf.com/b03cy7uif
密码:gxpi

**Comment by Wcoom** [comment]
巧了，我也是，反馈了一个周了

**Comment by Tornaco** [comment]
补充一下细节吧，执行哪个sh命令，失效是指什么。另外，sh命令是不需要su插件的，默认就可以支持。

最好有对应的情景模式也发出来，提问题最好方便别人能直接理解问题，或者有案例可以直接测试。

**Comment by UISSD** [comment]
> 补充一下细节吧，执行哪个sh命令，失效是指什么。另外，sh命令是不需要su插件的，默认就可以支持。
> 
> 最好有对应的情景模式也发出来，提问题最好方便别人能直接理解问题，或者有案例可以直接测试。

任何sh命令, 本来像熄屏清理电池优化白名单的, 后来发现空命令都不能执行, magisk已经授权了
![903274713394178842](https://user-images.githubusercontent.com/36440730/168195446-79eba605-382e-4793-91a7-91f6705b338b.jpg)
![184530674282942870](https://user-images.githubusercontent.com/36440730/168195469-5e818632-8c47-44a4-a135-461d69d43b7a.jpg)
![140358272912804533](https://user-images.githubusercontent.com/36440730/168195484-589ee9c3-3ff7-48c5-88c5-45b2f2647118.jpg)

**Comment by UISSD** [comment]
> 补充一下细节吧，执行哪个sh命令，失效是指什么。另外，sh命令是不需要su插件的，默认就可以支持。
> 
> 最好有对应的情景模式也发出来，提问题最好方便别人能直接理解问题，或者有案例可以直接测试。

只有关闭SELinux(setenforce 0)才可以使用情景模式, 但是这样的话很多银行应用都使用不了, 很不方便

**Comment by Tornaco** [comment]
换成su.exe("xxx")行吗？

**Comment by UISSD** [comment]
> 换成su.exe("xxx")行吗？

不行, 和之前一样, 还是code=-1

**Comment by Tornaco** [comment]
> > 换成su.exe("xxx")行吗？
> 
> 不行, 和之前一样, 还是code=-1

换成su之后测试的日志发一下

**Comment by UISSD** [comment]
> > > 换成su.exe("xxx")行吗？
> > 
> > 
> > 不行, 和之前一样, 还是code=-1
> 
> 换成su之后测试的日志发一下

详细介绍看Readme.md
话说你这个log里面不会有什么敏感信息吧...
[Thanox log.zip](https://github.com/Tornaco/Thanox/files/8685914/Thanox.log.zip)
脚本内容:
`[
    {
        "name": "Screen off shell test",
        "description": "息屏Shell测试",
        "priority": 1,
        "condition": "screenOff == true",
        "actions": [
            "ui.showShortToast(sh.exe(\"su\"))"
        ]
    }
]`

**Comment by Tornaco** [comment]
```shell
[
    {
        "name": "Screen off shell test",
        "description": "息屏Shell测试",
        "priority": 1,
        "condition": "screenOff == true",
        "actions": [
            "ui.showShortToast(su.exe(\"ls\"))"
        ]
    }
]
```

你没理解su的意思。看下我发的例子。

**Comment by Tornaco** [comment]
@UISSD

**Comment by UISSD** [comment]
> ```shell
> [
>     {
>         "name": "Screen off shell test",
>         "description": "息屏Shell测试",
>         "priority": 1,
>         "condition": "screenOff == true",
>         "actions": [
>             "ui.showShortToast(su.exe(\"ls\"))"
>         ]
>     }
> ]
> ```
> 
> 你没理解su的意思。看下我发的例子。
[Thanox log.zip](https://github.com/Tornaco/Thanox/files/8686225/Thanox.log.zip)
用su.exe()测试了一遍, 详细介绍看Readme.md

**Comment by Tornaco** [comment]
@UISSD 你没装su插件？

**Comment by UISSD** [comment]
> @UISSD 你没装su插件？

这次装了
[Thanox log.zip](https://github.com/Tornaco/Thanox/files/8692333/Thanox.log.zip)

**Comment by Tornaco** [comment]
@UISSD 然后呢，su命令还是不能用吗？我看你的截图执行没问题了。

**Comment by UISSD** [comment]
嗯, 现在可以了
