### ISSUE TITLE
下列情景模式失效，有时候短时间内重复触发

### ISSUE THREAD

**Issue by woshicuimianshi** [Tornaco/Thanox#495]
**下列情景模式在开机大概10分钟后会失效，有时候短时间内重复触发**
[
{
"name": "QQ进程优化单进程",
"description": "从QQ离开后 结束多余的进程",
"priority": 2,
"condition": "frontPkgChanged == true && from == \"com.tencent.mobileqq\"",
"actions": [
"Thread.sleep(1000);",
"su.exe(\"ps -ef|grep com.tencent.mobileqq:|grep -v :MSF|grep -v grep|awk '{print $2}'|xargs kill -9\")",
"ui.showShortToast(\"[已清理QQ进程]\")"
]
}
]
---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本：MIUI13.05（SKHCNXM），红米K40
> 2. Thanox版本，补丁方式（Thanox 3.9.6-prc,xposed）
> 3. 问题现象的详细描述，有图或者视频更好
上述情景模式失效，有时候短时间内重复触发
> 4. 不激活thanox有问题吗？不激活按情景模式按钮Thanox会闪退
> 5. Thanox激活后不做任何配置有问题吗？不做任何配置无法判断情景模式
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里
[logging.zip](https://github.com/Tornaco/Thanox/files/8692373/logging.zip)

**Comment by MajoSissi** [comment]
@woshicuimianshi 短时间重复触发很明显自己写的代码问题。。。延迟之后直接操作也没判断

**Comment by woshicuimianshi** [comment]
> @woshicuimianshi 短时间重复触发很明显自己写的代码问题。。。延迟之后直接操作也没判断

经确认，是最新版的Zygisk—LSPosed（6555）版本有问题，回退6552版本LSPosed后正常，无此问题产生

**Comment by Tornaco** [comment]
建议使用delay属性来实现延迟功能，例如：
```
[
  {
    "name": "Delayed action example",
    "description": "Execute the action delay 2000 ms: show a short toast 2s after app switched.",
    "priority": 1,
    "delay": 2000,
    "condition": "frontPkgChanged == true",
    "actions": [
      "ui.showShortToast(\"App switched 2s ago to: \" + thanos.getPkgManager().getAppInfo(to).getAppLabel())"
    ]
  }
]
```
