### ISSUE TITLE
情景模式增加音频焦点判断

### ISSUE THREAD

**Issue by myflavor** [Tornaco/Thanox#497]
虽然有些app会在后台播放无声音乐，但是音频焦点始终只有一个，顺便问一下小窗，有没有办法正确识别

**Comment by Tornaco** [comment]
`顺便问一下小窗，有没有办法正确识别` 能具体一点吗？

**Comment by myflavor** [comment]
activityResumed和frontPkgChanged都无法正确识别到小窗应用和非小窗应用的切换，这个小窗可能是各家自己实现的，不知道能不能有实现的方式

**Comment by myflavor** [comment]
希望增加焦点判断的时候，顺便加一下，音频焦点取消和获取的条件，然后有两个变量，一个是获得焦点的应用包名，一个是被取消焦点的应用包名

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/338/workflows/cc486bf8-d0b4-4b6a-988f-a8186bfa6d36/jobs/314/artifacts

```
[
  {
    "name": "Watch Audio Focus",
    "description": "Show toast on audio focus changed",
    "priority": 2,
    "condition": "audioFocusChanged == true",
    "actions": [
      "ui.showShortToast(\"Audio\" + lastFocusedPkgNames + \"-->\" + currentFocusedPkgNames);"
    ]
  }
] 
```

### API

https://github.com/Tornaco/Thanox/blob/master/android/android_framework/base/src/main/java/github/tornaco/android/thanos/core/audio/AudioManager.java

**Comment by myflavor** [comment]
@Tornaco 我试试

**Comment by myflavor** [comment]
@Tornaco thanos.getAudioManager().hasAudioFocus(pkgName) 是这样用api吗

**Comment by myflavor** [comment]
@myflavor thanos.getAudioManager()无法获取AudioManager对象

**Comment by myflavor** [comment]
@Tornaco audioFocusChanged这个条件是能触发的，就是给的例子能正常

**Comment by Tornaco** [comment]
> @Tornaco audioFocusChanged这个条件是能触发的，就是给的例子能正常

忘了加get了，晚点加。

**Comment by myflavor** [comment]
@Tornaco 好勒

**Comment by myflavor** [comment]
@Tornaco 坐等

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/340/workflows/90f82469-858a-4b14-a50c-a35cb2476bd1/jobs/315/artifacts

@myflavor

**Comment by myflavor** [comment]
@Tornaco 测试可用
