### ISSUE TITLE
pro版更新后无限软重启

### ISSUE THREAD

**Issue by dan880201** [Tornaco/Thanox#499]
更新后无限软重启，卸载后正常开机，幸好有救砖
![Screenshot_2022-05-24-10-47-35-19.jpg](https://user-images.githubusercontent.com/104725507/169938544-2f34fe3a-b288-4aba-bee8-0fc693304665.jpg)
(https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/thanox-core.log)
(https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/verbose_2022-05-24T12:17:51.375.log)
(https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/thanox-init.log)
(https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/modules_2022-05-24T12:17:51.376.log)

**Comment by hanxin1997** [comment]
要不发日志，要不发一下生辰八字，作者帮你算一下。

**Comment by Tornaco** [comment]
传一下thanox日志，以及lsp日志吧。

**Comment by dan880201** [comment]
> 传一下thanox日志，以及lsp日志吧。
[]()https://github.com/dan880201/-/blob/3305b131f6d53b6c6f63ba683def79b68a64b020/modules_2022-05-24T12:17:51.376.log[]()https://github.com/dan880201/-/blob/3305b131f6d53b6c6f63ba683def79b68a64b020/thanox-core.log[]()https://raw.githubusercontent.com/dan880201/-/main/thanox-init.log?token=GHSAT0AAAAAABU4GZBIDXPSPBX77CVOCF7UYUMMPAQ

**Comment by dan880201** [comment]
> 传一下thanox日志，以及lsp日志吧。

[](https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/verbose_2022-05-24T12:17:51.375.log)

**Comment by dan880201** [comment]
> 传一下thanox日志，以及lsp日志吧。

https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/thanox-init.log

**Comment by dan880201** [comment]
> 传一下thanox日志，以及lsp日志吧。

[https://github.com/dan880201/123456/blob/19771358a8baa86d67a2f6b248f506767db75f03/modules_2022-05-24T12:17:51.376.log]()

**Comment by dan880201** [comment]
> 传一下thanox日志，以及lsp日志吧。

不会上传😂折腾半天传上来了帮看一下，

**Comment by Tornaco** [comment]
@dan880201 能不能把data/system/thanos_xxx_logging 整个文件夹压缩一下，发出来。你发的日志明显不全。

**Comment by dan880201** [comment]
> @dan880201 能不能把data/system/thanos_xxx_logging 整个文件夹压缩一下，发出来。你发的日志明显不全。

好的我去上传一下

**Comment by dan880201** [comment]
> @dan880201 能不能把data/system/thanos_xxx_logging 整个文件夹压缩一下，发出来。你发的日志明显不全。

(https://github.com/dan880201/123456/blob/6e1bdb77d8adfd2b46895f18c583397c2f1e1c06/logging.zip)

**Comment by Tornaco** [comment]
@dan880201 试试 这个版本，记得先把pro版本取消勾选。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/314/workflows/7d5a94af-89f8-4bd5-8388-decf85c8446b/jobs/291/artifacts

**Comment by dan880201** [comment]
> @dan880201 试试 这个版本，记得先把pro版本取消勾选。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/314/workflows/7d5a94af-89f8-4bd5-8388-decf85c8446b/jobs/291/artifacts

还是一样软重启，我发现重启开机到锁屏界面电池电量显示0几秒以后就会恢复，卸载以后开机是正常显示电量，

**Comment by dan880201** [comment]
> @dan880201 试试 这个版本，记得先把pro版本取消勾选。
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/314/workflows/7d5a94af-89f8-4bd5-8388-decf85c8446b/jobs/291/artifacts

我用回老版本了，老版本啥问题也没有

**Comment by Tornaco** [comment]
@dan880201 大概猜出原因了，等下在测试下。

**Comment by Tornaco** [comment]
[thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761016/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)


@dan880201 这个，需要解压

**Comment by dan880201** [comment]
> [thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761016/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)
> 
> 
> @dan880201 这个，需要解压

还是一样，电量显示0几秒后显示出来电量后就软重启

**Comment by dan880201** [comment]
> [thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761016/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)
> 
> 
> @dan880201 这个，需要解压

让你整了一下午了，别整了我还是用老版本得了，

**Comment by Tornaco** [comment]
[thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761315/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)

这个呢。。

@dan880201

**Comment by dan880201** [comment]
> [thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761315/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)
> 
> 这个呢。。
> 
> @dan880201 

这个没事了，没有重启

**Comment by dan880201** [comment]
> [thanox_3.9.7-3-8b4e186-dirty-prc(3061058).apk.zip](https://github.com/Tornaco/Thanox/files/8761315/thanox_3.9.7-3-8b4e186-dirty-prc.3061058.apk.zip)
> 
> 这个呢。。
> 
> @dan880201 

我没有国内版激活码，给我整个pro版啊大佬

**Comment by Tornaco** [comment]
请更新到3.9.8，没问题的话就关闭issue了。

**Comment by dan880201** [comment]
> 请更新到3.9.8，没问题的话就关闭issue了。
这个版本没问题了，谢谢了

**Comment by Tornaco** [comment]
@dan880201 帮忙验证下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/333/workflows/c10fb73f-13e2-4c60-99ff-750e7af06d23/jobs/309/artifacts 这个版本，近期有些改动不确定会不会再次出问题。

**Comment by dan880201** [comment]
> @dan880201 帮忙验证下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/333/workflows/c10fb73f-13e2-4c60-99ff-750e7af06d23/jobs/309/artifacts 这个版本，近期有些改动不确定会不会再次出问题。

这个版本没有问题，
