### ISSUE TITLE
手机有时候会异常卡住黑屏

### ISSUE THREAD

**Issue by dellevin** [Tornaco/Thanox#501]
大大，我手机是rog2，android11的有时候手机异常卡住黑屏，重启才能解决，或者是息屏等一会就会好。刚才我玩游戏的时候又出现了，时间是11：22-11：25的时候您能帮忙看一下么。我之前用3.6的时候没有问题。
我把thanox和lsp的俩日志发给您，您看看能解决一下么。。。。麻烦您啦~

lsp日志
[LSPosed_2022-05-25T11_29_45.146.zip](https://github.com/Tornaco/Thanox/files/8767785/LSPosed_2022-05-25T11_29_45.146.zip)
thanox日志
[thanos_MdaLJBiUpzjbJNUj.zip](https://github.com/Tornaco/Thanox/files/8767790/thanos_MdaLJBiUpzjbJNUj.zip)

android/data下面的thanox日志
[2022-05-25.zip](https://github.com/Tornaco/Thanox/files/8768230/2022-05-25.zip)

**Comment by Tornaco** [comment]
@E-Levin  /data/anr 下的日志文件，打包发下。

**Comment by dellevin** [comment]
> @E-Levin /data/anr 下的日志文件，打包发下。
[anr.zip](https://github.com/Tornaco/Thanox/files/8768380/anr.zip)

好啦！

**Comment by dellevin** [comment]
> @E-Levin /data/anr 下的日志文件，打包发下。



@Tornaco 刚才在14:19-14:21的时候又黑了一下...我看这个lsp里面有那个anr日志,您看看哈~
[LSPosed_2022-05-25T14_23_31.904.zip](https://github.com/Tornaco/Thanox/files/8768475/LSPosed_2022-05-25T14_23_31.904.zip)

这个是那个thanox的日志
[thanos_MdaLJBiUpzjbJNUj(1).zip](https://github.com/Tornaco/Thanox/files/8768490/thanos_MdaLJBiUpzjbJNUj.1.zip)

**Comment by Tornaco** [comment]
```
: FATAL EXCEPTION: DROPBOX_UPLOAD_THREAD
05-25 07:16:13.009  3464  3564 E AndroidRuntime: Process: com.android.systemui, PID: 3464
05-25 07:16:13.009  3464  3564 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 5854944 bytes
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.DropBoxManager.addText(DropBoxManager.java:305)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker.implementDropboxUpload(DropboxTracker.java:146)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker.access$000(DropboxTracker.java:38)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker$1.run(DropboxTracker.java:110)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 5854944 bytes
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.android.internal.os.IDropBoxManagerService$Stub$Proxy.add(IDropBoxManagerService.java:189)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.DropBoxManager.addText(DropBoxManager.java:298)
05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	... 4 more
05-25 07:16:13.562  1157  3570 D TelephonyRegistry: listen oscl: mHasNotifyS
```

根据目前的信息只能推测是systemui 挂了，日志里发现了几次ANR问题。现在还不确定是thanox还是其他原因导致，甚至怀疑是厂商代码的问题。

你再发下以下几个文件：
1. system/framework/framework.jar
2. SystemUI.apk

**Comment by dellevin** [comment]
> ```
> : FATAL EXCEPTION: DROPBOX_UPLOAD_THREAD
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: Process: com.android.systemui, PID: 3464
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 5854944 bytes
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.DropBoxManager.addText(DropBoxManager.java:305)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker.implementDropboxUpload(DropboxTracker.java:146)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker.access$000(DropboxTracker.java:38)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.asus.systemui.dropbox.DropboxTracker$1.run(DropboxTracker.java:110)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 5854944 bytes
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:540)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at com.android.internal.os.IDropBoxManagerService$Stub$Proxy.add(IDropBoxManagerService.java:189)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	at android.os.DropBoxManager.addText(DropBoxManager.java:298)
> 05-25 07:16:13.009  3464  3564 E AndroidRuntime: 	... 4 more
> 05-25 07:16:13.562  1157  3570 D TelephonyRegistry: listen oscl: mHasNotifyS
> ```
> 
> 根据目前的信息只能推测是systemui 挂了，日志里发现了几次ANR问题。现在还不确定是thanox还是其他原因导致，甚至怀疑是厂商代码的问题。
> 
> 你再发下以下几个文件：
> 
> 1. system/framework/framework.jar
> 2. SystemUI.apk



弄好啦，emmmm，大大，如果实在不行，咱别弄了，为了我这一个机型适配，有点不值呀。。。。我可以回退老版本的。。。这么麻烦你，我都不好意思了qwq。

ps：有时候我也觉得rog这个系统挺离谱的，但是打游戏是挺香的，要是麻烦的话就咱别弄了。。。用这手机的人挺少的


文件地址：
https://wonder1999.lanzouu.com/ioVto05flopg

**Comment by dellevin** [comment]
那个搞错了,这个是SystemUI.apk

文件(CNAsusSystemUI.apk)地址：
https://wonder1999.lanzouu.com/iPrkP05ieere

**Comment by Tornaco** [comment]
@E-Levin 看了下你发的SystemUI的代码，猜测是asus ROM上报一些事件导致的。

```java
 /* ASUS SystemUI.apk */
    public void implementDropboxUpload() {
        if (this.mDropboxRecordSharedPreferences != null && this.mDropBoxManager != null) {
            Iterator<String> it = this.mTagArray.iterator();
            while (it.hasNext()) {
                String next = it.next();
                if (this.mDropBoxManager.isTagEnabled(next)) {
                    String string = this.mDropboxRecordSharedPreferences.getString(next, "");
                    if (string.length() > 0) {
                        if (next.equals(DropboxUtils.TAG_CHARGING_TIME)) {
                            StringBuffer stringBuffer = new StringBuffer();
                            String sharedPreferenceData = getSharedPreferenceData(DropboxUtils.TAG_CHARGING_TIME);
                            stringBuffer.append("load ").append(DropboxUtils.TAG_CHARGING_TIME).append("=").append(sharedPreferenceData).append("|");
                            if (!sharedPreferenceData.isEmpty()) {
                                stringBuffer.append("save dropbox ").append(DropboxUtils.TAG_CHARGING_TIME).append("=").append(string).append("|");
                                this.mDropBoxManager.addText(next, DropboxUtils.encrypt(string));
                                stringBuffer.append("clear ").append(DropboxUtils.TAG_CHARGING_TIME);
                                updateSharedPreferenceData(DropboxUtils.TAG_CHARGING_TIME, "");
                            }
                            Log.d(DropboxUtils.DROPBOX_TAG, stringBuffer.toString());
                        } else {
                            if (next.equals(DropboxUtils.TAG_CHARGING_CNT)) {
                                updateSharedPreferenceData(DropboxUtils.TAG_CHARGE_INCREMENTAL_CNT, "");
                            }
                            this.mDropBoxManager.addText(next, DropboxUtils.encrypt(string));
                            updateSharedPreferenceData(next, "");
                        }
                    }
                }
            }
        }
    }
```



建议关闭这些事件上报，观察一段时间看看。

需要关闭的tag：

```
   public static final String TAG_AUDIO_PLUG = "audio_plug";
    public static final String TAG_CHARGE = "charge";
    public static final String TAG_CHARGE_INCREMENTAL_CNT = "charge_incrementa_cnt";
    public static final String TAG_CHARGE_START_TIME = "charge_start_time";
    public static final String TAG_CHARGING = "charging";
    public static final String TAG_CHARGING_CNT = "charging_cnt";
    public static final String TAG_CHARGING_TEMPARATURE = "charging_temparature";
    public static final String TAG_CHARGING_TIME = "charging_time";
    public static final String TAG_MOBILE_TRANSMIT_RATE = "mobile_transmit_rate";
    public static final String TAG_NET_WORK = "net_work";
    public static final String TAG_NOTIFICATION_ARRIVE = "notification_arrive";
    public static final String TAG_NOTIFICATION_CLICK = "notification_click";
    public static final String TAG_SIM_ENTER = "sim_enter";
    public static final String TAG_UPLOAD_TIME = "upload_time";
    public static final String TYPE_ETHERNET = "ethernet";
    public static final String TYPE_MOBILE = "mobile";
    public static final String TYPE_WIFI = "wifi";
    public static final String TYPE_WIGIG = "wigig";
```

每个tag依次执行以下命令
settings put global dropbox:$tag disabled
以`TAG_AUDIO_PLUG`为例：

```
settings put global dropbox:audio_plug disabled
```

**Comment by Tornaco** [comment]
如果不知道如何执行shell命令，可以在情景模式---Action console中输入以下命令：
```java
android.provider.Settings.Global.putString(context.getContentResolver(), "dropbox:audio_plug", "disabled")
```

**Comment by dellevin** [comment]
> @E-Levin 看了下你发的SystemUI的代码，猜测是asus ROM上报一些事件导致的。
> 
> ```java
>  /* ASUS SystemUI.apk */
>     public void implementDropboxUpload() {
>         if (this.mDropboxRecordSharedPreferences != null && this.mDropBoxManager != null) {
>             Iterator<String> it = this.mTagArray.iterator();
>             while (it.hasNext()) {
>                 String next = it.next();
>                 if (this.mDropBoxManager.isTagEnabled(next)) {
>                     String string = this.mDropboxRecordSharedPreferences.getString(next, "");
>                     if (string.length() > 0) {
>                         if (next.equals(DropboxUtils.TAG_CHARGING_TIME)) {
>                             StringBuffer stringBuffer = new StringBuffer();
>                             String sharedPreferenceData = getSharedPreferenceData(DropboxUtils.TAG_CHARGING_TIME);
>                             stringBuffer.append("load ").append(DropboxUtils.TAG_CHARGING_TIME).append("=").append(sharedPreferenceData).append("|");
>                             if (!sharedPreferenceData.isEmpty()) {
>                                 stringBuffer.append("save dropbox ").append(DropboxUtils.TAG_CHARGING_TIME).append("=").append(string).append("|");
>                                 this.mDropBoxManager.addText(next, DropboxUtils.encrypt(string));
>                                 stringBuffer.append("clear ").append(DropboxUtils.TAG_CHARGING_TIME);
>                                 updateSharedPreferenceData(DropboxUtils.TAG_CHARGING_TIME, "");
>                             }
>                             Log.d(DropboxUtils.DROPBOX_TAG, stringBuffer.toString());
>                         } else {
>                             if (next.equals(DropboxUtils.TAG_CHARGING_CNT)) {
>                                 updateSharedPreferenceData(DropboxUtils.TAG_CHARGE_INCREMENTAL_CNT, "");
>                             }
>                             this.mDropBoxManager.addText(next, DropboxUtils.encrypt(string));
>                             updateSharedPreferenceData(next, "");
>                         }
>                     }
>                 }
>             }
>         }
>     }
> ```
> 
> 建议关闭这些事件上报，观察一段时间看看。
> 
> 需要关闭的tag：
> 
> ```
>    public static final String TAG_AUDIO_PLUG = "audio_plug";
>     public static final String TAG_CHARGE = "charge";
>     public static final String TAG_CHARGE_INCREMENTAL_CNT = "charge_incrementa_cnt";
>     public static final String TAG_CHARGE_START_TIME = "charge_start_time";
>     public static final String TAG_CHARGING = "charging";
>     public static final String TAG_CHARGING_CNT = "charging_cnt";
>     public static final String TAG_CHARGING_TEMPARATURE = "charging_temparature";
>     public static final String TAG_CHARGING_TIME = "charging_time";
>     public static final String TAG_MOBILE_TRANSMIT_RATE = "mobile_transmit_rate";
>     public static final String TAG_NET_WORK = "net_work";
>     public static final String TAG_NOTIFICATION_ARRIVE = "notification_arrive";
>     public static final String TAG_NOTIFICATION_CLICK = "notification_click";
>     public static final String TAG_SIM_ENTER = "sim_enter";
>     public static final String TAG_UPLOAD_TIME = "upload_time";
>     public static final String TYPE_ETHERNET = "ethernet";
>     public static final String TYPE_MOBILE = "mobile";
>     public static final String TYPE_WIFI = "wifi";
>     public static final String TYPE_WIGIG = "wigig";
> ```
> 
> 每个tag依次执行以下命令 settings put global dropbox:$tag disabled 以`TAG_AUDIO_PLUG`为例：
> 
> ```
> settings put global dropbox:audio_plug disabled
> ```

 谢谢大大,今天用了半，没有出现任何问题
