### ISSUE TITLE
安卓10 crdROM会自动开启药丸导航栏功能

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#502]
lsp激活，版本 3.9.7-prc，安卓10，自动开启导航栏和药丸功能，回退到上一个版本则不会。
![Screenshot_20220525-164941423](https://user-images.githubusercontent.com/106238637/170234777-563bba22-d37d-48ac-8367-e45d6279dd78.jpg)
![Screenshot_20220525-164917_Nova_Launcher~(1)](https://user-images.githubusercontent.com/106238637/170234812-30d32950-3ca6-4a81-9367-2421ec5c83b9.jpg)
![Screenshot_20220525-165446163](https://user-images.githubusercontent.com/106238637/170234844-c9f7d4d3-c045-4b40-9f88-3823f257ae87.jpg)

>   ##`
[ thanox log.zip](https://github.com/Tornaco/Thanox/files/8769934/thanox.log.zip)
`

**Comment by diweisong** [comment]
#

>  @``
[ thanox log.zip](https://github.com/Tornaco/Thanox/files/8770021/thanox.log.zip)

**Comment by Tornaco** [comment]
@diweisong 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/315/workflows/3955855a-1a10-4a01-942d-1a08d106b008/jobs/292/artifacts

**Comment by Tornaco** [comment]
请更新到3.9.8，没问题的话就关闭issue了。
