### ISSUE TITLE
出现数字助理指示光标

### ISSUE THREAD

**Issue by HHH3366** [Tornaco/Thanox#503]
3.9.7版本更新以后强制出现数字助理指示光标（底下的两条白色弧线）（回桌面2秒消失，锁屏则常驻）
![Screenshot_20220525-211233_Nova_Ler](https://user-images.githubusercontent.com/51955828/170271362-61be4104-5adb-41ee-aa46-f5a640afc7bd.png)

**Comment by HHH3366** [comment]
另之前也有自动开启导航栏（占了导航栏的地方但操作依然是手势），下载别的issue里的修复版本好了

**Comment by Tornaco** [comment]
#502 应该是同一个问题。

**Comment by HHH3366** [comment]
用的就是那个issue里的修复版本，导航栏好了，数字助理没好（主要数字助理这个找不到开关，不用可以消）

**Comment by Tornaco** [comment]
请更新到3.9.8，没问题的话就关闭issue了。

**Comment by Tornaco** [comment]
@HHH3366  帮忙验证下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/333/workflows/c10fb73f-13e2-4c60-99ff-750e7af06d23/jobs/309/artifacts 这个版本，近期有些改动不确定会不会再次出问题。
