### ISSUE TITLE
状态栏磁贴异常。系统卡死

### ISSUE THREAD

**Issue by brownfo** [Tornaco/Thanox#505]
**Describe the bug（现象描述）**
1.状态栏下拉后所有磁贴都不能正常加载，且点击后也无反应。
2.设置应用打开后白屏。
3.很大几率自动息屏，有闪屏现象，有几率卡死。
4.手动重启会一直卡在正在重启的界面，实际并未关机。(用电源键开关屏，屏幕会相应亮熄屏。 )

**To Reproduce**（如何复现）
一直有这个现象。开机后放一会儿有概率加载出状态栏的磁贴，但一点击又会卡死

**Expected behavior**（期望结果）
期望开发者能修复一下，目前回退了上一版本，一切正常。

**Screenshots**（截图）
![Screenshot_2022-05-26-18-33-26-1390133805](https://user-images.githubusercontent.com/76164253/170506302-8f7d94cf-5f26-4ca8-b6a6-8bf328bd365c.png)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文
[logging.zip](https://github.com/Tornaco/Thanox/files/8779606/logging.zip)
件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）lsposed
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？没有
> 5. Thanox激活后不做任何配置有问题吗？有
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@brownfo “这个版本”和“上个版本”分别是哪个版本？

**Comment by Tornaco** [comment]
@brownfo lsp日志也发一下吧

**Comment by brownfo** [comment]
开发者，抱歉。本来版本信息是详细的，从手机复制到电脑后不知道怎么回事被清楚了。下面是补充
这个版本：3.9.8-1-72ef6f2-prc
thanox@tornaco:348b245d-88b1-4cb8-a493-dce5a9c3c4e6
Thu May 26 08:03:09 CST 2022
Mac OS X
上个版本：[thanox_3.9.7-prc.3061058.apk](https://github.com/Tornaco/Thanox/releases/download/v3.9.7/thanox_3.9.7-prc.3061058.apk)
lsposed log：
[LSPosed_2022-05-27T02_43_00.158.zip](https://github.com/Tornaco/Thanox/files/8791337/LSPosed_2022-05-27T02_43_00.158.zip)

**Comment by Tornaco** [comment]
@brownfo 你能确认下退上个版本3.9.7是OK的吗？

麻烦也试试，如果3.9.8-1-72ef6f2-prc 把情景模式功能关闭的话会好吗？

**Comment by Tornaco** [comment]
看了你的日志，大部分ANR的时候，都有一处可疑的日志，不知道是哪个模块（截图看NM日志.丝雨）。建议你把其他xposed模块取消激活再试试。

```
  at android.os.MessageQueue.nativePollOnce(Native method)
  at android.os.MessageQueue.next(MessageQueue.java:342)
  at android.os.Looper.loop(Looper.java:202)
  **at 截图看NM日志.丝雨.run(:1)**
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:259)
  at android.app.ActivityThread.main(ActivityThread.java:8067)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
```

**Comment by brownfo** [comment]
你好！
我能确认在3.9.7版本是正常是用的，我使用的模块是“NoANR”，在3.9.7版本无论是启用或是禁用“NoANR”，都没有这个issue里所反馈的问题，启用它时会导致蓝牙耳机断开音乐不暂停。
我在3.9.8-1-72ef6f2-prc 版本测试了
①禁用“NoANR”，开启情景模式，
②禁用“NoANR”，关闭情景模式，
③卸载“NoANR”，关闭情景模式，
均会产生issue里提到的问题。
下面是情景模式的代码：
[解冻 .txt](https://github.com/Tornaco/Thanox/files/8793027/default.txt)
[冻结.txt](https://github.com/Tornaco/Thanox/files/8793028/default.txt)
下面是最近的日志（3.9.7版本，卸载NoANR，关闭情景模式）：
[LSPosed_2022-05-29T17_31_31.968.zip](https://github.com/Tornaco/Thanox/files/8793029/LSPosed_2022-05-29T17_31_31.968.zip)
[logging.zip](https://github.com/Tornaco/Thanox/files/8793030/logging.zip)

**Comment by Tornaco** [comment]
@brownfo  试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/325/workflows/18dd60c6-7254-4cf8-91a1-955243c14ea0/jobs/301/artifacts

**Comment by brownfo** [comment]
@[Tornaco](https://github.com/Tornaco)这个还是和之前的一样的问题(卸载“NoANR”，关闭情景模式，):
[logging_1.zip](https://github.com/Tornaco/Thanox/files/8793736/logging_1.zip)
[LSPosed_2022-05-29T23_34_02.888_1.zip](https://github.com/Tornaco/Thanox/files/8793738/LSPosed_2022-05-29T23_34_02.888_1.zip)

**Comment by Tornaco** [comment]
OK，明天再试别的。

**Comment by brownfo** [comment]
> OK，明天再试别的。

好，麻烦你了

**Comment by Tornaco** [comment]
[thanox_3.9.8-13-67fc89a-dirty-prc(3061060).apk.zip](https://github.com/Tornaco/Thanox/files/8801216/thanox_3.9.8-13-67fc89a-dirty-prc.3061060.apk.zip)

@brownfo 再试试这个吧。

**Comment by brownfo** [comment]
> [thanox_3.9.8-13-67fc89a-dirty-prc(3061060).apk.zip](https://github.com/Tornaco/Thanox/files/8801216/thanox_3.9.8-13-67fc89a-dirty-prc.3061060.apk.zip)
> 
> @brownfo 再试试这个吧。

![Screenshot_2022-05-31-22-22-10-1112722757.png](https://user-images.githubusercontent.com/76164253/171197537-76a509c9-b653-4168-8c2d-02af8a56cf81.png)
还是不可以，每次都是一回退3.9.7就正常了

**Comment by Tornaco** [comment]
[thanox_3.9.8-16-a473224-dirty-prc(3061060).apk.zip](https://github.com/Tornaco/Thanox/files/8820028/thanox_3.9.8-16-a473224-dirty-prc.3061060.apk.zip)


@brownfo 麻烦再试试这个。

**Comment by brownfo** [comment]
> 
> [thanox_3.9.8-16-a473224-dirty-prc(3061060).apk.zip](https://github.com/Tornaco/Thanox/files/8820028/thanox_3.9.8-16-a473224-dirty-prc.3061060.apk.zip)
> 
> 
> @brownfo 麻烦再试试这个。

@Tornaco 
开发者你好！你发这个版本修好了![Screenshot_2022-06-02-16-06-30-0301500189.png](https://user-images.githubusercontent.com/76164253/171586118-ac677e7d-a97a-4c78-8913-dbf80e9ebda4.png)

**Comment by Tornaco** [comment]
@brownfo https://app.circleci.com/pipelines/github/Tornaco/Thanox/333/workflows/c10fb73f-13e2-4c60-99ff-750e7af06d23/jobs/309/artifacts

再试试CI上的版本吧，这个问题还挺难修复的。

**Comment by brownfo** [comment]
@Tornaco 应该是完全修好了！辛苦了！
[logging.zip](https://github.com/Tornaco/Thanox/files/8823257/logging.zip)
![Screenshot_2022-06-02-19-21-28-1833365124](https://user-images.githubusercontent.com/76164253/171619148-b26e5ed5-4974-47a1-9f93-8c531266aa9b.png)

**Comment by Tornaco** [comment]
https://github.com/Tornaco/Thanox/releases/tag/v3.9.9

@brownfo  关注下最新版是否正常，若没问题这个isssue就close了。

**Comment by brownfo** [comment]
> https://github.com/Tornaco/Thanox/releases/tag/v3.9.9
> 
> @brownfo  关注下最新版是否正常，若没问题这个isssue就close了。

一切正常，请关闭

**Comment by myflavor** [comment]
你主动关闭就行了啊
