### ISSUE TITLE
开屏使用乱杀后台

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#507]
开屏正在使用的手机，应用手动启动，手动切换的后台，挂一会儿经常会自动杀掉，貌似三个版本这样了。不知道是不是我的个例，但是之前的版本确实不会，求大佬分析分析。
后台启动或者后台运行导致的，把这俩关了就能挂住，开屏状态下，所有应用
安卓10，crdriod，lsp激活的xp模式，版本 3.9.8-1-72ef6f2-prc#
[log.zip](https://github.com/Tornaco/Thanox/files/8790095/log.zip)

**Comment by Tornaco** [comment]
@diweisong 你不说一下哪些应用可能被误杀了我怎么帮你分析？

**Comment by Tornaco** [comment]
补充详细信息后再open

**Comment by diweisong** [comment]
> @diweisong你不说一下有哪些可能被误杀了我怎么应用分析？

所有应用啊，挂不住后台，不知道是后台启动还是后台运行，把这两个关了，就能挂住了
[log.zip](https://github.com/Tornaco/Thanox/files/8790727/log.zip)

**Comment by diweisong** [comment]
> 补充详细信息打开
后台启动或者后台运行的，把这两个关了就能挂住。开屏使用状态

**Comment by Tornaco** [comment]
@diweisong 

你说**所有应用**还是没法帮你定位问题。

1. 必须提供你测试的应用，例如支付宝。
2. 提供你的配置信息，例如打开任务清理，并且支付宝勾选了任务清理。建议直接把你的配置备份发出来。

**Comment by diweisong** [comment]
> @diweisong
> 
> 你说**所有应用**还是不能帮你解决问题。
> 
> 1. 必须提供你测试的应用程序，例如支付宝。
> 2. 你的配置信息，例如打开任务清理，并支付宝勾选了任务清理。

[Thanox-Backup-2022-05-29-15_58_25.zip](https://github.com/Tornaco/Thanox/files/8792881/Thanox-Backup-2022-05-29-15_58_25.zip)

**Comment by Tornaco** [comment]
@diweisong 必须提供你测试的应用，例如支付宝。

**Comment by diweisong** [comment]
> @diweisong必须提供你测试的应用程序，例如支付宝。

微信

**Comment by Tornaco** [comment]
看了日志没发现误杀问题，建议你排查一下情景模式。
