### ISSUE TITLE
后台运行和后台启动乱杀

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#508]
开屏状态下所有应用（除白名单）经常挂不住后台，自动杀了，关闭这俩功能就好了
我也不知道是后台启动还是后台运行的问题了…
安卓10，crdroid，lsp激活，版本 3.9.8-1-72ef6f2-prc
[log.zip](https://github.com/Tornaco/Thanox/files/8790743/log.zip)

**Comment by Tornaco** [comment]
dup #507
