### ISSUE TITLE
[严重bug]变量无法重置直接叠加导致卡死闪退

### ISSUE THREAD

**Issue by Clorasun** [Tornaco/Thanox#510]
全局变量在原有基础上删掉之前的重选新应用变量会直接叠加，不会重置之前所删除的应用变量，导致三方应用变量甚至比手机本身三方应用数量还多。最终出现thanox卡死和系统无响应的情况。
相关thanox文件链接：https://www.123pan.com/s/CDzA-vvsOA

_使用 [FastHub-RE](https://github.com/LightDestory/FastHub-RE/) 从我的 meizu 18 Pro 发送_

**Comment by Tornaco** [comment]
@MRDQ123 麻烦按照复现步骤描述一下你的问题。另外你发的附件打开基本是空白的，麻烦check下。

**Comment by Clorasun** [comment]
@Tornaco OK

_使用 [FastHub-RE](https://github.com/LightDestory/FastHub-RE/) 从我的 meizu 18 Pro 发送_

**Comment by Clorasun** [comment]
@Tornaco一个视频演示一个日志，我看crash是有的，你那里是没传输上去？
 链接：https://www.123pan.com/s/CDzA-hvsOA

_使用 [FastHub-RE](https://github.com/LightDestory/FastHub-RE/) 从我的 meizu 18 Pro 发送_

**Comment by Tornaco** [comment]
@MRDQ123 基本问题已修复，测试下：https://app.circleci.com/pipelines/github/Tornaco/Thanox/330/workflows/f1882f80-9c93-425b-bdd1-9a04f36ac5d0/jobs/306/artifacts

**Comment by Tornaco** [comment]
为了修复三方系统上span字符全选删除导致的卡顿问题，把高亮功能关闭了。

**Comment by Clorasun** [comment]
测试了可行，没复现bug了。但全选之后上滑会无法停留至顶，解释一下大概是滑至顶部会弹下来，应该是触发了系统文本选择菜单导致的（这个算bug不）

**Comment by Clorasun** [comment]
@Tornaco 还有情景模式执行是不是有些bug，会出现情景延迟，无法实时响应情景模式的问题

**Comment by Tornaco** [comment]
> @Tornaco 还有情景模式执行是不是有些bug，会出现情景延迟，无法实时响应情景模式的问题

你把问题表述清晰再@我吧。完全不知道你再说什么，没有代码，没有现象描述。如果没问题可以关闭issue了。

**Comment by Clorasun** [comment]
@Tornaco 完全就是字面意思，无法描述的更清楚了，上视频，可以更直观。之前老版本是保活之类的情景模式比如thanox保活不弹toast不生效这个修复过了，现在是单纯的延迟响应，偶尔直接不起作用，划卡应用了有时才弹toast。
链接：https://www.123pan.com/s/CDzA-HvsOA

**Comment by Tornaco** [comment]
@MRDQ123 能用文字描述用文字描述，写清楚步骤，写清楚用的情景模式代码。看视频效率太低。

**Comment by Clorasun** [comment]
@Tornaco 就是情景模式变量idle是变量应用返回后台直接休眠，但并没有直接执行，会出现延迟甚至主动杀完后台了才弹休眠了，而黑域情景模式我调的是返回后台60秒直接查杀后台，也是一样的情况，我都主动杀后台了，过了很久才弹响应后台60秒杀掉后台了的toast，情景模式根本就没起到作用。我不知道是不是同时执行的情景模式过多还是啥导致的，情景模式的问题是不能立即响应，视频里主要想表示的就是我让几个应用直接去后台，但立刻休眠延迟没立刻执行，甚至直接不执行。感觉就是一个立即响应的情景一次性处理响应过多直接就是让整个情景模式瘫痪了，所有情景直接报废，等缓过来，我都自己主动杀完所有后台了，他才跑来弹toast，我休眠了，我查杀了，我保活了。这个过程中情景模式就是假执行，没起到作用。

**Comment by Tornaco** [comment]
@mryun135 你不发一下你的情景模式吗？我咋知道你都在情景模式里执行了什么操作呢？

**Comment by Tornaco** [comment]
@mryun135 还有问题描述只需要描述具体步骤和问题即可，不需要描述其他个人感觉，这对复现问题分析问题没什么帮助。

**Comment by Clorasun** [comment]
步骤就是让应用回后台，它自己不执行，视频演示的就是步骤
链接：https://www.123pan.com/s/CDzA-AvsOA
