### ISSUE TITLE
有无机会添加对Lspatch实验性支持？

### ISSUE THREAD

**Issue by LaplaceTor** [Tornaco/Thanox#514]
现阶段Lspatch有了一个像是太极的APP，可以对作用域内的APP进行动态配置，Thanox能检测到但由于没有识别到激活无法使用任何功能

**Comment by myflavor** [comment]
@LaplaceTor Lspatch不是无root的？怎么可能

**Comment by yu12an** [comment]
laspatch有免root的 但是不好使

**Comment by Tornaco** [comment]
@yu12an 无法实现，除非lspatch能作用补丁到framework/services.jar

**Comment by yu12an** [comment]
太极呢

**Comment by Tornaco** [comment]
@yu12an 一样的问题，能作用到系统就可以
