### ISSUE TITLE
谷歌paly版 Android13 5月版本 使用LSPosed1.8.3无法激活

### ISSUE THREAD

**Issue by Itxiaoniao** [Tornaco/Thanox#516]
谷歌paly版 Android13 5月版本 使用LSPosed无法激活
有什么办法吗？谢谢
Android12的版本没有问题

**Comment by Itxiaoniao** [comment]
![Screenshot_20220610-153431](https://user-images.githubusercontent.com/62528051/173014780-75951e3d-f63d-4ede-b39b-b6a58fe4429e.png)

**Comment by Itxiaoniao** [comment]
[LSPosed_2022-06-10T15_34_52.484848.zip](https://github.com/Tornaco/Thanox/files/8876828/LSPosed_2022-06-10T15_34_52.484848.zip)

**Comment by Tornaco** [comment]
@Itxiaoniao 试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/345/workflows/9d0cee6f-4f6a-4cac-a7cb-84bad747a9d9/jobs/318

自测可以激活，没有对全部功能进行测试。

**Comment by Itxiaoniao** [comment]
> @Itxiaoniao 试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/345/workflows/9d0cee6f-4f6a-4cac-a7cb-84bad747a9d9/jobs/318
> 
> 自测可以激活，没有对全部功能进行测试。

[thanox_3.9.9.2-3-a76236b-prc(3061063).apk](https://output.circle-artifacts.com/output/job/79cd256d-426e-4f22-bb1e-3e8b517d9910/artifacts/0/android/out/app/outputs/apk/prc/release/thanox_3.9.9.2-3-a76236b-prc%283061063%29.apk)
厉害，的确可以激活了，不过我的是play版Thanox pro，老大什么时候更新

**Comment by Tornaco** [comment]
Fixed. 请更新到4.0.0 beta。
