### ISSUE TITLE
任务清理 自启限制全部失效

### ISSUE THREAD

**Issue by STTecCEO** [Tornaco/Thanox#518]
**Describe the bug（现象描述）**
最新版本 Magisk/Lsposed激活 都已测试
后台启动/任务清理 在部分软件上失效（e.g. es文件管理器 淘宝 酷安 小红书 全民k歌）
Thanox现已无法阻止链式唤醒

**To Reproduce**（如何复现）
1，es文件管理器、淘宝 会在开机后自启，且启动方式为null/null，此时点开es并划掉卡片，其依然会留在缓存中并疯狂吃cpu；
2，点开小红书 会通过 igexin(个推) 拉起其他包含此sdk的app 且这些被拉起的app都已在Thanox关闭了后台启动选项；

**Screenshots**（截图）

![Screenshot_20220611-202800](https://user-images.githubusercontent.com/35169436/173190339-8f0df3f9-a9e5-46fd-b073-09d269fd75af.png)
![Screenshot_20220611-210107](https://user-images.githubusercontent.com/35169436/173190341-ff102f37-991a-4791-a840-7894e957cb4f.png)
![Screenshot_20220611-210112](https://user-images.githubusercontent.com/35169436/173190342-41981c0a-7f56-4918-ab28-30ca123b7a79.png)
![Screenshot_20220611-211008](https://user-images.githubusercontent.com/35169436/173190344-61ff00d7-e867-43a5-accd-cc2de366815f.png)
![Screenshot_20220611-213309](https://user-images.githubusercontent.com/35169436/173190345-b4db61b6-d4f8-4b30-b46e-04ac5ce53992.png)
![Screenshot_20220611-213315](https://user-images.githubusercontent.com/35169436/173190346-1925028f-da54-4ad1-b8fc-fbc20e943611.png)

**Version（发现问题的版本）:**
 - OS: Android 12
 - Version [v3.9.9.2]

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

[logging.zip](https://github.com/Tornaco/Thanox/files/8883996/logging.zip)

---------

**Comment by Tornaco** [comment]
@STTecCEO  

日志看了，目前没发现异常。

总结下你的描述，有2个问题：

1. es管理器划卡后，thanox未清理其后台，导致其一直在后台运行。
   **该问题需要你提供你的thanox配置文件，以确保你开启了任务清理功能，并打开了es管理器的清理。**

2. thanox无法拦截向日葵等app的关联启动。
   **该问题需要你在启动记录里，看下允许它启动的原因，这里是对照表：https://tornaco.github.io/Thanox/5-Start-Rules.html
   把原因也回复一下。另外建议先把启动记录清除再测试这个关联启动的问题，启动记录要看最早的第一条才能找到它被允许启动的原因。**

另外提供一下你的**机型信息**。

**Comment by STTecCEO** [comment]
**1，任务清理视频示例**

https://user-images.githubusercontent.com/35169436/173234995-0e790d81-8209-4266-8e8c-e3a8b0df5b6e.mp4
**配置文件**
[Thanox-Backup-2022-06-12-20_46_20.zip](https://github.com/Tornaco/Thanox/files/8885903/Thanox-Backup-2022-06-12-20_46_20.zip)
**log**
[logging.zip](https://github.com/Tornaco/Thanox/files/8885933/logging.zip)

2，原因在之前的截图中已显示 
**BY PASS DEFAULT 
且截图均为导致其自启的第一条记录**
（瞎折腾一番后复现不出这个原因了 现在原因是如下图 BY PASS UI PRESENT&BY PASS PROCESS RUNNING）
![Screenshot_20220612-204009](https://user-images.githubusercontent.com/35169436/173235284-995f864d-7fe2-4963-8b5a-b70240872709.png)
![Screenshot_20220612-203944](https://user-images.githubusercontent.com/35169436/173235287-b6277787-17f5-472d-9f64-0b31090dc328.png)
![Screenshot_20220612-203953](https://user-images.githubusercontent.com/35169436/173235288-8295e449-aad9-412e-9946-071f45a6f74c.png)
![Screenshot_20220612-204004](https://user-images.githubusercontent.com/35169436/173235290-3be68d93-b3fe-4759-b1d5-5cef9662c162.png)

以及开机自启未拦截的视频（两段均为刚开机 但原因不同）


https://user-images.githubusercontent.com/35169436/173235417-9d5483bf-d1b1-4924-b36e-924a05a9362c.mp4


https://user-images.githubusercontent.com/35169436/173236056-6514cdc1-b14e-46f1-bec6-5e3489744553.mp4

**Comment by STTecCEO** [comment]
机型是索尼xperia1Ⅲ 港版系统

**Comment by STTecCEO** [comment]
再补一个**链式唤醒失效**的log和复现视频
[链式唤醒log+视频复现.zip](https://github.com/Tornaco/Thanox/files/8887831/log%2B.zip)

**Comment by Tornaco** [comment]
@STTecCEO 很详细。我先看下日志，随后可能需要你来测试并继续抓日志。

**Comment by Tornaco** [comment]
[thanox_4.0.0-beta1-1-42f971e-prc(3070154).apk.zip](https://github.com/Tornaco/Thanox/files/8888744/thanox_4.0.0-beta1-1-42f971e-prc.3070154.apk.zip)


@STTecCEO 还是按照你的测试方式，用这个apk版本复现问题。这是debug版，抓了日志之后发上来我再看。


这次不需要视频了，文字描述你测试的app和现象即可。

**Comment by STTecCEO** [comment]
1，开机后发现全民K歌、wps自启，但一会儿后都被清理了
2，手动启动酷安、抖音、小红书，发现知乎、全民K歌、索尼中国自启
3，划掉所有卡片（酷安、抖音、小红书），回到Thanox发现其仍留在缓存中，且’已运行‘时间归零计算
4，点击Thanox的一键加速，所有测试app被正常清理
[logging(1).zip](https://github.com/Tornaco/Thanox/files/8889063/logging.1.zip)

**Comment by Tornaco** [comment]
@STTecCEO 日志看着版本不太对。确保要装我上面附件发的apk。另外最好手动把原来的日志都删除，重启后在测试。

**Comment by STTecCEO** [comment]
没装错 删日志又复现了一遍
1，开机后发现**全民K歌、知乎**自启，点击**Thanox一键加速**正常清理干净
2，手动启动酷安、抖音、小红书，发现知乎、全民K歌、索尼中国自启，再手动启动淘宝、京东
3，逐个划掉卡片（酷安、抖音、小红书、京东、淘宝），回到Thanox发现这些app（手动启动的和被关联唤醒的）仍留在缓存中，且被划掉卡片的app’已运行‘时间归零计算
4，点击Thanox的一键加速，所有app被正常清理
[logging(2).zip](https://github.com/Tornaco/Thanox/files/8901571/logging.2.zip)
![5246BE9ACECFC97771677EF7BD52D8FE](https://user-images.githubusercontent.com/35169436/173624463-0e197762-ef73-49c8-bcb0-8cac2cff0d99.png)

**Comment by Tornaco** [comment]
@STTecCEO 用lsp激活测试下吧，优先解决lsp补丁的问题。我看了日志目前是magisk补丁。

**Comment by STTecCEO** [comment]
1，开机后发现小红书、索尼中国、B616咔叽、wps、全民K歌自启，首条自启原因由magisk的**BY PASS PROCESS RUNNING**变为**BY PASS DEFAULT**，内容是**个推组件**，部分内容是**null/null**，点击Thanox一键加速正常清理干净
2，手动启动酷安、抖音、小红书，发现知乎、全民K歌、索尼中国自启，再手动启动淘宝、京东
3，逐个划掉卡片（酷安、抖音、小红书、京东、淘宝），回到Thanox发现大部分测试app（手动启动的和被关联唤醒的）仍留在缓存中，且被划掉卡片的app’已运行‘时间归零计算
4，点击Thanox的一键加速，所有app被正常清理，几秒后酷安自启
5，再次打开小红书，发现全民K歌自启（直接弹前台广告了）、索尼中国、wps等自启
6，划掉小红书，仍然留在后台中，且’已运行‘时间归零
[loggin.zip](https://github.com/Tornaco/Thanox/files/8905215/loggin.zip)

**Comment by Tornaco** [comment]
看起来是getui推出了新的的关联唤醒方案，用的是activity启动的方式。后续我尝试加一下新的路径拦截。

**Comment by STTecCEO** [comment]
那划卡清理失效的问题定位到了嘛

**Comment by Tornaco** [comment]
[thanox_4.0.0-beta1-4-02573c6-dirty-prc(3070154).apk.zip](https://github.com/Tornaco/Thanox/files/8925734/thanox_4.0.0-beta1-4-02573c6-dirty-prc.3070154.apk.zip)


试试这个版本，先分析解决启动问题。测试完了发下测试结果和对应日志。

@STTecCEO

**Comment by STTecCEO** [comment]
基本压死关联启动了，但还是有些小问题
1，开机自启还是存在
2，小概率出现null/null的关联唤醒不拦截（一次知乎拉小红书，一次小红书拉索尼中国）
[logging(6).zip](https://github.com/Tornaco/Thanox/files/8926153/logging.6.zip)
![5234402CB612B1995F9C66B9AF6628FB](https://user-images.githubusercontent.com/35169436/174265845-9e568e00-9d31-43d8-a229-cbafe851f2ba.jpg)

**Comment by Tornaco** [comment]
> 基本压死关联启动了，但还是有些小问题
> 1，开机自启还是存在
> 2，小概率出现null/null的关联唤醒不拦截（一次知乎拉小红书，一次小红书拉索尼中国）
> [logging(6).zip](https://github.com/Tornaco/Thanox/files/8926153/logging.6.zip)
> ![5234402CB612B1995F9C66B9AF6628FB](https://user-images.githubusercontent.com/35169436/174265845-9e568e00-9d31-43d8-a229-cbafe851f2ba.jpg)
> 
> 

lsp日志导出来发我看下吧

**Comment by Tornaco** [comment]
[thanox_4.0.0-beta1-5-125ed02-prc(3070154).apk.zip](https://github.com/Tornaco/Thanox/files/8927913/thanox_4.0.0-beta1-5-125ed02-prc.3070154.apk.zip)

@STTecCEO 又更新了一下拦截的类型，用这个再试试呢，这次除了thanox日志，lsp日志也导出一下。

**Comment by STTecCEO** [comment]
暂时没发现异常，所有功能都恢复了，大佬幸苦☕
[log.zip](https://github.com/Tornaco/Thanox/files/8928102/log.zip)

**Comment by Tornaco** [comment]
@STTecCEO OK, 明天可以验证下CI上的release版本：

https://app.circleci.com/pipelines/github/Tornaco/Thanox/350/workflows/392faf6e-f66d-4e75-ada2-f981cbb8d1c6/jobs/323/artifacts

当前还在构建中，预计20分钟。

**Comment by dreamy06** [comment]
thanox更新拦截的类型后，关闭APP的后台启动，然后通知栏无法通过MiPush推送打开对应APP；在此之前没问题，希望能放行

**Comment by STTecCEO** [comment]
似乎会和后台启动规则冲突，表现为通过su启动服务后（支付宝举例 am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService）允许然又后被拦截

ps. 是不是要通过su启动某应用的话 就只能打开允许后台启动？
![EBC3E9523ABD9BB3A76A6EC3253D4012](https://user-images.githubusercontent.com/35169436/174606751-e6b43603-0328-44d8-8c22-c01e58f78956.png)
![A9D03B67064428C86662000CE6886A9C](https://user-images.githubusercontent.com/35169436/174606767-b5603c25-5f55-41b7-82e2-317e68e7fd2a.png)
![7C4711963BF84A285FC3C101C4EF5FFB](https://user-images.githubusercontent.com/35169436/174606788-006ac46d-90f2-47b9-b7e0-7a88b60a2b34.png)
![0A1FD37C778B162FF4A661A4406A89FB](https://user-images.githubusercontent.com/35169436/174606799-50cd5aa5-835d-4d9d-a966-432e4c60436a.png)

**Comment by STTecCEO** [comment]
自启又出现了 这次无法手动复现 是无操作突然全部自启的 
[logging(7).zip](https://github.com/Tornaco/Thanox/files/8945556/logging.7.zip)
![1E5885036B005236B2101A4423E387A5](https://user-images.githubusercontent.com/35169436/174710821-ad7f51db-6c3d-4b73-bf6a-4c4a2870c93b.png)
![2D1703E945D861FAB3E1AC7EED9F349F](https://user-images.githubusercontent.com/35169436/174710831-f608cefc-21d7-412d-9aa1-889372ee57ea.png)
![4027FD1635B93C2420156C9D75B762DB](https://user-images.githubusercontent.com/35169436/174710834-23bf1ec3-ac54-4d3d-9195-e9c6c0d883b6.png)
![Screenshot_20220621-113640](https://user-images.githubusercontent.com/35169436/174711046-51ee6617-c874-4c31-9f92-5d86811c68d4.png)

**Comment by Tornaco** [comment]
> thanox更新拦截的类型后，关闭APP的后台启动，然后通知栏无法通过MiPush推送打开对应APP；在此之前没问题，希望能放行

用哪个app测试的？

**Comment by dreamy06** [comment]
> > thanox更新拦截的类型后，关闭APP的后台启动，然后通知栏无法通过MiPush推送打开对应APP；在此之前没问题，希望能放行
> 
> 用哪个app测试的？

例如：支付宝，用另一支付宝转账或发信息，这边收到推送，点击通知没反应，启动记录显示是被拦截。
![Screenshot_2022-06-21-04-05-14-321-edit_github tornaco android thanos](https://user-images.githubusercontent.com/36306588/174765820-b0b08a16-328d-4d8e-ae0c-cc0884f0a8f4.jpg)

**Comment by Tornaco** [comment]
> am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService

/system/framework/services.jar 发我下

**Comment by STTecCEO** [comment]
[services.zip](https://github.com/Tornaco/Thanox/files/8949967/services.zip)

**Comment by Tornaco** [comment]
> > > thanox更新拦截的类型后，关闭APP的后台启动，然后通知栏无法通过MiPush推送打开对应APP；在此之前没问题，希望能放行
> > 
> > 
> > 用哪个app测试的？
> 
> 例如：支付宝，用另一支付宝转账或发信息，这边收到推送，点击通知没反应，启动记录显示是被拦截。 ![Screenshot_2022-06-21-04-05-14-321-edit_github tornaco android thanos](https://user-images.githubusercontent.com/36306588/174765820-b0b08a16-328d-4d8e-ae0c-cc0884f0a8f4.jpg)

试试这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts

**Comment by Tornaco** [comment]
> 自启又出现了 这次无法手动复现 是无操作突然全部自启的 [logging(7).zip](https://github.com/Tornaco/Thanox/files/8945556/logging.7.zip) ![1E5885036B005236B2101A4423E387A5](https://user-images.githubusercontent.com/35169436/174710821-ad7f51db-6c3d-4b73-bf6a-4c4a2870c93b.png) ![2D1703E945D861FAB3E1AC7EED9F349F](https://user-images.githubusercontent.com/35169436/174710831-f608cefc-21d7-412d-9aa1-889372ee57ea.png) ![4027FD1635B93C2420156C9D75B762DB](https://user-images.githubusercontent.com/35169436/174710834-23bf1ec3-ac54-4d3d-9195-e9c6c0d883b6.png) ![Screenshot_20220621-113640](https://user-images.githubusercontent.com/35169436/174711046-51ee6617-c874-4c31-9f92-5d86811c68d4.png)


自启问题，再观察下这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts

**Comment by Tornaco** [comment]
> 似乎会和后台启动规则冲突，表现为通过su启动服务后（支付宝举例 am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService）允许然又后被拦截
> 
> ps. 是不是要通过su启动某应用的话 就只能打开允许后台启动？


@STTecCEO 

目前只能通过添加规则允许android启动某个服务：
```
ALLOW android com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService

```


注意：这个规则从下面这个版本开始才支持：
https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts

**Comment by dreamy06** [comment]
> > > > thanox更新拦截的类型后，关闭APP的后台启动，然后通知栏无法通过MiPush推送打开对应APP；在此之前没问题，希望能放行
> > > 
> > > 
> > > 用哪个app测试的？
> > 
> > 
> > 例如：支付宝，用另一支付宝转账或发信息，这边收到推送，点击通知没反应，启动记录显示是被拦截。 ![Screenshot_2022-06-21-04-05-14-321-edit_github tornaco android thanos](https://user-images.githubusercontent.com/36306588/174765820-b0b08a16-328d-4d8e-ae0c-cc0884f0a8f4.jpg)
> 
> 试试这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts

好喽，我这个没问题了，感谢。

**Comment by STTecCEO** [comment]
任务清理又失效了。。 酷安 小红书 饿了么
[log (2).zip](https://github.com/Tornaco/Thanox/files/9017932/log.2.zip)

**Comment by 849506054** [comment]
@STTecCEO 你试一下关闭 不清理音频 看看

**Comment by STTecCEO** [comment]
> 

没效果

**Comment by Tornaco** [comment]
> 任务清理又失效了。。 酷安 小红书 饿了么 [log (2).zip](https://github.com/Tornaco/Thanox/files/9017932/log.2.zip)

看日志小红薯，酷安已经被thanox forcestop了。你说的失效具体是什么现象。

```
2022-06-30 16:29:10.941 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.xingin.xhs, multipleTaskKeep? false
2022-06-30 16:29:10.942 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.xingin.xhs
2022-06-30 16:29:10.989 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.xingin.xhs', processName='com.xingin.xhs', pid=0, uid=10397}
2022-06-30 16:29:10.997 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.xingin.xhs', processName='com.xingin.xhs:pushservice', pid=0, uid=10397}
2022-06-30 16:29:10.999 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.xingin.xhs', processName='com.xingin.xhs:longlink', pid=0, uid=10397}
2022-06-30 16:29:11.001 W/Thanox-Core: forceStopPackage Package: com.xingin.xhs
```

**Comment by STTecCEO** [comment]
和之前反馈的一样
划卡之后应用变成只剩下一个进程存留在缓存中  已运行时间归零重新计算 
一键清理和锁屏清理都正常
![Screenshot_20220630-221707](https://user-images.githubusercontent.com/35169436/176700633-cb16fae8-3426-4823-accc-63697f7f35d6.png)

**Comment by Tornaco** [comment]
@STTecCEO @dreamy06  有空再试试这个，限制策略调整了一下，只给mipush通知点击加了白名单，其他一律拦截。另外针对某些毒瘤无法一次性杀死的情况，加了一些手段。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/385/workflows/27374455-9c42-4bb6-8f89-c4bf11777036/jobs/353/artifacts

**Comment by STTecCEO** [comment]
这下能清掉了

**Comment by STTecCEO** [comment]
> > 似乎会和后台启动规则冲突，表现为通过su启动服务后（支付宝举例 am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService）允许然又后被拦截
> > ps. 是不是要通过su启动某应用的话 就只能打开允许后台启动？
> 
> @STTecCEO
> 
> 目前只能通过添加规则允许android启动某个服务：
> 
> ```
> ALLOW android com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService
> ```
> 
> 注意：这个规则从下面这个版本开始才支持： https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts

但是这个白名单规则失效了😢

**Comment by Tornaco** [comment]
> > > 似乎会和后台启动规则冲突，表现为通过su启动服务后（支付宝举例 am start-foreground-service com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService）允许然又后被拦截
> > > ps. 是不是要通过su启动某应用的话 就只能打开允许后台启动？
> > 
> > 
> > @STTecCEO
> > 目前只能通过添加规则允许android启动某个服务：
> > ```
> > ALLOW android com.eg.android.AlipayGphone/com.alipay.android.launcher.service.LauncherService
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意：这个规则从下面这个版本开始才支持： https://app.circleci.com/pipelines/github/Tornaco/Thanox/358/workflows/e5210ed5-2cda-4098-96e6-040540201469/jobs/328/artifacts
> 
> 但是这个白名单规则失效了😢

问题不大，后面会加上规则判断。

**Comment by STTecCEO** [comment]
全民k歌又开始犯病了，启动小红书大概率拉起全民k歌..
![6BFA4CE90B4E9087380F26086A40C567](https://user-images.githubusercontent.com/35169436/183383491-c4e62d70-87ca-4720-be19-3df67abfe68c.png)
[server_logging.zip](https://github.com/Tornaco/Thanox/files/9280530/server_logging.zip)

**Comment by STTecCEO** [comment]
这毒瘤甚至已经从后台里隐藏了(通知还在状态栏里)
!
![Screenshot_20220816-210559](https://user-images.githubusercontent.com/35169436/184909001-e1eb01a4-49e3-4251-ba1b-0f4072adda24.png)
[Screenshot_20220816-210603](https://user-images.githubusercontent.com/35169436/184908972-76cf1ec2-4cf8-424e-8116-0397ae3d7e55.png)
![Screenshot_20220816-205901](https://user-images.githubusercontent.com/35169436/184908989-8706000e-4c56-48d1-98bc-1af425eb73f6.png)
![Screenshot_20220816-210621](https://user-images.githubusercontent.com/35169436/184908997-2c56553b-6d15-4bd6-bae4-334c478bafaa.png)
