### ISSUE TITLE
tiktok隐匿问题

### ISSUE THREAD

**Issue by fengyueZz233** [Tornaco/Thanox#519]
请问在magisk和xp两种不同模式下实现的**隐匿效果**是否有**差异**?

在xp模式下对tiktok启用隐匿,Lsp已勾选tiktok作用域,sim项设置为**jp**,打开tiktok刷出视频内容和评论基本以**美区**英文内容为主,以及出现红心**点赞视频消失**的问题

而在magisk模式下,启用同一份模板隐匿tiktok后,打开tiktok视频内容和评论区是正常的**日区**内容,点赞视频也会保存

**Comment by Tornaco** [comment]
@fengyueZz233 理论上没区别。我晚点找时间试试看。

**Comment by fengyueZz233** [comment]
通过issues搜索发现之前有同样的问题 #187
你回复在android10测试正常,我之前A11和A12/12.1都用过,xp模式下都是同样的问题
只是最近试了下magisk激活,隐匿后打开tiktok发现正常了
为了试验我从magisk换成xp问题复现,再换回magisk一切正常

**Comment by Tornaco** [comment]
@fengyueZz233 刚看了下代码，xp补丁少了一些hook，回头我补上你再试试。

**Comment by fengyueZz233** [comment]
@Tornaco ok 好了@下我

**Comment by Tornaco** [comment]
@fengyueZz233 https://app.circleci.com/pipelines/github/Tornaco/Thanox/352/workflows/2473af89-0ad3-4f93-a024-f326b4015378/jobs/325/artifacts

20min 后构建完成。

**Comment by fengyueZz233** [comment]
> @fengyueZz233 https://app.circleci.com/pipelines/github/Tornaco/Thanox/352/workflows/2473af89-0ad3-4f93-a024-f326b4015378/jobs/325/artifacts
> 
> 20分钟后制作完成。

辛苦大大 xp补丁激活问题都已解决
![20220618_102617-COLLAGE~2](https://user-images.githubusercontent.com/89948717/174419246-450b88f5-5a59-445c-8266-e6573d8a853e.jpg)
![Screenshot_2022_06_18_10_19_05_068_github_tornaco_android_thanos](https://user-images.githubusercontent.com/89948717/174419248-5bc9430d-093b-42cb-af7f-2430af4c2685.jpg)
![Screenshot_2022_06_18_10_22_02_333_com_zhiliaoapp_musically2](https://user-images.githubusercontent.com/89948717/174419249-9dcacdf8-2a6e-4d36-8a80-f9f87f549565.jpg)
