### ISSUE TITLE
crash日志

### ISSUE THREAD

**Issue by Clorasun** [Tornaco/Thanox#520]
情景黑域检测后台查杀，常出现切换其他应用再返回应用，应用在前台被杀的情况
Document:一个日志，一个情景模式，
https://1drv.ms/u/s!AjYcMS1eD4bblngwK9WqXp4GGNY2
https://1drv.ms/u/s!AjYcMS1eD4bblnI3mUbr9LtYYlZ1
App version:4.0.0-beta1-row
Systeam:Flyme 9.2.5.3A

**Comment by diweisong** [comment]
我的手动挂着后台也经常被杀，你试着关闭后台启动试试看，有时候用着当前的应用，后台的应用就被杀掉了。

**Comment by STTecCEO** [comment]
> 我的手动挂着后台也经常被杀，你试着关闭后台启动试试看，有时候用着当前的应用，后台的应用就被杀掉了。

我也经常遇到前台莫名其妙消失的问题 连卡片都没了 一直不知道是哪里整的

**Comment by Tornaco** [comment]
Fixed
