### ISSUE TITLE
后台启动自动杀后台是不是BUG

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#524]
手动启动的应用挂在后台，正在使用其他应用，偶尔会把挂在后台的应用杀掉，挂不住后台，把这个功能关了就好了，之前也有遇到
安卓10
LSPosed-v1.8.3-6552-zygisk-release激活
版本 4.0.0-beta2-2-8b3dc27-prc
![Screenshot_20220623-082549847](https://user-images.githubusercontent.com/106238637/175188461-3ca07c4b-8e77-4b8a-a7a9-577f549a7f3b.jpg)
[logging.zip](https://github.com/Tornaco/Thanox/files/8962898/logging.zip)

**Comment by Tornaco** [comment]
你测试的哪个应用被杀了？不说哪个应用没法分析。

**Comment by Tornaco** [comment]
另外补充一下lsp日志吧，具体什么原因被杀可能性太多了，不确定能定位。

**Comment by diweisong** [comment]
> 你测试的哪个应用被杀了？不说哪个应用没法分析。

图片上的这些应用都被杀过，它是一次性全杀的，只剩下我前台正在浏览使用的应用，这些应用当时都在挂着后台的，微信，闲鱼，MT管理器，哔哩哔哩，蜜蜂便签……手机上的应用都被杀过

**Comment by diweisong** [comment]
> 另外补充一下lsp日志吧，具体什么原因被杀可能性太多了，不确定能定位。

[LSPosed_2022-06-23T09_42_16.335.zip](https://github.com/Tornaco/Thanox/files/8962940/LSPosed_2022-06-23T09_42_16.335.zip)

**Comment by diweisong** [comment]
> 另外补充一下吧，具体什么原因可以杀了，我能引起注意。

就是把应用挂在后台，在使用其他的应用当中就突然杀掉了。
lsp详细日志
[LSPosed_2022-06-23T09_45_10.566.zip](https://github.com/Tornaco/Thanox/files/8962960/LSPosed_2022-06-23T09_45_10.566.zip)
lsp模块日志
[LSPosed_2022-06-23T09_42_16.335.zip](https://github.com/Tornaco/Thanox/files/8962963/LSPosed_2022-06-23T09_42_16.335.zip)

**Comment by Tornaco** [comment]
从你给的日志看，目前得出的信息如下：

你的Nova launcher出现多次类似重启的情况，可能正因为此原因，多个测试app（mt、bilibili等）的最近任务被清理。你应该是对这些测试app开启了“任务清理”，因此thanox会杀死这些app。

因此你可能需要排查下Nova launcher是否有什么使用或配置上的问题。

另外，你可以搜索thanox日志中的关键字，查看日志上下文，以定位thanox杀死app的原因：`forceStopPackage Package`

下面是你的测试app被杀死的一段日志：
```
2022-06-22 09:08:44.367 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
2022-06-22 09:08:44.368 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.sankuai.meituan', userId=10}
2022-06-22 09:08:44.398 W/Thanox-Core: ActivityStartHookV29 aboutToStartActivityIntent, activityInfo: ActivityInfo{5208a79 com.teslacoilsw.launcher.NovaLauncher}
2022-06-22 09:08:44.398 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkg: Pkg{pkgName='com.teslacoilsw.launcher', userId=0}
2022-06-22 09:08:44.416 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.sankuai.meituan', userId=10}, hasRecentTaskForPkg? false
2022-06-22 09:08:44.416 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
2022-06-22 09:08:44.417 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.tencent.mm, multipleTaskKeep? false
2022-06-22 09:08:44.440 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.tencent.mm
2022-06-22 09:08:44.443 W/Thanox-Core: onTaskRemovingInternal: task pkg is: bin.mt.plus, multipleTaskKeep? false
2022-06-22 09:08:44.466 W/Thanox-Core: onTaskRemovingInternal: will force stop: bin.mt.plus
2022-06-22 09:08:44.468 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.One.WoodenLetter, multipleTaskKeep? false
2022-06-22 09:08:44.471 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.One.WoodenLetter
2022-06-22 09:08:44.472 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.teslacoilsw.launcher/.NovaLauncher }
2022-06-22 09:08:44.473 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.appbyme.app177150, multipleTaskKeep? false
2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.appbyme.app177150
2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.oasisfeng.greenify, multipleTaskKeep? false
2022-06-22 09:08:44.475 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.tencent.mm', userId=12}
2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.tencent.mm', userId=12}, hasRecentTaskForPkg? false
2022-06-22 09:08:44.480 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:push', pid=0, uid=10294}
2022-06-22 09:08:44.504 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm', pid=0, uid=10294}
2022-06-22 09:08:44.529 W/Thanox-Core: forceStopPackage Package: com.tencent.mm
```

**Comment by diweisong** [comment]
> 从你给的日志看，目前得出的信息如下：
> 
> 你的Nova launcher出现多次类似重启的情况，可能正因为此原因，多个测试app（mt、bilibili等）的最近任务被清理。你应该是对这些测试app开启了“任务清理”，因此thanox会杀死这些app。
> 
> 因此你可能需要排查下Nova launcher是否有什么使用或配置上的问题。
> 
> 另外，你可以搜索thanox日志中的关键字，查看日志上下文，以定位thanox杀死app的原因：`forceStopPackage Package`
> 
> 下面是你的测试app被杀死的一段日志：
> 
> ```
> 2022-06-22 09:08:44.367 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.368 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.sankuai.meituan', userId=10}
> 2022-06-22 09:08:44.398 W/Thanox-Core: ActivityStartHookV29 aboutToStartActivityIntent, activityInfo: ActivityInfo{5208a79 com.teslacoilsw.launcher.NovaLauncher}
> 2022-06-22 09:08:44.398 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkg: Pkg{pkgName='com.teslacoilsw.launcher', userId=0}
> 2022-06-22 09:08:44.416 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.sankuai.meituan', userId=10}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.416 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.417 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.tencent.mm, multipleTaskKeep? false
> 2022-06-22 09:08:44.440 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.tencent.mm
> 2022-06-22 09:08:44.443 W/Thanox-Core: onTaskRemovingInternal: task pkg is: bin.mt.plus, multipleTaskKeep? false
> 2022-06-22 09:08:44.466 W/Thanox-Core: onTaskRemovingInternal: will force stop: bin.mt.plus
> 2022-06-22 09:08:44.468 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.One.WoodenLetter, multipleTaskKeep? false
> 2022-06-22 09:08:44.471 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.One.WoodenLetter
> 2022-06-22 09:08:44.472 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.teslacoilsw.launcher/.NovaLauncher }
> 2022-06-22 09:08:44.473 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.appbyme.app177150, multipleTaskKeep? false
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.appbyme.app177150
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.oasisfeng.greenify, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.tencent.mm', userId=12}
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.tencent.mm', userId=12}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.480 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:push', pid=0, uid=10294}
> 2022-06-22 09:08:44.504 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm', pid=0, uid=10294}
> 2022-06-22 09:08:44.529 W/Thanox-Core: forceStopPackage Package: com.tencent.mm
> ```
我设置一下nova权限试试看，forceStopPackage Package` 后面的原因怎么查看？

**Comment by diweisong** [comment]
> 从你给的日志看，目前的结果信息如下：
> 
> 你的 Nova 启动器应用程序经常出现类似重启的情况，可能因为这个原因，多个测试（mt、bilibili 等）的最近任务被清理。你应该是对这些测试应用程序进行了“任务清理”，因此thanox会导致这些应用程序。
> 
> 因此你可能需要排查下 Nova 发射器是否有什么使用或配置上的问题。
> 
> 另外，你可以搜索thanox杀戮应用程序的关键字，查看日志时间原因，以解决thanox杀戮应用的日志：`forceStopPackage Package`
> 
> 下面是你的测试应用被杀死的一段日志：
> 
> ```
> 2022-06-22 09:08:44.367 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.368 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.sankuai.meituan', userId=10}
> 2022-06-22 09:08:44.398 W/Thanox-Core: ActivityStartHookV29 aboutToStartActivityIntent, activityInfo: ActivityInfo{5208a79 com.teslacoilsw.launcher.NovaLauncher}
> 2022-06-22 09:08:44.398 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkg: Pkg{pkgName='com.teslacoilsw.launcher', userId=0}
> 2022-06-22 09:08:44.416 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.sankuai.meituan', userId=10}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.416 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.417 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.tencent.mm, multipleTaskKeep? false
> 2022-06-22 09:08:44.440 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.tencent.mm
> 2022-06-22 09:08:44.443 W/Thanox-Core: onTaskRemovingInternal: task pkg is: bin.mt.plus, multipleTaskKeep? false
> 2022-06-22 09:08:44.466 W/Thanox-Core: onTaskRemovingInternal: will force stop: bin.mt.plus
> 2022-06-22 09:08:44.468 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.One.WoodenLetter, multipleTaskKeep? false
> 2022-06-22 09:08:44.471 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.One.WoodenLetter
> 2022-06-22 09:08:44.472 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.teslacoilsw.launcher/.NovaLauncher }
> 2022-06-22 09:08:44.473 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.appbyme.app177150, multipleTaskKeep? false
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.appbyme.app177150
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.oasisfeng.greenify, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.tencent.mm', userId=12}
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.tencent.mm', userId=12}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.480 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:push', pid=0, uid=10294}
> 2022-06-22 09:08:44.504 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm', pid=0, uid=10294}
> 2022-06-22 09:08:44.529 W/Thanox-Core: forceStopPackage Package: com.tencent.mm
> 

> 从你给的日志看，目前得出的信息如下：
> 
> 你的Nova launcher出现多次类似重启的情况，可能正因为此原因，多个测试app（mt、bilibili等）的最近任务被清理。你应该是对这些测试app开启了“任务清理”，因此thanox会杀死这些app。
> 
> 因此你可能需要排查下Nova launcher是否有什么使用或配置上的问题。
> 
> 另外，你可以搜索thanox日志中的关键字，查看日志上下文，以定位thanox杀死app的原因：`forceStopPackage Package`
> 
> 下面是你的测试app被杀死的一段日志：
> 
> ```
> 2022-06-22 09:08:44.367 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.368 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.sankuai.meituan', userId=10}
> 2022-06-22 09:08:44.398 W/Thanox-Core: ActivityStartHookV29 aboutToStartActivityIntent, activityInfo: ActivityInfo{5208a79 com.teslacoilsw.launcher.NovaLauncher}
> 2022-06-22 09:08:44.398 W/Thanox-Core: mayEnableAppOnStartActivityIntent pkg: Pkg{pkgName='com.teslacoilsw.launcher', userId=0}
> 2022-06-22 09:08:44.416 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.sankuai.meituan', userId=10}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.416 W/Thanox-Core: onTaskRemovingInternal, user is not current, will not clear tasks.
> 2022-06-22 09:08:44.417 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.tencent.mm, multipleTaskKeep? false
> 2022-06-22 09:08:44.440 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.tencent.mm
> 2022-06-22 09:08:44.443 W/Thanox-Core: onTaskRemovingInternal: task pkg is: bin.mt.plus, multipleTaskKeep? false
> 2022-06-22 09:08:44.466 W/Thanox-Core: onTaskRemovingInternal: will force stop: bin.mt.plus
> 2022-06-22 09:08:44.468 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.One.WoodenLetter, multipleTaskKeep? false
> 2022-06-22 09:08:44.471 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.One.WoodenLetter
> 2022-06-22 09:08:44.472 W/Thanox-Core: reportOnActivityResumed: Intent { cmp=com.teslacoilsw.launcher/.NovaLauncher }
> 2022-06-22 09:08:44.473 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.appbyme.app177150, multipleTaskKeep? false
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: will force stop: com.appbyme.app177150
> 2022-06-22 09:08:44.474 W/Thanox-Core: onTaskRemovingInternal: task pkg is: com.oasisfeng.greenify, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onTaskRemovingInternal: task pkg is: github.tornaco.android.thanos, multipleTaskKeep? false
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: Pkg{pkgName='com.tencent.mm', userId=12}
> 2022-06-22 09:08:44.475 W/Thanox-Core: onPkgTaskRemovedInternal: task pkg is: Pkg{pkgName='com.tencent.mm', userId=12}, hasRecentTaskForPkg? false
> 2022-06-22 09:08:44.480 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm:push', pid=0, uid=10294}
> 2022-06-22 09:08:44.504 W/Thanox-Core: AMS onProcessRemovedInternal: ProcessRecord{packageName='com.tencent.mm', processName='com.tencent.mm', pid=0, uid=10294}
> 2022-06-22 09:08:44.529 W/Thanox-Core: forceStopPackage Package: com.tencent.mm
> ```

测试过了，跟nova没关，晚上到凌晨又触发了几次，关掉后台启动就不杀，再看看？
04:55，关闭自启也突然杀掉后台，这下看不懂了，不知道什么导致的。
[logging.zip](https://github.com/Tornaco/Thanox/files/8970482/logging.zip)

**Comment by Tornaco** [comment]
@diweisong  日志里显示还是 最近任务 被清除，触发了任务清理。

下次你可以自己看下日志，直接定位到`forceStopPackage Package` 这行日志上下都有清晰的日志表明原因。

**Comment by diweisong** [comment]
> @diweisong 日志里显示还是 最近任务 被清除，触发了任务清理。
> 
> 下次你可以自己看下日志，直接定位到`forceStopPackage Package` 这行日志上下都有清晰的日志表明原因。

问题是我没动最近任务，意味着我没划卡它自己杀了，判定是不是有问题？
现在把任务清理关了，换成黑阈确实不杀了
这是杀完之后的日志
[logging.zip](https://github.com/Tornaco/Thanox/files/8984273/logging.zip)
这是关闭任务清理之后的日志
[logging (1).zip](https://github.com/Tornaco/Thanox/files/8984275/logging.1.zip)

**Comment by Tornaco** [comment]
> > @diweisong 日志里显示还是 最近任务 被清除，触发了任务清理。
> > 
> > 下次你可以自己看下日志，直接定位到`forceStopPackage Package` 这行日志上下都有清晰的日志表明原因。
> 
> 问题是我没动最近任务，意味着我没划卡它自己杀了，判定是不是有问题？
> 现在把任务清理关了，换成黑阈确实不杀了
> 这是杀完之后的日志
> [logging.zip](https://github.com/Tornaco/Thanox/files/8984273/logging.zip)
> 这是关闭任务清理之后的日志
> [logging (1).zip](https://github.com/Tornaco/Thanox/files/8984275/logging.1.zip)
> 
> 

不清楚你的系统为何会触发任务被移除的事件。目前这个问题还没有其他人报告。

**Comment by diweisong** [comment]
> > > @diweisong 日志里显示还是 最近任务 被清除，触发了任务清理。
> > > 下次你可以自己看下日志，直接定位到`forceStopPackage Package` 这行日志上下都有清晰的日志表明原因。
> > 
> > 
> > 问题是我没动最近任务，意味着我没划卡它自己杀了，判定是不是有问题？
> > 现在把任务清理关了，换成黑阈确实不杀了
> > 这是杀完之后的日志
> > [logging.zip](https://github.com/Tornaco/Thanox/files/8984273/logging.zip)
> > 这是关闭任务清理之后的日志
> > [logging (1).zip](https://github.com/Tornaco/Thanox/files/8984275/logging.1.zip)
> 
> 不清楚你的系统为何会触发任务被移除的事件。目前这个问题还没有其他人报告。

遇到几个类似的杀后台，我记得之前也不会，忘记从哪个版本后开始就这样了，之前一直以为是后台启动，然后你给我指明了说是任务清理，现在把这个关了就好了。能不能弄一弄😂

**Comment by STTecCEO** [comment]
遇到个类似的 前台被杀 启动器是lawnchair
出现在app使用时 或者从其他app上滑后台切换到此app时
具体表现为使用时app突然消失并回到桌面 后台中也没有此app的卡片
或切换最近任务时 点击此app的后台卡片 出现极快的上滑卡片动画 被杀掉 并回到桌面 
此时其他app正常
也不知道是不是启动器的原因
[lawn.txt](https://github.com/Tornaco/Thanox/files/8984717/lawn.txt)

**Comment by Tornaco** [comment]
[thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8984787/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)


@diweisong  用这个版本测试个半天，把日志发给我。我在里面加了一些日志，不确定能不能找到什么线索。

另外，把你的ROM信息，以及 system/framework/services.jar 发一下。

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8984787/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> @diweisong 用这个版本测试个半天，把日志发给我。我在里面加了一些日志，不确定能不能找到什么线索。
> 
> 另外，把你的ROM信息，以及 system/framework/services.jar 发一下。

好，测试可能需要一两天。
![Screenshot_20220625-224530059](https://user-images.githubusercontent.com/106238637/175778643-a2501ee3-9687-4bf8-a4ba-78d070a5f5e1.jpg)
[services.zip](https://github.com/Tornaco/Thanox/files/8984956/services.zip)

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8984787/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> @diweisong 用这个版本测试个半天，把日志发给我。我在里面加了一些日志，不确定能不能找到什么线索。
> 
> 另外，把你的ROM信息，以及 system/framework/services.jar 发一下。

关掉黑阈，开启任务清理，又杀了两三次，日志应该有记录，如果不够我再测一两天。
[logging.zip](https://github.com/Tornaco/Thanox/files/8985332/logging.zip)

**Comment by Tornaco** [comment]
@diweisong  system/framework/framework.jar 也发下

**Comment by Tornaco** [comment]
[thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)

再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。

**Comment by diweisong** [comment]
> @diweisong system/framework/framework.jar 也发下

[framework.zip](https://github.com/Tornaco/Thanox/files/8985999/framework.zip)

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。

好的

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。
凌晨4点10分左右，最近任务预览界面，微信，clash，youtube被杀，没有息屏，返回桌面一会没有操作，纯后台的谷歌服务，就是没有最近任务界面的那种好像也被杀了
[logging.zip](https://github.com/Tornaco/Thanox/files/8987400/logging.zip)

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。

如果不杀了，可以把桌面和ui从作用域移除吗

**Comment by diweisong** [comment]
> [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> 
> 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。

凌晨4点40左右再次被杀，clash，youtube，后台运行没有打勾的也被杀了，未息屏，clash计时我是马上手动启动了。具体如图
[logging (1).zip](https://github.com/Tornaco/Thanox/files/8987485/logging.1.zip)
![Screenshot_20220627-044111655](https://user-images.githubusercontent.com/106238637/175833387-03113219-a017-455e-870f-22dcfc5e4a4a.jpg)

**Comment by Tornaco** [comment]
@diweisong 忘了说了，lsp日志也要

**Comment by Tornaco** [comment]
> > [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> > 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。
> 
> 凌晨4点40左右再次被杀，clash，youtube，后台运行没有打勾的也被杀了，未息屏，clash计时我是马上手动启动了。具体如图 [logging (1).zip](https://github.com/Tornaco/Thanox/files/8987485/logging.1.zip) ![Screenshot_20220627-044111655](https://user-images.githubusercontent.com/106238637/175833387-03113219-a017-455e-870f-22dcfc5e4a4a.jpg)

这次的4:40左右日志，看起来可能跟锁屏清理的延迟处理逻辑有关，抽空我会改一下，你在测测。

**Comment by diweisong** [comment]
> > > [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> > > 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。
> > 
> > 
> > 凌晨4点40左右再次被杀，clash，youtube，后台运行没有打勾的也被杀了，未息屏，clash计时我是马上手动启动了。具体如图 [logging (1).zip](https://github.com/Tornaco/Thanox/files/8987485/logging.1.zip) ![Screenshot_20220627-044111655](https://user-images.githubusercontent.com/106238637/175833387-03113219-a017-455e-870f-22dcfc5e4a4a.jpg)
> 
> 这次的4:40左右日志，看起来可能跟锁屏清理的延迟处理逻辑有关，抽空我会改一下，你在测测。

四点左右遇到的两次杀掉好像都是因为这个，因为后台运行勾选了的始终在运行，没有勾选的都杀掉了。下次遇上我会附上lsp日志，现在需要的话也可以提供

**Comment by diweisong** [comment]
> > > [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> > > 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。
> > 
> > 
> > 凌晨4点40左右再次被杀，clash，youtube，后台运行没有打勾的也被杀了，未息屏，clash计时我是马上手动启动了。具体如图 [logging (1).zip](https://github.com/Tornaco/Thanox/files/8987485/logging.1.zip) ![Screenshot_20220627-044111655](https://user-images.githubusercontent.com/106238637/175833387-03113219-a017-455e-870f-22dcfc5e4a4a.jpg)
> 
> 这次的4:40左右日志，看起来可能跟锁屏清理的延迟处理逻辑有关，抽空我会改一下，你在测测。

下午挂着微信被杀，就开了微信+皮皮虾
[06271550微信被杀.zip](https://github.com/Tornaco/Thanox/files/8989740/06271550.zip)
[LSP微信被杀模块日志_2022-06-27T15_52_43.160.zip](https://github.com/Tornaco/Thanox/files/8989744/LSP._2022-06-27T15_52_43.160.zip)
[LSP微信被杀详细日志_2022-06-27T15_53_02.116.zip](https://github.com/Tornaco/Thanox/files/8989748/LSP._2022-06-27T15_53_02.116.zip)

**Comment by diweisong** [comment]
> > > [thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc(3070156).apk.zip](https://github.com/Tornaco/Thanox/files/8985967/thanox_4.0.0-beta3-5-7cf8ae4-dirty-prc.3070156.apk.zip)
> > > 再测试下这个包，注意：lsp里勾线Launcher和SystemUI作用域。回头日志再发下。
> > 
> > 
> > 凌晨4点40左右再次被杀，clash，youtube，后台运行没有打勾的也被杀了，未息屏，clash计时我是马上手动启动了。具体如图 [logging (1).zip](https://github.com/Tornaco/Thanox/files/8987485/logging.1.zip) ![Screenshot_20220627-044111655](https://user-images.githubusercontent.com/106238637/175833387-03113219-a017-455e-870f-22dcfc5e4a4a.jpg)
> 
> 这次的4:40左右日志，看起来可能跟锁屏清理的延迟处理逻辑有关，抽空我会改一下，你在测测。

下午16:10左右，微信贴吧share被杀
[06271611左右微信，share，贴吧被杀.zip](https://github.com/Tornaco/Thanox/files/8989927/06271611.share.zip)
[LSP微信贴吧share模块日志_2022-06-27T16_12_12.764.zip](https://github.com/Tornaco/Thanox/files/8989930/LSP.share._2022-06-27T16_12_12.764.zip)
[LSP微信share贴吧详细日志_2022-06-27T16_12_44.913.zip](https://github.com/Tornaco/Thanox/files/8989931/LSP.share._2022-06-27T16_12_44.913.zip)

**Comment by diweisong** [comment]
下午17:10左右被杀微信share贴吧lite椒盐音乐，貌似除没有勾选后台运行
[06271711微信share贴吧lite椒盐音乐被杀.zip](https://github.com/Tornaco/Thanox/files/8990427/06271711.share.lite.zip)
[LSPosed模块日志_2022-06-27T17_13_42.105.zip](https://github.com/Tornaco/Thanox/files/8990428/LSPosed._2022-06-27T17_13_42.105.zip)
[LSPosed详细日志_2022-06-27T17_13_46.285.zip](https://github.com/Tornaco/Thanox/files/8990429/LSPosed._2022-06-27T17_13_46.285.zip)
的全杀了

**Comment by Tornaco** [comment]
现在的bug跟你的锁屏清理延迟有关，一个小时杀一次。晚一点点我会修复。

**Comment by Tornaco** [comment]
@diweisong 试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/368/workflows/14977887-6c12-4bdc-93e5-beff42e83a60/jobs/338

**Comment by diweisong** [comment]
> @diweisong 试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/368/workflows/14977887-6c12-4bdc-93e5-beff42e83a60/jobs/338

好的，如果不杀了，可以把桌面和UI从作用域移除吗？发布的4.0正式版本可以用吗？

**Comment by Tornaco** [comment]
可以移除，作用御只是用来打印日志的，现在不需要日志了。

4.0可用。

**Comment by diweisong** [comment]
> 可以移除，作用御只是用来打印日志的，现在不需要日志了。
> 
> 4.0可用。

好的，如果再遇到的话我再反馈，我先这样用个几天看看。辛苦
