### ISSUE TITLE
能否增加一键加速开关喵

### ISSUE THREAD

**Issue by xianyuyimu** [Tornaco/Thanox#525]
希望可以在下滑面板里面添加一个一键加速的开关。虽然目前可以通过创建快捷方式在桌面上使用一件加速，但是有时候很麻烦。得切回桌面才可以。

**Comment by Tornaco** [comment]
@w1915591935  https://app.circleci.com/pipelines/github/Tornaco/Thanox/362/workflows/b29e63d6-e003-4bc5-8f49-41ab21f5cc9c/jobs/332
