### ISSUE TITLE
情景模式setDataNetworkType在红米K50上不工作

### ISSUE THREAD

**Issue by simplerick-simplefun** [Tornaco/Thanox#526]
**Describe the bug（现象描述）**
在红米K50手机上（MIUI13官方稳定版，天玑8100）
情景模式下的
data.setDataNetworkType
setDataNetworkTypeForPhone
setDataNetworkTypeForSlot
三项功能都不工作。

**Version（发现问题的版本）:**
MIUI 13.0.17（SLNCNXM） 稳定版

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
没有看到有用的log，不发了。应该是handle构造的问题。

> 2. Thanox版本，补丁方式（xposed还是magisk？）
LSPosed 系统框架

**Comment by Tornaco** [comment]
@simplerick-simplefun 要不你把手机寄给我，或者补充日志后再open。
