### ISSUE TITLE
后台运行功能能否增加杀前台呢？

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#527]
![Screenshot_20220627-213512053_mh1656336990393](https://user-images.githubusercontent.com/106238637/175954934-5512cb4b-b807-4e65-a2f3-b7ae1e5e5c76.jpg)
诸如起点，抖音，哔哩哔哩这些应用，息屏或者人睡着自动息屏了不会进入墓碑（判定不是后台在前台），cpu依旧在活跃唤醒使用，造成显著的待机电量消耗，能不能像绿色守护一样，前台也杀掉呢？
或者说可以给个开关之类的？如果用户有需要长期挂在后台的应用，只要取消勾选就行，比如微信之类的。
现在没有这个功能，一些挖矿类应用息屏后依旧肆无忌惮在唤醒使用CPU。

**Comment by Tornaco** [comment]
加个总开关？这个比较简单。如果要每个应用单独设置是否前台也杀，ui怎么设计呢。

**Comment by diweisong** [comment]
> 加个总开关？这个比较简单。如果要每个应用单独设置是否前台也杀，ui怎么设计呢。

不用每个应用单独啊，我的意思就是加一个息屏杀前台的功能就行，给个开关，只是让那些用不到的用户可以关闭这个。我觉得用户还是能用到的，如果需要息屏挂后台的应用，只要把后台运行打开就行了。真的会做的话或者做好了踢我一脚。辛苦

**Comment by Tornaco** [comment]
@diweisong  https://app.circleci.com/pipelines/github/Tornaco/Thanox/372/workflows/8241f4b6-5380-4dbe-8c4e-44d43f80f73e/jobs/342/artifacts

**Comment by diweisong** [comment]
> @diweisong https://app.circleci.com/pipelines/github/Tornaco/Thanox/372/workflows/8241f4b6-5380-4dbe-8c4e-44d43f80f73e/jobs/342/artifacts

牛批，谢谢老大采纳！
