### ISSUE TITLE
功能请求：加入对microg的支持

### ISSUE THREAD

**Issue by x6ufeng** [Tornaco/Thanox#528]
可以加入对microg的支持吗？
使用microg的情况下在最新版无法正常使用和跳过
![Screenshot_20220629-225340_Thanox Pro](https://user-images.githubusercontent.com/69743957/176467992-19800ca7-8856-44e4-960f-a727c14ae44d.jpg)

**Comment by CoelacanthusHex** [comment]
https://github.com/sn-00-x/fakestore2playstore
