### ISSUE TITLE
进入进程管理的应用详情页会重启

### ISSUE THREAD

**Issue by nita0318** [Tornaco/Thanox#529]
**Describe the bug（现象描述）**
thanox进程管理，随意点击查看一个运行中或已缓存的应用的详情，thanox会自动重启

**To Reproduce**（如何复现）
1. 打开thanox首页
2. 点击首页上方的内存部分进入进程管理
3. 点击任意一个运行中或已缓存的应用的详情（默认“三方”分类）
4. 出现很短暂（约0.5s）的应用运行详情页面，随后thanox重启，表现为出现冷启动的加载页面，然后回到首页

**Expected behavior**（期望结果）
可以正常查看应用详情

**Screenshots**（截图）

**Version（发现问题的版本）:**
 - OS: MIUI 12.5.10.0 Android 11
 - Version: 4.0.0-prc  xposed模式

**Additional context**（其他信息）
第一次使用进程管理的时候还可以看到详情，查看了大概5个应用的详情之后，在查看应用“微信”的详情时thanox就开始崩溃重启了，之后不重启的情况下，多次清除应用全部数据，只激活不配置thanox，也还会出现这个问题。

** Logs**（日志文件）
因为多次重试，日志有些大

[thanox-core.log](https://github.com/Tornaco/Thanox/files/9020665/thanox-core.log)

**Comment by Tornaco** [comment]
@nita0318 试试CI上的最新版：

https://app.circleci.com/pipelines/github/Tornaco/Thanox/377/workflows/76362118-a06b-4f45-99e5-01b9497f4ade/jobs/346/artifacts

如果还有问题请继续抓日志反馈。

**Comment by nita0318** [comment]
> @nita0318 试试CI上的最新版：
> 
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/377/workflows/76362118-a06b-4f45-99e5-01b9497f4ade/jobs/346/artifacts
> 
> 如果还有问题请继续抓日志反馈。

测试了一下，功能可以正常使用了
