### ISSUE TITLE
Want GCM Feature

### ISSUE THREAD

**Issue by AraafRoyall** [Tornaco/Thanox#530]
i want attached feature in thanox app
![Screenshot_2022-07-03-14-16-11-543_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/87515236/177032857-0fbc7feb-9f18-48c4-a35d-5feb7c3ad029.jpg)

**Comment by araafroyall** [comment]
![Screenshot_2022-07-03-14-16-11-543_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/87515236/177032835-e8c17f24-0242-4d78-9029-eeb65a643696.jpg)

**Comment by Tornaco** [comment]
You can try Profile feature, it has ability to detect FCM message, it can also post a notification on FCM received.
