### ISSUE TITLE
激活后卡顿

### ISSUE THREAD

**Issue by WJJ214453** [Tornaco/Thanox#542]
**Describe the bug（现象描述）**
在lsposed中激活thanox或后应用内界面卡顿

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1.打开lsposed激活thanox
2. 进入thanox，滑动／点击任意界面
3. 出现黑屏／卡顿 现象，系统报错“thanox没有响应”

**Screenshots**（截图）
[视频链接](https://wwt.lanzoum.com/tp/i9HEq07tncxa)我无法在github上上传大于25mb的文件，所以我选择将录屏文件打包上传到蓝奏云然后再将它的链接上传，望见谅

**Version（发现问题的版本）:**
 - OS: 11![Screenshot_20220714-150358_设置.png](https://user-images.githubusercontent.com/58324657/178946322-5149d2d6-1132-43e1-ac1a-cb8e57a3aada.png)
 - Version v4.0.3-prc

** Logs**（日志文件）
我无法在／data／system／thanos目录下找到logging文件夹，所以我只能上传lsposed中的详细日志
[LSPosed_2022-07-14T15_59_26.752.zip](https://github.com/Tornaco/Thanox/files/9110383/LSPosed_2022-07-14T15_59_26.752.zip)
（还是说我操作有问题没有让thanox录制日志？）

**Comment by Tornaco** [comment]
@WJJ214453 你的日志可用，这个问题修复了一下，你可以试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/405/workflows/91abe425-3017-465d-832d-f82542f45339/jobs/372/artifacts

**Comment by WJJ214453** [comment]
> @WJJ214453 你的日志可用，这个问题修复了一下，你可以试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/405/workflows/91abe425-3017-465d-832d-f82542f45339/jobs/372/artifacts

这是干嘛的？？🥰

**Comment by WJJ214453** [comment]
> @WJJ214453 你的日志可用，这个问题修复了一下，你可以试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/405/workflows/91abe425-3017-465d-832d-f82542f45339/jobs/372/artifacts

安装使用了一会儿，还是同样的问题，但是感觉比之前没那么卡了？不知道是不是错觉[LSPosed_2022-07-14T22_35_48.043.zip](https://github.com/Tornaco/Thanox/files/9112758/LSPosed_2022-07-14T22_35_48.043.zip)
[录屏](https://wwt.lanzoum.com/iQQ8407u67wd)

**Comment by Tornaco** [comment]
@WJJ214453 这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/406/workflows/e8c31694-f821-44db-8c79-fed5de6a3641/jobs/373/artifacts

**Comment by WJJ214453** [comment]
> @WJJ214453 这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/406/workflows/e8c31694-f821-44db-8c79-fed5de6a3641/jobs/373/artifacts

很流畅，完美解决😘，还需要提供日志和录屏吗？

**Comment by Tornaco** [comment]
@WJJ214453 不用了, close issue.
