### ISSUE TITLE
关于划卡功能无法正常启用

### ISSUE THREAD

**Issue by Cokeblue** [Tornaco/Thanox#543]
1. 系统版本  color os12 h13 [基于安卓12]

2. Thanox版本，补丁方式   
![Screenshot_2022-07-14-18-47-04-13_9bd1be20abe2442bf84e81e62f440f7d](https://user-images.githubusercontent.com/41640755/178965605-20885a0b-b520-44b3-bc24-008d6d98de07.jpg)

3.问题现象的详细描述，有图或者视频更好

划卡功能无法正常启用

因大小限制故将gif压缩后用lanzou上传

https://wwm.lanzouv.com/iVG6907tsmwj

4.按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

日志文件都打包了
路径是
 /data/system/thanos_LpEGYkBkfXxHQfLD/logging/server_logging

https://wwm.lanzouv.com/iMUoc07tsw0h

**Comment by Tornaco** [comment]
@Cokeblue 划卡是指 系统自带的多任务页面，划掉最近任务卡片。进程管理这个页面本就未设计滑动清除功能。
