### ISSUE TITLE
关于show short toast的功能

### ISSUE THREAD

**Issue by sandianyue** [Tornaco/Thanox#55]
老大 我仔细看了一遍你的文档 只有这个show short/long toast  文档里标注的含义是休眠/唤醒 涉及参数是延迟的毫秒数  但是下面的所有示例貌似都和这些无关  感觉好像是用来在屏幕上显示对动作进行状态的注释 ？？？
求老大解答一番 
谢谢
砰砰砰（莫名想到了dingdingding wengwengweng 233）

**Comment by Tornaco** [comment]
@sandianyue 文档有错误，已经纠正。

**Comment by sandianyue** [comment]
> @sandianyue 文档有错误，已经纠正。

好的
