### ISSUE TITLE
功能请求：新增亮度变化的Fatcs-params

### ISSUE THREAD

**Issue by fakerqu** [Tornaco/Thanox#551]
**Is your feature request related to a problem? Please describe.**
低亮度下的超频高刷存在偏色问题，需要在低亮度时关闭高刷，目前的解决方式是通过activityResume来根据当前亮度调整刷新率，但是此方案不够实时也不够直接，需求在亮度变化时能够直接判断亮度来调整刷新率

**Describe the solution you'd like**
亮度变化后，发布一个类似brightnessChanged这样的Fatcs-params,并伴随一个当前亮度的参数
有时可能亮度会存在连续变化的情况，可以考虑在亮度不再变化后（如亮度变化后，在200ms内没有变化）发布这个事实

**Comment by Tornaco** [comment]
@fakerqu 

facts:
```
    brightnessChanged: Boolean
    brightness: Int
    minBrightness: Int 
    maxBrightness: Int 
```

https://app.circleci.com/pipelines/github/Tornaco/Thanox/459/workflows/e5841304-191b-4088-a93f-36362de2beb9/jobs/424/artifacts
