### ISSUE TITLE
thanox进入app点击运行进程管理闪退

### ISSUE THREAD

**Issue by guiji2022** [Tornaco/Thanox#566]
1.进入thanox点进程管理闪
![微信图片_20220810091809](https://user-images.githubusercontent.com/110948813/183789489-6bf3259a-6eb3-49c4-b96a-3bf10d2fd9a2.jpg)

2.我更换了app版本，重刷了系统，停止所有模块仍然没有用 
3.thanox版本；酷安最新版4.0.4-prc，系统为安卓11
4.日志
[2022-08-10.zip](https://github.com/Tornaco/Thanox/files/9295702/2022-08-10.zip)
：

**Comment by Tornaco** [comment]
@guiji2022 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/441/workflows/7e8665fa-ceb2-42aa-828e-6e680cc5448e/jobs/407/artifacts

**Comment by guiji2022** [comment]
> 

还是一样的，不知道为啥

**Comment by guiji2022** [comment]
> @guiji2022 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/441/workflows/7e8665fa-ceb2-42aa-828e-6e680cc5448e/jobs/407/artifacts

还是一样的不知道为什么，还需要提供什么吗😭

**Comment by Tornaco** [comment]
> > @guiji2022 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/441/workflows/7e8665fa-ceb2-42aa-828e-6e680cc5448e/jobs/407/artifacts
> 
> 还是一样的不知道为什么，还需要提供什么吗😭

lsp详细日志或者按照thanox首页反馈说明提供对应日志。

**Comment by guiji2022** [comment]
> > > @guiji2022 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/441/workflows/7e8665fa-ceb2-42aa-828e-6e680cc5448e/jobs/407/artifacts
> > 
> > 
> > 还是一样的不知道为什么，还需要提供什么吗😭
> 
> lsp详细日志或者按照thanox首页反馈说明提供对应日志。
[LSPosed_2022-08-10T13_36_55.628(1).zip](https://github.com/Tornaco/Thanox/files/9297085/LSPosed_2022-08-10T13_36_55.628.1.zip)
[2022-08-10 (1).zip](https://github.com/Tornaco/Thanox/files/9297086/2022-08-10.1.zip)

第一个是lsp的详细日志，第二个是thanox的

**Comment by guiji2022** [comment]
> > > > @guiji2022 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/441/workflows/7e8665fa-ceb2-42aa-828e-6e680cc5448e/jobs/407/artifacts
> > > 
> > > 
> > > 还是一样的不知道为什么，还需要提供什么吗😭
> > 
> > 
> > lsp详细日志或者按照thanox首页反馈说明提供对应日志。 [LSPosed_2022-08-10T13_36_55.628（1）.zip](https://github.com/Tornaco/Thanox/files/9297085/LSPosed_2022-08-10T13_36_55.628.1.zip) [2022-08-10 （1）.zip](https://github.com/Tornaco/Thanox/files/9297086/2022-08-10.1.zip)
> 
> 第一个是lsp的详细日志，第二个是thanox的
thanox的我是直接把文件复制过来了，

**Comment by guiji2022** [comment]
![30b3213f2d4f20bdd453163733ecd54](https://user-images.githubusercontent.com/110948813/183902741-969f9114-146c-4422-863e-5c7c763a54fd.jpg)
![b4a413098fc2222c61d94a172e14021](https://user-images.githubusercontent.com/110948813/183902766-f1b90204-26a4-4509-9477-4115bc751511.jpg)

**Comment by Tornaco** [comment]
@guiji2022 试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/442/workflows/4a0ad32d-5be9-4f5a-a27f-3d27bd2eeda4/jobs/408/artifacts   如果没构建完请等待20分钟。

**Comment by guiji2022** [comment]
@Tornaco 可以了不过图标全是这种了问题不
![0e66e98a3d6e10e450f6e1e57daeb1f](https://user-images.githubusercontent.com/110948813/183915442-c4fb9949-7205-4d75-83f2-9bb7792db190.jpg)
大

**Comment by Yuxiong1992** [comment]
期待大佬早日解决并在谷歌商店更新

**Comment by Tornaco** [comment]
@guiji2022 不正常，其他界面呢，app图标可以正常加载？

**Comment by guiji2022** [comment]
@Tornaco thanox所有界面都是这样的图标

**Comment by Tornaco** [comment]
@guiji2022  进入进程管理，然后再抓个lsp详细日志，我看下能否修福。

**Comment by guiji2022** [comment]
@Tornaco
[LSPosed_2022-08-13T21_45_49.364.zip](https://github.com/Tornaco/Thanox/files/9331539/LSPosed_2022-08-13T21_45_49.364.zip)

**Comment by Tornaco** [comment]
@guiji2022  再用这个版本抓个日志，我加了一下日志。

**Comment by guiji2022** [comment]
@Tornaco
[2022-08-14.zip](https://github.com/Tornaco/Thanox/files/9332702/2022-08-14.zip)thanox日志

**Comment by Tornaco** [comment]
@guiji2022 你是开什么插件对thanox隐藏应用列表了吗？

**Comment by guiji2022** [comment]
@Tornaco 还真的是应用隐藏列表隐藏了😂
