### ISSUE TITLE
功能请求：希望thanox的自启动管理能像miui一样分别管理应用自启动与关联启动

### ISSUE THREAD

**Issue by Arlia-Etoile** [Tornaco/Thanox#573]
**Is your feature request related to a problem? Please describe.**

因为非miui使用mipush需要关联启动，但不需要应用自启动，所以需要thanox能够分别管理应用自身自启与关联启动

**Describe the solution you'd like**
在应用管理中，点击自启动之后，会弹出页面，分别有关联启动与自启动的开关

**Describe alternatives you've considered**

**Additional context**

**Comment by Tornaco** [comment]
@Arlia-Etoile 你是发现mipush启动其他应用时被拦截了吗？如果是这个问题的话麻烦你进入后台启动记录中，找到拦截的记录，点击之后会展示详情，截图发下。关于分开的问题暂时先不分，会增加复杂度，而且自启动和关联启动不是很好区分。
