### ISSUE TITLE
麻烦开发者完善一下情景模式文档

### ISSUE THREAD

**Issue by PPKunOfficial** [Tornaco/Thanox#576]
如题，需要完善情景模式文档
目前发现文档有部分地方是有很多的缺少的，希望开发者大大可以找时间将文档写一写
也可以在一些平台上（例如酷安）发布自愿补齐thanox文档项目

**Comment by Tornaco** [comment]
@PPKunOfficial 能说下哪部分缺少了吗？我优先把这部分补充上。

**Comment by PPKunOfficial** [comment]
可以优先补充一下thanos api部分，还有全局变量里的一些用法
比如 `thanos.activityManager` 里的用法还有 `globalValOf$value.contains()`
这些都是示例里出现的，但是文档里没有或一笔带过的

**Comment by xuchaoxin1375** [comment]
文档完善程度确实不太够
