### ISSUE TITLE
使用lsposed激活失败

### ISSUE THREAD

**Issue by Toedcreature** [Tornaco/Thanox#580]
thanox版本4.06
miui版本12.5
android11
lsposed版本1.8.3
无法使用lsposed激活 我换过几个thanox版本 都没法激活 手机已经重启几遍了 依旧无法激活
而且点进程管理以及其他功能 均会闪退
![Screenshot_2022-08-31-11-29-30-992_com miui home](https://user-images.githubusercontent.com/34999663/187586591-91c0b40b-b621-420c-a4fa-57a7ce5a6305.jpg)
[logging.zip](https://github.com/Tornaco/Thanox/files/9458195/logging.zip)

**Comment by Tornaco** [comment]
@Toedcreature 还装其他lsp模块了吗？

**Comment by Toedcreature** [comment]
> @Toedcreature 还装其他lsp模块了吗？

我在miui11 安卓10的时候能正常激活 前天升的miui12.5 所有模块都是和之前一样的 其他模块没有问题能正常运行 就是thanox无法激活

**Comment by Tornaco** [comment]
@Toedcreature 用这个版本在抓个日志，注意不要再点开发者设置中的no-root了。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/467/workflows/b7efaac2-fbf9-4b07-844f-6aae6565da65/jobs/432/artifacts

**Comment by Toedcreature** [comment]
@Tornaco 
[logging.zip](https://github.com/Tornaco/Thanox/files/9470424/logging.zip)
依旧同样的问题 无法激活 点击功能闪退

**Comment by Tornaco** [comment]
@Toedcreature 不能与X-APM同时激活。
