### ISSUE TITLE
 类型转换异常导致产生大量日志 ClassCastException caused massive log

### ISSUE THREAD

**Issue by michaellx1057** [Tornaco/Thanox#581]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）

在 LSPosed 日志中发现大量类型转换异常导致的错误日志。
Massive error log about ClassCastException appears in LSPosed. 

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）

1. Go to LSPosed Manager.（进入 LSPosed 管理器）
2. Switch to "Log" tab.（切换到“日志”）
3. See error（发现错误）

`09-02 04:52:23.248  1654  1996 E LSPosed-Bridge: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
09-02 04:52:23.248  1654  1996 E LSPosed-Bridge: 	at github.tornaco.android.thanos.services.xposed.hooks.IntentFirewallRegistry$2.beforeHookedMethod(Unknown Source:8)
09-02 04:52:23.248  1654  1996 E LSPosed-Bridge: 	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
09-02 04:52:23.248  1654  1996 E LSPosed-Bridge: 	at LSPHooker_.checkBroadcast(Unknown Source:42)`

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

Everything works good. （一切工作正常）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

![S20902-05075494](https://user-images.githubusercontent.com/26094621/188013461-48ae7086-7f4a-4a27-9647-c70c47915ba6.png)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

Device: meizu 17 Pro
OS: Flyme 9.3.0.0A + Android 11
ROOT: root
Magisk: Magisk 25.2(25200)  + Zygisk
LSPosed: 1.8.3 (6552) + API 93
Thanox: Thanox Pro (from Google Play)
![S20902-05145959](https://user-images.githubusercontent.com/26094621/188014503-22e0ebbf-2aec-4525-b300-2ceb43030616.png)

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

1. 如上
2. 如上
3. 如上
4. 不激活 Thanox （LSPosed 中不启用）时，没有问题、不会出现错误日志
5. Thanox 激活后（在 LSPosed 中启用并选择作用域为“系统框架”），无论是否做任何配置修改、都会出现错误日志
6. 如下

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

Thanox:
[2022-09-02.txt](https://github.com/Tornaco/Thanox/files/9473511/2022-09-02.txt)

LSPosed:
[LSPosed_2022-09-02T04_52_21.712.zip](https://github.com/Tornaco/Thanox/files/9473469/LSPosed_2022-09-02T04_52_21.712.zip)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by michaellx1057** [comment]
并没有在源码中找到与报错堆栈信息所示的同名的类，以“beforeHookedMethod”为关键词搜索找到
android\plugins\plugin_push_message_delegate_server\src\main\java\github\tornaco\android\plugin\push\message\delegate\hooks\ActivityIntentResolverRegistry.java
android\plugins\plugin_toolbox\src\main\java\github\tornaco\android\plugin\toolbox\hooks\DialogRegistry.java
这两个类，其中在 ActivityIntentResolverRegistry 第 54 行中有
`int resultCode = (int) param.args[3];`
是否会是类似的强转导致的呢？

Couldn't find the exact class in the code. I searched by keyword "beforeHookedMethod" and got two class
android\plugins\plugin_push_message_delegate_server\src\main\java\github\tornaco\android\plugin\push\message\delegate\hooks\ActivityIntentResolverRegistry.java
android\plugins\plugin_toolbox\src\main\java\github\tornaco\android\plugin\toolbox\hooks\DialogRegistry.java
And at ActivityIntentResolverRegistry, line 54, there is code below:
`int resultCode = (int) param.args[3];`
Might this be the root cause?

**Comment by Tornaco** [comment]
@michaellx1057  

/system/framework/services.jar 发一下看看。

**Comment by michaellx1057** [comment]
> @michaellx1057
> 
> /system/framework/services.jar 发一下看看。

@Tornaco 

LOG:
(/data/system/thanos_oBsynlEqMPyKtNcR/logging)
[thanos_oBsynlEqMPyKtNcR.zip](https://github.com/Tornaco/Thanox/files/9475715/thanos_oBsynlEqMPyKtNcR.zip)

services.jar
(/system/framework/services.jar)
[services.jar.zip](https://github.com/Tornaco/Thanox/files/9475739/services.jar.zip)

FYI~

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/469/workflows/ec80ac2a-68c5-4e97-8bb0-0d0beb6ec621/jobs/433/artifacts

试试这个版本呢，日志记得也再传一下。@michaellx1057

**Comment by michaellx1057** [comment]
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/469/workflows/ec80ac2a-68c5-4e97-8bb0-0d0beb6ec621/jobs/433/artifacts
> 
> 试试这个版本呢，日志记得也再传一下。@michaellx1057

@Tornaco 

安装了如上链接里的国内版后在 LSPosed 中把 Play 版取消了勾选，并勾选了新安装的国内版，然后重启（免费试用状态，没有激活），没有再发现之前的 ClassCaseException 报错了，只有零星的两次 Adding TV input service。详细日志如下：

Thanox：
[server_logging.zip](https://github.com/Tornaco/Thanox/files/9483194/server_logging.zip)

LSPosed：
[LSPosed_2022-09-04T02_33_52.292.zip](https://github.com/Tornaco/Thanox/files/9483195/LSPosed_2022-09-04T02_33_52.292.zip)

**Comment by Tornaco** [comment]
看起来正常了，tv_input日志是诊断用的，正常。

下次推play版本。
