### ISSUE TITLE
通知栏性能模式按钮失灵

### ISSUE THREAD

**Issue by sun2ot** [Tornaco/Thanox#585]
**Describe the bug（现象描述）**
- Thanox使用Lsposed方式激活后，会导致红米K50通知栏中的`性能模式`按钮失灵

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 在Lsposed中启用Thanox模块，默认勾选`系统框架`
2. 重启手机
3. 下滑通知栏菜单，点击`性能模式`
4. 系统无反应
    - 通过`手机管家`开启性能模式后，通知栏按钮状态无变化「即不变色」
    - 不通过手机管家，直接点击`性能模式`按钮，电池图标无变化「即未开启性能模式」

**Expected behavior**（期望结果）
- 下拉通知栏，点击按钮后，能正常开启性能模式

**Screenshots**（截图）
![Screenshot_2022-09-04-10-53-52-676_com.xiaomi.vipaccount.jpg](https://s2.loli.net/2022/09/04/Gi8nAEzSDmtPcXZ.jpg)

**Version（发现问题的版本）:**
 - OS: `Android 12` && `MIUI 13.1.22.8.29DEV`
 - Version v4.0.6-prc

**Additional context**（其他信息）
由于Thanox只注入了系统框架，且我已关闭除了Thanox外的其余所有注入系统框架的模块，经排除判断得出的该结论。

** Logs**（日志文件）
https://wwu.lanzouw.com/i7ye80b13iba
- 去除`.zip`后缀

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@zhihang-yi  恢复thanox到默认数据试试，要看是不是你的配置阻止了某些系统app的启动。也可以看下后台启动的启动记录。

**Comment by sun2ot** [comment]
1. 已清楚Thanox全部数据后重启，问题仍存在
2. 已确认没有冻结任何三方App或系统组件
3. 关闭Thanox后功能正常
> 如确认与Thanox无关，也可能是其他Xposed模块与之冲突，感谢您的回复！

**Comment by Tornaco** [comment]
你在再点击通知栏那个按钮复现一两次，随后到lsp里保存详细日志，我有空看下，不确定能否定位到原因。

**Comment by Tornaco** [comment]
@zhihang-yi
