### ISSUE TITLE
希望应用管理 批量禁用 组件和活动

### ISSUE THREAD

**Issue by hacamer** [Tornaco/Thanox#587]
如题
希望在应用管理 
组件和活动里面 
搜索完可以批量禁用
（全都/全不）
![Screenshot_20220908-205246_Lawnchair](https://user-images.githubusercontent.com/73057402/189126671-f01add6e-f416-4617-aace-51cb81bbdbb6.png)

**Comment by Tornaco** [comment]
@hacamer 试试这个  https://app.circleci.com/pipelines/github/Tornaco/Thanox/472/workflows/b3f88d3e-0549-48b4-ac57-c832686afcf6/jobs/436/artifacts

如果还没出现apk的话，稍等，构建需要20分钟。

**Comment by hacamer** [comment]
> @hacamer 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/472/workflows/b3f88d3e-0549-48b4-ac57-c832686afcf6/jobs/436/artifacts
> 
> 如果还没出现apk的话，稍等，构建需要20分钟。

@Tornaco 感谢大佬 可以正常用了
