### ISSUE TITLE
闪退和卡登录

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#588]
唤醒锁点击批量管理会导致thanox闪退应用重启，4.0.7-prc没修复，上个版本也存在。
还有就是会导致起点读书无法登陆，上个正式版本也是。
点击获取验证码，会卡在滑块这个页面一直没反应，经我多次重启测试，就是激活thanox后就有了。而且我还取消了对起点读书的各种限制，就变成了什么都没动，也是激活模块后会卡在登录页面。
MIUI版本12.5.7，A11，灭霸版本4.0.7-prc
[logging.zip](https://github.com/Tornaco/Thanox/files/9541758/logging.zip)
![IMG_20220911_122122](https://user-images.githubusercontent.com/106238637/189512462-546bb855-c519-4976-9e19-5f8ea9ee6f29.jpg)

**Comment by diweisong** [comment]
![IMG_20220911_123332](https://user-images.githubusercontent.com/106238637/189512586-368ed2a0-622c-4092-893f-866aeafcb677.jpg)

**Comment by Tornaco** [comment]
@diweisong 

1. 唤醒锁闪退请应该版本测试后：
https://app.circleci.com/pipelines/github/Tornaco/Thanox/479/workflows/6fadab96-9903-40ec-b3e0-7a0867459983/jobs/442/artifacts

抓取日志贴上来。

2. 读书app的问题，试一下恢复thanox到默认配置试试，需要排除个人配置原因。我自测正常。

**Comment by diweisong** [comment]
> @diweisong
> 
> 1. 唤醒锁闪退请应该版本测试后：
>    https://app.circleci.com/pipelines/github/Tornaco/Thanox/479/workflows/6fadab96-9903-40ec-b3e0-7a0867459983/jobs/442/artifacts
> 
> 抓取日志贴上来。
> 
> 2. 读书app的问题，试一下恢复thanox到默认配置试试，需要排除个人配置原因。我自测正常。

我试过了呀，把起点恢复默认没有对他动手还是卡登录，lsp取消thanox模块就好了不会卡登陆，不管是权限，后台管理，PM禁用都取消了还是卡登陆
![Stitch_20220912_140441](https://user-images.githubusercontent.com/106238637/189584385-a33334af-2a08-4424-81cf-c4eec71fdbdb.png)
![IMG_20220912_140337](https://user-images.githubusercontent.com/106238637/189584409-411a8412-7214-49bf-9043-c0bbf60cf762.jpg)
![IMG_20220912_140231](https://user-images.githubusercontent.com/106238637/189584438-98fbd5c6-d6e5-41a3-8ca2-8c9eee3337d1.jpg)

**Comment by Tornaco** [comment]
@diweisong 起点读书会检测root，需要hide一下。

目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。

**Comment by Tornaco** [comment]
@diweisong 抓个lsp详细日志吧，我尽量看看能不能找到线索。

**Comment by diweisong** [comment]
> @diweisong 抓个lsp详细日志吧，我尽量看看能不能找到线索。

[Download.zip](https://github.com/Tornaco/Thanox/files/9545127/Download.zip)
模块日志和详细日志。

**Comment by diweisong** [comment]
> @diweisong 起点读书会检测root，需要hide一下。
> 
> 目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。

在我原生安卓10的老设备上，我对它做了那么多的限制，都不会影响登录，也不会卡登录。所以我认为是MIUI和thanox的兼容性问题，只要lsp取消thanox模块激活就不会卡登录，问题是激活前和激活后都没有对起点做任何管理，就很迷

**Comment by Tornaco** [comment]
> > @diweisong 起点读书会检测root，需要hide一下。
> > 
> > 目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。
> 
> 在我原生安卓10的老设备上，我对它做了那么多的限制，都不会影响登录，也不会卡登录。所以我认为是MIUI和thanox的兼容性问题，只要lsp取消thanox模块激活就不会卡登录，问题是激活前和激活后都没有对起点做任何管理，就很迷

晚点我看日志。情景模式有用到吗？用到了的话关闭试试。

**Comment by diweisong** [comment]
> > > @diweisong 起点读书会检测root，需要hide一下。
> > > 目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。
> > 
> > 
> > 在我原生安卓10的老设备上，我对它做了那么多的限制，都不会影响登录，也不会卡登录。所以我认为是MIUI和thanox的兼容性问题，只要lsp取消thanox模块激活就不会卡登录，问题是激活前和激活后都没有对起点做任何管理，就很迷
> 
> 晚点我看日志。情景模式有用到吗？用到了的话关闭试试。

没有针对起点的情景，刚刚把情景功能关了，也是卡登录。

**Comment by Tornaco** [comment]
> > @diweisong 抓个lsp详细日志吧，我尽量看看能不能找到线索。
> 
> [Download.zip](https://github.com/Tornaco/Thanox/files/9545127/Download.zip) 模块日志和详细日志。

你贴的日志里full.log都是0B，是不是把logd关了。

**Comment by Tornaco** [comment]
> > > > @diweisong 起点读书会检测root，需要hide一下。
> > > > 目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。
> > > 
> > > 
> > > 在我原生安卓10的老设备上，我对它做了那么多的限制，都不会影响登录，也不会卡登录。所以我认为是MIUI和thanox的兼容性问题，只要lsp取消thanox模块激活就不会卡登录，问题是激活前和激活后都没有对起点做任何管理，就很迷
> > 
> > 
> > 晚点我看日志。情景模式有用到吗？用到了的话关闭试试。
> 
> 没有针对起点的情景，刚刚把情景功能关了，也是卡登录。

建议还是备份下thanox数据，然后到thanox设置，数据，恢复默认。用这种方式保证是默认数据，thanox能影响app的配置项太多了。

**Comment by diweisong** [comment]
> > > @diweisong 抓个lsp详细日志吧，我尽量看看能不能找到线索。
> > 
> > 
> > [Download.zip](https://github.com/Tornaco/Thanox/files/9545127/Download.zip) 模块日志和详细日志。
> 
> 你贴的日志里full.log都是0B，是不是把logd关了。

没有啊，我看了一下都打开的

**Comment by diweisong** [comment]
> > > > > @diweisong 起点读书会检测root，需要hide一下。
> > > > > 目前还没有其他人反馈起点读书问题。如果恢复默认配置都不行那我也无法修复了，抱歉。
> > > > 
> > > > 
> > > > 在我原生安卓10的老设备上，我对它做了那么多的限制，都不会影响登录，也不会卡登录。所以我认为是MIUI和thanox的兼容性问题，只要lsp取消thanox模块激活就不会卡登录，问题是激活前和激活后都没有对起点做任何管理，就很迷
> > > 
> > > 
> > > 晚点我看日志。情景模式有用到吗？用到了的话关闭试试。
> > 
> > 
> > 没有针对起点的情景，刚刚把情景功能关了，也是卡登录。
> 
> 建议还是备份下thanox数据，然后到thanox设置，数据，恢复默认。用这种方式保证是默认数据，thanox能影响app的配置项太多了。

试了一下，恢复默认重启之后就能登陆了，但是恢复备份后就又不行了。最主要的是根本没有对起点动手，太烦了

**Comment by Tornaco** [comment]
你打开情景模式——右上角—ActionConsole
村长  18:15:53
依次执行这三个命令

thanox.activityManager.setBlockAllProvider("com.qidian.QDReader", false)
村长  18:16:47
thanox.activityManager.setBlockAllService("com.qidian.QDReader", false)
村长  18:16:53
thanox.activityManager.setBlockAllReceiver("com.qidian.QDReader", false)


---


后续我会增加一个UI提示在组件列表，不然可能不知道之前用的情景模式对这个应用做了干涉

**Comment by diweisong** [comment]
> 你打开情景模式——右上角—ActionConsole 村长 18:15:53 依次执行这三个命令
> 
> thanox.activityManager.setBlockAllProvider("com.qidian.QDReader", false) 村长 18:16:47 thanox.activityManager.setBlockAllService("com.qidian.QDReader", false) 村长 18:16:53 thanox.activityManager.setBlockAllReceiver("com.qidian.QDReader", false)
> 
> 后续我会增加一个UI提示在组件列表，不然可能不知道之前用的情景模式对这个应用做了干涉

全部已恢复。

**Comment by Tornaco** [comment]
Dup with #589
