### ISSUE TITLE
情景模式重启一次不生效

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#595]
在使用的手机重启一次情景模式会变成不生效，需要重启第二次才生效。
比如开启应用开启gps情景，墓碑情景之类的，重启一次会全部失效，需要重启第二次才生效，下面是两个不生效不同时期的日志
[logging情景模式不生效.zip](https://github.com/Tornaco/Thanox/files/9591471/logging.zip)
[LSPosed_2022-09-17T18_36_59.325.zip](https://github.com/Tornaco/Thanox/files/9591472/LSPosed_2022-09-17T18_36_59.325.zip)
[LSPosed_2022-09-17T18_37_02.101.zip](https://github.com/Tornaco/Thanox/files/9591473/LSPosed_2022-09-17T18_37_02.101.zip)

[logging不生效.zip](https://github.com/Tornaco/Thanox/files/9591470/logging.zip)
![IMG_20220917_183634](https://user-images.githubusercontent.com/106238637/190852855-6c8ccedd-3e9e-4c5e-a8d1-25d36cc8b4c1.jpg)

**Comment by Tornaco** [comment]
```
[
{
"name": "A-GPS开关",
"description": "打开应用开启GPS，关闭应用关闭GPS，使用全局变量gps",
"priority": 2,
"condition": "frontPkgChanged || pkgKilled",
"actions": [
"if(frontPkgChanged && globalVarOf$gps.contains(to)) { (hw.enableLocation()) } else if ( pkgKilled && globalVarOf$gps.contains(pkgName)) { (hw.disableLocation()) }"
]
}
]
```

修改后可以正常工作。close。
