### ISSUE TITLE
rc3不能阻止某些app后台自启发出通知，beta6没有类似问题。

### ISSUE THREAD

**Issue by tifish** [Tornaco/Thanox#6]
rc3不能阻止某些app后台自启并发出通知，如闲鱼、美团、喜马拉雅等。收到通知后，在Thanox中查看进程列表，并没有发现对应的app。beta6没有类似问题。

运行环境：一加7 Pro，Android 10，EdExposed。

**Comment by ppouerct** [comment]
这个是系统push的问题
