### ISSUE TITLE
Need Internet Access blocker 

### ISSUE THREAD

**Issue by AraafRoyall** [Tornaco/Thanox#600]
Hi, developer can you add an option to disable internet access for apps with power of xposed , i mean the disable permission will be set as long as we do. And without requirement of any extra background service to block internet access.
Hope you understand .

**Comment by AraafRoyall** [comment]
Hi  please tell me will you impliment this or not

**Comment by Tornaco** [comment]
@araafroyall No I think not, buddy.

**Comment by araafroyall** [comment]
> @araafroyall No I think not, buddy.

Ok as you wish. But atleast can you make backup and restore components state of individual app. Sometime we need to uninstall and install single app but for restore component state we need to restore fully backup which is not as easy process for individual app. Hope you understand
