### ISSUE TITLE
乖巧模式未正常跳过有通知的应用

### ISSUE THREAD

**Issue by 849506054** [Tornaco/Thanox#605]
**Describe the bug（现象描述）**
已在乖巧模式设置中开启【跳过有通知的】，但未正常跳过有通知应用，

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 使用dvget下载文件进行测试，dvget在下载文件时会在通知栏显示一条通知展示下载进度
2. 将dvget切换到后台
3. 大约2秒左右下载进度停滞，下载进度通知消失，dvget被乖巧
4. 取消乖巧dvget可正常后台下载

**Expected behavior**（期望结果）
可以正确跳过有通知的应用

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![Screenshot_20220928-234022](https://user-images.githubusercontent.com/25845909/192825312-2980bf71-1f30-4434-8207-245141f2e637.jpg)

**Version（发现问题的版本）:**
 - OS: andriod10 一加氢os
 - Version 4.0.9国内版lsposed 1.8.4 （6609）激活

**Additional context**（其他信息）

** Logs**（日志文件）
[server_logging.zip](https://github.com/Tornaco/Thanox/files/9666746/server_logging.zip)

23:41分左右，dvget在有通知的情况下后台下载文件时被乖巧
23:43分左右取消dvget乖巧，后台正常下载文件

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@849506054 https://app.circleci.com/pipelines/github/Tornaco/Thanox/511/workflows/f1dadb0a-3420-414f-b018-0b1268ceb9c8/jobs/471/artifacts

Test this version pls.

**Comment by 849506054** [comment]
@Tornaco 测试了几款app，都可以正常跳过了有通知的后台应用了，感谢

**Comment by 849506054** [comment]
@Tornaco 顺带也同时修复了弹幕通知不显示的问题，nice！
