### ISSUE TITLE
[功能请求]乖巧模式增加开关跳过有悬浮窗的应用

### ISSUE THREAD

**Issue by 849506054** [Tornaco/Thanox#606]
希望在乖巧模式中增加跳过正在显示悬浮窗的应用，一些视频软件在播放视频的时候可以以悬浮窗的模式显示在其他应用上层，希望乖巧模式可以对此状态进行判断，并且在乖巧模式设置中提供开关（类似于“跳过有通知的”）

不同的安卓版本可能对于此权限和功能的描述不一样，截图为安卓10
![Screenshot_20220929-155519](https://user-images.githubusercontent.com/25845909/192974026-eba619ce-9596-4db7-9190-1eea337e5aca.jpg)
![Screenshot_20220929-155720](https://user-images.githubusercontent.com/25845909/192974379-3a8eabbe-6cc6-4bc2-9c99-7c0120940bd0.jpg)

相关日志：
16：02分左右，米家app在后台使用悬浮窗口显示的时候被乖巧处理
[logging.zip](https://github.com/Tornaco/Thanox/files/9672445/logging.zip)

**Comment by Tornaco** [comment]
@849506054 麻烦进入情景模式，右上角，action console输入如下代码执行，看下有悬浮窗和无悬浮窗的情况下，结果是否一样

```

thanos.activityManager.hasTopVisibleActivities("包名")

```

如果结果不一样的话，下个版本我会增加这个设置项。

**Comment by 849506054** [comment]
> 

![Screenshot_20221008-110525](https://user-images.githubusercontent.com/25845909/194685084-5bae9662-a0ee-4b1c-8c1d-49e0eac045e7.jpg)
![Screenshot_20221008-110525](https://user-images.githubusercontent.com/25845909/194685089-2a8efb29-521a-43d4-b23a-7d3cd2db1d61.jpg)

有无悬浮窗都是false，测试应用为哔哩哔哩7.0

**Comment by 849506054** [comment]
> @849506054 麻烦进入情景模式，右上角，action console输入如下代码执行，看下有悬浮窗和无悬浮窗的情况下，结果是否一样
> 
> ```
> 
> thanos.activityManager.hasTopVisibleActivities("包名")
> ```
> 
> 如果结果不一样的话，下个版本我会增加这个设置项。
![Screenshot_20221008-110533](https://user-images.githubusercontent.com/25845909/194685171-8ca257b0-702a-4437-ae75-4f10acb0adf7.jpg)
![Screenshot_20221008-110525](https://user-images.githubusercontent.com/25845909/194685174-dc4b6e96-4780-43d8-a803-8a80d284c49e.jpg)

有无悬浮窗都是false，测试应用为哔哩哔哩7.0

**Comment by Tornaco** [comment]
@849506054 OK 那可能要多花些时间搞了。

**Comment by Tornaco** [comment]
```java
thanos.windowManager.hasVisibleWindows("xxx.xxx.xxx")
```

你再用这个执行一下呢。

**Comment by 849506054** [comment]
> 

有区别了，无悬浮窗口false，有悬浮窗口true
![Screenshot_20221009-135843](https://user-images.githubusercontent.com/25845909/194740592-f34ce6f1-fd32-40ec-acfb-bef6eee4b4ff.jpg)
![Screenshot_20221009-135900](https://user-images.githubusercontent.com/25845909/194740597-c80bf2a8-3451-4933-8efa-21f4f75d6cf4.jpg)

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/520/workflows/9c55e575-bb39-42b9-bc84-0e53cd88d0be/jobs/473/artifacts


@849506054 加了开关，测试下？

**Comment by 849506054** [comment]
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/520/workflows/9c55e575-bb39-42b9-bc84-0e53cd88d0be/jobs/473/artifacts
> 
> @849506054 加了开关，测试下？

测试完毕，测试了几款app都达到预期效果了
打开开关可以正常跳过有悬浮窗的应用，关闭开关也可以正常处理有悬浮窗的应用
感谢老大！

**Comment by Tornaco** [comment]
OK Nice.
