### ISSUE TITLE
lsp载入灭霸，导致失去浏览器功能

### ISSUE THREAD

**Issue by player5201314** [Tornaco/Thanox#611]
最新前3版本，lsp刷入灭霸，导致没有webview运行，关闭lsp和灭霸没效果，需要重刷系统，没在继续刷新一些的版本
安卓12 los19.1  k30s

**Comment by Tornaco** [comment]
关闭thanox后如果还有问题的话，那就不是thanox的问题了，你是不是禁用了什么系统组件，或者导入了其他人的备份？

暂时关闭，请提供必要信息后open该issue。
