### ISSUE TITLE
app休眠后再切换到前台解除休眠不及时

### ISSUE THREAD

**Issue by recycle007** [Tornaco/Thanox#614]
最新版thanox，一加安卓10，目标app哔哩哔哩，在返回退出哔哩哔哩进入休眠状态一会儿后再打开，随机会出现无网络首页空白或者加载很慢才加载出视频的情况

**Comment by Tornaco** [comment]
@recycle007 没明白你用的什么功能？麻烦按照反馈提示提供一下截图，日志。

暂时关闭，请提供必要信息后open该issue。

**Comment by recycle007** [comment]
> @recycle007 没明白你用的什么功能？麻烦按照反馈提示提供一下截图，日志。
> 
> 暂时关闭，请提供必要信息后open该issue。

乖巧模式设置里打开休眠应用选项，会随机出现这种现象
