### ISSUE TITLE
更新后提示不兼容

### ISSUE THREAD

**Issue by funianshengsheng** [Tornaco/Thanox#616]
thanox版本:4.1.1-22-fd16024-row
系统:Android9
日志文件:https://mczka.lanzouv.com/i7Vzi0ekflsj

**Comment by Tornaco** [comment]
@funianshengsheng 又推了新版，麻烦再观察下。

**Comment by funianshengsheng** [comment]
> 



> @funianshengsheng 又推了新版，麻烦再观察下。

新版不提示了，爱了大大

**Comment by Tornaco** [comment]
好的感谢。
