### ISSUE TITLE
唤醒锁闪退

### ISSUE THREAD

**Issue by Chameng** [Tornaco/Thanox#619]
> 1. 安卓11
![Screenshot_2022-11-03-09-34-02-143_com android settings](https://user-images.githubusercontent.com/89916476/199632652-7f0875b6-a1fc-4433-bbc5-77b1b89a8261.jpg)
> 2. Thanox版本：github.tornaco.android.thanos，4.1.2-prc(3070479)，补丁方式：xposed  lsposed-1.8.4
> 3. 视频和日志：https://pan.huang1111.cn/s/ZYw6cL
> 4. 不激活thanox有问题吗？（可能是thanox功能问题）
> 5. Thanox激活后不做任何配置有问题吗？（没有尝试）

**Comment by Tornaco** [comment]
@Chameng  这个问题有其他人也报过，还没分析出原因，我先标记下，找时间一起看。

**Comment by Chameng** [comment]
> @Chameng 有其他人也报过，这个问题分析出原因，我先标记下，找时间一起看。

收到
