### ISSUE TITLE
开放检测正在播放音频的接口

### ISSUE THREAD

**Issue by StarLeet** [Tornaco/Thanox#620]
![Screenshot_20221113-133109_Thanox~2.png](https://user-images.githubusercontent.com/89691566/201526075-31167487-8acc-4e24-be21-7d2bde03508a.png)

可以将图示功能的判断接口抽象开放出来吗？很多情况要在情景模式里用到这个接口

**Comment by Tornaco** [comment]
`thanos.audioManager.hasAudioFocus("com.tencent.mm")`

**Comment by Tornaco** [comment]
https://github.com/Tornaco/Thanox/blob/master/android/android_framework/base/src/main/java/github/tornaco/android/thanos/core/audio/AudioManager.java

**Comment by StarLeet** [comment]
> `thanos.audioManager.hasAudioFocus("com.tencent.mm")`

了解到了。
