### ISSUE TITLE
tiktok使用 thanox 教程

### ISSUE THREAD

**Issue by user1121114685** [Tornaco/Thanox#624]
1,伪装你的Sim卡信息，你也可以直接关闭Sim卡读取权限
2.关闭tiktok激活VPN权限，居然是靠判断有无VPN来识别是否大陆用户。
![Screenshot_2022-11-27-05-42-00-608_github tornaco android thanos pro](https://user-images.githubusercontent.com/28774851/204110122-2099f32e-c0e8-44ce-a286-247ac452193a.jpg)

牛了个逼，为了不让中国人看费尽了苦心。

**Comment by user1121114685** [comment]
![Screenshot_2022-11-27-05-55-07-853-edit_github tornaco android thanos pro](https://user-images.githubusercontent.com/28774851/204110368-6b59adb9-9493-4871-8b34-8ed5cb4861ac.jpg)
sim卡伪装信息

**Comment by user1121114685** [comment]
代理域名信息

`tiktokv.com,tiktokcdn.com,tiktokcdn-us.com,isnssdk.com,appsflyer.com,byteoversea.com`

**Comment by PoseidonWake** [comment]
感谢，试了下，可以观看但是好像不能关注点赞

**Comment by ghost** [comment]
> 1,伪装你的Sim卡信息，你也可以直接关闭Sim卡读取权限 2.关闭tiktok激活VPN权限，居然是靠判断有无VPN来识别是否大陆用户。 ![Screenshot_2022-11-27-05-42-00-608_github tornaco android thanos pro](https://user-images.githubusercontent.com/28774851/204110122-2099f32e-c0e8-44ce-a286-247ac452193a.jpg)
> 
> 牛了个逼，为了不让中国人看费尽了苦心。

so这东西不应该放在issue里吧

**Comment by user1121114685** [comment]
> > 1,伪装你的Sim卡信息，你也可以直接关闭Sim卡读取权限 2.关闭tiktok激活VPN权限，居然是靠判断有无VPN来识别是否大陆用户。 ![Screenshot_2022-11-27-05-42-00-608_github tornaco android thanos pro](https://user-images.githubusercontent.com/28774851/204110122-2099f32e-c0e8-44ce-a286-247ac452193a.jpg)
> > 牛了个逼，为了不让中国人看费尽了苦心。
> 
> so这东西不应该放在issue里吧

不好意思打扰到你了，马上关闭。
