### ISSUE TITLE
英语下的排版错误

### ISSUE THREAD

**Issue by steve1145114** [Tornaco/Thanox#630]
![Screenshot_20221216-143902_Thanox](https://user-images.githubusercontent.com/89009827/208038170-3b97101b-af8a-424b-a7d1-41497cac44d4.png

**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
英语下的排版错误
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 将语言改为英语

**Expected behavior**（期望结果）
两个字母不应换行

**Screenshots**（截图）
![Screenshot_20221216-143902_Thanox](https://user-images.githubusercontent.com/89009827/208038454-0d9b7c44-e266-4bc6-8aa4-c7c210187016.png)

**Version（发现问题的版本）:**
 - OS: Android 13
 - Version 4.1.4-prc

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
Fixed
