### ISSUE TITLE
Google框架问题

### ISSUE THREAD

**Issue by YiRanMushroom** [Tornaco/Thanox#632]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
Google框架被莫名其妙禁用，包括Google框架，Google服务，和Google play商店。需要手动重新启用。我怀疑可能是thanox的问题。

**To Reproduce**（如何复现）
之前就出现这样问题，我把lsposed和thanox更新后就不出现这样问题，昨天更新了magisk后问题重新出现。
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
直接手动恢复了，没有保留截图，之后出现会补上。

If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - 10
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）
4.1.4_prc
**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
使用lsposed实现，magisk使用alpha版本。
** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
马上通过电脑补上

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by YiRanMushroom** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/10288612/logging.zip)

**Comment by YiRanMushroom** [comment]
![Screenshot_2022-12-23-21-34-40-530_com miui securitycenter](https://user-images.githubusercontent.com/114495322/209344759-20f98d0e-d1d9-4856-bffb-2bb3285966a7.jpg)
![Screenshot_2022-12-23-21-34-37-985_com miui securitycenter](https://user-images.githubusercontent.com/114495322/209344765-c15cf5f3-7f3a-495a-b0e7-0ed104363eef.jpg)
![Screenshot_2022-12-23-21-34-32-953_com miui securitycenter](https://user-images.githubusercontent.com/114495322/209344771-047a21e1-e3e3-4937-96b4-3c055e54dd04.jpg)
![Screenshot_2022-12-23-21-34-29-131_com miui securitycenter](https://user-images.githubusercontent.com/114495322/209344773-fe701b57-089d-4a54-ac57-3c8a66e2d44b.jpg)
又掉了一次，需要手动将三个点击启用。

**Comment by Tornaco** [comment]
@YiRanMushroom  Thanox不会主动禁用任何app，你看下是否启用了一些情景模式导致？

**Comment by YiRanMushroom** [comment]
不好意思，我后来翻日志发现是系统多开的问题。
