### ISSUE TITLE
thanox无法阻止被thanox禁用的app组件重新激活

### ISSUE THREAD

**Issue by fsxitutu** [Tornaco/Thanox#641]
**Describe the bug（现象描述）**
在thanox的应用管理中禁用app的组件，但该组件还是会被重新激活。与thanox所说会阻止被thanox禁用的组件重新激活不符

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 在应用管理的 活动管理、广播接收器管理 、服务管理、内容提供者管理 页面中禁用组件(此处以酷安的腾讯推送为例。包名com.coolapk.market，类名com.tencent.android.tpush.SettingsContentProvider)
2. 找到该组件并禁用
3. 打开酷安，刷一会(几秒钟左右)
4. 再次进入thanox，发现该组件已被重新激活。同时在MaAndroidTools中也可证实该组件处于启用状态。

**Expected behavior**（期望结果）
能阻止组件的自动重新激活

**Version（发现问题的版本）:**
 - OS: Android 13
 - Version: 4.1.4-row pro版

**Additional context**（其他信息）
1：thanox激活方式：Xposed(lsposed 1.8.5(6649)-zygisk)，作用域勾选系统框架和酷安。
2：曾尝试删除thanox日志后再次试验，未重新生成日志。故下面提供的日志文件为重启后再次试验的thanox日志+通过matlog抓取的系统日志

** Logs**（日志文件）
日志文件很长，手机端GitHub找不到上传文件功能，故使用网盘提供：https://fileserver.lanzouo.com/i66Zz0lhdwpe

**Comment by Tornaco** [comment]
@fsxitutu  试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/556/workflows/446b65ce-aff9-445b-a70e-ec5c7c669c6e/jobs/505/artifacts

**Comment by fsxitutu** [comment]
> @fsxitutu 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/556/workflows/446b65ce-aff9-445b-a70e-ec5c7c669c6e/jobs/505/artifacts



> 

感谢，有效😜。希望能尽快同步到pro版
