### ISSUE TITLE
情景模式无法自动关闭蓝牙

### ISSUE THREAD

**Issue by Matthew-Harris-36** [Tornaco/Thanox#648]
我的自动开关蓝牙的情景模式，每次打开全局变量btApps里的A应用，可以自动打开蓝牙，但关闭A应用，却不会关闭蓝牙，希望开发者大大能告诉我问题出在哪里，该怎么去解决？

Realme GT Neo3 安卓12
Thanox 4.1.1 Xpose

我有两套自动开关蓝牙的情景模式：
情景模式一：
```
[
    {
        "name": "BT Auto Control",
        "description": "蓝牙自动开关,全局变量btApps",
        "priority": 1,
        "condition": "if(frontPkgChanged && globalVarOf$btApps.contains(to) && !hw.isBTEnabled()){hw.enableBT();}else if(pkgKilled && globalVarOf$btApps.contains(pkgName) && hw.isBTEnabled()){flag=0;for(String val:globalVarOf$btApps){flag+=thanos.getActivityManager().isPackageRunning(val)?1:0};if(flag==0){hw.disableBT();}}",
        "actions": [""]
    }
]
```

情景模式二：
```
name: "蓝牙自动开启"
description: "打开应用打开蓝牙，全局变量 bt"
priority: 2
condition: "frontPkgChanged && globalVarOf$bt.contains(to) && !hw.isBTEnabled()"
actions:
    - "hw.enableBT()"
    - 'ui.showShortToast("🎉打开蓝牙")'
```
```
name: "蓝牙自动关闭"
description: "停止应用关闭蓝牙，全局变量 bt"
priority: 3
condition: "pkgKilled && globalVarOf$bt.contains(pkgName) && hw.isBTEnabled()"
actions:
- "hw.disableBT()"
- 'ui.showShortToast("🎉关闭蓝牙")'
```
[logging.zip](https://github.com/Tornaco/Thanox/files/10719485/logging.zip)

**Comment by Tornaco** [comment]
@BlueDolphin9527  你测试的关闭A应用是指如何关闭，是回到home，还是按了返回键？根据你的情景模式代码，在A应用被杀死的时候，会关闭蓝牙。

另外情景模式日志抓取方式：情景模式---Log-开启日志。 复现问题后，再抓取/data/thanos_xxx/logging 文件夹下的日志。

**Comment by Matthew-Harris-36** [comment]
> 

是划卡关闭，A应用同时也进Thanox的冻结APP名单里，划卡后直接变灰了。

**Comment by Tornaco** [comment]
> > 
> 
> 是划卡关闭，A应用同时也进Thanox的冻结APP名单里，划卡后直接变灰了。

按照上面回复里的说明，重新抓个日志看下呢。

**Comment by Tornaco** [comment]
看下划卡后，日志里又没有发布pkgKilled事件，如果没发布，可以把该应用加入“任务清理”试试。

**Comment by Matthew-Harris-36** [comment]
> 看下划卡后，日志里又没有发布pkgKilled事件，如果没发布，可以把该应用加入“任务清理”试试。

我不太懂这个，我上传下日志吧。
[log.zip](https://github.com/Tornaco/Thanox/files/10739036/log.zip)

**Comment by Tornaco** [comment]
@BlueDolphin9527 你测试的是 com.xiaomi.hm.health  这个app吗

**Comment by Matthew-Harris-36** [comment]
@Tornaco 是的

**Comment by Tornaco** [comment]
@BlueDolphin9527 看日志是没问题的，自测你的代码也是OK的；你可以进入Action console 输入 hw.disableBT() 执行，测试下是否可以关闭蓝牙。
