### ISSUE TITLE
最新的play版thanox会导致自动重启bug

### ISSUE THREAD

**Issue by a1623382** [Tornaco/Thanox#65]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
最新的play版thanox会导致自动软重启bug，原因不明
**To Reproduce**（如何复现）
触发没有规律，暂时多出现在打开app时
**Version（发现问题的版本）:**
 - OS: 氧OS 公测8 Android 10.0
 - Version 1.1.4-row
** Logs**（日志文件）
已在tg私发

**Comment by a1623382** [comment]
现发现自动软重启似乎是随机的，与是否打开app无关

**Comment by Tornaco** [comment]
@a1623382  试试最新版114的apk重新上传了，有问题再发下日志。

**Comment by Tornaco** [comment]
暂时关闭。有问题继续反馈。
