### ISSUE TITLE
启动thanox后手机卡死

### ISSUE THREAD

**Issue by GoodbyeNJN** [Tornaco/Thanox#655]
**Describe the bug（现象描述）**

使用中突然卡死，表现为：

  1. 屏幕常亮
  2. 不响应触摸和按键操作
  3. 可通过adb访问文件系统
  4. `adb shell pm list packages` 和 `adb shell pm uninstall` 无响应

重启后锁屏界面操作和adb都正常，但解锁后一两秒内再次卡死，卸载thanox后重启恢复正常。

重新安装内测版，重启后正常。在lsposed中激活，重启解锁后一开始正常，状态栏提示thanox已激活后几秒再次卡死。

**To Reproduce**（如何复现）
见现象描述

**Expected behavior**（期望结果）
正常使用

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: Android 13
 - ROM: PixelExperience
 - Kernel: 4.14.307-GulchR-PE
 - Version: 4.1.4-raw (一开始的版本), 4.1.6-raw (重新安装后的内测版)

**Additional context**（其他信息）
无

**Logs**（日志文件）
无

**Comment by GoodbyeNJN** [comment]
[logs.zip](https://github.com/Tornaco/Thanox/files/10957445/logs.zip)
两次复现过程中锁屏时和解锁时的 lsposed 日志

**Comment by Tornaco** [comment]
@GoodbyeNJN  能再抓下anr日志吗，/data/anr 

上面日志我先看着有啥线索再更新。

**Comment by GoodbyeNJN** [comment]
[logs.zip](https://github.com/Tornaco/Thanox/files/10971116/logs.zip)

重新抓取了一次日志，都保留了文件的原始时间戳

一共分为三个阶段：锁屏界面(仅lsp日志) -> 解锁后(仅lsp日志) -> 解锁一段时间后(lsp+anr日志)
前两个阶段的日志无异常，解锁一段时间后的lsp日志和anr日志显示 `com.google.android.googlequicksearchbox` 有异常

```
[ 2023-03-15T00:20:15.215    10126:  5986:  6095 E/AndroidRuntime  ] FATAL EXCEPTION: FinalizerWatchdogDaemon
Process: com.google.android.googlequicksearchbox:search, PID: 5986
java.util.concurrent.TimeoutException: android.window.WindowContext.finalize() timed out after 60 seconds
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.view.IWindowManager$Stub$Proxy.detachWindowContextFromWindowContainer(IWindowManager.java:5403)
	at android.window.WindowTokenClient.detachFromWindowContainerIfNeeded(WindowTokenClient.java:171)
	at android.window.WindowContextController.detachIfNeeded(WindowContextController.java:149)
	at android.window.WindowContext.release(WindowContext.java:114)
	at android.window.WindowContext.finalize(WindowContext.java:107)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Tornaco** [comment]
@GoodbyeNJN 能再抓下anr日志吗，/data/anr目录下。

上面的日志无法定位卡顿问题。

**Comment by GoodbyeNJN** [comment]
> @GoodbyeNJN 能再抓下anr日志吗，/data/anr目录下。
> 
> 上面的日志无法定位卡顿问题。

除了trace__00就没有其他日志了，排查哪个模块引发卡死的时候删了NoANR，后来就没有再安装

**Comment by Tornaco** [comment]
@GoodbyeNJN  那可以试试重启后手机接电脑，执行adb logcat > logs.txt，复现问题后过30s，断开设备，本地会有log.txt文件。

**Comment by GoodbyeNJN** [comment]
> @GoodbyeNJN 那可以试试重启后手机接电脑，执行adb logcat > logs.txt，复现问题后过30s，断开设备，本地会有log.txt文件。

[logs.txt](https://github.com/Tornaco/Thanox/files/10992944/logs.txt)
时间点大概在23:56附近

**Comment by Tornaco** [comment]
@GoodbyeNJN 日志里并没有看到跟卡顿相关的记录，这次/data/anr下还是没有文件？另外恢复thanox到默认数据还是会卡死吗？

**Comment by GoodbyeNJN** [comment]
> @GoodbyeNJN 日志里并没有看到跟卡顿相关的记录，这次/data/anr下还是没有文件？另外恢复thanox到默认数据还是会卡死吗？

[anr.tar.gz](https://github.com/Tornaco/Thanox/files/10999177/anr.tar.gz)
当时是没有日志的，但刚刚重新查看发现有，看时间戳像是23:56复现完问题重启恢复正常之后才生成的日志。

我现在每次复现都是全新安装thanox_4.1.5-prc(3070780)版本，全新安装应该直接就是默认数据，不需要手动清除数据吧？

**Comment by GoodbyeNJN** [comment]
最后通过删除`/data/system/thanox*`文件夹解决了问题。
这个文件夹看起来是存放了备份文件，似乎即使在重装后未打开thanox的情况下重启，thanox也会自动加载并应用这个备份
