### ISSUE TITLE
su.exe的语法怎么调整都不对

### ISSUE THREAD

**Issue by chenxiccc** [Tornaco/Thanox#656]
情景模式文件如下：

`[
  {
    "name": "Upnote with vpn",
    "description": "启动Upnote自动启动surfboard VPN",
    "priority": 1,
    "condition": "frontPkgChanged == true && to == \"com.getupnote.android\"",
    "actions": [
      "sh.exe(\"am start -W -a android.intent.action.VIEW -d \"surfboard:///start\"\");"
    ]
  }
]`

试了以下几种写法，都不行。
`
     "sh.exe("am start -W -a android.intent.action.VIEW -d \"surfboard\:\/\/\/start\"");"
`
` "sh.exe("am start \-W \-a android.intent.action.VIEW \-d \"surfboard\:\/\/\/start\"");"`

请问该怎么办呢？

**Comment by Tornaco** [comment]
@chenxiccc 试试  "su.exe(`am start -W -a android.intent.action.VIEW -d surfbord://`)"

**Comment by Tornaco** [comment]
试试  "su.exe('am start -W -a android.intent.action.VIEW -d surfbord://start')"

**Comment by Tornaco** [comment]
@chenxiccc

**Comment by chenxiccc** [comment]
@Tornaco 
su.exe('am start -W -a android.intent.action.VIEW -d surfboard:///start')
这个可以正常生效了，谢谢~
