### ISSUE TITLE
在 Android 14 DP 2 中无法检测到任何一个应用

### ISSUE THREAD

**Issue by aaa1115910** [Tornaco/Thanox#658]
- 系统版本：Android 14 DP 2
- Thanox Pro 版本：4.1.6-row，xposed
- 详细描述：Thanox Pro 无法获取到应用列表，导致所有功能均无法正常使用（功能点进去全是空列表）
  
![Screenshot_20230323-122850](https://user-images.githubusercontent.com/34527143/227103809-0fabe8bd-8c45-4749-b2fe-00320c9ebc21.png)

**Comment by aaa1115910** [comment]
[log.zip](https://github.com/Tornaco/Thanox/files/11047012/log.zip)

**Comment by Tornaco** [comment]
@aaa1115910 容我找找A14的镜像

**Comment by Tornaco** [comment]
@aaa1115910   今天14beta发布了，修了下，试试这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/610/workflows/06bee544-35dc-41f4-9ff2-c7e7c578d233/jobs/535/artifacts

**Comment by aaa1115910** [comment]
> @aaa1115910   今天14beta发布了，修了下，试试这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/610/workflows/06bee544-35dc-41f4-9ff2-c7e7c578d233/jobs/535/artifacts

即便重启多次也依旧提示请重启，应用列表依旧是空的

**Comment by Tornaco** [comment]
@aaa1115910 lsp激活的吗？帮忙抓个日志。

**Comment by aaa1115910** [comment]
> @aaa1115910 lsp激活的吗？帮忙抓个日志。

刚刚lsp取消勾选了pro版（play版）再重启后，你发的那个ci版就能用了。再重新勾选pro版，发现pro版也能读取到应用了（但是是请重启状态）
所以之前提示请重启可能是因为我没取消勾选pro版导致的

**Comment by Tornaco** [comment]
@aaa1115910 啊，是的，那等过几天推到play beta
