### ISSUE TITLE
打开冻结应用总是提示？

### ISSUE THREAD

**Issue by Matthew-Harris-36** [Tornaco/Thanox#659]
4.1.6版本，智能冻结suspend模式，最近一打开冻结程序，就会弹出下图那样的提示fail to unfreeze:包名，请问该怎么关闭？
这应该不是BUG，而是特性，所以就没上传日志。
![Thanox打开冻结应用提示](https://user-images.githubusercontent.com/62049321/227242280-1237ce5e-7b8e-40eb-98c1-20470ead5fda.jpg)

**Comment by Tornaco** [comment]
@BlueDolphin9527 我查了下代码，首先确定不是Thanox自带功能弹出来的，所以可以排查下情景模式、其他xposed模块看下。

**Comment by TQHYG** [comment]
你是否使用了Scene？Scene中的应用偏见和Thanox的智能冻结是重复的功能，两者冲突可能会引发你所描述的现象，我也遇到了，这条提示也是Scene跳出来的。解决方法是只使用其中一个的功能，如果使用Thanox的智能冻结，请把Scene的xposed模块相关功能在lsposed管理器中关闭，然后重启设备

**Comment by Matthew-Harris-36** [comment]
好吧， 感谢，我排查下。
