### ISSUE TITLE
关于在类原生a13系统上的功能性问题

### ISSUE THREAD

**Issue by Zerotii** [Tornaco/Thanox#660]
设备：一加8T
系统：nameless a13
thanox版本：4.16-prc
情况：在lsposed中打开thanox后会话微件的桌面组件无法点击互动效果（哪怕我已经在thanox中给了他启动和运行的权限），还有在激活thanox后再把某个应用切换到后台过一段时间后再切回去可能会遇到应用卡死无法点击必须关闭那个应用重新打开后才能正常使用（虽然不知道这个问题是不是因为thanox，但是我在关闭它的时候没有再次出现相关问题）

**Comment by Tornaco** [comment]
@guodaipi 你可以检查下是不是使用了一些情景模式；或者恢复thanox默认数据试试。如果还有问题麻烦先按照首页说明抓取下日志。

**Comment by Zerotii** [comment]
> @guodaipi 你可以检查下是不是使用了一些情景模式；或者恢复thanox默认数据试试。如果还有问题麻烦先按照首页说明抓取下日志。

好像不是，我卸载酷安版本使用GitHub的15版本后问题消失了

**Comment by Tornaco** [comment]
@guodaipi 好吧，那下次更新你试试4.1.7版本
