### ISSUE TITLE
记录器重现失败

### ISSUE THREAD

**Issue by 2478641181** [Tornaco/Thanox#664]
记录器随便一个消息点重现 没有效果 之前是可以的
系统版本 安卓13
机型 chopin
补丁模式 xp

**Comment by Tornaco** [comment]
@2478641181 检查下系统设置，thanox给通知权限没。

**Comment by 2478641181** [comment]
> @2478641181 检查下系统设置，thanox给通知权限没。

![Screenshot_2023-04-16-11-20-48-384_com android settings](https://user-images.githubusercontent.com/92560664/232264618-6ed39dac-2e7f-4361-8db6-159112ebd606.jpg)
都是灰色的怎么办

**Comment by Tornaco** [comment]
@2478641181  等下到 12:00 左右你试试这个包。https://app.circleci.com/pipelines/github/Tornaco/Thanox/601/workflows/742bd334-6191-4e4a-bdd0-9ecc2c9d869f/jobs/528/artifacts
