### ISSUE TITLE
应用锁疑似会导致应用无法滑动

### ISSUE THREAD

**Issue by HyperCherry** [Tornaco/Thanox#665]
日志文件：[log.zip](https://github.com/Tornaco/Thanox/files/11159014/log.zip)
![Screenshot_20230404-092325_Mosaic_9_24_10](https://user-images.githubusercontent.com/20416586/230088675-2cd8cf49-1453-4989-9f1a-143701e288f5.png)

**Describe the bug（现象描述）**
对部分应用开启应用锁（已测Telegram、Nekogram）时，使用解锁方式解锁应用后，应用主界面偶现无法滑动。关闭应用锁重启应用可以解决问题。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入被应用锁锁定软件
2. 使用解锁方式解除应用锁
3. 上下滑动应用界面
4. 应用界面无法被滑动

**Expected behavior**（期望结果）
应用界面能够被滑动

**Screenshots**（截图）
（见附件）

**Version（发现问题的版本）:**
 - OS: Android 11
 - Version 4.1.7-row

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本：Android 11
> 2. Thanox版本，补丁方式（xposed还是magisk？）：4.1.7-row、lsposed(zygisk)
> 3. 问题现象的详细描述，有图或者视频更好：见附件
> 4. 不激活thanox有问题吗？：无
> 5. Thanox激活后不做任何配置有问题吗？：无
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里：见附件

**Comment by Tornaco** [comment]
@HyperCherry 试试这个呢，重新设计了一下应用锁的实现。

https://app.circleci.com/pipelines/github/Tornaco/Thanox/578/workflows/d71c6eb2-3531-4b1c-8e1e-7a346b779838/jobs/524/artifacts

**Comment by HyperCherry** [comment]
OK！！，先试试看
