### ISSUE TITLE
情景模式su无法授权

### ISSUE THREAD

**Issue by GentsunCheng** [Tornaco/Thanox#666]
**Describe the bug（现象描述）**
首次申请su权限的时候未授权，之后则无法正确申请su权限，magisk的超级用户列表也并未找到thanox

1. 系统版本  oneui5.0 Android13
2. lsposed激活
3. magisk版本v26.0

日志等详细信息有时间再补，目前没有尝试重启后是否能恢复

**Comment by Tornaco** [comment]
@GentsunCheng 情景模式引擎里开关一下 su引擎试试
