### ISSUE TITLE
情景模式全部不生效，延迟生效

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#669]
安卓11，MIUI12.5.7，应用版本4.1.8-prc
所有的情景模式不生效了，要么就是延迟很大，比如连接WiFi关闭数据，连接上WiFi之后要过很久，就突然来一下关闭数据的tost提示，是以前都是秒的，还有其他的大量情景模式都不生效
![IMG_20230420_065800](https://user-images.githubusercontent.com/106238637/233217772-0fc51aba-8a9c-485e-a6ea-6fbd6a6282d5.jpg)
![IMG_20230420_065812](https://user-images.githubusercontent.com/106238637/233217787-340601c6-97dd-4b30-becb-285cf95b6aa9.jpg)
![IMG_20230420_065821](https://user-images.githubusercontent.com/106238637/233217795-6c6fe1a6-eb1f-438e-97e3-8a7f6fc2deb7.jpg)
![IMG_20230420_065831](https://user-images.githubusercontent.com/106238637/233217798-b916a400-82ea-40b5-bc11-9b290377ee85.jpg)
![IMG_20230420_065841](https://user-images.githubusercontent.com/106238637/233217800-f56044f3-455e-4fb4-ad4f-66f8ecfe93ad.jpg)
[magisk_log_2023-04-20T06.58.56.log](https://github.com/Tornaco/Thanox/files/11278122/magisk_log_2023-04-20T06.58.56.log)
[LSPosed_2023-04-20T06_58_49.762.zip](https://github.com/Tornaco/Thanox/files/11278124/LSPosed_2023-04-20T06_58_49.762.zip)
[logging (1).zip](https://github.com/Tornaco/Thanox/files/11278125/logging.1.zip)

**Comment by diweisong** [comment]
好像是su api的问题，还是这个[
{
"name": "当应用进入后台杀死",
"description": "应用进入后台1分钟后杀死",
"priority": 1,
"condition": "frontPkgChanged",
"actions": [
"Thread.sleep(60000);",
"foreach(needKill : globalVarOf$frontPkgChangedKill){ thanos.activityManager.killProcessByName(needKill); }"
]
}
]
情景模式的问题？
开启了这个情景模式，所有情景模式就会不生效
要再次全部生效的话，需要把这个情景关闭，重新开关suAPI过一会儿才会恢复
这是软件bug还是情景模式？

**Comment by diweisong** [comment]
应该不是这个情景模式的问题，是应用本身的问题，suapi会自己掉，掉了之后需要重新开关才会生效

**Comment by diweisong** [comment]
100%复现方法，输入这个情景[
{
"name": "当应用进入后台杀死",
"description": "应用进入后台1分钟后杀死",
"priority": 1,
"condition": "frontPkgChanged",
"actions": [
"Thread.sleep(60000);",
"foreach(needKill : globalVarOf$frontPkgChangedKill){ thanos.activityManager.killProcessByName(needKill); }"
]
}
]
开启之后所有情景模式会失效，suapi不管重新开关都无用
关闭该情景，thanox后台清掉，重新开关suapi，这时候之前堆积的情景操作也会重新复活，比如关闭数据

**Comment by Tornaco** [comment]
@diweisong 你这里线程休眠时间较长，导致执行情景模式的线程被阻塞。建议将priority改为-1（优先级小于0），这样这条情景模式会在新线程执行，不会阻塞其他。

**Comment by diweisong** [comment]
> @diweisong你这里休眠时间，导致导致导致执行执行模式模式的线程线程线程被被建​​议阻塞。建议将。。。建议建议建议建议将改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为改为阻塞。。。建议阻塞阻塞阻塞阻塞。建议。。建议。。。建议。。建议。建议建议（（（（（（（（（建议（（（（（（（（（（建议（（（（（（（（（（（（（（（（（（（（（（（（（（（（（（（（（小于建议建议建议。

已经好了
