### ISSUE TITLE
4.1.8的notificationRemoved可能存在一个小问题

### ISSUE THREAD

**Issue by sidesand** [Tornaco/Thanox#671]
**Describe the bug（现象描述）**
4.1.7版本的notificationRemoved，可以监测到大多数通知取消动作，包括点击mipush推送的通知（例如QQ的mipush推送的通知，亦或者正常微信推送的通知），点击该通知后，该通知移除同时跳转到QQ，这个“由点击导致的通知取消”的过程4.1.7是可以监测到的。
但是4.1.8版本却无法监测到“点击通知而引起的通知取消”，只能监测“划掉该通知或者清除通知按钮”引起的通知取消。

当然，原4.1.7版本的notificationUpdated无法监测多条QQ消息引起的通知更新，4.1.8可以监测了。

系统是：MIUI 14 V14.0.23.4.10.DEV，安卓13
开发版，不知道是个例还是

**Comment by Tornaco** [comment]
@sidesand 上个版本更换了通知监听方案，系统没有把点击后的取消事件传递出来。我自己简单处理了一下，你可以测试下：https://app.circleci.com/pipelines/github/Tornaco/Thanox/606/workflows/ad0442f0-4fbf-4ac0-b1f6-cc920b57d5be/jobs/532/artifacts

**Comment by sidesand** [comment]
这个版本点击通知导致的通知取消可以监测到了。感谢！

不知道后续能不能解决#670 的连接第二个蓝牙问题
