### ISSUE TITLE
情景模式不触发

### ISSUE THREAD

**Issue by powerAn2020** [Tornaco/Thanox#674]
**Describe the bug（现象描述）**
情景模式中配置应用切换不触发(Toast 都不显示)。

**To Reproduce**（如何复现）
### 配置信息
```json
[
  {
    "name": "v2rayn",
    "description": "开启v2rayng",
    "priority": 5,
    "condition": "frontPkgChanged == true && globalVarOf$vpn_list.contains(to)",
    "actions": [
      "ui.showShortToast('启动代理');",
      "su.exe('am start -a android.intent.action.VIEW -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity');"
    ]
  }
]
```
### 全局变量 vpn_list
```json
[
  "com.google.android.youtube",
  "​com.android.vending",
  "​org.telegram.messenger",
  "​com.aurora.store",
  "​com.netflix.mediaclient",
  "​com.fox2code.mmm​",
  "com.valvesoftware.android.steam.community"
]
```
**Version（发现问题的版本）:**
 - OS: [MIUI 14.0.6 稳定版(Android 13)]
 - Version [Thanox 4.1.8-row xposed]

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[log.zip](https://github.com/Tornaco/Thanox/files/11339897/log.zip)

**Comment by Tornaco** [comment]
@powerAn2020 导入自带的示例，“Use var example” 能弹出Toast吗？

**Comment by powerAn2020** [comment]
样例`current pkg`是可以正常打印的。而且诡异我上面定义的软件中只有“com.google.android.youtube” 成功显示Toast，其他的软件都没反应。另外启用了多项辅助功能（包含了`轻启动`的坐标模式，但是我去掉后现象依旧存在，不确定是否有冲突的情况）

**Comment by Tornaco** [comment]
@powerAn2020  也可以看下情景模式的日志，切换应用有没有对应日志记录。
