### ISSUE TITLE
功能请求：自动勾选隐匿app作用域

### ISSUE THREAD

**Issue by powerAn2020** [Tornaco/Thanox#675]
隐匿模式说明中需要为应用开启xposed作用域才能生效。是否可以参照这个[模块](https://github.com/Houvven/Guise)加入自动勾选app呢
![image](https://user-images.githubusercontent.com/25736019/234835852-bb99116d-e6cb-4612-91a4-686cdfe29774.png)

**Comment by Tornaco** [comment]
@powerAn2020  你给的项目没有参考性。我看了下最新libxposed介绍，加了一下。你可以试试，设置里有开关和说明。https://app.circleci.com/pipelines/github/Tornaco/Thanox/619/workflows/79a29b0d-4b96-4257-922d-8d4aef643823/jobs/544/artifacts

**Comment by powerAn2020** [comment]
>大佬，这个需要先卸载掉pro版本吗，我试了下去掉pro的作用域，并启动ci版本的作用域，重启后，在隐匿模式中选择app后发现lsposed没有自动勾选目标。
完全卸载pro后重试的日志：
[log.zip](https://github.com/Tornaco/Thanox/files/11493886/log.zip)

**Comment by Tornaco** [comment]
@powerAn2020 不用卸载，需要更新LSOPSed框架到最新版本，在CI版本里进行隐匿设置，说明里也写了要允许Thanox自启动，需要检查下系统设置。

**Comment by Tornaco** [comment]
@powerAn2020 你现在的lsp版本是多少了。

**Comment by powerAn2020** [comment]
@Tornaco 最新稳定版zygisk1.8.6（6712），这是我的操作
![操作](https://github.com/Tornaco/Thanox/assets/25736019/3e899967-c441-4088-b571-b9a8225f22d0)

**Comment by Tornaco** [comment]
@powerAn2020  看LSP 1.8.6 日志 
https://github.com/LSPosed/LSPosed/releases/tag/v1.8.6
这个特性应该在下个LSP版本才会实现。

> 新的 Xposed API 提案
随着 Android 版本的迭代，原有的 rovo89 Xposed API 已经达到了极限。 我们正在开发新的现代 Xposed API，它具有模块作用域管理、远程配置文件、dex 解析器接口等功能。
新的 API 将在 LSPosed 的下一个版本中实现，欢迎在 https://github.com/libxposed 上发表您的建议。


我自己打包了最新的lsp源码，你可以测试下。

[LSPosed-v1.8.6-6894-zygisk-debug.zip](https://github.com/Tornaco/Thanox/files/11494037/LSPosed-v1.8.6-6894-zygisk-debug.zip)

**Comment by powerAn2020** [comment]
> @powerAn2020 看LSP 1.8.6 日志 https://github.com/LSPosed/LSPosed/releases/tag/v1.8.6 这个特性应该在下个LSP版本才会实现。
> 
> > 新的 Xposed API 提案
> > 随着 Android 版本的迭代，原有的 rovo89 Xposed API 已经达到了极限。 我们正在开发新的现代 Xposed API，它具有模块作用域管理、远程配置文件、dex 解析器接口等功能。
> > 新的 API 将在 LSPosed 的下一个版本中实现，欢迎在 https://github.com/libxposed 上发表您的建议。
> 
> 我自己打包了最新的lsp源码，你可以测试下。
> 
> [LSPosed-v1.8.6-6894-zygisk-debug.zip](https://github.com/Tornaco/Thanox/files/11494037/LSPosed-v1.8.6-6894-zygisk-debug.zip)

在这一版LSPosed中已生效并在通知栏弹出请求，允许后LSPosed正常勾选，感谢大佬。

**Comment by powerAn2020** [comment]
@Tornaco 大佬，请问pro版何时可以上线这个功能，lsposed已更新到1.9.1版本
