### ISSUE TITLE
情景模式经常不触发或者说不生效

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#676]
[LSPosed_2023-04-28T19_01_46.095.zip](https://github.com/Tornaco/Thanox/files/11352851/LSPosed_2023-04-28T19_01_46.095.zip)
[logging.zip](https://github.com/Tornaco/Thanox/files/11352852/logging.zip)
我这个情景在4.1.6没问题，升到4.1.8就经常出现息屏不划卡，退回到4.1.7也这样了，能不能看看啥情况，安卓11，MIUI12.5.7
![IMG_20230428_190307](https://user-images.githubusercontent.com/106238637/235131919-7d858acc-f173-4176-9875-a266453eebce.jpg)

**Comment by Tornaco** [comment]
@diweisong  关掉其他情景模式试试，或者检查下是否有其他情景模式使用了长时间的sleep操作。
