### ISSUE TITLE
冻结应用以后，把冻结的应用卸载，重新安装冻结的应用直接自动重启，无法进行安装

### ISSUE THREAD

**Issue by 1airman12** [Tornaco/Thanox#678]
我遇到一个问题在thanox里面冻结了QQ，但是我不小心把QQ卸载掉了，现在只要安装QQ就会自动重启，怎么解决，安装别的应用不会重启

**Comment by svipm** [comment]
安卓12
在不激活thanox的时候也无法安装QQ，也是会出现软重启，``

**Comment by Tornaco** [comment]
@1airman12 能抓下系统日志吗，或者看下data/tombstone下有日志文件没，发出来看下系统重启的原因；罕见的问题。

**Comment by Tornaco** [comment]
暂时关闭，有日志再open
