### ISSUE TITLE
如何创建一个 Pkg 对象

### ISSUE THREAD

**Issue by GoodbyeNJN** [Tornaco/Thanox#679]
我在翻看源码时，注意到一些签名中带有 `String pkgName` 参数类型的函数已标记为 deprecated，新增了 `Pkg pkg` 参数类型的同名函数，猜测是为了能正确处理分身应用。

`github.tornaco.android.thanos.core.pm.Pkg` 提供了几个静态方法来创建 `Pkg` 对象，但在情景模式中使用 Thanos API 时，似乎找不到办法直接调用这几个方法。

请问目前的 Thanos API 是否提供了类似的方法，如果没有的话，是否会考虑加入相关方法？

**Comment by Tornaco** [comment]
@GoodbyeNJN 确实是为了多用户加的一个Class。我在里面加了一个新的静态方法，可以在表达式里通过`Pkg.newPkg("PKG_NAME", USER_ID)` 来创建对象了。要测试的话，可以先试试 https://app.circleci.com/pipelines/github/Tornaco/Thanox/607/workflows/002e28b8-7bd7-404a-8113-7c56f1b4a03c/jobs/533/artifacts

**Comment by GoodbyeNJN** [comment]
@Tornaco 感谢解答。

另外还有两点麻烦再看看：
1. Action Console 里运行代码时，如果有报错，界面上无任何显示，日志里也不输出报错信息，这个能不能考虑优化一下？
2. 情景模式的 actions 字段是个字符串数组，是不是可以理解为每一条都是单独运行，相互之间上下文独立、不共享变量的？

**Comment by GoodbyeNJN** [comment]
3. 我目前通过 `su.exe("pm list packages -3 --user " + pkg.getUserId() + " | grep " + pkg.getPkgName())` 来验证某个 pkg 是否真实存在，Thanos API 里能不能提供相关的验证方法？

**Comment by Tornaco** [comment]
@GoodbyeNJN 1. 日志加上了，你测试下。2.  是独立的

**Comment by Tornaco** [comment]
@GoodbyeNJN thanos.pkgManager.getAppInfo(Pkg.newPkg("PACKAGE_NAME", USER_ID)) != null 如果为true，就表示应用已安装。

**Comment by GoodbyeNJN** [comment]
@Tornaco 感谢，不过我现在测试不了，我是在 google play 购买的，暂时验证不了
