### ISSUE TITLE
thanox应用锁在特定场景会崩溃

### ISSUE THREAD

**Issue by Pennages** [Tornaco/Thanox#680]
**Describe the bug（现象描述）**
应用锁在特定场景生物识别（例如指纹）错误时会导致弹窗thanox停止运行。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 打开任意被加入应用锁的应用（不要退出该应用）
2. 将手机锁屏
3. 打开屏幕，解锁，随后就会出现thanox应用锁
4. 随后进行生物识别（我这边用指纹），因为识别不出我的手指，然后就直接弹出错误随后闪退重进。

**Screenshots**（截图）
下面是出错截图
![Screenshot_20230512_215457_Thanox](https://github.com/Tornaco/Thanox/assets/38871500/d0513e2c-9244-4c51-8eb4-beed0f525516)
下面是复现视频（录屏录不出😭
https://github.com/Tornaco/Thanox/assets/38871500/bff6fbc1-8a61-4649-8330-d104974762a6

**Version（发现问题的版本）:**
 - OS: Android 13 (OneUI 5.1)
 - Version: 4.1.8-prc
 - Thanox补丁方式:Xposed (Lsposed1.8.6(6712))

** Logs**（日志文件）
这是thanox崩溃日志(系统自带dropbox)
[data_app_crash@1683900653559.txt](https://github.com/Tornaco/Thanox/files/11465010/data_app_crash%401683900653559.txt)
这是thanox自带日志，大概是从12251行左右开始
[thanox-core.log.txt](https://github.com/Tornaco/Thanox/files/11465093/thanox-core.log.txt)

**Comment by Tornaco** [comment]
@Pennge 收到。下来我试试。

**Comment by Tornaco** [comment]
@Pennge 试试这个版本：https://app.circleci.com/pipelines/github/Tornaco/Thanox/613/workflows/9b7cde73-d59c-4f71-a5c8-a0cec1eebef7/jobs/538/artifacts

**Comment by Pennages** [comment]
@Tornaco 非常感谢，已经解决了我上述问题。但现在又出现了另一个小问题（仅仅只是偶尔出现而已，个人感觉不影响使用），就是和上面一样的测试步骤，只不过最后一步指纹识别错误以后，原先的thanox弹出停止运行窗口变为了thanox闪出重进thanox应用锁的界面
下面这一张是正确的：识别错误后的，直接闪出界面
https://github.com/Tornaco/Thanox/assets/38871500/a9eea383-8aa4-465e-80b6-fe50305922b2

下面是另一个识别错误的：识别指纹错误后又重新进入thanox应用锁，同时也在下面的log文件的67931行输出了错误，貌似和之前上传的thanox日志一样的错误🤔
https://github.com/Tornaco/Thanox/assets/38871500/35a61ffa-30ce-4415-bcfd-c58565855474
这是thanox的log文件，系统dropbox与tombstones没有输出错误log
[thanox-core-2.log.txt](https://github.com/Tornaco/Thanox/files/11470017/thanox-core-2.log.txt)

**Comment by Tornaco** [comment]
@Pennages 日志中确实有错误，不过这个错误跟应用锁无关，你发下/system/framework/services.jar 我先试试把错误消除。

**Comment by Pennages** [comment]
@Tornaco 👌
[service.jar](https://wwkt.lanzoul.com/isIH00w70uoj)

**Comment by Tornaco** [comment]
@Pennages s试试这个版本，错误应该修复了，但是应用锁的问题暂时没修复，我试了下小概率能复现，不太好修。 https://app.circleci.com/pipelines/github/Tornaco/Thanox/616/workflows/f3de2db4-d79a-4b44-be2b-681e551b4875/jobs/541/artifacts

**Comment by Pennages** [comment]
@Tornaco 错误已修复，非常感谢Orz
