### ISSUE TITLE
微信代收问题

### ISSUE THREAD

**Issue by ngguanrui74** [Tornaco/Thanox#684]
**Describe the bug（现象描述）**
微信代收在正常情况下没有任何问题但是只要我一连接电脑版微信通知就只会在电脑了然后我一断开连接就恢复正常了

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 登录电脑版微信
2. 使用小号发送消息（只有电脑有消息）
3. 电脑断开连接
4. 再次使用小号发送消息（正常了，而且还非常快）

**Expected behavior**（期望结果）
我觉得这可能不是bug，可能原本就这样但是我希望能改掉这个，就和原版微信一样

**Screenshots**（截图）
没有截图

**Version（发现问题的版本）:**
 - OS: android 13 
 - Version：4.2.0-prc
 
**Additional context**（其他信息）
pe系统 三月份更新设备是k40

Add any other context about the problem here.（其他的补充信息）
补充一下我是海外的所以我的fcm绝对是正常的，不是vpn的问题

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------
[thanox-core.log](https://github.com/Tornaco/Thanox/files/11600621/thanox-core.log)

[thanox-init.log](https://github.com/Tornaco/Thanox/files/11600623/thanox-init.log)

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. android 13
> 2. xposed
> 3. 微信代收在正常情况下没有任何问题但是只要我一连接电脑版微信通知就只会在电脑了然后我一断开连接就恢复正常了
> 4. 不确定
> 5. 没有
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@ngguanrui74 你好，由于收发push消息策略是腾讯做的，thanox只负责展示接收到的push消息。这类问题目前无解。

**Comment by ngguanrui74** [comment]
明白
