### ISSUE TITLE
建议优化UI

### ISSUE THREAD

**Issue by Guhe-o** [Tornaco/Thanox#685]
![Screenshot_2023-05-31-14-04-50-968_github tornaco android thanos pro](https://github.com/Tornaco/Thanox/assets/67861307/5ba627bf-f5be-4d52-94c2-ea795670d293)
很明显对不上数字

**Comment by Tornaco** [comment]
@Termux000001  哪个数字对不上？ 麻烦把期望数字与实际数字表述清楚。

**Comment by Tornaco** [comment]
看到了，是CPU吧，这个问题这么久才被爆出来。。

**Comment by Tornaco** [comment]
改好了 https://app.circleci.com/pipelines/github/Tornaco/Thanox/625/workflows/3dea6228-a0eb-4891-a033-b345bf644098/jobs/550/artifacts

@Termux000001

**Comment by Guhe-o** [comment]
我是Pro版，等推送

**Comment by Guhe-o** [comment]
右边的UI能否优化一下，不看数字%根本分不清mem是外圆还是内圆

**Comment by kengbiNO1** [comment]
> 看到了，是CPU吧，这个问题这么久才被爆出来。。

这个问题有年头了，估计是没什么功能性问题，就没人提交
