### ISSUE TITLE
是否可以添加两个API，可供情景模式调用

### ISSUE THREAD

**Issue by kengbiNO1** [Tornaco/Thanox#693]
**您的功能请求是否与问题有关？请描述**
添加可以将指定应用开启/关闭乖巧模式的接口

**描述您想要的解决方案**
我正在使用FCM推送微信消息，但谷歌服务太耗电了，若将其添加到乖巧模式中，在使用谷歌商店时，还需关闭乖巧模式，否则无法连接。
所以我的想法就是
在打开代理软件时，自动将谷歌服务从乖巧模式中删除
在杀掉代理软件时，自动将谷歌服务加入到乖巧模式中

**描述你考虑过的替代方案**
我试过冻结FCM推送不需要的服务，但手机重启后不会自动解冻，怕到时候再死机了，就没再试。
也想过轮询杀掉不需要的服务，但又太浪费CPU性能，不太合适。
试过替换谷歌为microg，这个确实省电，也会推送消息，但microg会和我手机系统有冲突，安装特定软件时，会软重启，并自动关闭面具的zygisk选项。我手机系统为oneui5.1

**Comment by Tornaco** [comment]
@kengbiNO1 

以下API现有版本可直接调用：

将app加入乖巧：
```
thanos.activityManager.setPkgSmartStandByEnabled("com.xx.xx", true)
```

将app移除乖巧：
```
thanos.activityManager.setPkgSmartStandByEnabled("com.xx.xx", false)
```

**Comment by kengbiNO1** [comment]
好的，使用正常
