### ISSUE TITLE
在 14 Beta3 中未激活

### ISSUE THREAD

**Issue by aaa1115910** [Tornaco/Thanox#695]
**Describe the bug（现象描述）**
在 14b3 中未激活

**To Reproduce**（如何复现）
pixel6pro 更新到 14b3 后出现未激活情况

**Expected behavior**（期望结果）
在 14b3 中能正常使用

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: Android 14 Beta 3
 - Version 4.2.1-row - lsposed

**Additional context**（其他信息）
无

** Logs**（日志文件）
未输出任何日志

**Comment by Tornaco** [comment]
@aaa1115910 https://app.circleci.com/pipelines/github/Tornaco/Thanox/643/workflows/e1f84635-a293-4b2d-9673-ae8341934f2d/jobs/566/artifacts

**Comment by aaa1115910** [comment]
> @aaa1115910 https://app.circleci.com/pipelines/github/Tornaco/Thanox/643/workflows/e1f84635-a293-4b2d-9673-ae8341934f2d/jobs/566/artifacts

能用👍
