### ISSUE TITLE
4.2.2無法激活

### ISSUE THREAD

**Issue by gblje** [Tornaco/Thanox#697]
**Describe the bug（现象描述）**
4.2.2無法激活

**To Reproduce**（如何复现）
更新後重啟顯示未激活

**Expected behavior**（期望结果）
成功激活

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: Android 13
 - Thanox：4.2.2-row [激活方式：lsp 1.8.6 (6712) Zygisk]

**Additional context**（其他信息）
无

** Logs**（日志文件）
[thanox-core.log](https://github.com/Tornaco/Thanox/files/11705211/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/11705212/thanox-init.log)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@gblje xposed里重新勾选试试呢

**Comment by gblje** [comment]
> 
@Tornaco 
我在lsp把“系统框架”取消打勾，弹出来重启。启动手机后，“系统框架”默认打勾的，不过thanox还是未激活

**Comment by Tornaco** [comment]
@gblje lsp日志也发一下吧。4.2.1你可以激活吗？

**Comment by gblje** [comment]
@Tornaco 4.2.1也是不行。
[LSPosed_2023-06-09T20_19_12.471008.zip](https://github.com/Tornaco/Thanox/files/11706161/LSPosed_2023-06-09T20_19_12.471008.zip)
[LSPosed_2023-06-09T20_19_07.606897.zip](https://github.com/Tornaco/Thanox/files/11706165/LSPosed_2023-06-09T20_19_07.606897.zip)

**Comment by Tornaco** [comment]
@gblje 好的，我先看看日志，那你哪个版本行呢？

**Comment by gblje** [comment]
@Tornaco 我这是pixel 7 pro新手机，安装的是4.2.1，一直都不能用。我另外的旧手机 lsp 6712 ，thanox 4.1.6可以正常使用。

**Comment by Tornaco** [comment]
@gblje 你是不是还安装thanox的magisk补丁了？magisk补丁和lsp勾选只能同时用一个哦

**Comment by gblje** [comment]
@Tornaco 我尝试过装magisk补丁，但是他会提示我有2个激活方法，然后闪退，一直循环。并且使用指纹识别功能会导致手机重启。最后删除了magisk激活方法～

**Comment by Tornaco** [comment]
@gblje 有点晕了，现在是用的lsp还是magisk？ 要不手动把/data/system/thanos_xxx/logging删除，重新抓下thanox日志吧，之前你发的日志还是带magisk信息的，不好定位。

**Comment by gblje** [comment]
@Tornaco 现在都是lsp激活。删掉logging过后，不管在lsp重新启动或者在thanox操作。/data/system/thanos_xxx/logging文件夹都没有生成～

**Comment by Tornaco** [comment]
@gblje 试试这个版本，我加了一些日志；测试完还是发lsp日志 和 thanox日志（不一定有）

[thanox_4.2.2-1-1b01935-dirty-prc(3071483).apk.zip](https://github.com/Tornaco/Thanox/files/11711190/thanox_4.2.2-1-1b01935-dirty-prc.3071483.apk.zip)

**Comment by gblje** [comment]
@Tornaco 它显示“请重启”，不再是“未激活”。重启过后还是显示“请重启”。
lsp
[LSPosed_2023-06-10T09_44_44.229704.zip](https://github.com/Tornaco/Thanox/files/11711221/LSPosed_2023-06-10T09_44_44.229704.zip)
[LSPosed_2023-06-10T09_44_53.155980.zip](https://github.com/Tornaco/Thanox/files/11711222/LSPosed_2023-06-10T09_44_53.155980.zip)
thanox
[thanox-core.log](https://github.com/Tornaco/Thanox/files/11711223/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/11711224/thanox-init.log)

**Comment by Tornaco** [comment]
@gblje 要把pro版本取消勾选。

**Comment by gblje** [comment]
@Tornaco 重启之后可以激活使用了，
lsp
[LSPosed_2023-06-10T10_19_50.771444.zip](https://github.com/Tornaco/Thanox/files/11711293/LSPosed_2023-06-10T10_19_50.771444.zip)
[LSPosed_2023-06-10T10_19_55.427811.zip](https://github.com/Tornaco/Thanox/files/11711294/LSPosed_2023-06-10T10_19_55.427811.zip)
thanox
[thanox-core.log](https://github.com/Tornaco/Thanox/files/11711295/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/11711296/thanox-init.log)

**Comment by Tornaco** [comment]
@gblje 晚点重新推个play版本你再试试，其实什么都没改，play版本你不能激活就很奇怪😂

**Comment by gblje** [comment]
@Tornaco 好好，感谢～我之前也在github下过不是play版，也是未激活 T_T

**Comment by gblje** [comment]
@Tornaco 感觉是被你发的thanox激活了一般，我把你发的thanox关闭，再把pro启动，你竟然可以正常激活了。

**Comment by Tornaco** [comment]
@gblje 确实，本来不能激活就比较奇怪。。你先用着看，下个版本也试试

**Comment by gblje** [comment]
@Tornaco 好的~感谢
