### ISSUE TITLE
后台启动规则失效

### ISSUE THREAD

**Issue by StarLeet** [Tornaco/Thanox#698]
1. Thanox 4.19+   LSP激活
2. android 12L

规则内容如下, 在App中无法阻止跳到微信
![556ACFC944F477C808E6FB8ADB6E15BA](https://github.com/Tornaco/Thanox/assets/89691566/b546a698-3865-42e9-9196-fbddc721f88c)

**Comment by Tornaco** [comment]
@StarLeet  后台启动功能，作用是拦截服务进程等自启动；是不能拦截Activity页面启动的。
