### ISSUE TITLE
强烈建议增加黑名单功能

### ISSUE THREAD

**Issue by fengxi000** [Tornaco/Thanox#699]
MIUI13 13.0.3
激活thanox后微信不保活，掉后台
去激活正常运行，可以存活后台
建议增加黑名单，排除某些三方应用

**Comment by fengxi000** [comment]
MIUI13 13.0.3
激活thanox后微信不保活，掉后台
去激活正常运行，可以存活后台
建议增加黑名单，排除某些三方应用

**Comment by Tornaco** [comment]
@fengxi000  恢复默认thanox配置试试吧，正常情况都是你自己做的一些配置或开启了某些功能导致的，默认是不会影响微信的。
