### ISSUE TITLE
tiktok隐匿

### ISSUE THREAD

**Issue by pockyneko** [Tornaco/Thanox#701]
**Describe the bug（现象描述）**
隐匿tiktok后无法点赞与关注，会出现一瞬间但是之后会消失，收藏功能应该是正常的，但是有时候也会出现收藏一瞬间然后消失（简洁的描述该bug的现象）

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 点赞或者关注（进入XXX）
2. 转到个人里，可以看到哥刚刚点赞或收藏的出现一瞬间，然后消失（点击XXX）
3. 美区和日区都是这样的问题，手机时区未更改，语言为英语

**Expected behavior**（期望结果）
可以正常使用（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
啊，这个我怕是无解，或者看其他人是有经验的能判断出是哪个field导致tiktok的逻辑判断出现分支。 @Rnreck

**Comment by pockyneko** [comment]
好吧,估计是新更新出来的判断策略之类的,之前用的话还是可以做到完美隐匿的
