### ISSUE TITLE
情景模式变量添加bug

### ISSUE THREAD

**Issue by HedeNgYoung** [Tornaco/Thanox#703]
反馈一个bug,如果一个情景模式中的进程变量要加两个变量,要两个进程连在一起加，如图中的哔哩哔哩。如果不连在一起，手机重启后，后加的那个进程会消失，比如说这两个哔哩哔哩的变量中间隔了其他什么变量，重启后，这个叫ijkservice的变量就会消失。 

**Version（发现问题的版本）:4.2.2.prc
 - OS: A13
 - Version [e.g. v2.3.4]:4.2.2.prc

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by HedeNgYoung** [comment]
![Screenshot_2023-06-12-20-28-35-082_github tornaco android thanos-edit](https://github.com/Tornaco/Thanox/assets/60473778/f252c361-b988-4c9f-8d38-16e4e8632a61)

**Comment by Tornaco** [comment]
@HedeNgYoung 能按照1、2、3这种方式，列一下复现步骤吗，我操作半天没复现。

**Comment by HedeNgYoung** [comment]
1.先添加tv.danmaku.bili，再添加com.qiyi.video，最后添加tv.danmaku.bili:ijkservice，如图
![Screenshot_2023-06-13-17-55-11-650_github tornaco android thanos](https://github.com/Tornaco/Thanox/assets/60473778/98287545-e793-4027-adbd-533300204a9c)。重启后。tv.danmaku.bili:ijkservice会消失，如图
![Screenshot_2023-06-13-17-56-54-002_github tornaco android thanos](https://github.com/Tornaco/Thanox/assets/60473778/92327fb4-29a6-4a4a-86a8-52702a74adc6)

**Comment by HedeNgYoung** [comment]
> 
看上面的评论

**Comment by Tornaco** [comment]
@HedeNgYoung  刚试了没复现，我猜测是添加最后一个你立刻重启了，由于thanox内部缓存还没写入磁盘（内部有缓存优化，防止频繁读取磁盘），导致最后一条丢失了。是正常的。
