### ISSUE TITLE
应用锁是否能设置Activity白名单

### ISSUE THREAD

**Issue by Typhonling** [Tornaco/Thanox#708]
**Is your feature request related to a problem? Please describe.**
应用锁对某些Activity来说反而是个麻烦。举例来说，我需要对VPN软件上锁，但当我使用快捷方式切换VPN开关时却造成不便（如使用Tasker根据网络环境自动开关VPN）

**Describe the solution you'd like**
设置Activity白名单

**Describe alternatives you've considered**
请参考https://github.com/Maxr1998/MaxLock

**Additional context**

**Comment by Tornaco** [comment]
@Typhonling 合理，晚点弄一下。

**Comment by Tornaco** [comment]
@Typhonling  https://app.circleci.com/pipelines/github/Tornaco/Thanox/661/workflows/18f54075-d188-4098-a77c-d277d61294cc/jobs/583/artifacts

**Comment by Typhonling** [comment]
谢谢！另外忘了提，现在应用锁是调用系统锁，如果thanox自身有独立的锁定方式就更好了。
