### ISSUE TITLE
google play外区价格问题

### ISSUE THREAD

**Issue by wuyilingwei** [Tornaco/Thanox#711]
嗯，平心而论18块没啥问题，但是美区4.5刀，加区6刀，价格已经到30+了
![image](https://github.com/Tornaco/Thanox/assets/53390868/d2913683-2b83-4de3-830a-172602c65fc3)
希望能修改各区价格

**Comment by Tornaco** [comment]
美区4.5是固定的，几年前就是这个价格了，其他地区貌似是谷歌自己生成的的。

**Comment by Tornaco** [comment]
@yige-yigeren 哦，刚看了价格可以改，我去改下CA

**Comment by Tornaco** [comment]
加拿大
CAD 5.99  目前已经是这个价格了，换成USD就是4.53$
