### ISSUE TITLE
软件关闭了自启动后fcmfix也无法拉起fcm的软件推送

### ISSUE THREAD

**Issue by sujiuer5201314** [Tornaco/Thanox#712]
如果要拉起需要开启应用自启动，那么软件就会随意自启动，关闭了就没有推送了，希望可以有一个两全其美的办法，谢谢

**Comment by Tornaco** [comment]
@sujiuer5201314 试试这个版本，更新了下策略，收到gcm之后，会给15秒的窗口期允许其后台启动。https://app.circleci.com/pipelines/github/Tornaco/Thanox/671/workflows/c2f4351f-6cc0-4def-b88a-23bbeebc9876/jobs/591/artifacts

**Comment by sujiuer5201314** [comment]
可以正常使用了，谢谢大佬
