### ISSUE TITLE
模拟消息没通知

### ISSUE THREAD

**Issue by MOldtime** [Tornaco/Thanox#713]
**Describe the bug（现象描述）**
微信代收 -> 模拟消息
点击后没有通知出现

**To Reproduce**（如何复现）
微信代收 -> 点击模拟消息

**Expected behavior**（期望结果）
可以收到通知

**Screenshots**（截图）
无

**Version（发现问题的版本）:**
 - OS: Flyme 10.0.0.0A Android 13
 - Version: 4.2.4-row thanox@tornaco:6ea2cee5-5db7-46d6-a60f-94e224867ad4 Mon Jul0315:16:52CST2023Mac OS X

**Additional context**（其他信息）
无

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[server_logging.zip](https://github.com/Tornaco/Thanox/files/11997196/server_logging.zip)

**Comment by Tornaco** [comment]
@ls148478 截图看下你的代收设置项

**Comment by MOldtime** [comment]
@Tornaco 
![S30710-10571919_com google android gms](https://github.com/Tornaco/Thanox/assets/38435967/9f379168-5ee0-451e-9614-71e0961e32c1)
![S30710-10571301_github tornaco android thanos pro](https://github.com/Tornaco/Thanox/assets/38435967/b7701237-0632-479b-af92-02c9fc965812)

**Comment by MOldtime** [comment]
视频大于10Mb 所以发不了 我认为这和系统设置有关系
我记得有个入口可以设置 以前可以用的时候我在里面换过通知铃声
但是现在找不到这个入口了

**Comment by Tornaco** [comment]
@ls148478 测试的时候，把自动略过关闭或把微信杀死。微信在后台运行了就不弹通知了。

**Comment by MOldtime** [comment]
@Tornaco 感谢 原来是这样
