### ISSUE TITLE
后台运行锁屏清理无效

### ISSUE THREAD

**Issue by wiseman815** [Tornaco/Thanox#714]
**Describe the bug（现象描述）**
在后台运行设置锁屏清理，无效。一键清理和手动划最近任务有效。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
后台运行中取消勾选，锁屏，达到设定时间后打开正在运行任务，应用仍在

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
修复bug或告知排查解决方案

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: android 10 
 - Version 4.2.2prc 3071482

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
使用了冻它，尝试卸载冻它重启后，还是无效

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
尝试删除了日志，复现操作一遍，目录日志未产生新日志文件

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 一加7Pro  氢10.0.11
> 2. 4.2.2prc 3071482，losped激活

![c37bc932a012e4a04a84999983c03d2](https://github.com/Tornaco/Thanox/assets/39221181/81b9d063-0f49-4150-bb75-5dc9179ed7ca)
![ed3abd455e4371d09bc7a3a7af5b26d](https://github.com/Tornaco/Thanox/assets/39221181/4f3835bb-b15f-4642-9a0e-151b5f6da4f1)
![0f70ef8079a5b3695dc53cb90af8aa7](https://github.com/Tornaco/Thanox/assets/39221181/a8d47168-8470-4d0f-9a1a-7670bbfcb2c2)

**Comment by Tornaco** [comment]
@wiseman815 你测试的是讯飞输入法对吧？另外建议你再重新看下日志文件，没日志是不可能分析的。

**Comment by wiseman815** [comment]
> @wiseman815 你测试的是讯飞输入法对吧？另外建议你再重新看下日志文件，没日志是不可能分析的。

测试的酷安
[thanox-core.log](https://github.com/Tornaco/Thanox/files/11998371/thanox-core.log)

**Comment by Tornaco** [comment]
@wiseman815  试试这个版本。

**Comment by wiseman815** [comment]
> @wiseman815 试试这个版本。

没看到文件或版本号呢

**Comment by Tornaco** [comment]
https://app.circleci.com/pipelines/github/Tornaco/Thanox/675/workflows/68b744cc-295e-495d-9a82-a7b1a9bc0f26/jobs/595/artifacts

@wiseman815   忘了发连接了

**Comment by wiseman815** [comment]
似乎找到原因，我使用了冻它，里面的超时冻结时间设置，如果大于thanox的延时设置就有效，否则锁屏清理就无效。
如图片这样，就不会生效
![9a3535b138dbcfd2ccc4b22908d03df](https://github.com/Tornaco/Thanox/assets/39221181/48389307-699d-408f-895f-5ad3f3dfe749)
![1ae75905f6ff1506d526fce6d05d439](https://github.com/Tornaco/Thanox/assets/39221181/a555f01c-6d60-4755-8e4b-7d61edcdf3e0)
[3_thanox-core.log](https://github.com/Tornaco/Thanox/files/11999158/3_thanox-core.log)

**Comment by wiseman815** [comment]
> https://app.circleci.com/pipelines/github/Tornaco/Thanox/675/workflows/68b744cc-295e-495d-9a82-a7b1a9bc0f26/jobs/595/artifacts
> 
> @wiseman815 忘了发连接了

这个版本有bug，会触发无限重启

**Comment by wiseman815** [comment]
> 似乎找到原因，我使用了冻它，里面的超时冻结时间设置，如果大于thanox的延时设置就有效，否则锁屏清理就无效。 如图片这样，就不会生效 ![9a3535b138dbcfd2ccc4b22908d03df](https://user-images.githubusercontent.com/39221181/252270076-48389307-699d-408f-895f-5ad3f3dfe749.jpg) ![1ae75905f6ff1506d526fce6d05d439](https://user-images.githubusercontent.com/39221181/252270090-a555f01c-6d60-4755-8e4b-7d61edcdf3e0.jpg) [3_thanox-core.log](https://github.com/Tornaco/Thanox/files/11999158/3_thanox-core.log)

回到4.2.2版本，按照这个方式设置延时，就还是不生效。

**Comment by Tornaco** [comment]
@wiseman815 无线重启，能发个日志吗。。

**Comment by Tornaco** [comment]
@wiseman815 原因我来分析就行了，跟其他app无关的。

**Comment by wiseman815** [comment]
> @wiseman815 无线重启，能发个日志吗。。

触发条件似乎是，亮屏，上划使用人脸解锁，前置摄像头一弹出就重启。
[server_logging(1).zip](https://github.com/Tornaco/Thanox/files/11999599/server_logging.1.zip)

**Comment by Tornaco** [comment]
@wiseman815 收到，还得抓个lsposed日志。

**Comment by wiseman815** [comment]
> @wiseman815 收到，还得抓个lsposed日志。

[LSPosed_2023-07-10T17_25_50.571.zip](https://github.com/Tornaco/Thanox/files/12000305/LSPosed_2023-07-10T17_25_50.571.zip)
[LSPosed_2023-07-10T17_25_55.531.zip](https://github.com/Tornaco/Thanox/files/12000311/LSPosed_2023-07-10T17_25_55.531.zip)

**Comment by Tornaco** [comment]
@wiseman815 https://app.circleci.com/pipelines/github/Tornaco/Thanox/676/workflows/639e4170-5b8e-492a-a09a-fe5d78a0b80a/jobs/596/artifacts   这个呢，修了一下你再试试

**Comment by wiseman815** [comment]
> @wiseman815 https://app.circleci.com/pipelines/github/Tornaco/Thanox/676/workflows/639e4170-5b8e-492a-a09a-fe5d78a0b80a/jobs/596/artifacts 这个呢，修了一下你再试试

牛皮，人脸解锁不重启了，和冻它时间设置问题貌似也解决了，再观察下

**Comment by Tornaco** [comment]
@wiseman815 OK 有问题再看。

**Comment by wiseman815** [comment]
我又来了。。今天改了下息屏清理延时时间，又不行了。
分别做了以下设置，以小红书为例测试
息屏清理延时设置2、3、5、6、7秒，清理有效
设置8、9、10秒，无效
[thanox-core.log](https://github.com/Tornaco/Thanox/files/12011086/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/12011088/thanox-init.log)
[LSPosed_2023-07-11T13_54_49.909.zip](https://github.com/Tornaco/Thanox/files/12011090/LSPosed_2023-07-11T13_54_49.909.zip)
[LSPosed_2023-07-11T13_54_46.548.zip](https://github.com/Tornaco/Thanox/files/12011092/LSPosed_2023-07-11T13_54_46.548.zip)

**Comment by Tornaco** [comment]
@wiseman815 无解了，你设备锁屏之后跟休眠一样、，alram和线程都不准确了，没想到什么好办法。

**Comment by Tornaco** [comment]
wont fix

**Comment by wiseman815** [comment]
最新4.2.6没修这个问题嘛

**Comment by wiseman815** [comment]
破案了，应该是用了nowakelock，不知道什么时候把这个定时器关了
![Uploading Screenshot_20230901-215842.jpg…]()
