### ISSUE TITLE
更新后启动器崩溃

### ISSUE THREAD

**Issue by huimao28** [Tornaco/Thanox#718]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. Go to '...'（进入XXX）
2. Click on '....'（点击XXX）
3. Scroll down to '....'（下滑到XXX）
4. See error（发现错误XXX）

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

**Version（发现问题的版本）:**
 - OS: [e.g. Android 6.0.1]（系统版本，例如Android 6.0.1）
 - Version [e.g. v2.3.4]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@huimao28 传一下日志，路径 data/system/thanos/logging，以及lsp日志

**Comment by huimao28** [comment]
不知道要怎么搞

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tornaco ***@***.***>
发送时间: Wednesday, August 9, 2023 10:17:34 AM
收件人: Tornaco/Thanox ***@***.***>
抄送: huimao28 ***@***.***>; Mention ***@***.***>
主题: Re: [Tornaco/Thanox] 更新后启动器崩溃 (Issue #718)


@huimao28<https://github.com/huimao28> 传一下日志，路径 data/system/thanos/logging，以及lsp日志

―

**Comment by huimao28** [comment]
另外要等晚上才能传

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 柏辉 李 ***@***.***>
发送时间: Wednesday, August 9, 2023 11:30:52 AM
收件人: Tornaco/Thanox ***@***.***>; Tornaco/Thanox ***@***.***>
抄送: Mention ***@***.***>
主题: Re: [Tornaco/Thanox] 更新后启动器崩溃 (Issue #718)

不知道要怎么搞

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tornaco ***@***.***>
发送时间: Wednesday, August 9, 2023 10:17:34 AM
收件人: Tornaco/Thanox ***@***.***>
抄送: huimao28 ***@***.***>; Mention ***@***.***>
主题: Re: [Tornaco/Thanox] 更新后启动器崩溃 (Issue #718)


@huimao28<https://github.com/huimao28> 传一下日志，路径 data/system/thanos/logging，以及lsp日志

―

**Comment by huimao28** [comment]
没有root,没权限

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tornaco ***@***.***>
发送时间: Wednesday, August 9, 2023 10:17:34 AM
收件人: Tornaco/Thanox ***@***.***>
抄送: huimao28 ***@***.***>; Mention ***@***.***>
主题: Re: [Tornaco/Thanox] 更新后启动器崩溃 (Issue #718)


@huimao28<https://github.com/huimao28> 传一下日志，路径 data/system/thanos/logging，以及lsp日志

―

**Comment by huimao28** [comment]
@Tornaco 有没有办法退回上一个版本呀

**Comment by Tornaco** [comment]
@huimao28 退出beta计划，可以回到正式版。但是你不能永远不更新吧。

**Comment by huimao28** [comment]
@Tornaco 怎么操作呀

**Comment by Tornaco** [comment]
@huimao28 https://www.google.com/search?q=google+play+%E9%80%80%E5%87%BAbeta&oq=google+play+%E9%80%80%E5%87%BAbeta&aqs=chrome..69i57j0i546l4j69i64.6925j0j4&sourceid=chrome&ie=UTF-8

**Comment by huimao28** [comment]
@Tornaco 我是系统的启动器 Arrow launcher 崩溃呀

**Comment by huimao28** [comment]
@Tornaco 想退回arrow OS的上一个版本

**Comment by Tornaco** [comment]
@huimao28 那你自己刷机？ 这我就不会了

**Comment by huimao28** [comment]
人在外地，搞不了
我是小米平板5pro WiFi版，代号elish，不知道要怎么办

**Comment by Tornaco** [comment]
@huimao28 如果你是因为崩溃无法开机，可以连接电脑使用shell命令卸载thanox模块；命令如下：pm uninstall github.tornaco.android.thanos.pro       或者进入recovery模式，使用rec自带的terminal删除/data/system/thanos_xxx 试试。   其他的刷机相关我不清楚。抱歉。

**Comment by huimao28** [comment]
rec换了，无页面，能在系统内想办法吗

**Comment by Tornaco** [comment]
@huimao28 你说下你的条件啊? 有电脑没？手机处于什么状态，你要什么结果。。。。。

**Comment by huimao28** [comment]
当时不换rec刷不了arrow OS

**Comment by huimao28** [comment]
无电脑，平板除了启动器崩溃，无手势导航和三大金刚外，无故障

**Comment by huimao28** [comment]
希望能让arrowlauncher不崩溃，能正常用返回，主页等导航键

**Comment by huimao28** [comment]
但，没电脑应该不太可能

**Comment by Tornaco** [comment]
@huimao28 平板上有终端吗

**Comment by huimao28** [comment]
OS Android13
version 4.19.157-perf-gbfafbd1901db
#1 Fri Mar 10 10:12:41 UTC 2023

**Comment by huimao28** [comment]
指？

**Comment by huimao28** [comment]
@Tornaco

**Comment by huimao28** [comment]
黑域里面的那种行吗

**Comment by Tornaco** [comment]
@huimao28 能运行命令的就行

**Comment by huimao28** [comment]
有

**Comment by huimao28** [comment]
@Tornaco 有能运行命令的

**Comment by huimao28** [comment]
> @huimao28 能运行命令的就行

@Tornaco 要不我们加个微信，好搞一点

**Comment by Tornaco** [comment]
@huimao28 运行 pm uninstall github.tornaco.android.thanos.pro 或者  pm uninstall github.tornaco.android.thanos 可以卸载thanox。 我只能和你说到这了，准备休息了~

**Comment by huimao28** [comment]
> @huimao28 运行 pm uninstall github.tornaco.android.thanos.pro 或者  pm uninstall github.tornaco.android.thanos 可以卸载thanox。 我只能和你说到这了，准备休息了~

@Tornaco 都不行![Screenshot_20230809-214835_黑阈.png](https://github.com/Tornaco/Thanox/assets/112787526/30dc671f-a171-4da2-b521-3ef1ec704529)

**Comment by Tornaco** [comment]
@huimao28 QQ 1300332322

**Comment by Tornaco** [comment]
非Thanox Issue
