### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by ghost** [Tornaco/Thanox#719]

**Comment by TheBinger** [comment]
MD3主题其实应该也有问题，可能是这里的按钮写死了就是黑色的，因为MD3这里也是黑色，好像不符合设计规范
![Screenshot_2023-08-10-13-59-00-822_github tornaco android thanos pro-edit](https://github.com/Tornaco/Thanox/assets/61423853/ea2f2729-1a0e-4a6b-b6b6-3002b0edee2c)
