### ISSUE TITLE
无法恢复备份2（新bug）

### ISSUE THREAD

**Issue by isnthzy** [Tornaco/Thanox#72]
在使用了应用程序组件重新后如未安装相应的app则无法恢复备份

**Comment by 2398569839** [comment]
在使用了应用组件禁用后如未安装相应的app则无法恢复备份

**Comment by ICMYS** [comment]
的确存在这个问题，临时解决方案：
打开备份文件（是个压缩包）
编辑其中的disabled_components.xml
去除已卸载的app组件

**Comment by isnthzy** [comment]
> 的确存在这个问题，临时解决方案：
> 打开备份文件（是个压缩包）
> 编辑其中的disabled_components.xml
> 去除已卸载的app组件



> 的确存在这个问题，临时解决方案：
> 打开备份文件（是个压缩包）
> 编辑其中的disabled_components.xml
> 去除已卸载的app组件

这个备份并不急着用，或许可以让作者把不能成功导入的去掉，而不是提示错误并停止导入。这些错误提示应该打印在日志中，因为toast提示普通用户无法看懂

**Comment by isnthzy** [comment]
这个帖子爆出了大量的问题
https://www.coolapk.com/feed/16343798?shareKey=OTk0N2MxYjU2YTlmNWUzZmY0NzA~&shareUid=1014434&shareFrom=com.coolapk.market_10.0

**Comment by Vstory** [comment]
> > 的确存在这个问题，临时解决方案：
> > 打开备份文件（是个压缩包）
> > 编辑其中的disabled_components.xml
> > 去除已卸载的app组件
> 
> > 的确存在这个问题，临时解决方案：
> > 打开备份文件（是个压缩包）
> > 编辑其中的disabled_components.xml
> > 去除已卸载的app组件
> 
> 这个备份并不急着用，或许可以让作者把不能成功导入的去掉，而不是提示错误并停止导入。这些错误提示应该打印在日志中，因为toast提示普通用户无法看懂


都用这个了，还是懂些的吧🤔

**Comment by Tornaco** [comment]
Fix since 1.1.6-beta1
