### ISSUE TITLE
安卓13权限管理里禁用振动权限不生效

### ISSUE THREAD

**Issue by loave** [Tornaco/Thanox#720]
**Describe the bug（现象描述）**
权限管理中的振动权限无效

**To Reproduce**（如何复现）
1. 在权限管理中拒绝百度输入法的振动权限
2. 在百度输入法中开启输入振动
3. 使用百度输入输入内容，仍然振动

**Expected behavior**（期望结果）
应用没有振动权限，不会振动

**Version（发现问题的版本）:**
 - OS: ColorOS13 Android13
 - Thanox：4.2.2

**Additional context**（其他信息）
用权限狗、appops试过禁用百度输入法的振动权限，都是可以正常生效的

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本：Android
> 2. Thanox版本：4.2.2，补丁方式：xposed

**Comment by loave** [comment]
系统回滚到ColorOS 12.1   Android12版本，同样的thanox、百度输入法，禁用振动权限是能正常生效的，所以应该就是系统版本导致的问题

**Comment by Tornaco** [comment]
新版已修复，如果仍有问题，再open
