### ISSUE TITLE
（功能请求）希望可以添加一个隐藏后台的功能

### ISSUE THREAD

**Issue by unreal-alex** [Tornaco/Thanox#726]
希望可以添加一个隐藏后台的功能（指隐藏其他app的后台卡片）

很多别的隐藏后台软件也只能隐藏主用户里的后台，但是他们检查不到分身的app以至于无法隐藏分身app后台

我注意到thanox能检测到分身app，而且能模糊分身的卡片，所有希望能有一个隐藏后台以及app分身后台的功能

**Comment by Tornaco** [comment]
@unreal-alex  应用管理 -- 目标应用 -- 最近任务卡片 可隐藏。

如果该功能跟你预期不一样，请说明一下。

**Comment by unreal-alex** [comment]
👍，完全一致。
