### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by IamSingh01** [Tornaco/Thanox#727]
- Is it possible to not eliminate the dependency on lsposed?
- is it possible to run thanox with lsposed non rooted version (I'd like to use thanox on my rooted device and I don't wish to root it).
- next time can you translate the t&c? Everytime I update thanox there's some chinese text that I can't read.
- from last few version i wasn't able to find WhatsApp for cloning (is it fixed? Too lazy to destroy my existing work profile.)
- I'm not able to find system frozen apps (chrome)

Device running on AOSP Rom based on A13
Thanox version: 4.2.7.1-row (Playstore version)

**Comment by Tornaco** [comment]
@singhh9596 1. Thanox apply a  lot of patches to Android system, without LSPosed, not easy to find hook points, and will be painfull to compat versions of Android, so impossible for now. 
2. impossible, need patch to android system
3. Wht do you mean by T&C? which language code? I was busy these months, will glad if someone can help to translate, Thanox is 80% open sourced project.
4. Dont known if it has been fixed, you can try and report if still exists. remember to attach logs under /data/system/thanos_xx/logging
5. Dont understand...

Thanks

**Comment by IamSingh01** [comment]
Terms and conditions (T&C)
1. In the smart freeze, I wanna put chome to the smart freeze. But I can't see chrome, whatsapp in the list.
2. Still couldn't find whatsapp to clone.
3. Couldn't find the directory you mentioned.
![IMG_20230911_112447_169](https://github.com/Tornaco/Thanox/assets/31469965/343b8dde-8af5-456f-bce8-d267b7c78e8c)

**Comment by Tornaco** [comment]
@singhh9596 can you see what's app in Thanox/AppManager/All Apps list?

**Comment by IamSingh01** [comment]
[ logs.log…]()

**Comment by IamSingh01** [comment]
No, in the app manager as well, chrome and whatsapp is missing

**Comment by Tornaco** [comment]
@singhh9596 And also pls check your user whitelist: App manager/ Package sets/ User white list, if Chrome or what's app is in there

**Comment by IamSingh01** [comment]
> @singhh9596 And also pls check your user whitelist: App manager/ Package sets/ User white list, if Chrome or what's app is in there

Yes, found it in the custom allow list.

**Comment by Tornaco** [comment]
@singhh9596 Pls remove from there. User white list is for those apps you dont want to manage by Thanox.

**Comment by IamSingh01** [comment]
I did thank you. but I never added them. By the way is it possible to remove fm radio to  be cloned in its own.

**Comment by Tornaco** [comment]
@singhh9596 Can, send me the package name of the FM radio app pls.

**Comment by IamSingh01** [comment]
com.caf.fmradio

**Comment by Tornaco** [comment]
@singhh9596 OK. You can test on next update.
