### ISSUE TITLE
求pro版本的旧版本

### ISSUE THREAD

**Issue by vs2pk0** [Tornaco/Thanox#733]
大佬，求pro版本的旧版本

**Comment by YBY1306** [comment]
可以试试第三方GooglePlay客户端[Aurora](https://auroraoss.com/)
右上角有一个手动下载输入正确的版本号就能下载旧版本（前提是已买的软件）
Thanox在GooglePlay的Pro版和在Github的普通版的版本号好像是一样的

**Comment by Tornaco** [comment]
@vs2pk0 你要什么版本？ 可以邮件thanox@163.com 给你私发。
