### ISSUE TITLE
Android 14 权限管理失效

### ISSUE THREAD

**Issue by nakixii** [Tornaco/Thanox#740]
**Describe the bug（现象描述）**
权限管理失效，无法禁止应用调节亮度。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1.禁止哔哩哔哩调节亮度
2.进入哔哩哔哩打开一个视频，滑动画面左侧调节亮度

**Expected behavior**（期望结果）
亮度无变化

**Version（发现问题的版本）:**
 - OS: Android 14 HyperOS 1.0.16
 - Version: v5.0.0-prc

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[thanox-core.log](https://github.com/Tornaco/Thanox/files/13283222/thanox-core.log)
[thanox-init.log](https://github.com/Tornaco/Thanox/files/13283185/thanox-init.log)

**Comment by Tornaco** [comment]
@nakixii OK等我修复

**Comment by Tornaco** [comment]
@nakixii 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/712/workflows/a2340b08-44c2-4683-983c-0b95e400eca7/jobs/625/artifacts

**Comment by nakixii** [comment]
> @nakixii 试试这个 https://app.circleci.com/pipelines/github/Tornaco/Thanox/712/workflows/a2340b08-44c2-4683-983c-0b95e400eca7/jobs/625/artifacts

这个版本可以禁止调节亮度了👍
