### ISSUE TITLE
Thanox Pro Not Activating

### ISSUE THREAD

**Issue by ToothlessXD** [Tornaco/Thanox#741]
**Describe the bug（现象描述）**
I activated Thanox Pro in my lsposed with scope to android system. After reboot Thanox still saying not active. I can't use magisk mode, due to I am in kernelsu. Kindly help me to resolve this issue

**To Reproduce**（如何复现）
1. Activate Thanox in lsposed
2. Leave default scope to system Framework
3. Reboot device
4. Open Thanox Pro after reboot done

**Expected behavior**（期望结果) 
I should have seen Thanox Pro active and working, but not. Tried rebooting multiple times and enable and disable thanox Pro multiple times and rebooting. Nothing seems to work

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![Screenshot_20231109-092329_Google Play Store](https://github.com/Tornaco/Thanox/assets/57696616/6ad63473-5b41-4b5e-9ae2-bfc3d0c42019)
![Screenshot_20231109-094259_Shell](https://github.com/Tornaco/Thanox/assets/57696616/a22fa4e9-418a-4683-92e2-57857b9a1427)
![Screenshot_20231109-094234_Thanox Pro](https://github.com/Tornaco/Thanox/assets/57696616/86005df7-64f0-4931-961c-0fe92d72959e)
![Screenshot_20231109-094240_Thanox Pro](https://github.com/Tornaco/Thanox/assets/57696616/e0d1f835-95ae-4c22-a2b2-842ae06894f8)
![Screenshot_20231109-094634_Shell](https://github.com/Tornaco/Thanox/assets/57696616/b86a2589-eb58-413c-88ca-5fb86ba27cf7)

**Version（发现问题的版本）:**
 - OS: Android 13 [Rising OS official for Redmi Note 10 Pro (sweet)
 - Version 5.0.0 (I signed up for beta too)

**Additional context**（其他信息）
Tried normal version and beta version. Both has same issue.

** Logs**（日志文件)
[LSPosed_2023-11-09T09_22_38.046647.zip](https://github.com/Tornaco/Thanox/files/13303678/LSPosed_2023-11-09T09_22_38.046647.zip)
[Thanos system logs.zip](https://github.com/Tornaco/Thanox/files/13303680/Thanos.system.logs.zip)

---------

I think I provided everything asked below. I don't understand Chinese. I used Google translate to English for understanding below notes. 

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@ToothlessXD Are you using a TV device? from your logs I found your device has published `TvInputManagerService`. Thanox core service is not able to init because of it.

Will try to find a new solution, will take some time.

**Comment by ToothlessXD** [comment]
@Tornaco. No I didn't used it in TV. Redmi Note 10 Pro is a mobile device. Thanks. Please look into it

**Comment by Tornaco** [comment]
@ToothlessXD Your gmail pls, I will push a test version to you via Play store

**Comment by ToothlessXD** [comment]
@Tornaco Thank you so much for consideration. My email is xdtoothless@gmail.com

**Comment by Tornaco** [comment]
@ToothlessXD Click https://play.google.com/apps/internaltest/4699745136264046535 this join, you will receive 3079284 (5.0.0-1-c38de41-row).

**Comment by ToothlessXD** [comment]
@Tornaco Thank you so much. Issue resolved. It's working now. Let me know if you need any logs. 
![Screenshot_20231110-111525_Thanox Pro](https://github.com/Tornaco/Thanox/assets/57696616/f0822c7e-ae7d-4ef1-9026-7f1e3cb9d4d5)

**Comment by Tornaco** [comment]
@ToothlessXD OK，done👍

**Comment by ToothlessXD** [comment]
Everything working fine. Thanks again for support and wonderful app.
