### ISSUE TITLE
[BUG] Thanox Crahses the Pixel Launcher

### ISSUE THREAD

**Issue by DeannWinchesterr** [Tornaco/Thanox#742]
Description: Whenever something new happens on the lock screen for example if something changes in at a glance or if a widget was added to the home screen the launcher Crahses and Thanox gives Error. 

Steps to reproduce the behaviour:
1. Go to Chrome, click on three dots on top right
2. Click on "add to home screen"
3. A pop up will show from launcher saying add to home screen 
4. As soon as you hit yes, it Crahses the launcher and Thanox gives an error 

Expected behavior:
Well expected behaviour is for the launcher to not crash and Thanox to not error out. 

Screen recording:
https://github.com/Tornaco/Thanox/assets/131953486/50372cf9-f4bd-4644-9ac2-e3a03cded798

Version:
 - OS: Android 13
 - Version:  5.0.0-row

Additional context:
The problem also existed on v4.2.9.2-row, same issue and same behaviour.  Both times thanox was running through magisk.  This issue happens only when thanox is activated.

Logs:
[thanox-core.log](https://github.com/Tornaco/Thanox/files/13304249/thanox-core.log)

**Comment by Tornaco** [comment]
@DeannWinchesterr It's frastrated that Thanox only works well through Xposed, there always be some issue if you active it via magisk, it's not easy for me to fix. so suggest to active via Xposed if you can...

If you can use[ adb to catch a full log ](https://www.google.com/search?q=use+adb+to+catch+log&oq=use+adb+to+catch+log&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigAdIBCDM3NzlqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8)when issue reproduce, then I think I can try to analyse and see if we can fix it. currently the log you atttached say nothing about this issue.
