### ISSUE TITLE
SU API损坏

### ISSUE THREAD

**Issue by ajdgsu** [Tornaco/Thanox#743]
**Describe the bug（现象描述）**
在原先的thanox版本中，使用su api的样子大致是这样的：su.exe(\"echo test\");，在最新版本中这样执行会报错：
2023-11-13 21:31:31.162 E/[Profile]: executeAction:
su.exe(\"echo test\"); failed
[Error: unterminated string literal]
[Near : {... su.exe(\"echo test\"); ....]
在去除双引号的转义后：su.exe("echo test");  的确可以在action console里正常执行也不会有任何报错，但是在情景模式里无法保存取消转义双引号的配置文件【Unexpected character ('e' (code 101)):
was expecting comma to separate Array
entries
at [Source: (StringReader); line: 10,
column: 11] (through reference chain:
java.lang.Object[][O])】

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入情景模式的action console
2.执行：su.exe(\"echo test\"); 就会报错，去除转义就不会报错
3. 回到情景模式的编辑器内
4. 输入："su.exe("echo test");" 后thanox提示语法错误，无法保存配置文件

**Expected behavior**（期望结果）
确保su api需要转义双引号后才能工作，如果要改为不需要转义双引号的话则应确保配置文件内的语义检查不会报错

**Screenshots**（截图）
![Screenshot_2023-11-13-21-45-48-682_github tornaco android thanos pro](https://github.com/Tornaco/Thanox/assets/45306865/6b20641a-5a48-46df-9128-d3148e834732)
![Screenshot_2023-11-13-21-36-10-716_github tornaco android thanos pro](https://github.com/Tornaco/Thanox/assets/45306865/a69ffdfd-7227-4505-8182-ecb8ee3ca1f9)
![Screenshot_2023-11-13-21-43-51-101_github tornaco android thanos pro](https://github.com/Tornaco/Thanox/assets/45306865/1c2ed514-7f7b-4581-b450-d1101ca8378e)

**Version（发现问题的版本）:**
 - OS: [Android 13]
 - Version [e.g. 5.0.0-row]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本
> 2. Thanox版本，补丁方式（xposed还是magisk？）
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
@ajdgsu 发一下你测试的情景模式代码，我没复现。

**Comment by Tornaco** [comment]
Close no response.
