### ISSUE TITLE
某app屏蔽了广告activity后依然显示，设置无效

### ISSUE THREAD

**Issue by githubcatheaven** [Tornaco/Thanox#748]
**Describe the bug（现象描述）**
软件：[间隔计时器, 运动计时器 [Interval Timer]](https://play.google.com/store/apps/details?id=com.interval.timer.workout.tabata.hiit.free&ref=apkcombo.com)
通过 Thanox 5.0.1 禁用了所有ADS相关的服务（互动、广告、服务、内容）后，进入APP依然显示底栏广告

**Expected behavior**（期望结果）
禁用广告服务，进入APP底栏广告去掉，或不再显示

**Screenshots**（截图）
![image](https://github.com/Tornaco/Thanox/assets/1519099/94c6ef9e-b948-4f9b-9872-c9b07005ce1a)
![image](https://github.com/Tornaco/Thanox/assets/1519099/644c9fef-f823-4d85-805d-4305bf00adab)

**Version（发现问题的版本）:**
系统：一加 Oxygen 11 A11（Android 11）
软件：5.0.1 Magisk

**Comment by Tornaco** [comment]
如果是无法禁用服务的bug，需要你抓一下日志；如果是禁用了服务依然有广告，该问题不在thanox功能范围。

**Comment by githubcatheaven** [comment]
怎么解决呢
