### ISSUE TITLE
数字健康模式导致的后台运行-不清理最近任务里的应用失效

### ISSUE THREAD

**Issue by zhengzavan** [Tornaco/Thanox#749]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）

安卓原生数字健康，开启专注模式并勾选目标应用，然后打开应用，有个“使用应用 5 分钟”，点击后切换到桌面，保留后台卡片，息屏重开后应用被杀了，明明后台清理开了“不清理最近任务里的应用”

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 开启专注模式，勾选 b 站
2. thanox 设置 b 站 开乖巧模式 开任务清理 关后台运行 关后台运行，并设置不清理最近任务里的应用
3. 打开 b 站，点击使用应用 5 分钟，进入二级界面，回到桌面并保留任务卡片，息屏，亮屏进 b 站发现 b 站被杀

**Expected behavior**（期望结果）

b 站有卡片，不应该被杀

**Version（发现问题的版本）:**
 - OS: 安卓 13 类原生
 - Version v5.0.0

**Comment by Tornaco** [comment]
@zhengzavan 录个屏，按照首页说明抓个日志吧。刚才在我这没复现。

**Comment by Tornaco** [comment]
提供录屏和log后open。
