### ISSUE TITLE
恳求增加应用单独备份

### ISSUE THREAD

**Issue by diweisong** [Tornaco/Thanox#756]
经常测试禁用服务的人来说太折磨了，没有应用单独备份，用其他的软件指不定又会复活，刚好thanox集成了。
可是有的应用多达上百个服务，比如禁用了30个服务，功能测试没有发现异常，这时候应该备份一下，继续往下面禁用，可是没有的话，应用哪些出现功能了异常，又要翻上去一个个打开才知道，因为你不知道他有的是并联的
如果用别的应用配合的话，thanox完全备份只会备份自己的设置，比如我用其他的软件打开了那个服务，thanox恢复备份是禁用状态的，你需要先关闭，再打开才会变成新的
还有就是更新新版本，本来你这版本的禁用是刚好的，有单独备份的话可以先备份一下，然后升级再进行禁用，但是没有的话就很麻烦，你在新版本直接进行升级的话，想回推退老版本那个禁用设置就只能全局
描述能力有限，真的很需要这个功能，球球开发者加一个

**Comment by diweisong** [comment]
![IMG_20231223_171941](https://github.com/Tornaco/Thanox/assets/106238637/9fd9c96f-604e-4159-8f4f-a9a0dd2a58b6)

**Comment by Tornaco** [comment]
新版5.0.5已经支持
