### ISSUE TITLE
测试版情景模式失效

### ISSUE THREAD

**Issue by dreamy06** [Tornaco/Thanox#778]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
 5.0.1-55-149e6ce-prc 此版本情景模式失效，且全局变量无法添加

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）

全局变量无法添加截图
![Screenshot_2024-01-02-15-04-41-838-edit_github tornaco android thanos](https://github.com/Tornaco/Thanox/assets/36306588/81bb1dad-9ed3-4f13-877c-0d915bb66abb)

**Version（发现问题的版本）:**
 - OS: Android 14
 - Version: 5.0.1-55-149e6ce-prc

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
[Thanox-Log-2024-01-02-15_16_33.zip](https://github.com/Tornaco/Thanox/files/13807813/Thanox-Log-2024-01-02-15_16_33.zip)

**Comment by Tornaco** [comment]
@dreamy06 无法生效的情景模式代码发下

**Comment by dreamy06** [comment]
> @dreamy06 无法生效的情景模式代码发下
大概是都不生效
`[
  {
    "name": "Show toast",
    "description": "微信回到后台，显示toast(测试)",
    "priority": 2,
    "condition": "frontPkgChanged == true && from == \"com.tencent.mm\"",
    "actions": [
      "ui.showShortToast(\"微信回到后台\");"
    ]
  }
]`

**Comment by Tornaco** [comment]
@dreamy06  试试这个呢 https://app.circleci.com/pipelines/github/Tornaco/Thanox/779/workflows/7002c097-b63e-469b-8eab-8c1589a29fdc/jobs/686/artifacts

**Comment by dreamy06** [comment]
> @dreamy06 试试这个呢 
感谢，刚刚试了可以了

**Comment by dreamy06** [comment]
Done👍
