### ISSUE TITLE
开启某个功能导致安卓 14 无障碍失效

### ISSUE THREAD

**Issue by luofan996** [Tornaco/Thanox#784]
安卓 14  coloros14
一加 ace2pro
xposed  5.0.1prc（3079383）
开机后无障碍无法调用，显示各种空，其他需要无障碍权限的应用无法调用，恢复默认设置后正常，导入配置后异常，导入后关闭五项主要功能后重启后异常

不激活没有问题

激活后不做配置没问题
![IMG20240109082852](https://github.com/Tornaco/Thanox/assets/40208515/d15bf19a-73c8-435d-b5c2-9cce80f19f4c)
![Image_1704776259395](https://github.com/Tornaco/Thanox/assets/40208515/6a19db11-39e4-4d8c-b137-99f07d3369bd)
![Image_1704776257150](https://github.com/Tornaco/Thanox/assets/40208515/7e163f83-862d-4e9b-9947-e8b0f0cf61b6)
[logging.zip](https://github.com/Tornaco/Thanox/files/13869062/logging.zip)
[Thanox-Backup-2024-01-07-14_42_44.zip](https://github.com/Tornaco/Thanox/files/13869065/Thanox-Backup-2024-01-07-14_42_44.zip)

**Comment by Tornaco** [comment]
@q1365528996 可以临时关闭情景模式的ui引擎，重启试试。如果是我猜测的原因，那么我会很快修复。

**Comment by luofan996** [comment]
我不知道你说的情景模式的 ui 引擎如何关闭，但是我把整个情景模式功能关闭后正常了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tornaco/Thanox] 开启某个功能导致安卓 14 无障碍失效 (Issue #784)




 
@q1365528996 可以临时关闭情景模式的ui引擎，重启试试。如果是我猜测的原因，那么我会很快修复。

**Comment by Tornaco** [comment]
@q1365528996  试一下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/783/workflows/e71cb302-d8b2-4351-ae25-50508f9024c0/jobs/690/artifacts

**Comment by luofan996** [comment]
昨天晚上安装的开了情景模式，截止现在都正常的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月10日(周三) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tornaco/Thanox] 开启某个功能导致安卓 14 无障碍失效 (Issue #784)




 
@q1365528996  试一下 https://app.circleci.com/pipelines/github/Tornaco/Thanox/783/workflows/e71cb302-d8b2-4351-ae25-50508f9024c0/jobs/690/artifacts

**Comment by Tornaco** [comment]
@q1365528996 OK thanks mate.
