### ISSUE TITLE
应用锁适配瓶下指纹

### ISSUE THREAD

**Issue by sky96111** [Tornaco/Thanox#79]
![](https://i.niupic.com/images/2020/02/17/6wc1.jpg)

在屏下指纹手机上，指纹传感器会遮挡住图形密码或数字密码的几个点。建议屏下指纹手机可以主动选择图形和pin码键盘向上偏移量

**Comment by Tornaco** [comment]
Fixed

**Comment by sky96111** [comment]
我觉得当前这可能并不是最好的解决方案...在先用图形解锁的情况下，指纹图标依然会遮挡图案。个人建议是图案和数字可选向上偏移
