### ISSUE TITLE
希望能优化任务清理功能

### ISSUE THREAD

**Issue by qianxu2001** [Tornaco/Thanox#8]
像微信 QQ 这类应用，在使用其小程序功能时，会在最近任务界面产生多个窗口，如果将这类应用加入任务清理列表，我在划掉这类应用的某个窗口后，整个应用都将被停止运行，希望能优化任务清理功能，对应用的最近任务窗口多一层判断，只有清理掉某应用全部最近任务窗口时，才将该应用停止运行。

**Comment by Tornaco** [comment]
P1.
