### ISSUE TITLE
[问题反馈]智能冻结和冻结图标重新出现

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#80]
已冻结或者已智能冻结的应用在更新后图标会重新在启动器中出现
已冻结的应用在应用管理界面依然会显示已冻结的字样，但在应用信息则显示应用已启用
已智能冻结的应用需要重新智能冻结
![IMG_20200217_215149](https://user-images.githubusercontent.com/49943258/74659792-ed53e580-51cf-11ea-96f1-3e47f9f0a12b.jpg)
![IMG_20200217_215237](https://user-images.githubusercontent.com/49943258/74659796-efb63f80-51cf-11ea-98cb-5b3c2ca43581.jpg)
![IMG_20200217_215259](https://user-images.githubusercontent.com/49943258/74659800-f04ed600-51cf-11ea-9146-179c2951acc4.jpg)

**Comment by Gladtbam** [comment]
智能冻结问题已修复，但是冻结的应用依然存在问题，应用更新后自行解冻了 @Tornaco

**Comment by Tornaco** [comment]
@sakurabot 你是通过哪个商店更新的。

**Comment by Gladtbam** [comment]
> @sakurabot 你是通过哪个商店更新的。

Google play商店

**Comment by abcdol** [comment]
一人血书跪求增加一个智能冻结总是创建代理应用的开关(╬ Ò ‸ Ó)
另外代理应用的名字能不能改成跟原来一样的呢 强迫症看着2总感觉怪怪的o(´^｀)o

**Comment by Gladtbam** [comment]
> @sakurabot你是通过哪些商店更新的。

MIUI应用商店安装也出现了该情况
