### ISSUE TITLE
情景模式 sh.exe 无法执行sh命令

### ISSUE THREAD

**Issue by inused** [Tornaco/Thanox#85]
**Describe the bug（现象描述）**

情景模式 Profile 使用 sh.exe 无法执行shell代码

**To Reproduce**（如何复现）

1. 创建情景模式

    a. 条件：应用切换&切换到的应用为Google play 且 (Google服务框架或者play服务被冻结)
    b. 操作：启用Google服务框架和play服务同时使用sh.exe运行shell命令开启v2rayNG

2. 运行

    a. 启动Google play
    b. 被冻结的Google服务框架和play服务启用成功
    c. v2rayNG未开启
    d. "am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity" 命令使用 adb(无需root权限) 和 手机终端中(需root权限) 可以正常开启v2rayNG

3. 情景模式代码如下

```json
[
  {
    "name": "Auto Google APP Enable",
    "description": "打开Google Play时自动启用服务框架",
    "priority": 1,
    "condition": "frontPkgChanged == true && to == \"com.android.vending\" && (pkg.isApplicationEnabled(\"com.google.android.gms\") == false || pkg.isApplicationEnabled(\"com.google.android.gsf\") == false)",
    "actions": [
      "sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\");",
      "pkg.enableApplication(\"com.google.android.gms\");",
      "pkg.enableApplication(\"com.google.android.gsf\");",
      "ui.showShortToast(\"自动启用Google\")"
    ]
  }
]
```

**Expected behavior**（期望结果）

- v2rayNG也能开启成功

**Screenshots**（截图）

无

**Version（发现问题的版本）:**

 - OS: Android10 ; MIUI 11 20.1.21 | 开发版
 - Version: 1.1.6-beta2-4-38dbd79-dirty-prc

**Additional context**（其他信息）

开始以为是不支持am指令
所以使用 echo 123 > /sdcard/1.txt 之类的命令进行了测试，无法生成文件;
之后又将该命令写入 /sdcard/1.sh 中用sh.exe调用，同样没有生成文件;
另外导入示例中的 sh example 屏幕点亮后toast本应弹出 thanox版本信息，但是toast弹出信息为空

**Logs**（日志文件）

[log.zip](https://anonfiles.com/f320ncb4o2/log_zip)

**Comment by Tornaco** [comment]
很赞。稍晚点看下。

**Comment by Tornaco** [comment]
@zhzjwd 日志网站打不开，帮忙换个网站吧。

**Comment by inused** [comment]
@Tornaco
之前上传GitHub一直网络错误，才用了那个网站
[log.zip](https://github.com/Tornaco/Thanox/files/4243675/log.zip)

**Comment by Tornaco** [comment]
@zhzjwd 有些命令需要su去执行。
之前考虑到安全、google审核策略原因，暂时只公布了sh能力，后面将会开放su能力。
到时候使用`su.exe(xxx)`试试。

**Comment by inused** [comment]
@Tornaco OK，期待

**Comment by Tornaco** [comment]
目前发现selinux enforce的设备，无法以system server的身份执行shell command :(

**Comment by inused** [comment]
搞了selinux，现在可以执行了
magisk上好像是有个模块，用了下可以
就先这么用吧

**Comment by ghost** [comment]
大佬，用了你的情景模式打开app直接卡v2rayng了，能帮忙看下有啥问题吗，把to改成from在关闭app时正常调用 但打开就卡
[
{
"name": "自动开启v2ray",
"description": "自动开启v2ray，应用名单来自全局变v2ray",
"priority": 1,
"condition": "frontPkgChanged == true && globalVarOf$v2ray.contains(to)",
"actions":
[
"sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")"
]
}
]

**Comment by inused** [comment]
@krecycle 建议先去看一下文档情景模式 [应用切换](https://tornaco.github.io/Thanox/2019-12-02-Profile/#042-应用切换)
frontPkgChanged==true意思是前台应用发生了变化，也就是说从应用A变成了应用B，
to是一个变量，前台应用变成了哪个应用to就是哪个应用的包名，也就是指B，
from同理，是指前台应用变化之前是哪个应用，也就是指A
所以，
条件里如果是to就是说应用B变成了前台应用(一般就是指打开应用B)的时候触发，
from意思就是应用A不再是前台应用(比如关闭了应用A、打开其他应用等多种情况)的时候触发

ScSwitchActivity 这个活动是切换V2rayNg状态的，就类似灯的开关，调用一次就开，再调一次就关，再一次是开，再一次是关，没法直接控制是打开还是关闭，只能把状态变成和当前状态相反。但是这是通过命令行直接调用的，所以可能偶尔会出现ScSwitchActivity在前台存活时间过长的情况。

你卡住的情况是缺少条件形成了死循环，我来说一下你卡住的具体过程

to的时候：刚才说了，to是指打开这个应用(假设叫B)；

1. 你打开B，B就变成了前台应用，符合条件触发情景模式执行shell命令打开ScSwitchActivity这个活动，此时V2rayNg变成了前台应用应用B变成了后台应用，

2. ScSwitchActivity切换了V2rayNg开关后自动结束跳转回应用B，此时应用B又变成了前台应用，符合条件触发情景模式打开ScSwitchActivity，此时V2rayNg变成了前台应用应用B变成了后台应用，

3、4、5、6......无限循环步骤2，可能ScSwitchActivity存活时间过长，导致一直显示V2rayNg

from的时候：from是指本来应用A是前台的，现在A不是前台了

0. 关闭应用A(这种情况一般是回到桌面)，符合条件触发情景模式调用ScSwitchActivity改变V2rayNg开关，ScSwitchActivity自动结束自动跳转到桌面，不符合条件，流程结束

1. 打开应用A，这个时候to是指应用A，from是指其他应用，这个按理说是不会导致卡住的，除非这个时候这几个应用都在你的全局变量v2ray里面

上面是我根据你描述的个人分析，具体情况还是看你自己了

**Comment by ghost** [comment]
> @krecycle 建议先去看一下文档情景模式 应用切换
> frontPkgChanged==true意思是前台应用发生了变化，也就是说从应用A变成了应用B，
> to是一个变量，前台应用变成了哪个应用to就是哪个应用的包名，也就是指B，
> from同理，是指前台应用变化之前是哪个应用，也就是指A
> 所以，
> 条件里如果是to就是说应用B变成了前台应用(一般就是指打开应用B)的时候触发，
> from意思就是应用A不再是前台应用(比如关闭了应用A、打开其他应用等多种情况)的时候触发
> 
> ScSwitchActivity 这个活动是切换V2rayNg状态的，就类似灯的开关，调用一次就开，再调一次就关，再一次是开，再一次是关，没法直接控制是打开还是关闭，只能把状态变成和当前状态相反。但是这是通过命令行直接调用的，所以可能偶尔会出现ScSwitchActivity在前台存活时间过长的情况。
> 
> 你卡住的情况是缺少条件形成了死循环，我来说一下你卡住的具体过程
> 
> to的时候：刚才说了，to是指打开这个应用(假设叫B)；
> 
> 你打开B，B就变成了前台应用，符合条件触发情景模式执行shell命令打开ScSwitchActivity这个活动，此时V2rayNg变成了前台应用应用B变成了后台应用，
> 
> ScSwitchActivity切换了V2rayNg开关后自动结束跳转回应用B，此时应用B又变成了前台应用，符合条件触发情景模式打开ScSwitchActivity，此时V2rayNg变成了前台应用应用B变成了后台应用，
> 
> 3、4、5、6......无限循环步骤2，可能ScSwitchActivity存活时间过长，导致一直显示V2rayNg
> 
> from的时候：from是指本来应用A是前台的，现在A不是前台了
> 
> 关闭应用A(这种情况一般是回到桌面)，符合条件触发情景模式调用ScSwitchActivity改变V2rayNg开关，ScSwitchActivity自动结束自动跳转到桌面，不符合条件，流程结束
> 
> 打开应用A，这个时候to是指应用A，from是指其他应用，这个按理说是不会导致卡住的，除非这个时候这几个应用都在你的全局变量v2ray里面
> 
> 上面是我根据你描述的个人分析，具体情况还是看你自己了

大佬我理解了原理，也就是ScSwitchActivity跟gps开关等不一样，是要打开v2ray前台服务来切换的，所以在开启v2ray后重新回到app被再次执行规则了，退出不会触发所以正常。你的规则还有个谷歌服务被冻结的条件，但我这个只是单纯打开app没有附加条件怎么办。。。感觉应该在前面加个v2ray处于关闭状态的条件，但小白不知道怎么实现。。。。

**Comment by ghost** [comment]
懂了，加了一个从桌面打开的条件就ok了
可惜从后台回到app也会切换v2ray开关，不知道有什么办法没有

**Comment by inused** [comment]
@krecycle 你这个情况建议尝试一下[activity created](https://tornaco.github.io/Thanox/2019-12-02-Profile/#044-activity-created)
把你需要的应用首屏活动的created事件作为条件
thanox有可以显示当前活动项的功能

**Comment by ghost** [comment]
> @krecycle 你这个情况建议尝试一下activity created
> 把你需要的应用首屏活动的created事件作为条件
> thanox有可以显示当前活动项的功能

这个好像有点复杂。。。因为我加了多个app的全局变量应用这个规则，这样是得把这些全都一个个列出来嘛。。

**Comment by Gladtbam** [comment]
> 懂了，加了一个从桌面打开的条件就ok了
> 可惜从后台回到app也会切换v2ray开关，不知道有什么办法没有

这个简单，你碰到的问题应该是重复进入app后，规则再一次被执行了对吧！这种情况只需要多加一个判断条件就行。添加判断app是否被杀死或者app是否有最近任务的接口即可

**Comment by ghost** [comment]
> 懂了，加了一个从桌面打开的条件就ok了
> 可惜从后台回到app也会切换v2ray开关，不知道有什么办法没有
> 
> 这个简单，你碰到的问题应该是重复进入app后，规则再一次被执行了对吧！这种情况只需要多加一个判断条件就行。添加判断app是否被杀死或者app是否有最近任务的接口即可

后面加上最近任务条件就好了，一个时正常运行，但加上其他的又卡住了😂，补上从桌面打开的条件问题又变回之前的问题了
"condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && (task.hasTaskFromPackage(\"org.telegram.messenger\") == false || task.hasTaskFromPackage(\"com.twitter.android\") == false || task.hasTaskFromPackage(\"com.app.pornhub\") == false || task.hasTaskFromPackage(\"com.apkpure.aegon\") == false)",

**Comment by Gladtbam** [comment]
> > 懂了，加了一个从桌面打开的条件就ok了
>#-  > 可惜从后台回到app也会切换v2ray开关，不知道有什么办法没有
> > 
> > 这个简单，你碰到的问题应该是重复进入app后，规则再一次被执行了对吧！这种情况只需要多加一个判断条件就行。添加判断app是否被杀死或者app是否有最近任务的接口即可
> 
> 后面加上最近任务条件就好了，一个时正常运行，但加上其他的又卡住了😂，补上从桌面打开的条件问题又变回之前的问题了
> "condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && (task.hasTaskFromPackage(\"org.telegram.messenger\") == false || task.hasTaskFromPackage(\"com.twitter.android\") == false || task.hasTaskFromPackage(\"com.app.pornhub\") == false || task.hasTaskFromPackage(\"com.apkpure.aegon\") == false)",

既然你已经用了全局变量，这里就不用这么写了啊，直接写成&& !task.hasTaskFromPackage(pkgName)就行了

**Comment by ghost** [comment]
> 懂了，加了一个从桌面打开的条件就ok了
> #- > 可惜从后台回到app也会切换v2ray开关，不知道有什么办法没有
> 
> 这个简单，你碰到的问题应该是重复进入app后，规则再一次被执行了对吧！这种情况只需要多加一个判断条件就行。添加判断app是否被杀死或者app是否有最近任务的接口即可
> 
> 后面加上最近任务条件就好了，一个时正常运行，但加上其他的又卡住了，补上从桌面打开的条件问题又变回之前的问题了
> "condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && (task.hasTaskFromPackage("org.telegram.messenger") == false || task.hasTaskFromPackage("com.twitter.android") == false || task.hasTaskFromPackage("com.app.pornhub") == false || task.hasTaskFromPackage("com.apkpure.aegon") == false)",
> 
> 既然你已经用了全局变量，这里就不用这么写了啊，直接写成&& !task.hasTaskFromPackage(pkgName)就行了

一样的问题，打开app还是在循环切换v2ray开关，加上从桌面打开的条件后这个又没用了😂

**Comment by Gladtbam** [comment]
> 一样的问题，打开app还是在循环切换v2ray开关，加上从桌面打开的条件后这个又没用了😂

不应该啊，能把你的情景模式代码完全发过来吗？我测试一下

**Comment by inused** [comment]
@Tornaco 大佬，请问 sh.exe 返回的结果可以直接获取命令的输出吗
文档中说明返回结果是 `CommandResult `这个类
```java
@HandlerName("sh")
interface ISh {
    CommandResult exe(String command);
}
```
直接toast弹出返回结果的话是下面格式的字符串
```json
Result{out=[xxx], err=[xxx], code=0}
```
返回结果可以调用`toString()`方法，下面这个比较结果是true
```bash
sh.exe(\"ip ro | awk '{print $3}' | grep -wq 'tun0' &&  echo 'Y' || echo 'N'\").toString() == \"Result{out=[N], err=null, code=0}\")
```
`CommandResult.toString()`方法可以正常调用返回字符串
所以测试调用了`getOut()`方法，无法弹出信息，应该是出错了，调用`getOut()`方法这一行后面的代码也不再执行
然后反编译应用找到了`CommandResult`这个类，发现存在`getStdout()`方法，测试调用仍然不行
然后发现里面的几个属性`exitCode stdout`都是`public`，所以直接调用了这几个属性，仍然不行

日志中没有打印错误信息

请问是我调用方式有问题还是没有提供这个调用能力啊

**Comment by ghost** [comment]
> 一样的问题，打开app还是在循环切换v2ray开关，加上从桌面打开的条件后这个又没用了
> 
> 不应该啊，能把你的情景模式代码完全发过来吗？我测试一下



> 一样的问题，打开app还是在循环切换v2ray开关，加上从桌面打开的条件后这个又没用了
> 
> 不应该啊，能把你的情景模式代码完全发过来吗？我测试一下

`[{"name": "auto v2ray",
"description": "自动打开v2ray",
"priority": 1,
"condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && !task.hasTaskFromPackage(pkgName)",
"actions": [
"sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")"
]}]`

**Comment by Gladtbam** [comment]
> 
> `[{"name": "auto v2ray",
> "description": "自动打开v2ray",
> "priority": 1,
> "condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && !task.hasTaskFromPackage(pkgName)",
> "actions": [
> "sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")"
> ]}]`

再加个!task.hasTaskFromPackage(\"com.v2ray.ang\")就可以了😂
```
[
  {
    "name": "auto v2ray",
    "description": "自动打开v2ray",
    "priority": 2,
    "condition": "frontPkgChanged == true && globalVarOf$v2ray.contains(to) && !task.hasTaskFromPackage(pkgName) && !task.hasTaskFromPackage(\"com.v2ray.ang\")",
    "actions": 
    [
      "sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")"
    ]
  }
]
```
需要注意的是，执行这个规则不能有v2ray的后台，所以如果不想重复执行，必须保证最近任务里面有v2rayng

**Comment by ghost** [comment]
> [{"name": "auto v2ray", "description": "自动打开v2ray", "priority": 1, "condition":"frontPkgChanged == true && globalVarOf$v2ray.contains(to) && !task.hasTaskFromPackage(pkgName)", "actions": [ "sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")" ]}]
> 
> 再加个!task.hasTaskFromPackage("com.v2ray.ang")就可以了
> 
> [
>   {
>     "name": "auto v2ray",
>     "description": "自动打开v2ray",
>     "priority": 2,
>     "condition": "frontPkgChanged == true && globalVarOf$v2ray.contains(to) && !task.hasTaskFromPackage(pkgName) && !task.hasTaskFromPackage(\"com.v2ray.ang\")",
>     "actions": 
>     [
>       "sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\")"
>     ]
>   }
> ]
> 需要注意的是，执行这个规则不能有v2ray的后台，所以如果不想重复执行，必须保证最近任务里面有v2rayng

这样打开一次v2ray已经在后台，虽然从后台打开不会重复执行，这样下次打开又不生效了，要手动把v2ray清掉才行😂

**Comment by Gladtbam** [comment]
> 
> 这样打开一次v2ray已经在后台，虽然从后台打开不会重复执行，这样下次打开又不生效了，要手动把v2ray清掉才行😂

对，不过如果清掉了v2ray的最近任务的话的话，v2ray也会关闭。所以说，不管怎么样，只要需要使用2ray，必须保持v2ray在后台😂，把清理v2ray的最近任务当作关闭v2ray的开关就行了😋

**Comment by ghost** [comment]
> 这样打开一次v2ray已经在后台，虽然从后台打开不会重复执行，这样下次打开又不生效了，要手动把v2ray清掉才行
> 
> 对，不过如果清掉了v2ray的最近任务的话的话，v2ray也会关闭。所以说，不管怎么样，只要需要使用2ray，必须保持v2ray在后台，把清理v2ray的最近任务当作关闭v2ray的开关就行了

我在退出关闭v2ray的规则里加了个清理v2ray的最近任务，然后退出v2ray本身也加了，总算舒服了，谢谢

**Comment by ghost** [comment]
> 这样打开一次v2ray已经在后台，虽然从后台打开不会重复执行，这样下次打开又不生效了，要手动把v2ray清掉才行
> 
> 对，不过如果清掉了v2ray的最近任务的话的话，v2ray也会关闭。所以说，不管怎么样，只要需要使用2ray，必须保持v2ray在后台，把清理v2ray的最近任务当作关闭v2ray的开关就行了

额，发现在v2ray打开的状态下手动清理会关闭，但thanox清理的最近任务并不会关闭v2ray
哦了，搭配后台清理就好了

**Comment by inused** [comment]
@krecycle 你可以暂时使用下面这个命令作为条件判断v2Rayng有没有开启
```
(sh.exe(\"ip ro | awk '{print $3}' | grep -wq 'tun0' &&  echo 'Y' || echo 'N'\").toString() == \"Result{out=[N], err=null, code=0}\")
```
这个是通过判断网络接口中有没有VPN的接口来间接判断是不是开启了v2Rayng，
如果这条命令结果是true，则说明没有开启v2Ray
`out=[N]`改成`out=[Y]`后，结果为true则说明开启了v2Rayng连接，或者把`==`改成`!=`，多种方式，看你喜欢

命令中的`tun0`是我自己手机上开启v2Rayng连接后新增的网络接口，你需要在终端中使用`ip ro`命令自己测试你手机中是不是也叫这个，查看命令输出中每一行以空白隔开的第三部分。
另外，不确定是不是所有的手机都是开启v2Rayng后新增一个网络接口，关闭连接则删除这个接口，需要你自己测试

**Comment by ghost** [comment]
> @krecycle 你可以暂时使用下面这个命令作为条件判断v2Rayng有没有开启
> 
> (sh.exe(\"ip ro | awk '{print $3}' | grep -wq 'tun0' &&  echo 'Y' || echo 'N'\").toString() == \"Result{out=[N], err=null, code=0}\")
> 这个是通过判断网络接口中有没有VPN的接口来间接判断是不是开启了v2Rayng，
> 如果这条命令结果是true，则说明没有开启v2Ray
> out=[N]改成out=[Y]后，结果为true则说明开启了v2Rayng连接，或者把==改成!=，多种方式，看你喜欢
> 
> 命令中的tun0是我自己手机上开启v2Rayng连接后新增的网络接口，你需要在终端中使用ip ro命令自己测试你手机中是不是也叫这个，查看命令输出中每一行以空白隔开的第三部分。
> 另外，不确定是不是所有的手机都是开启v2Rayng后新增一个网络接口，关闭连接则删除这个接口，需要你自己测试

试了一下，可行，但效率有点低了，打开app要卡在v2ray判断好几秒才进去😂
本来执行切换v2ray的指令也经常会出现v2ray界面在进入app，不过速度比较快影响不大，这个就比较影响了

**Comment by ghost** [comment]
> @krecycle 你可以暂时使用下面这个命令作为条件判断v2Rayng有没有开启
> 
> ```
> (sh.exe(\"ip ro | awk '{print $3}' | grep -wq 'tun0' &&  echo 'Y' || echo 'N'\").toString() == \"Result{out=[N], err=null, code=0}\")
> ```
> 
> 这个是通过判断网络接口中有没有VPN的接口来间接判断是不是开启了v2Rayng，
> 如果这条命令结果是true，则说明没有开启v2Ray
> `out=[N]`改成`out=[Y]`后，结果为true则说明开启了v2Rayng连接，或者把`==`改成`!=`，多种方式，看你喜欢
> 
> 命令中的`tun0`是我自己手机上开启v2Rayng连接后新增的网络接口，你需要在终端中使用`ip ro`命令自己测试你手机中是不是也叫这个，查看命令输出中每一行以空白隔开的第三部分。
> 另外，不确定是不是所有的手机都是开启v2Rayng后新增一个网络接口，关闭连接则删除这个接口，需要你自己测试

大佬，有没有让"sh.exe(\"am start -n com.v2ray.ang/com.v2ray.ang.ui.ScSwitchActivity\");",后台运行而不是前台切换的办法😂

**Comment by inused** [comment]
@krecycle 
那是四大组件中负责界面的activity，在不改动v2rayng现有代码的情况下使用该命令必定会弹出界面，但是这个调起活动在正常情况下一定会成功
你可以使用下面这个命令直接调起service
```bash
am startservice -n com.v2ray.ang/.service.V2RayVpnService
```
V2RayNg就是使用这个服务启动VPN的，启动的时候不会弹出界面，但是极有可能因为没有后台运行导致出现服务调起成功但VPN未能连接或者直接服务调起失败的情况，很烦人，所以我是没有用这个法子的
`stopservice` 是关闭服务，但是单纯关闭这个服务貌似并没有关闭VPN连接，所以有点问题
下面是强制停止v2ray，可以实现关闭VPN连接
```bash
am force-stop com.v2ray.ang
```

**Comment by ghost** [comment]
> @krecycle
> 那是四大组件中负责界面的activity，在不改动v2rayng现有代码的情况下使用该命令必定会弹出界面，但是这个调起活动在正常情况下一定会成功
> 你可以使用下面这个命令直接调起service
> 
> ```shell
> am startservice -n com.v2ray.ang/.service.V2RayVpnService
> ```
> 
> V2RayNg就是使用这个服务启动VPN的，启动的时候不会弹出界面，但是极有可能因为没有后台运行导致出现服务调起成功但VPN未能连接或者直接服务调起失败的情况，很烦人，所以我是没有用这个法子的
> `stopservice` 是关闭服务，但是单纯关闭这个服务貌似并没有关闭VPN连接，所以有点问题
> 下面是强制停止v2ray，可以实现关闭VPN连接
> 
> ```shell
> am force-stop com.v2ray.ang
> ```

好用，我这调用基本都成功，谢谢！
