### ISSUE TITLE
[问题反馈]情景模式写代码卡死

### ISSUE THREAD

**Issue by Gladtbam** [Tornaco/Thanox#86]
在情景模式代码编辑界面停留时间太长Thanox会卡死，已经成功复现
![Screenshot_2020-02-20-00-25-44-633_github tornaco android thanos pro](https://user-images.githubusercontent.com/49943258/74852914-2c249f80-5378-11ea-94ea-6282c74b2c4e.jpg)
![Screenshot_2020-02-20-00-26-43-660_github tornaco android thanos pro](https://user-images.githubusercontent.com/49943258/74852925-2f1f9000-5378-11ea-8a14-ee1e2116ad44.jpg)

**Comment by Tornaco** [comment]
帮忙抓一下data/anr下的日志。奇怪。

**Comment by Gladtbam** [comment]
> 帮忙抓一下data/anr下的日志。奇怪。

时间太久了，只有今天的日志

**Comment by Gladtbam** [comment]
新版本我无法复现该BUG，暂时关闭该issues
@Tornaco
