### ISSUE TITLE
无法使用磁贴/快速设置进行应用管理

### ISSUE THREAD

**Issue by C-neon** [Tornaco/Thanox#869]
**磁贴工作不正常**
在a14 pixelOS(unofficial)内，快速设置界面中的应用管理点击后会导致thanox停止运行，且当前活动点击后需等待3-4秒才能启动。
https://github.com/Tornaco/Thanox/assets/73581147/e9fb256f-9a29-483e-b3a4-370f1e1dc262

**Version:**
 - OS: Android 14 pixelOS(unofficial)
 - Version v5.0.6-prc

** Logs**
![Thanox-Log-2024-03-16-13_21_09.zip](https://github.com/Tornaco/Thanox/files/14622495/Thanox-Log-2024-03-16-13_21_09.zip)

**Comment by Tornaco** [comment]
@C-neon 试试[这个包 ](https://app.circleci.com/pipelines/github/Tornaco/Thanox/1007/workflows/4f8edf89-036b-452c-ae3e-398d72a8bc1c/jobs/911/artifacts)

**Comment by C-neon** [comment]
> @C-neon 试试[这个包 ](https://app.circleci.com/pipelines/github/Tornaco/Thanox/1007/workflows/4f8edf89-036b-452c-ae3e-398d72a8bc1c/jobs/911/artifacts)

非常感谢！问题解决了
