### ISSUE TITLE
使用其他magisk模块，导致Thanox出现不兼容

### ISSUE THREAD

**Issue by ZeonXr** [Tornaco/Thanox#870]
**现象描述**
使用 https://github.com/ys1231/MoveCertificate magisk模块用于将移动用户证书到系统证书
Thanox出现不兼容（但是功能似乎正常）
![bfec430cb0ac342a71471a3f78b0660](https://github.com/Tornaco/Thanox/assets/30890851/f60a99e5-1b88-44ca-aa56-5c6aab5c4153)
卸载上述的magisk模块后，不兼容字样消失
尝试另一款功能相同的magisk模块 https://github.com/lupohan44/TrustUserCertificates 也是如此

**版本**
 - OS: Android 14
 - Magisk 27, Lsposed 1.9.2
 - Thanox Pro 5.0.6（谷歌商店 lsp激活）

**日志文件**
[Thanox-Log-2024-03-16-16_26_35.zip](https://github.com/Tornaco/Thanox/files/14622970/Thanox-Log-2024-03-16-16_26_35.zip)

**Comment by Tornaco** [comment]
@ZeonXr 试试[这个包 ](https://app.circleci.com/pipelines/github/Tornaco/Thanox/1007/workflows/4f8edf89-036b-452c-ae3e-398d72a8bc1c/jobs/911/artifacts)

**Comment by ZeonXr** [comment]
> @ZeonXr 试试[这个包 ](https://app.circleci.com/pipelines/github/Tornaco/Thanox/1007/workflows/4f8edf89-036b-452c-ae3e-398d72a8bc1c/jobs/911/artifacts)
特地买了个激活码测试了一下没问题，期待谷歌商店的更新

**Comment by Tornaco** [comment]
@ZeonXr 谷歌已经推了。你发邮件我给你退了吧。

**Comment by ZeonXr** [comment]
> @ZeonXr 谷歌已经推了。你发邮件我给你退了吧。

不用不用，支持一下开发者
