### ISSUE TITLE
一加7pro锁屏清理后台失效

### ISSUE THREAD

**Issue by flyinsz** [Tornaco/Thanox#89]
**Describe the bug（现象描述）**
锁屏清理后台无效（简洁的描述该bug的现象）

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
百分之百复现

**Expected behavior**（期望结果）
能正常清理后台

**Screenshots**（截图）

**Version（发现问题的版本）:**
 - OS: 氧OS B9（Android 10）
 - Version: 1.1.5 | 1.1.6（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
之前邮件反馈过，请搜索邮件。

**Comment by Tornaco** [comment]
@flyinsz 请提供最新日志。。 中间间隔
过几个版本了。

**Comment by flyinsz** [comment]
刚升级了1.16正式版好像解决了。我再测多几次看
