### ISSUE TITLE
thanox能完全摆脱xp吗？

### ISSUE THREAD

**Issue by ppouerct** [Tornaco/Thanox#9]
虽然xp很好很强，但是有一大堆兼容问题，一大堆的毛病，thanox其实可以完全摆脱xp，利用magisk/riru，这样既能减少很多xp本身带了的额外问题，还能减少安装问题，还能减低入门门槛

**Comment by Tornaco** [comment]
riru理论上可以。但是相对xp工作量更大，作用范围更小。

**Comment by ppouerct** [comment]
好的

Potesta de Tornaco <notifications@github.com> 于 2019年11月9日周六 下午10:58写道：
