### ISSUE TITLE
开机后应用无法自起导致自动套用模板无效

### ISSUE THREAD

**Issue by Jkkoi** [Tornaco/Thanox#95]
RT，现在需要开机后手动开启应用一次才能正常使用自动模板

小米6 
QQ1B.200205.002
PixelExperience_sagit-10.0-20200215-0336-UNOFFICIAL

**Comment by Tornaco** [comment]
1. 反馈问题，尤其是bug必须按照模板反馈，至少要提供日志。
2. 自动模板理论上是完全不依赖thanox app启动的，麻烦提供一下开机--新装应用的日志。

**Comment by Jkkoi** [comment]
> 1. 反馈问题，尤其是bug必须按照模板反馈，至少要提供日志。
> 2. 自动模板理论上是完全不依赖thanox app启动的，麻烦提供一下开机--新装应用的日志。

好的，我以为是app出问题所以没有想到日志这一回事🙈🙈🙈
这是/data/system/thanos/logging的log（其他log好像关联性不大）

文件说明：
logs-before.zip 为开机后直接安装应用，此时没有自动套用模板
logs-after.zip为接上面步骤，卸载后，打开thanox再次安装，此时正确套用模板
高德版_调用第三方APP查看地图.apk 为测试app
https://www.lanzous.com/i9orvja

**Comment by Jkkoi** [comment]
好像还没有修复，麻烦再看一下了
（log明天传）

**Comment by Jkkoi** [comment]
[logging.zip](https://github.com/Tornaco/Thanox/files/4409264/logging.zip)
log 来了
测试时间 3/31
