### ISSUE TITLE
Thanox会使Flyme11的“打开其他应用”功能失效

### ISSUE THREAD

**Issue by Shainly** [Tornaco/Thanox#959]
**Describe the bug（现象描述）**
激活Thanox后（没开Thanox的打开其他应用功能），Flyme系统自带的“打开其他应用”功能失效

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 使用Flyme11且在lsposed中激活Thanox并重启
2. 打开开屏有摇一摇广告的流氓应用（如知乎，百度网盘等具有摇一摇打开某购物软件功能的应用）
3. 稍微摇一下
4. 会发现某购物软件会被直接打开

**Expected behavior**（期望结果）
打开行为应该被Flyme11的“打开其他应用”拦截住才对

**Screenshots**（截图）
期望结果的截图↓
![S40619-14175642_android](https://github.com/Tornaco/Thanox/assets/167941804/34b0b1c1-6952-4344-adf6-e718dff85993)

**Version（发现问题的版本）:**
 - OS: [e.g. Android 14]
 - Version [e.g. v5.0.8-prc]

**Additional context**（其他信息）
已自行排除其它所有lsposed模块和magisk模块是否会导致此bug，开发者大可放心

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
不知道为啥我导不出log

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本：安卓14，Flyme 11.24.6.17daily14
> 2. Thanox版本：5.0.8-prc，补丁方式：xposed
> 3. 已经描述很清楚了🙏🙏🙏
> 4. 不激活thanox没问题！
> 5. Thanox不做任何配置会有问题

**Comment by Tornaco** [comment]
@Shainly 按照设置中的反馈说明抓个日志吧，最好也抓个lsp的日志。我没flyme11的设备没法分析。
