### ISSUE TITLE
shizuku模式下打开智能冻结与后台清理闪退

### ISSUE THREAD

**Issue by MCxlm1** [Tornaco/Thanox#961]
**Describe the bug（现象描述）**
A clear and concise description of what the bug is.（简洁的描述该bug的现象）
使用shizuku模式激活后打开后台清理和打开智能冻结上方的加号会闪退

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 进入thanox
2. 使用shizuku激活
3. 打开后台清理
4. 闪退到主界面

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
能够正常使用这两个功能

**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
https://github.com/Tornaco/Thanox/assets/115008407/869d69c7-bfde-47bb-9204-d18e0ebbaff8

**Version（发现问题的版本）:**
 - OS: [e.g. Android 9]（系统版本，例如Android 6.0.1）
 - Version [e.g. 5.1.1-prc]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）

** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。

![crash-github-tornaco-android-thanos-29_06-08-29-25_922.zip](https://github.com/user-attachments/files/16066567/crash-github-tornaco-android-thanos-29_06-08-29-25_922.zip)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本 HarmonyOS2
> 2. Thanox版本，补丁方式（xposed还是magisk？）shizuku
> 3. 问题现象的详细描述，有图或者视频更好
> 4. 不激活thanox有问题吗？
> 5. Thanox激活后不做任何配置有问题吗？
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里

**Comment by Tornaco** [comment]
我没有华为手机，尝试修了下，可以测试下：https://app.circleci.com/pipelines/github/Tornaco/Thanox/1110/workflows/e72c1213-bd7a-4888-ba35-e49b1e5e0eaf/jobs/1011

**Comment by MCxlm1** [comment]
构建失败了[Screenshot_20240821_083642_mark.via.jpg](https://github.com/user-attachments/assets/8f13e797-b557-46d3-8bf8-fef3cf7d99f7)

**Comment by Tornaco** [comment]
[thanox_5.1.1-11-07a6e37-prc(3080394).apk.zip](https://github.com/user-attachments/files/16687338/thanox_5.1.1-11-07a6e37-prc.3080394.apk.zip)


@MCxlm1  手动打了一个。

**Comment by Tornaco** [comment]
Fixed
