### ISSUE TITLE
打开多开功能后，必须手动添加IntentResolver才能使用主用户和分用户的分享和文件选择

### ISSUE THREAD

**Issue by uwu-gl** [Tornaco/Thanox#965]
**Describe the bug（现象描述）**
打开多开功能后，必须手动添加IntentResolver才能使用主用户和分用户的分享和文件选择，否则无法使用
**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. Go to 'mt manager'
2. Click on a file and tap 'share'
3. See error: the Mt manager will exit directly. Sometimes android system will give a window says "IntentResolver keeps stopping"

**Expected behavior**（期望结果）
A clear and concise description of what you expected to happen.（描述一下期望的结果）
如现象描述
**Screenshots**（截图）
If applicable, add screenshots to help explain your problem.（通过截图更好的解释你的问题）
![Screenshot_20240721-165423](https://github.com/user-attachments/assets/89db90ef-ed8d-4c26-8793-2ab84d30de51)

**Version（发现问题的版本）:**
 - OS: [e.g. 14(QPR3)]（系统版本，例如Android 6.0.1）
 - Version [e.g. latest in release(2024.7.21)]（软件版本，例如v2.3.4）

**Additional context**（其他信息）
Add any other context about the problem here.（其他的补充信息）
我认为要么需要在打开多开功能时自动克隆，要么在用户文档中提前写好，或者是打开这个功能时弹窗提醒用户。
** Logs**（日志文件）
务必将截取到的日志文件发到该issue里。
Android Intent Resolver崩溃日志：https://bin.mkr.pw/~669cca2b3b6efb2a97621384
thanox的崩溃日志：
[Thanox-Log-2024-07-21-16_57_51.zip](https://github.com/user-attachments/files/16323593/Thanox-Log-2024-07-21-16_57_51.zip)

---------

> Thanox本身提供的配置很多都是会对系统或app造成影响，所以很多时候如果你只是描述问题现象，我是无法分析定位的。
> 所以问题反馈请务必提供更详细的信息。

> 1. 系统版本 14
> 2. Thanox版本，补丁方式（xposed还是magisk？）xposed
> 3. 问题现象的详细描述，有图或者视频更好，上面有了
> 4. 不激活thanox有问题吗？没有
> 5. Thanox激活后不做任何配置有问题吗？没
> 6. 按照app首頁最下面「反饋」的提示抓取日志并上传到issue里，行

**Comment by uwu-gl** [comment]
https://github.com/Tornaco/Thanox/pull/966
在这里提了个治标不治本的pr，有空请开发者查看 :)

**Comment by Tornaco** [comment]
👍

**Comment by Tornaco** [comment]
后面的版本，在启用双开时会默认安装这个包，同时merge了你的提示。

**Comment by uwu-gl** [comment]
感谢
