### ISSUE TITLE
应用列表不刷新问题

### ISSUE THREAD

**Issue by mpamxl** [Tornaco/Thanox#971]
应用卸载后，在后台应用里还是会有这个应用，只能重启手机才能刷新，求修复下这个问题。

**Comment by Vstory** [comment]
是的，我也有这个问题。我在群组也看到很多人有这个问题

**Comment by Tornaco** [comment]
@mpamxl 问题反馈需要提供基本的截图和日志（data/system/thanos_xx/logging/xxx）。

**Comment by mpamxl** [comment]
> @mpamxl 问题反馈需要提供基本的截图和日志（data/system/thanos_xx/logging/xxx）。

![Screenshot_20240811-164829_Thanox.jpg](https://github.com/user-attachments/assets/041fff31-40e2-4e4f-9855-ade21c962f97)

如图，MT管理器已经卸载，但后台应用中还有，只能重启手机才会消失，这个很多人都遇到，随便安装一个应用再卸载，手机没重启前都会在后台应用里残留这个

**Comment by mpamxl** [comment]
> @mpamxl 问题反馈需要提供基本的截图和日志（data/system/thanos_xx/logging/xxx）。

这个问题日志中好像也并没有记录，就是没有及时刷新应用列表的感觉，但别的软件一般就重新启动应用就会刷新，Thano必须要重启手机才会刷新，这个不太合理...

**Comment by mpamxl** [comment]
> @mpamxl 问题反馈需要提供基本的截图和日志（data/system/thanos_xx/logging/xxx）。

可以修复下吗？这个问题

**Comment by Tornaco** [comment]
行，我看下，要日志是需要看下你的设备，版本之类的基础信息。没有日志，没有截图的话会浪费很多时间。

**Comment by mpamxl** [comment]
> 行，我看下，要日志是需要看下你的设备，版本之类的基础信息。没有日志，没有截图的话会浪费很多时间。

明白，设备是三星S10e国行版 G9700，安卓9，但这问题百分百复现，群组也很多人都提过，麻烦大佬修复下了，感谢大佬

**Comment by mpamxl** [comment]
> 行，我看下，要日志是需要看下你的设备，版本之类的基础信息。没有日志，没有截图的话会浪费很多时间。

那还需要我复现下Bug再发一份日志吗？

**Comment by Tornaco** [comment]
@mpamxl 不用了，等新版再试试

**Comment by mpamxl** [comment]
> @mpamxl 不用了，等新版再试试

感谢大佬，坐等新版

**Comment by mpamxl** [comment]
> @mpamxl 不用了，等新版再试试
还有个建议，可否在后台应用后台启动之类的添加全选或者长按可多选之类的，不然一个个翻了点还是有点麻烦

**Comment by Tornaco** [comment]
[thanox_5.1.1-17-c9798fd-prc(3080400).apk.zip](https://github.com/user-attachments/files/16725522/thanox_5.1.1-17-c9798fd-prc.3080400.apk.zip)

@mpamxl 要不先测试这个包刷新修复没。

**Comment by mpamxl** [comment]
> [thanox_5.1.1-17-c9798fd-prc(3080400).apk.zip](https://github.com/user-attachments/files/16725522/thanox_5.1.1-17-c9798fd-prc.3080400.apk.zip)
> 
> @mpamxl 要不先测试这个包刷新修复没。

好像已经修复，刚看到，感谢大佬
