### ISSUE TITLE
Thanox Magisk模块版适配问题

### ISSUE THREAD

**Issue by Astoritin** [Tornaco/Thanox#973]
**Describe the bug（现象描述）**
因为Magisk的更新，Thanox使用的过时直接安装脚本被忽略，Thanox Magisk模块版无法完成安装。并且由于近期KSU可能也会抛弃直接安装脚本，这个问题可能在未来版本的KSU管理器也会出现。

**To Reproduce**（如何复现）
Steps to reproduce the behavior:（复现步骤）
1. 更新到Magisk 27006+ （topjohnwu官方版/LSP开发团队负责的Alpha都行）
2. 打开Magisk，切换到模块界面，点击从本地安装，选择Zygisk-Thanox-xxx.zip
3. 等待刷入完成后，模块列表里并没有出现 Zygisk - Thanox，重新启动设备以后仍然没有Zygisk - Thanox模块。

**Expected behavior**（期望结果）
Thanox Magisk版正常安装完成并在新版面具显示。
（Magisk开发者们说匹配安装脚本是模块开发者们的责任，所以要求他们重新加回去是没有指望了）

**Screenshots**（截图）
![Screenshot_20240825-090747_Alpha](https://github.com/user-attachments/assets/d2879af4-33d0-401a-bbfa-9038dd2ebe6f)
![Screenshot_20240825-090753_Alpha](https://github.com/user-attachments/assets/7347d674-b158-45e9-9697-96b7fc8cab85)
![Screenshot_20240825-090803_Alpha](https://github.com/user-attachments/assets/0639b505-bb8c-42b2-bf97-20fa4d5b90c5)
安装时和重启后截图（看样子是因为Magisk抛弃了旧版本安装脚本直接没能完成安装）

**Version（发现问题的版本）:**
 - OS: Android 14 QPR3 (安卓安全补丁日期：2024-08-05)
 - Thanox版本: Thanox Pro v5.1.2-row
 - 补丁方式: Magisk方式无法完成刷入安装，故目前仍然使用的是Xposed方式 (LSPosed)
 - 由于是在安装/初始化期间出现的问题，故不也没有必要提供Thanox的日志

**Additional context**（其他信息）
Magisk Alpha公告：https://t.me/magiskalpha/654

** Logs**（日志文件）
![Screenshot_20240825-091321_Root Explorer](https://github.com/user-attachments/assets/f166216f-e992-4d8d-9019-6329a4e08033)

---------

> 感谢您的Thanox，我用了三年多了，对我而言无论是类原生还是国产OS,它都是不可或缺的强大的手机管家（？但是的确我是这么认为的）和高级的玩机必备工具，再度感谢♥️

**Comment by Astoritin** [comment]
5.1.6 Pro 版本已解决
[
![Screenshot_20241011-231802_Alpha](https://github.com/user-attachments/assets/02129b9c-b961-4b4f-9bdf-337ed112dd1d)
](url)

**Comment by Ostrichbeta** [comment]
v5.1.7 from Google Play still has this issue:
```
- Copying zip to temp directory
- Installing zygisk_thanox-5.1.7.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
mkdir: can't create directory '/modules_update/': Read-only file system
*****************
 Zygisk - Thanox 
*****************
*******************
 Powered by Magisk 
*******************
unzip: can't change directory to '/modules_update/zygisk_thanox': No such file or directory
unzip: can't change directory to '/modules_update/zygisk_thanox': No such file or directory
touch: /modules/zygisk_thanox/update: No such file or directory
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: line 613: can't create /modules/zygisk_thanox/update: nonexistent directory
chmod: /modules/zygisk_thanox/update: No such file or directory
cp: can't stat '/modules_update/zygisk_thanox/module.prop': No such file or directory
- Extracting module files
- Done
```

Magisk version is 28000, with Zygisk Enabled

**Comment by littlef0x** [comment]
Same here for both v5.1.6 (play) and v5.2.3 (github). Android 15. Magisk 28000 with Zygisk Enabled.
