### ISSUE TITLE
应用锁锁了Thanox自己导致App无法打开

### ISSUE THREAD

**Issue by Sfssup** [Tornaco/Thanox#98]
只是想测试一下，打开应用锁，手残点了个全选
结果
别的App都好好的，没什么问题，解锁什么的都很6
Thanox自己锁了自己，解锁就闪退，然后无限循环
这会已重装回来

**Comment by Tornaco** [comment]
💯

**Comment by Tornaco** [comment]
@GuanguangT 麻烦发下日志。刚试了下没复现。，。

**Comment by Sfssup** [comment]
不好意思刚看到，日志我这边关了，Xposed，Magisk日志都没有@GuanguangT

**Comment by rododo-meow** [comment]
@Tornaco 目前在4.0.3版复现，清thanox数据无效，关掉lsposed模块后可以打开thanox了，重置设置再激活之后又会死循环，需要哪些日志？

系统是lineage 19，magisk和lsposed日志没有数据，附上logcat
[logcat.txt](https://github.com/Tornaco/Thanox/files/9127039/logcat.txt)

**Comment by Tornaco** [comment]
> @Tornaco 目前在4.0.3版复现，清thanox数据无效，关掉lsposed模块后可以打开thanox了，重置设置再激活之后又会死循环，需要哪些日志？
> 
> 系统是lineage 19，magisk和lsposed日志没有数据，附上logcat
> [logcat.txt](https://github.com/Tornaco/Thanox/files/9127039/logcat.txt)

你试试ci上的最新版本，前几日修复了这个问题。

@rododo-meow
