### ISSUE TITLE
全面屏手势打开最近任务不会触发卡片模糊

### ISSUE THREAD

**Issue by sky96111** [Tornaco/Thanox#99]
一加7 oxygenos，设置卡片模糊后用全面屏首饰进入最近任务，无法触发模糊

**Comment by JiZhi-Error** [comment]
目前一加桌面的任务栏有个截图遮罩，得给他干了才行

**Comment by Tornaco** [comment]
@JiZhi-Error 🤣

**Comment by sky96111** [comment]
> 目前一加桌面的任务栏有个截图遮罩，得给他干了才行

绝了..国产UI神仙操作
